### ISSUE TITLE
skipControllerAndAction break routing in TYPO3 9

### ISSUE THREAD

**Issue by echavaillaz** [georgringer/news#1017]
## Bug Report

**Current Behavior**
If the setting `plugin.tx_news.settings.link.skipControllerAndAction` is set to 1, the routing in TYPO3 9 is broken.

**Possible Solution**
I purpose to clearly document this directly in the typoscript file or to skip the behaviour if realurl (or other) is not installed.

Thanks

**Comment by chrisprog20** [comment]
I can confirm this. Thank you echavaillaz for your report. I struggled also with this ;)

**Comment by georgringer** [comment]
removed in branch 11
