### ISSUE TITLE
"News not found" action is never executed with TYPO3 site configs

### ISSUE THREAD

**Issue by jonaseberle** [georgringer/news#1018]
## Bug Report

**Current Behavior**
Currently news expects its controller action `function detailAction($news = null)` to be called with $news = null if the news was not found

This is not the case any more with a PersistedAliasMapper because it does not find a match for an unexisting slug and does not activate the route at all. Instead, the site's default 404 action is executed.

The action is not called at all in that case.

**Expected behavior/output**
The configured "News not found"-action should be executed

**Environment**
- TYPO3 version(s): 9+
- news version: 

**Possible Solution**
* a custom routeEnhancer
* adding a 404-functionality for a slug-not-found-situation to PersistedAliasMapper (in TYPO3 core)

**Comment by plojewski** [comment]
@georgringer Any idea? How to show 404 error when I open single view news record that doesn’t exist anymore?

**Comment by georgringer** [comment]
this needs a custom enhancer I guess

**Comment by georgringer** [comment]
I am closing this issue because this is not something the extension can solve. please open an issue/feature request at https://forge.typo3.org/projects/typo3cms-core/issues

**Comment by jonaseberle** [comment]
For my use case (show a special 404-page for hidden records) I've since solved it with an extended `PersistedAliasMapper`. 

It goes a bit like this if anybody is interested:

```php
class PersistedAliasMapper404 extends PersistedAliasMapper

    protected function findByRouteFieldValue(string $value): ?array
    {
        $foundValidRecord = parent::findByRouteFieldValue($value);
        if (null !== $foundValidRecord) {
            return $foundValidRecord;
        }

        // ... code from parent function PersistedAliasMapper::findByRouteFieldValue()

        $queryBuilder->getRestrictions()
            ->removeAll();

        // ... code from parent function PersistedAliasMapper::findByRouteFieldValue()
    }
}
```
It resolves the UID of the hidden record.
It is not too pretty and it does not solve the generic case.

It requires the Extbase controller to accept `null` in which case it can get the original UID from the request and do some magic ("that news is not online any more - you might be interested in these related news:") with it.
