### ISSUE TITLE
multiday events still not showing correct

### ISSUE THREAD

**Issue by chequille** [georgringer/news#102]
Hi Georg,
I am really sorry and of course, I do not want you to be angry, but I do not understand why you closed issue #93 regarding Multiday Events. There is still no solutions for it.

I tried latest news (5.1.0) and eventnews (1.1.1) but a multi day event is only shown in the month were it starts, but not in the following month when the enddate is in this following month.

It is not very urgent for my project, but it would be nice if this will work in some future releases.

I am looking forward to hearing from you.
Best regards,
Jürgen

**Comment by chequille** [comment]
Any chance to implement this?

**Comment by georgringer** [comment]
if still valid, please open issue in eventnews github project. would be cool if your client could sponsor that as well.
