### ISSUE TITLE
Update from 7.2.3 to 7.3.0 leads to 500 Server Error (TYPO3 v8)

### ISSUE THREAD

**Issue by Bufallo** [georgringer/news#1027]
## Bug Report

**Current Behavior**
Update (composer update) from 7.2.3 to 7.3.0 breaks my installation.
500 Server Error:
2019/08/29 10:57:14 [error] 2415#2415: *3218 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of GeorgRinger\News\Xclass\XclassedXliffParser::getParsedData($sourcePath, $languageKey) must be compatible with TYPO3\CMS\Core\Localization\Parser\LocalizationParserInterface::getParsedData($sourcePath, $languageKey, $charset = '') in /vagrant/htdocs/typo3conf/ext/news/Classes/Xclass/XclassedXliffParser.php on line 0

**Expected behavior/output**
No 500 Error after update ;-)

**Environment**
- TYPO3 version(s): 8.7.27
- news version: 7.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian 9.9

**Possible Solution**
Downgrade to 7.2.3 fixes the issue

**Comment by schugabe** [comment]
Can confirm issue: the new XclassedXliffParser is not compatible with TYPO3 8

**Comment by rafu1987** [comment]
With the bugfix, I still get an error in frontend:

```
Call to undefined method GeorgRinger\News\Xclass\XclassedXliffParser::getLocalizedFileName() 

Error thrown in file
/xyz/typo3conf/ext/news/Classes/Xclass/XclassedXliffParser.php in line 35.
```

**Comment by georgringer** [comment]
@rafu1987 works now in master?

**Comment by rafu1987** [comment]
Yes, @georgringer - works now! Thank you! :-)
