### ISSUE TITLE
Registered icons as identifier of news in pagetree

### ISSUE THREAD

**Issue by angeloprevitali** [georgringer/news#1032]
Could you please revert and keep the original BLUE icon registered 
/typo3conf/ext/news/Resources/Public/Icons/ext-news-folder-tree.svg

as THE **default** before EXT:news version 7.3.1 _insted_ of the new icon from the core 
https://typo3.github.io/TYPO3.Icons/images/apps/apps-pagetree-folder-contains-news.svg

This concerns the changes you made from https://github.com/georgringer/news/issues/958

It is confusing our customer if the icon is changed again and we have to adapt all the TYPO3 everywhere plus we got to adapt our manuals again, too.  

We are welcome if someone would like to have override the registered icons and you did it, but think about all our customers.

It would be really helpful if you could revert this to the original. 

Thank you very much.

Best regards,
Angelo

**Comment by anpfeiffer** [comment]
Hi,

i agree with Angelo.

Another point is, that the icon for "pages contains news", shows a lila folder. With that the icons have nothing in common anymore between folger and page and confuse user.

Thank you

**Comment by georgringer** [comment]
not gonna change that, therefore closing the issue
