### ISSUE TITLE
TYPO3 7.6.11, news 5.1.0 pagination not working with realurl enabled

### ISSUE THREAD

**Issue by robsonrobi** [georgringer/news#104]
I am using a pagination to display the news list.
With realurl enabled the page is changed in the browser, f.e. /page/2/ but the list is not rendered for that offset. disabling real url the pagination works.

Any idea?

**Comment by robsonrobi** [comment]
Ist seems that realurl disables the functionality. going down to 2.0.14 it works.
any idea either ?

**Comment by georgringer** [comment]
does it work when not logged in the backend? however this is not an issue of news.

**Comment by frankschmelcher** [comment]
I had the same problem under TYPO3 7.6.9. I solved it:
* Check out new version of realurl 2.1.0, install from TER 
 * WARNING! Run the update script in the EM followed by the database update!
* and don't forget: **clear your BrowserCache!**

**Comment by robsonrobi** [comment]
Version 2.1.0 did the trick! thanks!
