### ISSUE TITLE
Custom data to news list view

### ISSUE THREAD

**Issue by dextar47** [georgringer/news#1045]
## Feature Request

**Is your feature request related to a problem? Please describe.**
If i have another doktype lets say ABC, and i also want to show some of them in the news then how i can add that data to listAction? there is no hook for that as of yet.

**Describe the solution you'd like**
Maybe a hook in listAction where third-party class can give the data, actually News objects so that those objects can be included in the rendering process. Or typoscript configuration where user can specify which custom table / TCA should be shown and on which criteria like when special checkbox is checked and then mapping of the columns.

**Comment by georgringer** [comment]
signal slots are available and should be fine
