### ISSUE TITLE
Show internal or external news in shortcut render

### ISSUE THREAD

**Issue by GuillaumeGBzh** [georgringer/news#1046]
## Bug Report

**Current Behavior**
A 404 error is generated when I want to show an internal/external news in a "shortcut" content type.

**Expected behavior/output**
Show the news. 

**Environment**
- TYPO3 version(s): 8.7.27
- news version: 7.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by georgringer** [comment]
merged
