### ISSUE TITLE
Exception on switching type on new record without title

### ISSUE THREAD

**Issue by JakoD** [georgringer/news#1054]
## Bug Report

**Current Behavior**
Create a new news record.
Switching to a different news type when the title is not yet set throws an exception in the backend.

**Expected behavior/output**
Create a new news record.
Switching to a different news type when the title is not yet set throws an exception in the backend.

**Environment**
- TYPO3 version(s): 8.7.27
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Additional context**
The exception is thrown from the DataHandler hook.
The `title` field has `eval` set to `required`, so the DataHandler will remove it from the `$fieldArray` if it is not set. It is then passed as `null` to `NewsSlugHelper->sanitize()`, which expects a string.
It seems this case is currently not handled by the code, as simple `$slugHelperFor8->sanitize($fieldArray['title'] ?? '');` at the call site would defy of setting the slug to the initial title. It would simply leave the slug as an empty string. Likewise would adding a check if the key is actually included in the `$fieldArray`.

**Comment by georgringer** [comment]
PR has been merged, issue can be solved
