### ISSUE TITLE
CategoryMenu/Filter and ListView on the same page results in translation errors

### ISSUE THREAD

**Issue by medarob** [georgringer/news#1059]
## Bug Report

**Current Behavior**
I have a website in German (Default) and English. News are available in both languages, so are the categories. When I use the Listview plugin all works fine. If I add the CategoryMenu as a filter to the same page I end up having the english translation for some categories when I'm on the German website. Only one categorie is in German, the other child categories are all in English.

**Expected behavior/output**
I would expect that the translation are handled correctly and that only categories in German are shown on the German website.

**Environment**
- TYPO3 version(s): 9.5.9
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10

**Possible Solution**
No idea.

**Additional context**
![grafik](https://user-images.githubusercontent.com/33951787/65889069-e6534480-e3a0-11e9-8d5b-7c129f3f2403.png)

I used the offical Template (https://docs.typo3.org/p/georgringer/news/master/en-us/Tutorials/Templates/MultiCategorySelection/Index.html)

![grafik](https://user-images.githubusercontent.com/33951787/65889186-17337980-e3a1-11e9-850a-c14d0a994acf.png)
![grafik](https://user-images.githubusercontent.com/33951787/65889304-5792f780-e3a1-11e9-9e1a-df278414f360.png)
Only one child category is translated correct, all other child categories are in English.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Use typoscript setting "plugin.tx_news.settings.respectSysLanguageInFindInList = 1"

It's this issue which is already resolved: https://github.com/georgringer/news/issues/900
