### ISSUE TITLE
Category records imported but importation of news records generates an error

### ISSUE THREAD

**Issue by YolfTypo3** [georgringer/news#106]
Hi,
I am trying to migrate from tt_news to news on TYPO3 7.6.11 using the latest version in GitHub of news and the latest version in GitHub of news_ttnewsimport.
Category records are correctly imported.
When trying to import news records I get a pop-up with "error" in it.

Any hint ?

Thanks in advance for your help

**Comment by georgringer** [comment]
open the console and check the response of the ajax call. that should contain more information

**Comment by YolfTypo3** [comment]
Thanks for taking into account this problem. The message in the console is
"NetworkError: 500 Internal Server Error - http://mySite/typo3/index.php?M=system_NewsTxNewsM1&moduleToken=0114f43b475889cf6ceb78fc3399fb761ada0d0b"

**Comment by YolfTypo3** [comment]
I have done several trials. It seems that importing more than 20 news generates this internal error.

**Comment by YolfTypo3** [comment]
In fact it is not a bug. After having created the directory news_import, the importation is OK.
May I suggest to create it by default or, at least, to generate an error message if not created.
Thanks for your work on news.
