### ISSUE TITLE
Wrong redirect in backend in 5.2

### ISSUE THREAD

**Issue by zelcode** [georgringer/news#107]
Hi,

after upgrade from 5.1 to 5.2, creating new record is OK, but when you open existing record and then close (or save) you get 404 Not Found. Look at the link:

http://abc.dev/typo3/'/typo3/index.php?M=web_NewsTxNewsM2&moduleToken=b4a134582f15b17d2b94669a7c94d0beb4373a9f&id=6&%27

there is extra `'/typo3/` in link.

Regards.

**Comment by skydivematy** [comment]
I have on two TYPO3 7.6.10 instance tx_news 5.2 running. I can't reproduce your fails...

**Comment by georgringer** [comment]
can you check out version 5.3 or master, thanks

**Comment by zelcode** [comment]
Hi Georg,

does not work with master, checked with Nginx and Apache.

Here is link from Close button, returnURL is enclosed in single quotes (not in 5.1), can't find from where comes that single quotes:

http://abc.dev/typo3/index.php?route=/record/edit&token=2273e6a024cfb17e09236de02a43292c18043ee7&edit[tx_news_domain_model_news][717]=edit&returnUrl='/typo3/index.php?M=web_NewsTxNewsM2&moduleToken=d5b91a9011c6b75da3cfefa28fca9d9138c4990e&id=6'#

Minimal test case, 7.6.11, bootstrap_package and news 5.2, with news 5.1 is OK.

Regards.
