### ISSUE TITLE
Category Database Table not updated if a news record is deleted

### ISSUE THREAD

**Issue by riegeo** [georgringer/news#1086]
## Bug Report

**Current Behavior**
I have some Categories for the news system and every news entry is assigned to a category.
Now if I delete a news entry in the backend, the database (sys_category) is not updated.

- Let's say we have "category 1" assigned to one news item. Then the field "items" of the table "sys_category" is set to "1".
- Now I delete the news item in the backend and I'd expect the field "item" for "category 1" to be set to "0". But it isn't, it is still on "1".
- If I go to the category in the backend there is no item assigned to "category 1" as expected. So I save the category and now the database is updated and the field "item" for "category 1" is set to "0".

**Expected behavior/output**
I'd expect the database to be updated as soon as I delete a news entry. Otherwise the output of a category menue isn't updated.
I have a category with typoscript and only categories that have items should be visible ( like "where = parent=0 AND deleted=0 AND hidden=0 AND items>0"). But this does only work if the database is updated when deleting items.

**Environment**
- TYPO3 9.5.10
- news version: 7.3.1]

**Comment by georgringer** [comment]
can you check this behaviour if you use the categories for e.g. pages? that it work there?

**Comment by riegeo** [comment]
Hi Georg,
I tested it and it's the same with pages. Also noticed that it happens even when creating new News entries / pages.

So I guess it's not news related?

Thank you

**Comment by georgringer** [comment]
yes not news related, so I am closing it here, feel free to open an issue at https://forge.typo3.org/projects/typo3cms-core/issues
