### ISSUE TITLE
Slug upgrade wizard does not consider slashes

### ISSUE THREAD

**Issue by fnagel** [georgringer/news#1088]
## Bug Report

**Current Behavior**
When using the upgrade wizard `Updates slug field "path_segment" of EXT:news records` slashes within a news record title are not removed. 

Example: 
Title: "Some nice news record / article with a slash"
Slug: "some-nice-news-record-/-article-with-a-slash"

**Expected behavior/output**
Slug: "some-nice-news-record-article-with-a-slash"
Slashes need to be removed, otherwise the routing will crash with something like:

```
(1/1) Symfony\Component\Routing\Exception\InvalidParameterException

Parameter "tx_news_pi1__news" for route "tx_news_pi1_0" must match "[^/]++" ("projektfilm-stellt-arbeit-und-leitmotive-des-dortmunder-profil-fuer-inklusionsorientierte-lehrer/-innenbildung-doprofil-vor" given) to generate a corresponding URL.
```

**Environment**
- TYPO3 version(s): 9.5.10
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 16

**Possible Solution**
Using SlugHelper::generate() instead of SlugHelper::sanitize() would take the TCA config `replacements` in consideration (related to #832). A simple str_replace would do the job, too.

**Additional context**
Here's a simple SQL query which fixes the issue quick and dirty:

`UPDATE tx_news_domain_model_news SET path_segment = replace(path_segment, '/', '');`

**Comment by georgringer** [comment]
Wanna create a pr to consider the replacement?

**Comment by fnagel** [comment]
Yes, will do!
