### ISSUE TITLE
Some French locallang files don't contain translations

### ISSUE THREAD

**Issue by sdelcroix** [georgringer/news#1092]
## Bug Report

The new translation server says that French translation is 100% complete : https://crowdin.com/project/typo3-extension-news
but some locallang files dont contain translation when we download the ZIP from TER or Github

**List of empty files**
- fr.locallang_modadministration.xlf
- fr.locallang_mod.xlf  
- fr.locallang_csh_tag.xlf

**Environment**
- TYPO3 version(s): 8.7.28
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
Crowdin will be available with next 9.5 version. 8.7 won't be supported soon, please upgrade
