### ISSUE TITLE
bootstrap 4: pagebrowser styling broken

### ISSUE THREAD

**Issue by cboltz** [georgringer/news#1094]
## Bug Report

**Current Behavior**
When using the latest `bootstrap_package` (11.0.1, which uses Bootstrap 4) and the news bootstrap template, the page browser appears unstyled.

**Expected behavior/output**
Styled pagebrowser with a border and some spacing around the link

**Environment**
- TYPO3 version(s): 9.5.10
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux - openSUSE Leap 15.1

**Possible Solution**
Add some classes to the pagebrowser template:
* change `<a>` to `<a class="page-link">`
* inside `<li class="active">` and `<li class="disabled">`, change the `span` to `<span class="page-link">`

**Additional context**

References:
* https://getbootstrap.com/docs/4.0/migration/#pagination
* https://getbootstrap.com/docs/4.0/components/pagination/

Workaround: Add the following lines to your CSS:

```
.news .pagination a, .news .pagination li.active span, .news .pagination li.disabled span {                                                                                                                                                                                    
    padding: 0.5rem 0.75rem;
    border: 1px solid #dee2e6;
}
```

**Comment by typo3ua** [comment]
[In my case](https://www.typo3.org.ua/news/), it is working correctly

**Comment by georgringer** [comment]
in the meantime a bootstrap5 compatible template is pushed. as templating is part of the integrator I will close this issue to also avoid possible regressions
