### ISSUE TITLE
RSS (List.xml) - teaser not displayed in feedreader

### ISSUE THREAD

**Issue by cboltz** [georgringer/news#1095]
## Bug Report

**Current Behavior**
The RSS feed (`List.xml` template) includes the teaser in `<description>` and the remaining text in `<content:encoded>`. The result is that feedreaders (like Akregator) only display the bodytext, but not the teaser text.

According to https://validator.w3.org/feed/docs/warning/NeedDescriptionBeforeContent.html this seems to be a bad idea because "When both [description and content:encoded] appear in an RSS 2.0 item, some consumers will simply pick up the last such element."

**Expected behavior/output**
Have the whole text (teaser and bodytext) in one tag so that the feedreader displays all of it.

**Environment**
- TYPO3 version(s): 9.5.10
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux - openSUSE Leap 15.1

**Possible Solution**

```
<description>
    {newsItem.teaser -> f:format.stripTags() -> f:format.htmlspecialchars()}
    {newsItem.bodytext -> f:format.stripTags() -> f:format.htmlspecialchars()}
</description>
```

Note: I didn't test this yet ;-)

**Comment by georgringer** [comment]
I don't plan to change the templates. those can be easily adopted
