### ISSUE TITLE
RSS: Image displayed as for-download-link

### ISSUE THREAD

**Issue by cboltz** [georgringer/news#1096]
## Bug Report

**Current Behavior**
The RSS feed (`List.xml` template) includes the image in `<enclosure>`. The result is that feedreaders (like Akregator) display a download link for the image (for example `Attachment:https://example.com/fileadmin/_processed_/example.png (image/png, 2,5 MiB)`) - but not the image itsself.

**Expected behavior/output**
The image should be displayed in the feedreader.

**Environment**
- TYPO3 version(s): 9.5.10
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux - openSUSE Leap 15.1

**Possible Solution**

Embed the image in `<description>` and/or `<content:encoded>` (see also #1095) using an `<img>` tag.

Please also make sure that a scaled-down version of the image gets embedded - the "Attachment" link points to the full-size image.

**Comment by georgringer** [comment]
closing this issue because this can easily be changed by the integrator. if there are more issues coming up I might rethink my decision
