### ISSUE TITLE
routeEnhancer for detail link and pagination Widget link not working together in List View (not core related)

### ISSUE THREAD

**Issue by derMatze82** [georgringer/news#1098]
## Bug Report

**Current Behavior**
With the config below (config.yaml), the link for the detail is not routed (remains https://domain.com/newspage/detail/?tx_news_pi1%5Bnews%5D=2301&cHash=21c4db34ce07a75a1fd5ccb3a7316386), the link for pagination is routed: https://domain.com/newspage/seite-2/
When I switch the value of "defaultController" to "News::detail", the detail link is routed (https://domain.com/newspage/detail/path-segment/), but the pagination link keeps unrouted (https://domain.com/newspage/?tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=13&cHash=7e4e8c32674a33c8c7c0f4a5123323b9.
Tested with default Templates.
This is not core related, because the use of pagination and detail routing is working in other modules on my website.
Any help is appreciated

**Expected behavior/output**
Detail and Pagination Link should be routed.

**Environment**
- TYPO3 version(s): 9.5.5 LTS
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: not related

sites/project/config.yaml:

> routeEnhancers:
  NewsPluginPresse:
    type: Extbase
    limitToPages:
      - 9 #pid of News list page
      - 14 #pid of News detail page
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/{page-label}-{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    defaultController: 'News::list'
    defaults:
      page: ''
    requirements:
      page: '\d+'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      page-label:
        type: LocaleModifier
        default: 'page'
        localeMap:
          - locale: 'en_.*'
            value: 'page'
          - locale: 'de_.*'
            value: 'seite'

**Comment by jokumer** [comment]
This is not a bug by news package for TYPO3.
If your list- and detail-view are on different pages, split your route-enhancer configuration for "NewsPluginPress" into two different route-enhancers fx "NewsPluginPressList" and "NewsPluginPressDetail".
Your current configuration issues in having optional routes in one and the same path, which cant be solved.

**Comment by derMatze82** [comment]
Thanks, it`s working with two route-enhancer!
