### ISSUE TITLE
Typo3 10 Compatibility

### ISSUE THREAD

**Issue by rfc2822** [georgringer/news#1100]
Hi,

I have made some work for Typo3 10 compatibility in my fork: https://github.com/rfc2822/news (maybe I'll add another commits)

However, it would need some testing and I don't know whether it's still compatible with older versions because I only use it for a Typo3 10 project.

Is there a way how to help contribution Typo3 10 support? Shall I send a PR when I'm finished? But it would need more testing.

**Comment by georgringer** [comment]
Pls checkout https://github.com/georgringer/news/tree/8.0?files=1

**Comment by rfc2822** [comment]
Thanks, I'll test the 8.0 branch which seems to work with Typo3 10. Is there still any specific work to do?

**Comment by georgringer** [comment]
checkout https://github.com/georgringer/news/projects ;)
