### ISSUE TITLE
Class error when adding custom type

### ISSUE THREAD

**Issue by bendoo** [georgringer/news#1105]
## Bug Report

**Current Behavior**
I wanted to add an extra custom type and followed:
https://docs.typo3.org/p/georgringer/news/master/en-us/DeveloperManual/ExtendNews/AddCustomType/Index.html
Exactly at it was explained there...
**Expected behavior/output**
This gives me in the Backend an extra custom type "myCustomNewsType".
However, when I call the Frontend, I get:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476045117: Could not find class definition for name "Galileocr\CustomPackage\Domain\Model\MyCustomNewsType". This could be caused by a mis-spelling of the class name in the class definition. | TYPO3\CMS\Extbase\Persistence\Generic\Exception\InvalidClassException thrown in file /usr/home/galileo98/public_html/typo3_src-9.5.11/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapFactory.php in line 131. 

**Environment**
- TYPO3 version(s): [9.5.0]
- news version: [e.g. 7.0.5]
- Composer (Composer Mode): [ no]
- OS: [e.g. OSX 10.13.4]

Have no idea why this occurs, is this example not complete?

Thanks and regards

**Comment by georgringer** [comment]
this error is thrown by the core, not really something I can do here
