### ISSUE TITLE
Show only news for editors with assigned categories in user group or user in backend

### ISSUE THREAD

**Issue by sdesign6** [georgringer/news#1108]
It is not possible to limit the displayed news in the backend to show only news from assigned  categories in beusergroup / beuser with category mounts (category_perms). All news are shown no matter which categories are assigned to the user / group, but only the assigned news are editable. In the admin modul only the assigned categories show up in the filter.
I don't know if this is a bug.
I found a description where it seemed that this was or seemed to be possible. 
https://stackoverflow.com/questions/45983204/typo3-tx-news-the-user-sees-news-of-categories-for-which-he-is-not-authorized

- TYPO3 version(s): 9.5.11
- news version: 7.3.1

**Comment by georgringer** [comment]
I am closing this issue because using such assignments could be done by a 3rd party extension. I can certainly implement such code if someone wants to sponsor it. currently I don't know of anyone needing it
