### ISSUE TITLE
Make pagination information to TSFE register optional

### ISSUE THREAD

**Issue by msollmann** [georgringer/news#1109]
Would it be possible to make the hardcoded feature "pagination information to TSFE register" (https://github.com/georgringer/news/pull/781/commits/7e568f22e9ced388e4a4ece3c003c06a049812d0) optional? I would prefer to deactivate it by TS.

**Comment by georgringer** [comment]
Sure

**Comment by msollmann** [comment]
Also in version 8.0.0 I cannot see any possibility to deactivate it. Would be great if you could implement it in future versions. Currently I have to comment out the extension of the page title in the PaginateController.php of every installation manually :-(
// $GLOBALS['TSFE']->page['title'] .= $titleAddition;

**Comment by georgringer** [comment]
the widget implementation has been removed, therefore also this information is gone and I close this issue
