### ISSUE TITLE
NewsSlugUpdater doesn't take care of slashes in the news title

### ISSUE THREAD

**Issue by hannesbochmann** [georgringer/news#1111]
Is it possible that the fix from #845 has to be taken into account in the NewsSlugUpdater, too? At least I got slashes in the path_segment when a news has slashes in it's title and the updater is executed. When the path_segment is recalculated in the backend editing form the slash is removed as expected. Can you shed some light on this?

**Environment**
- TYPO3 version(s): 9.5
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 18.04

**Comment by georgringer** [comment]
can you test latest master, should work there already

**Comment by hannesbochmann** [comment]
Thanks for the feedback. The problem is resolved with the latest master.
