### ISSUE TITLE
Exclude already displayed news not working with pagination

### ISSUE THREAD

**Issue by nicolez9911** [georgringer/news#1118]
## Bug Report

**Current Behavior**
Already displayed news are not excluded on second page of pagination.

**Expected behavior/output**
These already displayed news should also be excluded of the list on the next pages.

**Environment**
- TYPO3 version: 9.5.13
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: 10.15.2

**Comment by georgringer** [comment]
thanks for the issue report. it is impossible to know during runtime which news have been on other pages. if you know this is as integrator because you can take some assumptions, use one of the hooks to skip the known ids.

closing the issue therefore
