### ISSUE TITLE
path_segment is not swapped when news record is published to live workspace

### ISSUE THREAD

**Issue by hannesbochmann** [georgringer/news#1119]
## Bug Report

**Current Behavior**
When the path_segment of a news record inside a non-live workspace is edited, the changes are not published to live. This is due to the limitations which arise when using the unique evaluation in the TCA. (@see https://docs.typo3.org/c/typo3/cms-workspaces/master/en-us/Administration/Versioning/Index.html#unique-fields)
The same should apply to the title of tags as they are unique as well.

**Expected behavior/output**
The path_segment and maybe the title of tags, too, should at least not be visible when inside a non-live workspace

**Environment**
- TYPO3 version(s): 7.6.40 and 8.7.30 but will be the same in 9.5.x and onwards
- news version: 6.3.0 and 7.3.1 but will be the same in newer versions
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**
Add the displayCond "VERSION:IS:false" to unique fields like suggested in the TYPO3 documentation (see above)

**Comment by hannesbochmann** [comment]
When using the displayCond as suggested the fields will be visible in a non-live workspace when a news record is created. Thus they can be filled initially but not changed afterwards in non-live workspaces which is only possible behaviour.
The alias field of pages is configured just like that and it works like described.

**Comment by georgringer** [comment]
thanks for creating the issue. can you create a PR for that?

**Comment by hannesbochmann** [comment]
@georgringer done.

**Comment by ohader** [comment]
I had to revert this change individually in a project, where editors are only working in a workspace and handing articles to a different department for reviewing and publishing.

**Comment by georgringer** [comment]
@ohader what do you suggest for news?

**Comment by georgringer** [comment]
IMO this is more a core issue, at least I don't plan to work on that because of too less knowledge. closing for now
