### ISSUE TITLE
Sqlite 3.0 compatibility

### ISSUE THREAD

**Issue by nimayneb** [georgringer/news#1120]
## Bug Report

**Current Behavior**

If you run TYPO3 with Sqlite, the database schema updater cannot be carried out completely when this extension will be installed.

The database schema updater throws an "Invalid Argument" exception with the message "Expeting a string as Index Column".

First you have to adapt the file "ext_tables.sql" for the core tables "sys_category" and "tt_content" accordingly.

```
#
# Extend table structure of table 'sys_category'
#
CREATE TABLE sys_category (
	fe_group varchar(100) DEFAULT '0' NOT NULL,

	images int(11) unsigned DEFAULT '0',
	single_pid int(11) unsigned DEFAULT '0' NOT NULL,
	shortcut int(11) DEFAULT '0' NOT NULL,

	import_id varchar(100) DEFAULT '' NOT NULL,
	import_source varchar(100) DEFAULT '' NOT NULL,

	seo_title varchar(255) NOT NULL DEFAULT '',
	seo_description text,
	seo_headline varchar(255) NOT NULL DEFAULT '',
	seo_text text,
	slug varchar(2048),

	KEY import (import_id,import_source)
);
```

```
#
# Table structure for table 'tt_content'
#
CREATE TABLE tt_content (
	tx_news_related_news int(11) DEFAULT '0' NOT NULL,

	KEY index_newscontent (tx_news_related_news)
);
```

The "KEY" instructions must be removed in both.

Such properties cannot be adjusted for existing tables. These will probably have to be created from scratch?

**Expected behavior/output**

The database schema updater can be carried out completely.

**Environment**
- TYPO3 version(s): 9.5.13
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: macOS 10.14.6
- PHP: 7.3.13 (pdo+sqlite3)
- Sqlite3: 3.28.0

**Reproduce behavior**

Copy "composer.json" and ".env" (extract zip file attachment) to a new folder.
Change to new folder.
Run "composer install" (throws exception - but installs runnable TYPO3 installation).
Run "composer serve".
Browse to "http://127.0.0.1:8080/typo3/" and login.
Go to "Maintenance" view.
Click on button "Analyse database" (shows "Ajax Error" dialog).

![error01](https://user-images.githubusercontent.com/9550921/71985534-05c4fd80-322b-11ea-823c-027d47d9d737.png)
![error02](https://user-images.githubusercontent.com/9550921/71985532-052c6700-322b-11ea-9898-842e2a3b1a65.png)
![error03](https://user-images.githubusercontent.com/9550921/71985531-052c6700-322b-11ea-911b-09aba4e07a1c.png)
![error04](https://user-images.githubusercontent.com/9550921/71985530-052c6700-322b-11ea-931b-06c54854b61f.png)
![error05](https://user-images.githubusercontent.com/9550921/71985529-052c6700-322b-11ea-96a5-645732781867.png)
![error06](https://user-images.githubusercontent.com/9550921/71985526-0493d080-322b-11ea-8f85-bf8c995a4ac1.png)
![error07](https://user-images.githubusercontent.com/9550921/71985525-0493d080-322b-11ea-916f-201b13ee3a35.png)

---

[news.zip (includes composer.json & .env)](https://github.com/georgringer/news/files/4035728/news.zip)

**Comment by georgringer** [comment]
I currently have no idea how to fix it and also won't change it right now. therefore I am closing this issue
