### ISSUE TITLE
In translated news record appears wrong content elements which should not be connected to the news record

### ISSUE THREAD

**Issue by lisardo2** [georgringer/news#1126]
## Bug Report

**Current Behavior**
News article with content elements attached. The news article will be translated. The attached content element will become translated too. BUT: in the foreign language there is one additional content element which is in the default language not attached to the news article. The foreign content elements comes from a total different page. 

It is possible to click on the button synchronize with the default language which removes the foreign content element (and throws an exception for every correct content element because they are translated already). But in the database the foreign content element contains still the UID of the news record in the field tx_news_related_news. 

We observe this behavior in a large multi domain installation. The wrong content elements comes from all over the page tree. 

When translating one news after the other often appears the same foreign/wrong content element and the value in tx_news_related_news changed to the new news record ... but sometimes a complete new content element appears. After translating 30 news i am struck with 4 wrong elements which are attached to a news record via tx_news_related_news.  

**Expected behavior/output**
No "ghost"-translation should appear. No content element which is not connected to a news record in the default language should be translated and connected to the translated news record. 

**Environment**
- TYPO3 version(s): 8.7.30
- news version: 7.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**

**Additional context**

**Comment by pmuelhaupt** [comment]
I can confirm this behaviour with news version 6.3.0 and TYPO3 8.7.28
No changes where made to either news or TYPO3, this behaviour suddenly appeared 1 week ago. We also have a large installation with 2.305 news records currently in the database. 
The "wrong" content elements is already localized in the target language and has a correct l10n_source assigned

**Comment by martin-junker** [comment]
> The wrong content elements comes from all over the page tree.

Same problem here. If you then delete the wrong content element from your news it'll be deleted from the page it comes from too.

**Comment by MatzeLandwehr** [comment]
Maybe related to #914?

**Comment by pmuelhaupt** [comment]
Does not seem to be an issue related to tx_news.
I found out that if a tt_content record with "sys_language_uid > 0 AND l18n_parent > 0 AND l10n_parent = 0 AND deleted = 0" is found (which, i guess, should not be the case), this record gets attached to the translated News. The Query comes out of TYPO3\CMS\Core\DataHandling\Localization\DataMapProcessor

**Comment by abeutel** [comment]
Maybe related to https://forge.typo3.org/issues/91430

**Comment by georgringer** [comment]
if those are attached in the backend, then this is not the fault of ext:news as the whole translation process is core and not done by ext:news. closing this issue. if still valid, please open an issue at https://forge.typo3.org/projects/typo3cms-core/issues
