### ISSUE TITLE
links in simplePrevNext not working on seperate detail page

### ISSUE THREAD

**Issue by millemedia** [georgringer/news#1129]
## Bug Report

**Current Behavior**
When a seperate page for showing detail view is used and settings.detail.showPrevNext = 1 then the news title will be shown but no links are rendered. When using list and detail view on one plugin on single page everyting is working.

**Expected behavior/output**
Perv and next links in separate detail view should be rendered .

**Environment**
- TYPO3 version(s): 9.5.13
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Debian Buster (10)

Best regards Andreas

**Comment by georgringer** [comment]
It is called simple prev next and just checks same pid. If you need more, please create a custom vh
