### ISSUE TITLE
Backend: Closing News entry broken

### ISSUE THREAD

**Issue by chris246** [georgringer/news#113]
Hi,

when clicking on the 'x' button to close the edit view in the TYPO3 Backend, the iframe is redirected to an URL like `https://HOST/typo3/'/typo3/index.php?M=web_NewsTxNewsM2&moduleToken=FOO&id=BAR` (note the _/typo3/'/typo3/_ part). As this path is usually not resolved, this sort of breaks the backend until you reselect the page.

Clicking on 'Save and close' results in the same issue.

**Comment by georgringer** [comment]
Resolved with #107
