### ISSUE TITLE
TemplateService->getFileName - Deprectaed

### ISSUE THREAD

**Issue by alexk136** [georgringer/news#1130]
Replace this line $GLOBALS['TSFE']->tmpl->getFileName($path);

with 

$filePathSanitizer = GeneralUtility::makeInstance(\TYPO3\CMS\Frontend\Resource\FilePathSanitizer::class);
$path = $filePathSanitizer->sanitize($path);

according to https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85445-TemplateService-getFileName.html

**Comment by georgringer** [comment]
fixed with 43469c65 in 8.0 branch already.
