### ISSUE TITLE
Backend | Administration | Search by page number

### ISSUE THREAD

**Issue by schmoe-github** [georgringer/news#1131]
## Bug Report

**Current Behavior**
If you enter a page number in the Administration backend module, then nothing happens inside the table. Furthermore there is a JavaScript error that prints:

> /typo3/index.php?route=%2Fweb%2FNewsTxNewsM2%2F&token=9b0e90852f5bb7d4613fcc0be4e0745424357cfe&id=4:2725 Uncaught TypeError: Cannot set property 'action' of undefined
> onclick @ /typo3/index.php?route=%2Fweb%2FNewsTxNewsM2%2F&token=9b0e90852f5bb7d4613fcc0be4e0745424357cfe&id=4:2725
> 

**Expected behavior/output**
The table should paginate to the given page number.

**Environment**
- TYPO3 version(s): 9.5.13
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Possible Solution**
-

**Additional context**
-

**Comment by georgringer** [comment]
not reproduceable and 9.5 is not supported anymore with latest version, therefore closing it
