### ISSUE TITLE
Call to a member function dispatch() on null with TYPO3 10.2.2

### ISSUE THREAD

**Issue by greinerdavid** [georgringer/news#1133]
## Bug Report

**Current Behavior**
While opening the form to create a new news item an error 500 occurs with the following messages

`Call to a member function dispatch() on null`
`in TYPO3.CMS/typo3/sysext/core/Classes/Tree/TableConfiguration/DatabaseTreeDataProvider.php line 305`

**Expected behavior/output**
No errors

**Environment**
- TYPO3 version: 10.2.2
- news version: current 8.0 branch, 8.0.0-dev
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: local Ubuntu 19.10, server CentOS Linux 7
- PHP Version 7.2.10

**Comment by georgringer** [comment]
closed in favor of #1134
