### ISSUE TITLE
error because of missing object in signalslot (tx_news)

### ISSUE THREAD

**Issue by lisardo2** [georgringer/news#1146]
## Bug Report

**Current Behavior**
signal slot extension for tx_news which extends the detailAction. When the detail page is called without valid parameters for a existing news entry the following error is thrown: 

    Oops, an error occurred!
    Argument 1 passed to .....\Slots\NewsControllerSlot::detailActionSlot() must be an instance of GeorgRinger\News\Domain\Model\News, null given

The error is easy to understand:

    public function detailActionSlot(News $newsItem, $currentPage, $demand, $settings, $extendedVariables)

the first parameter $newsItem is missing.

**Expected behavior/output**
No error should be thrown, i would expect an empty page or a redirect to 404. 

**Environment**
- TYPO3 version(s): 9.7.13
- news version: [e.g. 7.0.5]
- Is your TYPO3 installation set up with Composer (Composer Mode): no. 
- OS: unix

**Possible Solution**

**Additional context**

**Comment by DavidBruchmann** [comment]
I'd try if this is working:
```
public function detailActionSlot(News $newsItem = null, $currentPage, $demand, $settings, $extendedVariables)
```

**Comment by lisardo2** [comment]
Hi David, 
perfect, you are right: 

    public function detailActionSlot(News $newsItem = null, $currentPage, $demand, $settings, $extendedVariables)
    {
        if (is_object($newsItem)) { 
            // do stuff here
       }
    }

works perfectly even the 404 is thrown. 

Thanks!!

---

Well, not a bug but an error of mine ... Issue could be closed.

**Comment by DavidBruchmann** [comment]
Glad that it worked Peter ;-)
