### ISSUE TITLE
News written only for english language are also available in default language. Leads to duplicate content

### ISSUE THREAD

**Issue by DaveWoody** [georgringer/news#1158]
## Bug Report

**Current Behavior**
When i am creating a news - setting English as the language and save it, is available here
/news/article/this-is-a-news

All fine. But i found out that the exact same news is available in my default language 
even though it is not declared / translated as a news with german language

/neues/artikel/this-is-a-news

The News itself is english weirdly.

This behavior results in a duplicate content error from google. How do i fix this?

**Expected behavior/output**
News is only available in declared languages.

**Environment**
- TYPO3 version(s): 8.7.3
- news version: 6.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: MAC OSX

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by Gitsko** [comment]
I have the same Problem, @DaveWoody - do you have a soultion ?

**Comment by georgringer** [comment]
this is a core issue and IMO fixed with 9. as I can't do anything here, closing this
