### ISSUE TITLE
Weiterentwicklung

### ISSUE THREAD

**Issue by in-session** [georgringer/news#116]
Hallo Georg,

habe noch ein paar Verbesserungsvorschläge falls gewünscht auf Basis 5.2.0:
- Wenn eine News mit Inhaltselementen erstellt wird und dieses Element ggf. schon angelegt ist, gibt es keine Möglichkeit dieses zu Verknüpfen. Man hat nur die Möglichkeit innerhalb der News ein neues zu erstellen. Ebenfalls ist das Praktisch wenn man mal ein Content von einer News gelöscht hat diese wieder einzufügen ohne es neu anzulegen.
- Zur Sortierung der einzelnen Artikel in der Liste Ansicht wäre es super wenn man auch den Bottom per drag and drop verschieben drinnen hätte. Derzeit werden nur die Pfeile angezeigt, was sehr mühselig ist.

Grüße Chris

**Comment by georgringer** [comment]
magst du zu beiden einen patch machen?

**Comment by georgringer** [comment]
@in-session Sorry, can you describe the 2nd one again. I don't really get it.

**Comment by in-session** [comment]
Hi,

ich kann es Probieren:
Es geht um die manuelle Sortierung von Nachrichten: records.manualSorting
Das ist in der Listenansicht nur mit Hilfe der Pfeile zu Sortieren. Eine Sortierung per Mausklick Verschiebung wäre hier um einiges einfacher und schnellerr. So als wenn man bei Text mit Medien die verschiedenen Bilder sortieren möchte.

Hoffe das ist verständlicher?

Gruß Chris

**Comment by georgringer** [comment]
the list module is done by the core, so I can do nothing there. I am closing the issue therefore here.
checkout https://forge.typo3.org/issues/43134
