### ISSUE TITLE
Support for canonical URLs to link to original news article when syndicating

### ISSUE THREAD

**Issue by mabolek** [georgringer/news#1160]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I recently syndicated an article from richardhaeser.com on typo3.org. Without the possibility to manually add a canonical URL, Google will punish us.

**Describe the solution you'd like**
A "External Canonical URL" field when creating or editing a news article, where I can paste the link to the external article I am syndicating. The content of the field will be inserted into a `rel="canonical"` meta tag in the page header.

**Describe alternatives you've considered**
I have considered writing an extension extending News. However, I think this is a feature that could be useful to more people than myself. I'm therefore first trying to have it accepted as a new feature.

**Teachability, Documentation, Adoption, Migration Strategy**
Users will be able to use this new field with great ease. Educators (and the documentation) can instruct users to paste the URL to the original article in the "External Canonical URL" field. Users will feel happy and cared for. With the amount of unattributed second-hand content on the Internet, this will also serve as a reminder for editors to think before they paste.

**Comment by georgringer** [comment]
this is something which should be done in a 3rd party extension - at least for the start. if you don't or can't create this extension, feel free to contact me
