### ISSUE TITLE
how do i show selected categories ?

### ISSUE THREAD

**Issue by Marat91** [georgringer/news#1162]
how do i show selected categories ?
![4fbe8d89f8](https://user-images.githubusercontent.com/38013831/74846479-8d7d4c00-5341-11ea-9b8c-915f21c8e39c.png)

``<f:section name="categoryTree">
	<div class="category__checkbox">
		<f:for each="{categories}" as="category">
		<div class="checkbox-field category__checkbox--field">
			<label>
                <f:if condition="{category.item.uid} == {overwriteDemand.categories}">
                    <f:then>
							<f:form.checkbox
									property="{category.item.title}."
									value="{category.item.title}"
							        class="category__checkbox--input" />
							<span class="checkbox-custom"></span>
							<div class="modal-label">
								<f:link.page title="{category.item.title}" class="active" pageUid="{settings.listPid}"
											 additionalParams="{tx_news_pi1:{overwriteDemand:{categories: category.item.uid}}}">{category.item.title}
								</f:link.page>
							</div>
                    </f:then>
                    <f:else>
							<f:form.checkbox property="{category.item.title}."
								value="{category.item.title}"
								class="category__checkbox--input" />
						<span class="checkbox-custom"></span>
							<div class="modal-label">
								<f:link.page title="{category.item.title}" pageUid="{settings.listPid}"
											 additionalParams="{tx_news_pi1:{overwriteDemand:{categories: category.item.uid}}}">{category.item.title}
								</f:link.page>
							</div>
                    </f:else>
                </f:if>
                <f:if condition="{category.children}">
                    <f:render section="categoryTreeSub" arguments="{categories: category.children,overwriteDemand:overwriteDemand}" />
                </f:if>
			</label>
		</div>
		</f:for>
	</div>

</f:section>``

**Comment by Marat91** [comment]
`<f:section name="categoryTree">
	<div class="category__checkbox">
		<f:for each="{categories}" as="category">
		<div class="checkbox-field category__checkbox--field">
			<label>
                <f:if condition="{category.item.uid} == {overwriteDemand.categories}">
                    <f:then>
							<f:form.checkbox
									property="{category.item.title}."
									value="{category.item.title}"
							        class="category__checkbox--input" />
							<span class="checkbox-custom"></span>
							<div class="modal-label">
								<f:link.page title="{category.item.title}" class="active" pageUid="{settings.listPid}"
											 additionalParams="{tx_news_pi1:{overwriteDemand:{categories: category.item.uid}}}">{category.item.title}
								</f:link.page>
							</div>
                    </f:then>
                    <f:else>
							<f:form.checkbox property="{category.item.title}."
								value="{category.item.title}"
								class="category__checkbox--input" />
						<span class="checkbox-custom"></span>
							<div class="modal-label">
								<f:link.page title="{category.item.title}" pageUid="{settings.listPid}"
											 additionalParams="{tx_news_pi1:{overwriteDemand:{categories: category.item.uid}}}">{category.item.title}
								</f:link.page>
							</div>
                    </f:else>
                </f:if>

                <f:if condition="{category.children}">
                    <f:render section="categoryTreeSub" arguments="{categories: category.children,overwriteDemand:overwriteDemand}" />
                </f:if>
			</label>
		</div>
		</f:for>
	</div>

</f:section>`

**Comment by georgringer** [comment]
It depends on the view where you need that. in the news list view, you should get those items in fluid within `{categories}`. in the category-list view you get the selected ones with `{overwriteDemand.categories}` and either iterate over all categories or use a custom VH to get the full objects.
