### ISSUE TITLE
Possibility to show more news of the same categories

### ISSUE THREAD

**Issue by dkoether** [georgringer/news#1163]
## Feature Request

**Is your feature request related to a problem? Please describe.**
There is no way (afaik) to show more news from the selected categories of the current news record. I want to provide an area like "more from this topic".

**Describe the solution you'd like**
The possibility to show more news of the same categories as the selected one on the detail page, without the problem below.

**Describe alternatives you've considered**
This typoscript but it's showing the selected news multiple times because 'excludeAlreadyDisplayedNews' wont work and considers only the first category:

```
lib.newsRelatedBySameCategories = USER
lib.newsRelatedBySameCategories {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = News
    pluginName = Pi1
    vendorName = GeorgRinger

    switchableControllerActions {
        News {
            1 = list
        }
    }

    settings < plugin.tx_news.settings
    settings {
        excludeAlreadyDisplayedNews = 1
        templateLayout = previewTeaser
        relatedView = 1
        limit = 4
        useStdWrap := addToList(categories)
        categories.current = 1
        categoryConjunction = or
        disableOverrideDemand = 0
        overrideFlexformSettingsIfEmpty := addToList(detailPid)
    }
}
```

Best regards and thanks in advance, and explicitly said: Keep up the good work! :)

**Comment by georgringer** [comment]
Thanks for your request. I would solve this with a custom VH which would work but as this is not the way how to do it in best practice I won't ship such VH myself
