### ISSUE TITLE
Cannot uncheck crdate and tstamp columns in listview individually

### ISSUE THREAD

**Issue by 99kennetn** [georgringer/news#1165]
## Bug Report

**Current Behavior**
Cannot toggle crdate and tstamp off individually in listview.
temp. fix:  toggle all choices off and save fields, and put the wanted selections back on.

**Expected behavior/output**
when i uncheck crdate or tstamp and press "set fields" it should remove these columns from the listview.

**Environment**
- TYPO3 version: [9.5.14]
- news version: [7.3.1]
- Composer Mode: [yes]
- OS: [Windows 10]

**Additional context**
Add any other context about the problem here
![image](https://user-images.githubusercontent.com/38552536/75238155-d3626600-57c0-11ea-81d3-682714ca84c5.png)
![image](https://user-images.githubusercontent.com/38552536/75238191-de1cfb00-57c0-11ea-90a9-11e8334a1195.png)

**Comment by georgringer** [comment]
if still exists, this is a core issue
