### ISSUE TITLE
Route config for Date year/month + pagination breaks the site with TYPO3 9.5.14

### ISSUE THREAD

**Issue by agendartobias** [georgringer/news#1176]
## Bug Report
Route config for Date year/month + pagination breaks the site with TYPO3 9.5.14. With 9.5.13 it works OK.
`       # Date year/month + pagination:
      - routePath: '/{date-year}/{date-month}/page-{page}'
        _controller: 'News::list'
        _arguments:
          date-month: 'overwriteDemand/month'
          date-year: 'overwriteDemand/year'
          page: '@widget_0/currentPage'
        requirements:
          date-month: '\d+'
          date-year: '\d+'
          page: '\d+'`

When i remove {page} from routePath it's OK, but paginator dont have nice URL

**Environment**
- TYPO3 version(s): 9.5.14
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by chesio** [comment]
Hi @agendartobias , maybe have a look at #1166, it seems that similar problem have been reported (and solved) there.

**Comment by agendartobias** [comment]
It works. Thank you & sory for spamming.
