### ISSUE TITLE
ext:typoscriptRendering t:uri:ajaxAction is deprecated

### ISSUE THREAD

**Issue by TrueType** [georgringer/news#1177]
v7.3.1
see paginate helper. I did not check, when the changes came in EXT:typoscript_rendering. There is a migration within EXT:typoscript_rendering. But that does not prevent EXT:news from breaking, if run with a too old version of EXT:typoscript_rendering, if this helper is changed.

**Comment by georgringer** [comment]
the widget vh have been deprecated and removed, therefore I am not supporting this anymore until I come up with a new solution (if still needed)
