### ISSUE TITLE
Variable {settings.templateLayout} not available in list

### ISSUE THREAD

**Issue by svenkuhn** [georgringer/news#1179]
## Bug Report

**Current Behavior**
If several template options are provided via PageTS using tx_news.templateLayouts {...} the selected option is not passed to Fluid

**Expected behavior/output**
The variable {settings.templateLayout} should be passed to the fluid template.

**Environment**
- TYPO3 9.5.13
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- Linux System at Mittwald (I don't know the version)

**Additional context**
I use the following setup
**Page TSConfig:**
```
tx_news.templateLayouts {
    110 = Listlayout 01
    120 = Listlayout 02
    130 = Detaillayout 01
}
```

**List.html**
```
...
<f:if condition="{news}">
    <f:then>
        <f:debug inline="1">{settings}</f:debug>
        <f:debug inline="1">{contentObjectData}</f:debug>
...
```
The output of the {settings} variable:

> array(25 items)
    cssFile => 'EXT:news/Resources/Public/Css/news-basic.css' (44 chars)
    displayDummyIfNoMedia => '1' (1 chars)
    format => 'html' (4 chars)
    overrideFlexformSettingsIfEmpty => 'cropMaxCharacters,dateField,timeRestriction,archiveRestriction,orderBy,order Direction,backPid,listPid,startingpoint,recursive,list.paginate.itemsPerPage,list.paginate.templatePath' (179 chars)
    allowEmptyStringsForOverwriteDemand => '0' (1 chars)
    includeSubCategories => '0' (1 chars)
    respectSysLanguageInFindInList => '0' (1 chars)
    detailPidDetermination => 'flexform, categories, default' (29 chars)
    defaultDetailPid => '0' (1 chars)
    dateField => 'datetime' (8 chars)
    cropMaxCharacters => '150' (3 chars)
    orderBy => 'datetime' (8 chars)
    orderDirection => 'desc' (4 chars)
    topNewsFirst => '0' (1 chars)
    orderByAllowed => 'sorting,author,uid,title,teaser,author,tstamp,crdate,datetime,categories.title' (78 chars)
    facebookLocale => 'en_US' (5 chars)
    googlePlusLocale => 'en' (2 chars)
    disqusLocale => 'en' (2 chars)
    demandClass => '' (0 chars)
    analytics =>array(1 item)
    link =>array(3 items)
    search =>array(2 items)
    detail =>array(8 items)
    list =>array(3 items)
    opengraph =>array(15 items)

However, the debug output of {contentObjectData} lists the variable 

> ...
flexform_settings.templateLayout => '110' (3 chars). 
...

Due to the unfortunate choice of the variable name it is not possible to access this variable.

**Update**
The same problem exists with the pagination. This can neither be deactivated via the flexform nor can the number of news per page be set.
It seems that none of the flexform values are passed to the settings array.

**Comment by georgringer** [comment]
Never had this problem, can you retest on empty installation?

**Comment by svenkuhn** [comment]
Sorry about the late check-in.
In a bare system everything works as it should.

I've managed to isolate the cause. The problem occurs if the news plugin was created in an element of the extension "gridelements". In this case the flexform data is not passed to the settings.
If the problem is caused by news or gridelements I can't say.

**Comment by georgringer** [comment]
closing it, nothing I can do here IMO.

**Comment by caplod** [comment]
Today I stumbled on the same problem. I am using gridelements as well.

The fix is described here:
https://github.com/CodersCare/gridelements/issues/76

You need to set `resolveChildFlexFormData = 0` in gridelements
