### ISSUE TITLE
Image size in detail view

### ISSUE THREAD

**Issue by biZZa2** [georgringer/news#1180]
Version Typo3 9.5.14
Bootstrap Package 11.0.2

i don't know if my workaround right. In my root template, i add the extensions in following ordner
![Template](https://user-images.githubusercontent.com/61582505/76505027-09eae280-6449-11ea-85bb-b116be015c78.jpg)
 
The object browser shows me, that the bootstrap template loads
![ObjectBrowser](https://user-images.githubusercontent.com/61582505/76505319-90072900-6449-11ea-8de1-f70960a28bde.jpg)
  
In frontend, detail view,  the pictures are in original size, how i can make the pictures smaller?
![DetailView](https://user-images.githubusercontent.com/61582505/76505708-34896b00-644a-11ea-9a5b-4768e449338e.jpg)

**Comment by typo3ua** [comment]
You can try change TypoScript config

`plugin.tx_news {
	settings {
		detail {
			media {
				image {
					maxWidth = 282
					maxHeight =182`

Or to borrow these feature in the Bootstrap Package

**Comment by biZZa2** [comment]
thanks, i had already tried it bevore, it doesn't solve my problem.

>Or to borrow these feature in the Bootstrap Package 

i doens't know how i can do this. I use the bootstrap-package because i can't do it by myself

**Comment by typo3ua** [comment]
...for this is not need much knowledge... it is easily

![ext_news_w_and_h](https://user-images.githubusercontent.com/638022/77226995-11b33100-6b85-11ea-8a83-f20486b3dda6.png)

**Comment by biZZa2** [comment]
thanks for your post. These plugin options has no effect for bootstrap template. 

my solution no was now, to intergate the bootstrap 3.x (LESS) object in template.
