### ISSUE TITLE
News administration returns error on submit: The requested resource "web_NewsTxNewsM2" was not found.

### ISSUE THREAD

**Issue by TheWirsing** [georgringer/news#1181]
## Bug Report

**Current Behavior**
When I try to search for a news item using the news administration I get an error on submit:

(1/1) #1425389240 TYPO3\CMS\Backend\Routing\Exception\ResourceNotFoundException
The requested resource "web_NewsTxNewsM2" was not found.

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 9.5.14
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Manjaro

**Possible Solution**

**Additional context**
The submit button of the administration form lacks a caption (no matter what backend language is selected). Maybe this is a hint for problems loading some resources.

**Comment by typo3ua** [comment]
Strange! I can not reproduce this problem in my instance.

![search_news_error](https://user-images.githubusercontent.com/638022/76898686-da9c0180-689e-11ea-9446-0181255d5076.png)

...search does work well

**Comment by multras** [comment]
I had the same problem, and I solved it here #1147 

hope this helps.

**Comment by TheWirsing** [comment]
Turns out, I was overriding Backend Templates without recognising
