### ISSUE TITLE
No categories available after upgrade to Typo3 v9.5.14

### ISSUE THREAD

**Issue by tobiasd** [georgringer/news#1183]
## Bug Report

**Current Behavior**
No categories can be selected when editing or creating a news article.

**Expected behavior/output**
Categories being select.able.

**Environment**
- TYPO3 version(s): 9.5.14
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Possible Solution**

**Additional context**
I've set up the Typo3 installation with version 9.5.13 and integrated the news extension. After upgrading to v9.5.14 the category listing when creating or editing a news article is empty. Before the upgrade the system categories were shown.

![image](https://user-images.githubusercontent.com/433490/76736256-c94fd980-6766-11ea-9b68-bb652ebe6190.png)

There is a work-around to add / remove the category after the edit of an article, via "Web -> List -> Categories" and then in the "Entries" tab. But being able to select the categories directly would be much more appreciated from the workflow.

(Sorry for the initial empty issue description. Github somehow removed the text during the submission)

**Comment by typo3ua** [comment]
I updated recently TYPO3 to 9.5.14 too, I do not have this issue, I see all added categories.

**Comment by tobiasd** [comment]
Thanks for your replay @typo3ua 

That is somewhat unfortunate for me as it then seems that something went wrong with my update ;-) Any idea where I could look for that? I'd really appreciate any hint as all other things seem to work as expected after the update.

**Comment by typo3ua** [comment]
Hard to say what you need to do...  I do not see what over there in your setup...

I would try to use "Update Wizard", "Analyze Database Structure" and "Flush TYPO3 and PHP Cache".

You also can try to remove all templates in the Tab "Include" -> "Include static (from extensions)" your root "Temple" and leave the only `ext:news`.

...and as the last variant to make a clean install

**Comment by tobiasd** [comment]
Yes, sure you don't see that. As the page just starts out it's basically a Typo3 with the news extension and my own site extension for the styling. Thanks anyways for the hints! I'll have a look.

**Comment by tobiasd** [comment]
Closing as it is now working as expected after a re-installation of Typo3
