### ISSUE TITLE
TCAdefaults.tt_content.imagecols gets ignored

### ISSUE THREAD

**Issue by fritzgithub** [georgringer/news#1188]
Hi,
we use news 7.3.1 and typo3 8.7.31

When I add a regular CE 'Textpic', our usual setting
TCAdefaults.tt_content.imagecols = 1
seems to be ignored  and will show typo-default value '2'.

Outside news, when using textpic, the setting gets respected and shows '1'.

Also other TSConfig gets respected within news.

**Comment by georgringer** [comment]
there is nothing I do in that regard, must be a core issue
