### ISSUE TITLE
Resource "web_NewsTxNewsM2" was not found

### ISSUE THREAD

**Issue by multras** [georgringer/news#1193]
## Bug Report

I click on the module "News Administration" in BE, and when I'm trying to search a newsitem using the filter I get the following error :

`(1/1) #1425389240 TYPO3\CMS\Backend\Routing\Exception\ResourceNotFoundException
The requested resource "web_NewsTxNewsM2" was not found.
in /var/www/src/typo3_src-9.5.14/typo3/sysext/backend/Classes/Routing/Router.php line 78`

- TYPO3 version(s): 9.5.14
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

I tried the [BUGFIX] #751 but the problem still persists.

**Comment by Teisi** [comment]
Same problem here:
TYPO3 version(s): 10.3.0
news version: 8.0.0-dev

**Comment by multras** [comment]
This happens after upgrading the News System extension.

To solve the problem I overwrote the file : 
`\fileadmin\templates\ext\news\Templates\Administration\Index.html`

with the new version of this file from : 
`\typo3conf\ext\news\Resources\Private\Templates\Administration\Index.html`

hope this helps.
