### ISSUE TITLE
News records from wrong news storage displayed

### ISSUE THREAD

**Issue by chris246** [georgringer/news#1194]
## Bug Report

**Current Behavior**
I have to distinct websites (A and B with different domains and news storages), that both have a news entry with the same path_segment but different bodytext.
When opening the detail view on website A, I see the news item of website B (checked by modifying the bodytext).
Furthermore, after changing the path_segment, I can load News from website B on website A and vice-versa by modifying the URL using the respective path_segment.

**Expected behavior/output**
The detail view should respect the defined news storage and load news entries only from the defined storages/folders.

**Environment**
- TYPO3 version(s): 9.5.15
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian 10, PHP 7.3.14

**Additional context**
URL Handling based on this: https://typo3.com/blog/how-to-route-enhancer-for-news

**Comment by georgringer** [comment]
I guess you use the site handling and the slug field still got `uniqueInSite`  in the eval section? This should generate different slugs per site then. if not, this is a core issue.

With `plugin.tx_news.settings.detail.checkPidOfNewsRecord = 1` you can set a startingpoint in the detail view and let the plugin check the pid as well
