### ISSUE TITLE
Invalid argument ClassCacheManager.php

### ISSUE THREAD

**Issue by prdt3e** [georgringer/news#1197]
PHP Warning: Invalid argument supplied for foreach() in /typo3conf/ext/news/Classes/Utility/ClassCacheManager.php line 49

when save a root template.

Typo3: 10.3.0
News: 8.0.0-dev

**Comment by derfony** [comment]
Same here. DDEV Composer setup with georgringer/news:dev-master and TYPO3 10.3.0 in debug mode displays this message whenever a record is saved. As far as I can see records _are_ being saved but after that the exception is thrown. When you do something in the page tree that actually requires the system to save changes (like (un-) hiding or renaming a page), a flash message in red appears (Page tree error, Got unexpected response from the server. Please check logs for details.) and you can then see the above message in the system's log.

The problem also appears in 9.5 (another DDEV composer setup in debug mode). Unlike in 10.3.0 the backend is completely locked with an error message though:

![t3_9 5 15_news_dev-master](https://user-images.githubusercontent.com/13416152/78366800-5a291080-75c1-11ea-942c-adcf6d2b3be3.png)
