### ISSUE TITLE
TCAdefaults for categories

### ISSUE THREAD

**Issue by zelcode** [georgringer/news#1198]
## Bug Report

Is there some changes for TCAdefaults categories, this doesn't work anymore:

**Current Behavior**
```
TCAdefaults.tx_news_domain_model_news {
    categories = sys_category_9
}
```
**Expected behavior/output**

But this works (lucky guess):
```
TCAdefaults.tx_news_domain_model_news {
    categories = 9
}
```

**Comment by typo3ua** [comment]
It is not a bug... You just don't know how it does to do... look at the documentation

```
TCAdefaults {
    tx_news_domain_model_news {
        #  uid of the category default
        categories = 1
        #  uid of the page where storage record categories
        pid = 1
    }
}
```
it does works
