### ISSUE TITLE
Error on News Administration

### ISSUE THREAD

**Issue by BerndSx** [georgringer/news#1199]
## Bug Report

**Current Behavior**
I have upgraded typo3 from 8.7 to 9.5.15. After going through upgrade wizzard, data base check a.s.o. I'm not able to get into News Administration, but I get an FluidError which seems to be related to news extension (namespace n).

I attach the error-log. It is the CRITICAL error, which is related to the issue.

A second error is shown in ALERT with "Oops...", which means that the news are not shown. This might be another issue or may be caused by this one.

It seems to be similar to #897, but on this webspace I never created any own template. I used pure news out of the box without any changes.
[typo3_c04beda92b.log](https://github.com/georgringer/news/files/4434332/typo3_c04beda92b.log)

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 9.5.14
- news version: [e.g. 7.3.1]
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: [e.g. OSX 10.13.4, Windows 10] Linux

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
please remove all administration module templates if you got those in your sitepackage/theme extension and also check your templates if those are outdated.
