### ISSUE TITLE
SimpleNext/Previous link skips news with the same date / time

### ISSUE THREAD

**Issue by RudStar** [georgringer/news#1201]
## Bug Report

**Current Behavior**
I have several news items with the same date / time entry. SimpleNextPrev shows only the first in this group and then jumps to an entry with a more recent or older date.

**Environment**
- TYPO3 version(s): 9.5.14
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Possible Solution**
Extend query by ID?

**Comment by georgringer** [comment]
It is called `Simple` for a reason. I don't know how this can be fixed easily TBH

**Comment by RudStar** [comment]
OK thanks. 
Any tip or tutorial for not `Simple` solution.

**Comment by liayn** [comment]
> I have several news items with the same date / time entry

@RudStar If the timestamps are identical for all those news articles, how should a machine find a deterministic ordering then?
Turning the use-case around: How do you manage to have them all created at the exact same time?

**Comment by RudStar** [comment]
@liayn It is created manually. However, the creation date and time are output in the frontend and must have an exact value. Therefore a different date / time is not possible.

**Comment by liayn** [comment]
Then I suggest adding another field for the "time to show" value and use the existing datetime field to sort the news. Unless there is a mathematically deterministic method to set the order of news, there is no algorithm which can provider such an order.

**Comment by georgringer** [comment]
closing this issue as no change planned
