### ISSUE TITLE
Category menu disappears when Top news are selected

### ISSUE THREAD

**Issue by SeBigBoss** [georgringer/news#1214]
## Bug Report

**Current Behavior**
Hi Georg,
I've an installation at a customer where we have a news category menu in the navigation column and the news list in the other column. Realized with 2 news plugins.
Everything works fine ... except when I check "prefer Top news above". Then the category-navigation-menu disappears.

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 8.7.31
- news version: [e.g. 7.0.5]
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: [e.g. OSX 10.13.4, Windows 10]

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
can't reproduce with latest versions, will close
