### ISSUE TITLE
ext_localconf.php TYPO3_MODE === 'BE'

### ISSUE THREAD

**Issue by prdt3e** [georgringer/news#1221]
You have a condition for BE in ext_localconf.
Wouldn't it make sense to put more parts in these condition?

**Comment by josefglatz** [comment]
I would not:

Regarding the TYPO3 Core ChangeLog rST's an extension developer is advised not to use them. Off course there are exceptions.

---

**Source**: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Important-82692-GuidelinesForExtensionFiles.html

> It is heavily recommended to AVOID checks on `TYPO3_MODE` or `TYPO3_REQUESTTYPE` constants which differentiate between contexts (e.g. `if(TYPO3_MODE === 'BE'))` within these files as it limits the functionality to cache the whole systems’ configuration. Any extension author should remove the checks if not explicitly necessary, and re-evaluate if these context-depending checks could go inside the hooks / caller function directly. **However a check, which isn’t context-depending and only checks for TYPO3 like `defined('TYPO3_MODE') or die();` is no problem.**
