### ISSUE TITLE
Select links using for example a drop-down box

### ISSUE THREAD

**Issue by Epoche-Napoleon** [georgringer/news#1222]
Is it possible in the future not to enter the links manually in the tab "Relations" and to assign the URL, title and description of each link manually, but to reuse existing links from the table tx_news_domain_model_news_links, e.g. via a selection list or similar?

**Comment by georgringer** [comment]
I am closing this in favor of core feature suggestion https://forge.typo3.org/issues/18968. I don't plan to use such thing.

If this is really important to you, we could find a solution which still needs to be funded. contact me via slack if needed
