### ISSUE TITLE
Argument 3 passed to getPluginNameByAction()

### ISSUE THREAD

**Issue by prdt3e** [georgringer/news#1227]
Argument 3 passed to TYPO3\CMS\Extbase\Service\ExtensionService::getPluginNameByAction() must be of the type string, null given, called in /public/typo3/sysext/extbase/Classes/Mvc/Web/Routing/UriBuilder.php on line 579

If I include the search plugin of news.
I set a action="" to f:form
https://github.com/georgringer/news/blob/master/Resources/Private/Templates/News/SearchForm.html

Template Bug !

Typo3: 10.3.0
News: 8.0.0-dev

**Comment by georgringer** [comment]
can you checkout 10.4 released today?

**Comment by prdt3e** [comment]
that works without problems :)
thx
