### ISSUE TITLE
news detail view and related news issue with path_segment / URLs on multi site

### ISSUE THREAD

**Issue by sdesign6** [georgringer/news#1228]
I'm not quite shure if this is a bug, or maybe a missing feature or a configuration issue.

I have a multi-site-setup with two domains and two site trees. 
In site A is a main news-folder with sys_categories. These articles are displayed correctly on site A via plugin configuration "starting point set to site-A news-folder".
In site B is also a news folder and these news are correctly displayed **only** in site B. Now there are some news which are displayed in both sites. e.g. news-to-display-in-site-a-b with category "display-in-site-a-and-b". Detail Page is the same as list page. 

**Problem / Question 1:** 
news-to-display-in-site-a-b from news folder of site A gets displayed on site A and B (which is good, because both have the category), but is linking to a detail view inside each domain.
e.g.
www.domain-a.tld/news1
and 
www.domain-b.tld/news1
Question: Shouldn't the detail view only link to one site, e.g. where the news is stored? Or maybe the news article should at least get a right canonical URL if they are displayed in both domains? Or is this configurable or should be configurable?

**Problem 2:**
In detail view of this news article (news-to-display-in-site-a-b), there are related news items linking to news, which are stored in sysFolder of site A and site B. The Urls of the related news in site B seem to work correct amazingly. The related news-items from site "A" are linking to domain-a.tld and the news-items from storage site "B" are linking to site-b / domain-b. 
But the same news in detail view of site A is only linking all the same related news to site-a / domain-a.

Hard to explain. Thanks in advance.

A problem is, that there is duplicate content and second the hrefs / URLs seem to be wrong.

**Environment**
- TYPO3 version(s): 9.5.15
- news version: 7.3.1
- Composer Mode: no

**Comment by georgringer** [comment]
IMO those are all core issues and nothing I can do within the news ext.

**Comment by sdesign6** [comment]
Thanks, here is the solution: https://github.com/georgringer/news/issues/1258
