### ISSUE TITLE
News Extension with Bootstrap GridColumnItem::getBackendLayout()

### ISSUE THREAD

**Issue by Pestichen** [georgringer/news#1229]
## Bug Report

**Current Behavior**
After installing and inserting the Plugin on a Page everything works fine so far.
But when i try to edit this page in Backend will lead to the following error.
![typo3_error](https://user-images.githubusercontent.com/681027/79950318-2ed66a80-8477-11ea-9877-6a61dd5f3156.png)
https://prnt.sc/s3rlbb
Call to undefined method GridColumnItem::getBackendLayout()

This error only happens on pages with news Plugin in it.

ErrorText from Log:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method  >TYPO3\CMS\Backend\View\BackendLayout\Grid\GridColumnItem::getBackendLayout() \| Error >thrown in file >***/public/typo3/sysext/backend/Classes/Preview/Standar>dContentPreviewRenderer.php in line 172. Requested URL: ***/index.php?>route=%%2Fmodule%%2Fweb%%2Flayout&token=--AnonymizedToken--&id=11
>--

**Expected behavior/output**
Pages with this Plugin should be editable.

**Environment**
- TYPO3 version(s): 10.4.0
- news version: ["georgringer/news": "^8.0"]
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: CentOS 8.1

**Possible Solution**

**Additional context**
My Typo-Project uses the twitter Bootstrap Package

**Comment by MatthiasPeltzer** [comment]
Hi there. I got the same error.

Environment
    TYPO3 version(s): 10.4.0
    Is your TYPO3 installation set up with Composer (Composer Mode): no
    OS: CentOS 7
    PHP: php 7.3

**Comment by Pestichen** [comment]
Good to know, 
that the same error happens without twitter package.
Had already considered deleting all templates so far. :-/

**Comment by georgringer** [comment]
This is an issue in the core fixed with https://review.typo3.org/c/Packages/TYPO3.CMS/+/64297

please just disable the fluid page template in the install tool

**Comment by Pestichen** [comment]
Work like a charm

THX
