### ISSUE TITLE
preview images missing in List/Item partial (5.1.0 and 5.2.0)

### ISSUE THREAD

**Issue by dmnkhhn** [georgringer/news#123]
One of our customers noticed that those nice little preview images in the news listing were missing after we upgraded to EXT:news version 5.1.0.
As we have custom templates I have at first compared our templates to the default templates but the part responsible for rendering the image is exactly the same.
Just to make sure I have also renamed the partial file but that did not help either.

Within the template you are mapping _{newsItem.falMediaPreviews.0}_ to _{mediaElement}_. Debugging this variable reveals no obvious problems but digging deeper the {_mediaElement.originalResource.type}_ seems to be _NULL_ thus none of the conditions are true and none of the ViewHelpers are in use.

When I remove all conditions and use the _{mediaElement}_ variable as the image-attribute for the image-ViewHelper I get an exception:
`The argument "image" was registered with type "object", but is of type "array" in view helper "TYPO3\CMS\Fluid\ViewHelpers\ImageViewHelper"`

Something seems to be off with _{newsItem.falMediaPreviews.0}_…
We are currently running version 5.2.0 but the problem is still there.

The solution, at least for us, was to map _{mediaElement}_ to _{newsItem.firstFalImagePreview}_. This might fail when something else but an image is used as a preview.

The complete code part of the partial (Resources/Private/Partials/List/Item.html) looks like this:

```
<n:link newsItem="{newsItem}" settings="{settings}" title="{newsItem.title}">
  <f:alias map="{mediaElement: newsItem.firstFalImagePreview}">
    <f:image image="{mediaElement}" title="{mediaElement.originalResource.title}" alt="{mediaElement.originalResource.alternative}" maxWidth="{settings.list.media.image.maxWidth}" maxHeight="{settings.list.media.image.maxHeight}"/>
  </f:alias>
</n:link>
```

Greetings,
Dominik

**Comment by Sonezi** [comment]
I am facing a same issuie with this. Couldn't not get to preview image in list view module, getting only dummy image? 
running on news 6.1.1
