### ISSUE TITLE
Call to undefined method TYPO3\CMS\Backend\View\BackendLayout\Grid\GridColumnItem::getBackendLayout()

### ISSUE THREAD

**Issue by Marat91** [georgringer/news#1230]
Call to undefined method TYPO3\CMS\Backend\View\BackendLayout\Grid\GridColumnItem::getBackendLayout()

typo3 v10 immediately after saving the plugin

**Comment by froschdesign** [comment]
Duplicate of #1229

**Comment by georgringer** [comment]
Core issue
