### ISSUE TITLE
detail page title in browser drops to a backend news detail page title

### ISSUE THREAD

**Issue by njuman-alex** [georgringer/news#1245]
## Bug Report
It is not a bug, of course, but i cant figure out how to solve it.
With previous version of News there was all fine.
Sorry for my language, it hard to explain.
**Current Behavior**
For example - I have this page title behaivor for the first time news detail page visit -
**"SiteName: Some NewsRecord Title"** (this is fine, how it should be).

Then when i go to list view, and again click on news to view it in detail (or just refresh the page I'm currently viewing) - page title gets look like this:
**"SiteName: news"** where "**news**" is a page title in the backend page tree, that contains newsDetailView plugin

To override this strange behavior, i use such typoscript setup (But this should not be a permanent solution to the problem, of course)
```
[globalVar = TSFE:id = 7]

config.noPageTitle = 2
temp.newsTitle = RECORDS
temp.newsTitle {
  dontCheckPid = 1
        tables = tx_news_domain_model_news
        source.data = GP:tx_news_pi1|news
        source.intval = 1
        conf.tx_news_domain_model_news = TEXT
        conf.tx_news_domain_model_news {
            field = title
            htmlSpecialChars = 1
        }
        wrap = <title>SiteName:&nbsp;|</title>
}
page.headerData.1 >
page.headerData.1 < temp.newsTitle

[global]
```

**Environment**
- TYPO3 version(s): [9.5.15]
- news version: [8.0.0]
Composer (Composer Mode): [no]

**Comment by georgringer** [comment]
closing it in favor of https://stackoverflow.com/questions/61485138/detail-page-title-in-browser-drops-to-a-backend-news-detail-page-title/61496418?noredirect=1#comment108828273_61496418. no need for duplication
