### ISSUE TITLE
Frontend Editing?

### ISSUE THREAD

**Issue by crochelt** [georgringer/news#125]
Currently there is no frontend editing option for news, which is a key feature for some usage scenarios. Any plans to integrate this in the near future?

**Comment by georgringer** [comment]
I got no plans for that, wanna sponsor it if it is a key feature for your clients?

**Comment by crochelt** [comment]
Hello Georg, 

For my current project this will not be an option, but maybe for future
projects.
How much would that cost and how fast could you implement it? 

Best regards, 

Christine Rochelt 

Am 2016-10-10 11:30, schrieb Georg Ringer:

> I got no plans for that, wanna sponsor it if it is a key feature for your clients? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

  

Links:
------
[1]
https://github.com/georgringer/news/issues/125#issuecomment-252571649
[2]

**Comment by georgringer** [comment]
It depends if you need it based on the regular feedit or as a custom ext (I did something like that 3 years ago https://github.com/georgringer/newsfe). couple of days I guess incl. testing, ... however I can't see how fast if you don't know when. write me a mail if you need it.

**Comment by georgringer** [comment]
IMO the new frontend editing ext can handle that
