### ISSUE TITLE
Minor glitch: Corrupt html in label

### ISSUE THREAD

**Issue by ayacoo** [georgringer/news#1250]
## Bug Report

**Current Behavior**
The html tag from the public/typo3conf/ext/news/Resources/Private/Language/locallang_db.xlf:tx_news_domain_model_tag.seo.seo_title is hown with htmlspecialchars now

**Possible solution**
Just remove the CData and html tag. I think an editor knows also about a "title-tag" :-)

**Environment**
- TYPO3 version(s): 10.4.1
- news version: 8.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10

![image](https://user-images.githubusercontent.com/5963331/80764970-26022a80-8b42-11ea-9c8e-c587f24a7c2b.png)

**Comment by georgringer** [comment]
should be fixed today
