### ISSUE TITLE
Set minimum version to 10.4.1 in composer.json

### ISSUE THREAD

**Issue by helhum** [georgringer/news#1255]
## Bug Report

**Current Behavior**
It is possible to install version 8.1.1 with TYPO3 10.4.0.

**Expected behavior/output**
It is NOT possible to install version 8.1.1 with TYPO3 10.4.0.

**Environment**
- TYPO3 version(s): 10.4.0
- news version: 8.1.1

**Possible Solution**
Set minimum version to 10.4.1 in composer.json
Such version constraint remains impossible to set in ext_emconf.php as long as the news extension is still compatible with 9.5.x, but at least for Composer this can be improved.

**Comment by georgringer** [comment]
@helhum is this related to https://github.com/georgringer/news/issues/1235? IMO there is no code yet which requires 10.4.1 or did I miss something?

**Comment by helhum** [comment]
resolved
