### ISSUE TITLE
Error saving news items in backend

### ISSUE THREAD

**Issue by berndvolke** [georgringer/news#1257]
Hello!

**Current Behavior**

I am using the 8.1.1 version of news with my TYPO3 10.4.1 installation. When saving a news item in the backend I receive the following error in multiple tested installations and changes are not saved:

Oops, an error occurred!
Too few arguments to function TYPO3\CMS\Core\Database\SoftReferenceIndex::__construct(), 0 passed in /var/typo3/typo3_src-10.4.1/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3422 and exactly 1 expected

**Expected behavior/output**

The news item should be saved without errors.

**Environment**
- TYPO3 version: 10.4.1
- news version: 8.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

With kind regards,

Bernd Volke

**Comment by georgringer** [comment]
can you clear caches in install tool? this is nothing news related, therefore I am closing the issue

**Comment by berndvolke** [comment]
Hello!

Yes, I already cleared the TYPO3 and PHP cache but still the same errors 
in multiple installations.

With kind regards,

Bernd

TOUGH werbeagentur GmbH

Peterstrasse 11 | 90478 Nürnberg | Deutschland
Tel +49 911 5303900 | Fax +49 911 5303905
Registergericht Nürnberg HRB 26247 | UST-ID DE815159752
Geschäftsführer: Bernd Lindner

http://www.tough-werbeagentur.de
http://www.facebook.com/TOUGHwerbeagentur

Am 05.05.2020 um 15:35 schrieb Georg Ringer:

**Comment by georgringer** [comment]
are there any other extensions in use then news and core? please disable for testing all others and retest

**Comment by berndvolke** [comment]
Hello!

Thank you very much for your time and input.

After uninstalling non-core extensions i found out that an old extension 
/rte_ckeditor_image /is causing the problem.

Thanks again,

Bernd

Am 05.05.2020 um 16:40 schrieb Georg Ringer:
