### ISSUE TITLE
Slug field is configured as `uniqueInSite`

### ISSUE THREAD

**Issue by helhum** [georgringer/news#1258]
## Bug Report

**Current Behavior**
Slug field is configured as `uniqueInSite`

**Expected behavior/output**
It would be better it would be configured `unique`.

**Rationale**

Obivously many people are storing News in a global folder and render them
on different sites which [broke](https://forge.typo3.org/issues/91235) with
latest TYPO3 release for them, because they still used News' default TCA
altough they use News records globally.

Thing is: The setting being `unique` covers **all** use cases, it only disallows
same slugs for different news in different sites, but nothing breaks hard. Whereas the other way around, you'll get a 404 when trying to render news
from a different site.

**Possible Solution**
Because changing that setting now would be a breaking change, I'd suggest to either release a new major version or evaluate the [feature flag](https://review.typo3.org/64351) and only change that setting for new installations. 

Alternatively a extension setting could be introduced to allow users to easily change that value.

**Comment by georgringer** [comment]
@helhum I would use a custom feature flag + check this feature flag to avoid a state like now. what do you think?

**Comment by georgringer** [comment]
resolved
