### ISSUE TITLE
Adding custom field to all type (best practice)

### ISSUE THREAD

**Issue by Megafry** [georgringer/news#1259]
Hi Georg,
I got a problem by adding a custom field to the table `tx_news_domain_model_news`.
In the backend I can see the new field, I can fill them with content and when I save them they are in the database. So that works fine.
On the frontend it does not show up in the debug.

**Environment**:  TYPO3: `10.4.1`, news: `8.1.1`, Composer: `yes`

After taking a look at the [eventnews](https://github.com/georgringer/eventnews/blob/master/ext_localconf.php#L43) extension, I stumbled upon this line in the `ext_localconf.php`
```php
$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Domain/Model/News'][] = 'eventnews';`
```
I added this line to my extension and now that seems to work.
Is that the right way to go?

PS:
Can you update the manual "[Add a custom type](https://docs.typo3.org/p/georgringer/news/master/en-us/DeveloperManual/ExtendNews/AddCustomType/Index.html#typoscript)" in regard to the [Breaking change: #87623](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html). (TYPO3 10.x)

Thanks for your amazing work and best regards
Megafry

**Comment by JarvisH** [comment]
Hi Megafry,

how to extend the News Model is described here: https://docs.typo3.org/p/georgringer/news/master/en-us/DeveloperManual/ExtendNews/ProxyClassGenerator/Index.html#register-the-class
