### ISSUE TITLE
stdWrap returns string "Array" instead of expected value

### ISSUE THREAD

**Issue by Jpsy** [georgringer/news#126]
Consider the following simple TS:

```
useStdWrap := addToList(categories)
categories.ifEmpty = 5
```

This code always sets the categories property to the string "Array" instead of the value 5.

The bug resides around line 502 of news/Classes/Controller/NewsController.php:

It reads:

```
$originalSettings[$key] = $this->configurationManager->getContentObject()->stdWrap(
    $originalSettings[$key],
    $typoScriptArray[$key . '.']
);
```

It should be:

```
$originalSettings[$key] = $this->configurationManager->getContentObject()->stdWrap(
    $typoScriptArray[$key],    // <-- HERE IS THE DIFFERENCE
    $typoScriptArray[$key . '.']
);
```

The current version fails, if the stdWrap does not set its own content, but simly tries to modify any existing content from $originalSettings.

**Comment by Jpsy** [comment]
A more complete solution would be to fill the default content of the useStdWrapped field with the settings chosen in the plugin incarnation (as described in http://stackoverflow.com/questions/39962216/usestdwrap-conflicts-with-overrideflexformsettingsifempty-in-tx-news/40006158#40006158 ).
This would allow for real stdWrap processing of settings chosen in a plugin incarnation and it would allow to writer TS that only kicks in if no settings are defined within a plugin (which is the standard behavior of overrideFlexformSettingsIfEmpty _without_ useStdWrap.

As currently the default content of useStdWrapped fields is broken (= "Array") this change would _not_ affect any existing news installations.

**Comment by georgringer** [comment]
resolved
