### ISSUE TITLE
Categories list (newsItem.categories) not sorted

### ISSUE THREAD

**Issue by lennsa** [georgringer/news#1263]
## Bug Report

**Current Behavior**
The categories of an article (newsItem.categories) don't get sorted.
They appear in the order the categories are created, not in the sorting order.

**Expected behavior/output**
I suggest sorting the list by the sorting order.

**Environment**
- TYPO3 version: 9.5.16
- news version: 8.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS:

**Comment by Gitsko** [comment]
i may have a similar problem, with me the news can not be sorted, no matter what i create in the plugin, does it work for you?

- TYPO3 version: 10.4.4
- news version: 8.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by georgringer** [comment]
the sorting is always depending on the parent of the category as it is a tree. If you depend on a certain order I suggest to use a VH to sort those - I currently don't plan to change anything
