### ISSUE TITLE
Remove nonexistent OpenGraph properties

### ISSUE THREAD

**Issue by echavaillaz** [georgringer/news#1264]
## Bug Report

**Current Behavior**
Some OpenGraph properties rendered in `Resources/Private/Partials/Detail/Opengraph.html` does not exist (see https://ogp.me)

**Expected behavior/output**
Remove them in the `partials`:
* `og:email`
* `og:phone_number`
* `og:fax_number`
* `og:latitude`
* `og:longitude`
* `og:street-address`
* `og:locality`
* `og:region`
* `og:postal-code`
* `og:country-name`

And remove them also in the settings.

**Environment**
- TYPO3 version(s): 10.4.1
- news version: 8.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 18.04.4

**Possible Solution**
See above.

**Additional context**
Thanks!

**Comment by georgringer** [comment]
those have once be used by FB, don't really know if those are outdated or not

**Comment by echavaillaz** [comment]
If you have a look here, they are not mentioned : https://developers.facebook.com/docs/sharing/webmasters
