### ISSUE TITLE
RSS Feed XML Error because div is in output

### ISSUE THREAD

**Issue by runningnet** [georgringer/news#1265]
Hi,
I use that RSS Integration:
https://docs.typo3.org/p/georgringer/news/8.2/en-us/AdministratorManual/BestPractice/Rss/Index.html#automatic-rss-feeds-based-on-plugins

Now I got this error:
> This page contains the following errors:
> error on line 1 at column 21: XML declaration allowed only at the start of the document
> Below is a rendering of the page up to the first error.

Because the XML starts with:
`<div id="308"> <?xml version="1.0" encoding="utf-8"?>`

I can't remove the div of the output. I checkt the Fluid Style Content List.html Template there is no div. So i think it came via TS but i don't find anything in the TS. 
![TYPO3_CMS_7_6_31_](https://user-images.githubusercontent.com/8833297/81297018-03f13680-9073-11ea-9c63-75e61781735d.jpg)

I Use Typo3 7.6 and News 6.0.0

Thx

**Comment by liayn** [comment]
Seems like you modified your TypoScript in tt_content.* somehow. Otherwise I see no other source where this div-tag should come from.

**Comment by runningnet** [comment]
Sorry my fault. 
Yes it was the List.html Page Layout file.
