### ISSUE TITLE
Month View fehlerhaft?

### ISSUE THREAD

**Issue by HerrGuhr** [georgringer/news#1267]
Hi

ich hoffe es ist ok wenn ich auf deutsch schreibe, wenn nicht bitte bescheid geben und ich schreibe auf englisch.

Kann es sein das die Month-View defekt ist?

Wenn ich es Einstelle taucht direkt ein link zu orf.at auf, es belegt quasi die gesamte Seite und sieht sehr fehlerhaft aus.

Ich kenne mich mit Typo3 (Version 10.4.1) kaum aus, ich versuche für einen Verein wieder ein News System einzurichten (die haben bis jetzt Version 5 oder 6) ...

URL mit der defekten Ansicht per PM?

**Comment by georgringer** [comment]
hey, sorry I once shipped a eventnews view, so the month.html inside ext:news. just remove that and take the one from eventnews.
