### ISSUE TITLE
Plain html code instead of date

### ISSUE THREAD

**Issue by spiderrider** [georgringer/news#1268]
The date in my installation appears enclosed by html code. This is how it looks like with me:

time itemprop="datePublished" datetime="2020-04-27">
27.04.2020
</time>Typo3

Category and author are displayed correctly. How do I get rid of the code?

**Environment**
- TYPO3 version(s): 9.5.16
- news version: 8.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
I have never seen such thing and it depends if you are using the default templates or modified ones. 
I would override the templates you want to change and just remove the markup you don't need.
