### ISSUE TITLE
prevNextHeaderTags removal

### ISSUE THREAD

**Issue by cjanody** [georgringer/news#1269]
## Feature Request

As mention in the link provide in the documentation, Rel=prev/next is not an indexing signal anymore.
https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Remove related code

**Describe alternatives you've considered**
None

**Teachability, Documentation, Adoption, Migration Strategy**
None

**Comment by georgringer** [comment]
i will keep it as it works and there are more search engines out there then google
