### ISSUE TITLE
New slug handling "unique" does not work

### ISSUE THREAD

**Issue by liayn** [georgringer/news#1272]
## Bug Report

**Current Behavior**
An editor used a news title, which is already in use.
The path_segment was generated with no suffix, so it is a duplicate.

**Expected behavior/output**
The path_segment should be suffixed with "-1".

**Environment**
- TYPO3 version(s): 10.4.1
- news version: 8.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**
Maybe needs a fix in Core to have "unique" evaluated for slug-fields.
\TYPO3\CMS\Core\DataHandling\DataHandler::checkValueForSlug

**Comment by georgringer** [comment]
fixed in core today, not a news issue

**Comment by liayn** [comment]
Link for reference: https://forge.typo3.org/issues/91235

**Comment by liayn** [comment]
Still the extension uses a default setting that simply does not work with the released core versions. So the next release of news must require 10.4.2 obviously.

**Comment by georgringer** [comment]
@liayn yes will require next core version when released
