### ISSUE TITLE
older templates do not work anymore getting an error log and an Oops error

### ISSUE THREAD

**Issue by sebastiangaertner** [georgringer/news#1276]
--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1425389240: The requested resource "/web/NewsTxNewsM2/" was not found. | TYPO3\CMS\Backend\Routing\Exception\ResourceNotFoundException thrown in file /homepages/30/d171144326/htdocs/typo3cms/typo3_src-9.5.15/typo3/sysext/backend/Classes/Routing/Router.php in line 78. Requested URL: http://ggggggg.com/typo3/index.php?route=%%2Fweb%%2FNewsTxNewsM2%%2F&token=--AnonymizedToken--&id=3

---

* Slack Chat: [https://typo3.slack.com](https://typo3.slack.com) in channel `#ext-news` (you can sign-up at [https://forger.typo3.com/slack](https://forger.typo3.com/slack) for an invite)
* StackOverflow: https://stackoverflow.com/questions/tagged/tx-news using the tag `tx-news`
* Twitter: If it's just a quick question you can ping [@georg_ringer](https://twitter.com/georg_ringer) on Twitter

**Comment by georgringer** [comment]
closing because lack of a readable issue. sorry
