### ISSUE TITLE
offset Nerd count

### ISSUE THREAD

**Issue by p-Enzi** [georgringer/news#128]

**Comment by p-Enzi** [comment]
The offset for news items has a very nice ;-)) description:
Starting with given news record. 0 means first record, 1 the 2nd one!
Very nerdy - )

How about doing some incredible complicated counting voodoo in PageLayoutView.php instead?
$offset = .... -1
or something like this?

**Comment by t3easy** [comment]
This would break all installations using this.
Or we have to implement a config in extension manager to adjust the offset and change the description. 🤔
Would you like to send in a PR?

**Comment by georgringer** [comment]
I actually don't plan to change it currently, therefore I am closing it
