### ISSUE TITLE
News title is used as Browser title

### ISSUE THREAD

**Issue by BerndSx** [georgringer/news#1280]
## Bug Report

**Current Behavior**
on my start page I have put a single news in detail view. The browser title of the page is changed to the news title instead of the page title. If I deactivate the news, the browser shows the page title again.

**Expected behavior/output**
The news article should not change the page title.

**Environment**
- TYPO3 version(s):9.5.17
- news version: 8.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux
![2020-05-17 22_17_43-news](https://user-images.githubusercontent.com/12103752/82159135-6bd22900-988c-11ea-807a-45b09ab7c9c8.png)

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
Just modify the templates and remove the titletag vh

**Comment by BerndSx** [comment]
Ist das ein gewollter Effekt, dass eine News innerhalb einer Seite den Titel bestimmt?

⁣Gesendet mit BlueMail ​
