### ISSUE TITLE
Slug-Generation fails in multisite systems since version 8.2.0

### ISSUE THREAD

**Issue by neonic** [georgringer/news#1281]
## Bug Report

**Current Behavior**
We have about 10000 news in about 70 projects in our Database and a lot of them have same title.
With the new generation of slugs the latest news with the same title (having the same path segment) is shown in all projects on the detail page.

**Expected behavior/output**
The explicit news is not shown. 

**Environment**
- TYPO3 version(s): 9.5.18
- news version: >= 8.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: OSX 10.15.4, Windows 10

**Possible Solution**
Revert the change, because PersistedAliasMapper do work correctly since Typo3 9.5.16:
https://forge.typo3.org/issues/88720
Or do respect page roots. An url path like "*-1" is not an option regarding all web projects in one system and SEO.

**Additional context**
It seems news >=8.2.0 checks all path segments and do not respect the "is_siteroot".

**Comment by georgringer** [comment]
please open detailed issue at https://forge.typo3.org/projects/typo3cms-core/issues and test latest 9.5.18, this is an core issue if still valid in latest version

**Comment by neonic** [comment]
Ok. I did and it did not work for all projects. I will do so again.
