### ISSUE TITLE
Still Issue with resource /web/NewsTxNewsM2/ 

### ISSUE THREAD

**Issue by anjaspunkt** [georgringer/news#1282]
After Update from 7.3.1 to 8.x.x I still get this error-message:
(1/1) #1425389240 TYPO3\CMS\Backend\Routing\Exception\ResourceNotFoundException 
The requested resource "/web/NewsTxNewsM2/" was not found.

Frontend works fine, but Backend shows this error-message.
This problem seems to appear only in a little bit older installations, with newer ones the update shows no errors.  
Bugfix #751 unfortunately doesn't work with this Backend-Issue :-(

- TYPO3: 9.5.18
- news : 7.3.1 (works fine), 8.x.x (error)
- Composer: no
- Windows 10

Thanks very much for any help!!

**Comment by transdata** [comment]
Try to update your local language.
All extensions
This solved the Problem for me.
