### ISSUE TITLE
contentObjectData not available in Category-List

### ISSUE THREAD

**Issue by mjpr263** [georgringer/news#1283]
## Bug Report

**Current Behavior**
The variable contentObjectData, used e.g. in News-Listing or Detail-View is not available in "Category->List"-Template.

**Expected behavior/output**
The variable contentObjectData should be available in all Templates

**Environment**
- TYPO3 version: 10.4.3
- news version: 8.3.0
- Composer Mode: yes

**Possible Solution**

**Additional context**
I think it's a bug and not an expected behaviour. Without the variable a header, subheader or element-uid is not usable in category-listing.

**Comment by georgringer** [comment]
The `CategoryController` extends the `NewsController` which extends the `NewsBaseController` which sets this in `initializeView`. Do you set the category listing by TypoScript? I can't imagine why this shouldn't work

**Comment by mjpr263** [comment]
No, i added the category-listing as an content-element to the page (Plugin -> News -> What to display: Category Menu). When i add a news-listing on the same page (whether in company with the category-listing or alone), the variable is avaliable.
By the way, the same applies to the "pageData" and "emConfiguration" variable.

**Comment by georgringer** [comment]
just checked that and it works for me, placing a `<f:debug>{_all}</f:debug>` inside `Category/List.html` but maybe you place the debug inside the section `categoryTree` which only recieves categories + overwriteDemand?

**Comment by mjpr263** [comment]
Thats it! Sorry, my fault. So, the error was sitting in front of the screen. ;)

**Comment by georgringer** [comment]
thx for your feedback
