### ISSUE TITLE
n:imageSize inside List.xml breaks the view if the image has not been processed 

### ISSUE THREAD

**Issue by Xippo** [georgringer/news#1287]
## Bug Report

**Current Behavior**
When a Image is not processed, cuz the the max parameters are respected, the viewhelper tries to fetch the size from the processed image. Inside the method getSize() from the ProcessedFile there is the attempt to get the file, so the size can be read, but if the file has not been processed the wrong storage is tried(here maybe we something related with the core a well). So we get an Exception:
Uncaught TYPO3 Exception: #1314516809: File **_fileidentifier_** does not exist. | InvalidArgumentException thrown in file /var/www/html/web/typo3/sysext/core/Classes/Resource/Driver/LocalDriver.php in line 263 

**Environment**
- TYPO3 version(s): 9.5.18
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by Xippo** [comment]
i have added a pull request (#1288) that fixed the bug for me

**Comment by georgringer** [comment]
the viewhelper changed and the fix is not needed anymore
