### ISSUE TITLE
Cannot unserialize 'TYPO3\CMS\Core\Locking\FileLockStrategy'

### ISSUE THREAD

**Issue by typo3ua** [georgringer/news#1290]
```
System:
PHP 7.2
TYPO3 9.5.18
News 8.2.0
```
Related links:
- https://forge.typo3.org/issues/91404
- https://forge.typo3.org/issues/91451
- https://github.com/FluidTYPO3/vhs/issues/1647

I did a new clean install - TYPO3 9.5.18 without an additional custom extension.

Than I added `<v:render.uncache partial="Uncache" arguments="{uid: data.uid}"/>`

The `<v:render.uncache/>` does work well.

**Next step I added custom extension** `ext:bootstrap_package`

I added to him `<v:render.uncache partial="Uncache" arguments="{uid: data.uid, height: settings.logo.height, nav: mainnavigation.0.data.uid}"/>` and checked `{_all -> f:debug(title:'Bootstrap Package')}`
```
### Bootstrap package - uncache work well -> TYPO3 9.5.18 ###
page uid: 1: | logo height: 52 | uid nav item: 4
```
![bs_debug](https://user-images.githubusercontent.com/638022/83557289-0df34180-a51a-11ea-9ac0-865c81c177e2.png)

The `ext:bootstrap_package` passed as arguments only that I wrote and a little more... just because passed argument `height: settings.logo.height` related to `settings.logo` and located inside

![debug_bs](https://user-images.githubusercontent.com/638022/83559752-c79fe180-a51d-11ea-8b47-14808aa263f6.png)

**Next step I added custom extension** `ext:news`

I added to him `<v:render.uncache partial="Detail/Uncache" arguments="{page: pageData.uid, news: newsItem.uid, content: contentObjectData.uid}"/>` and checked `{_all -> f:debug(title:'Detail News')}`
```
### Detail news -> uncache works well -> TYPO3 9.5.18 ###
uid page: 4 | uid news: 3 | uid content: 6
```
![news_debug](https://user-images.githubusercontent.com/638022/83557873-0da77600-a51b-11ea-967a-8816f7aa0944.png)

...but when I repeat visit the detail news page I get an error
```
Oops, an error occurred!
Cannot unserialize TYPO3\CMS\Core\Locking\FileLockStrategy
More information regarding this error might be available online.
```
![debug_news](https://user-images.githubusercontent.com/638022/83558753-2a907900-a51c-11ea-8505-24100b9aeaca.png)

The reason as I think the `settings array` which I do not pass as arguments and it is not under the control, it is very large... I passed only `arguments="{page: pageData.uid, news: newsItem.uid, content: contentObjectData.uid}"` it passes the whole array - `settings (array)`

![news_debug_all](https://user-images.githubusercontent.com/638022/83560803-77298380-a51f-11ea-8828-754cda9f7a66.png)

**...and therefore сan not unserialize**

**I think there are two ways to resolve it:**

1. Not to pass all arguments that are not specified in the `arguments' attribute. It can do an author `ext:news`.
2. Restrict the passing of all arguments that are not specified in the 'arguments' attribute. It can do an author `ext:vhs` and this is will better for the future.

**Comment by georgringer** [comment]
IMO this is a combination of security bugfix in latest core + vhs. I won't change behaviour here

**Comment by typo3ua** [comment]
...then how to define the cause?

**Comment by typo3ua** [comment]
> @NamelessCoder in https://github.com/FluidTYPO3/vhs/issues/1647 wrote:
> Create a new partial to contain the call to v:render.uncache and then use f:render to render that partial, but limit the settings array. This will make the context inside the new partial contain a limited set of variables in {settings}, hopefully avoiding the unserializable ones.

**I did it:**

Install a clean system last version TYPO3 and `ext:bootstrap_package` and `ext:news`

1 step:
In the  `/ext/news/Resources/Private/Templates/News/Detail.html` I added
```
<f:render partial="Detail/RenderWithoutUncache" arguments="{
	page: pageData.uid,
	news: newsItem.uid,
	content: contentObjectData.uid,
	settings: '{startingpoint: settings.startingpoint}'
}"/>
```
2 step:
in the `/ext/news/Resources/Private/Partials/Detail/RenderWithoutUncache.html` I added
```
{_all->f:debug(title:'Render Without Uncache Partial')}

<v:render.uncache partial="Detail/RenderWithUncache" arguments="{
    page: page,
    news: news,
    content: content,
    settings: settings
}"/>

<h3>Render Partial - "f:render"</h3>
<ul>
    <li>Page UID == {page}</li>
    <li>News UID == {news}</li>
    <li>Content UID == {content}</li>
    <li>News settings (startingpoint) == {settings.startingpoint}</li>
</ul>
```
3 step:
In the `/ext/news/Resources/Private/Partials/Detail/RenderWithUncache.html` I added
```
{_all->f:debug(title:'Render With Uncache Partial')}

<h3>Render Partial - "v:render.uncache"</h3>
<ul>
    <li>Page UID == {page}</li>
    <li>News UID == {news}</li>
    <li>Content UID == {content}</li>
    <li>News settings (startingpoint) == {settings.startingpoint}</li>
</ul>
```
## Results:
**Debug:**
![render_partials](https://user-images.githubusercontent.com/638022/84400902-4c1fed80-ac0b-11ea-8bdf-8bd600c636d2.png)
### Render
I go to the `list news` then click record of news and go to the `detail news` all work well I see detail news and my technical information
**News->List->News->detail**

**Render Partial - "v:render.uncache"**
```
- Page UID == 2
- News UID == 4
- Content UID == 2
- News settings (startingpoint) == 3
```
 
**Render Partial - "f:render"**
```
- Page UID == 2
- News UID == 4
- Content UID == 2
- News settings (startingpoint) == 3
```
**But that is where it all well ends.... when I revisit again the same page I get this error**

![cannot_unserialize](https://user-images.githubusercontent.com/638022/84403681-a4a4ba00-ac0e-11ea-9b92-ef1cdb7b12d9.png)

This error appears when I revisit again the same page where the TYPO3 first `can unserialize` but then `cannot unserialize`.

When I first-time visite the page, where the happening "**unserialize**" and the TYPO3 can "**unserialize**" something then all works well and this error does not appear.

This error appears when I revisit again the same page where the TYPO3 first **can unserialize** but then **cannot unserialize**.
