### ISSUE TITLE
RSS links not working

### ISSUE THREAD

**Issue by blackbasket** [georgringer/news#1297]
## Bug Report

**Current Behavior**
I configured RSS in the news extension following the 2nd Option in the documentation (ext. Template). The feed is working as well as the XML page. I also set up the option parameter. But the links are not working. If I try the link from the XML, I see the XML page itself.
The link in the feed mail brings this error: „Sorry, the requested view was not found. The technical reason is: No template was found. View could not be resolved for action ‚detail‘ in class ‚GeorgRinger\News\Controller\NewsController‘.“

**Expected behavior/output**
The link in the feed‘s mail should show the news detail.

**Environment**
- TYPO3 version(s): 9.5.19
- news version: 8.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: SunOS 5.10 (Strato)
- Route Enhancer is used

**Comment by blackbasket** [comment]
I have upgraded my dev environment to 10.4.4 today. After this, the links are shown as they should using route enhancer. But the rssfeed‘s page name is still in the URL, so „Show article“ in the feed‘s mail still shows the rss page itself.

**Comment by georgringer** [comment]
what do you mean with `feed‘s mail ` please give some more information how this can be reproduced

**Comment by georgringer** [comment]
closing issue as really old. feel free to open a new issue if still valid
