### ISSUE TITLE
tx_news.templateLayouts doesn't works as exptected

### ISSUE THREAD

**Issue by frisgaard** [georgringer/news#130]
Hello,

I'm trying to add an alternative template layout, that should be selectable in the configuration form, but the following Page TSConfig-syntax, found in the documentation, doesn't works:
tx_news.templateLayout {
        0 = Default view
        1 = Alternative view
}

Regards
Asger Frisgård

**Comment by r4fx** [comment]
use `tx_news.templateLayouts` not `tx_news.templateLayout `

**Comment by frisgaard** [comment]
I have tried both, but still no effect....

**Comment by r4fx** [comment]
You must reload/save content element with plugin to get fresh settings

**Comment by frisgaard** [comment]
Have tried to do that, but still no effect...

**Comment by r4fx** [comment]
I use below code on my page `TSConfig` and it work as expected, maybe you have syntax error somewhere in another place and this is the cause

```js
tx_news {
    templateLayouts {
        // Portal
        10 = --div--,Portal
        11 = Standard List

        // Expo
        100 = --div--,EXPO
        101 = Slider
    }
}
```

**Comment by frisgaard** [comment]
I've never used Page TSConfig manually before, so I dont think there is a syntax error, but still I can't get your code to work.....

**Comment by jousch** [comment]
I've actually tested [this snippet](https://raw.githubusercontent.com/jousch/TYPO3-Distribution/master/app/web/typo3conf/ext/theme/Configuration/TSConfig/Page/General/TxNews.tsc) with ext:news dev-master and TYPO3 CMS dev-master. It works for me. I've also checked the [documentation](https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Templates/TemplateSelector/Index.html) - seems ok for me.

**Comment by georgringer** [comment]
don't use any compat extension!

**Comment by typo3ua** [comment]
I have last version TYPO3 and ext:News, php 7.2.1

I tested it too
```
tx_news.templateLayouts {
    1 = --div--,Group 1
    2 = Group 1.1
    3 = --div--,Group 2
    4 = Group 2.1
    5 = --div--,Group 3
    6 = Group 3.1
}
```
I get output so:

![tx_news_templateLayouts](https://user-images.githubusercontent.com/638022/54854359-58b0e100-4cfb-11e9-8b87-562e46f25840.png)

...it is not works as expected.

What is wrong?
