### ISSUE TITLE
Page 1 in paginator returns 404

### ISSUE THREAD

**Issue by webian** [georgringer/news#1302]
News paginator generates a link to page 1 that is `/news/page/0/` that returns 404.
It should be `/news/page/1/` or better simply `/news/` (to avoid duplicated content).

**Comment by MrMooky** [comment]
We're having the same issue with news 8.3.0 and TYPO3 9.5.18.

**Comment by xperseguers** [comment]
Facing the same problem, the documentation on https://docs.typo3.org/p/georgringer/news/8.5/en-us/AdministratorManual/BestPractice/Routing/Index.html is wrong, at some point it shows

```
defaults:
  page: '0'
```

at another place (when localizing segment), it shows

```
defaults:
  page: ''
```

If you change that into

```
defaults:
  page: '1'
```

Then everything works!

**Comment by xperseguers** [comment]
As suggested by @echavaillaz I tried to totally remove the `defaults` part for the page and this makes the link to page 1 just much more pretty by totally removing the `page-#` segment and point to the page itself without further decoration.

**Comment by georgringer** [comment]
IMO this works now fine, closing the issue
