### ISSUE TITLE
Add feature to jump to first or last item with showPrevNext

### ISSUE THREAD

**Issue by awi-linkgroup** [georgringer/news#1303]
Hi,
I'd like to use the ViewHelper showPrevNext to create a "loop".

I use only the Prev-function to scroll through my articles, starting from the newest. When reached the very first article in my list, I'd like to jump back to the newest. 
I don't want my visitors the get stuck in a dead end ;-)

Is there a feature that I could already use for this? Like paginated.first or paginated.last?
Would be great.

Using tx_news 8.0.0 @ TYPO3 9.5.19

Regards
Adrian

**Comment by georgringer** [comment]
Hey Adrian,

this feature doesn't exit. I would suggest that you copy the ViewHelper to your own site package and implement it there. feel free to create a PR as well

**Comment by georgringer** [comment]
as no one asked for it in last 4 years and I don't want to make the "simple" vh more complex I am finally rejecting this issue. sorry for such a late response
