### ISSUE TITLE
Change title column from tinytext to varchar(255)

### ISSUE THREAD

**Issue by sksksksk** [georgringer/news#1307]
The title column for each news item is created as a tinytext column. According to MySQL spec, this type of column can use up to 255 **Bytes** of data. 

Using characters with multiple UTF-8 bytes per character (e.g. greek - 2 bytes per character), leads to a maximum title length of 128 characters, which is rather small. 

So my suggestion is to use varchar(255) instead of tinytext. Varchar length counts against the number of characters, and not the number of bytes. The pages table uses varchar(255), too

**Comment by Megafry** [comment]
Hi
You can also overwrite it yourself, create an extension with a dependencies for `news` and add these lines to the file ext_tables.sql:

```sql
CREATE TABLE tx_news_domain_model_news (
	title varchar(255)
);
```
use the Database Analyze to update the field.

best regards

**Comment by sksksksk** [comment]
Hi @Megafry . Thanks for the response. I already did that. The idea was that this would be something of general interest for the extension. If not, it can be marked as "wont fix" or something

**Comment by georgringer** [comment]
@sksksksk can you add a PR for the change and I would be happy to merge it

**Comment by infabo** [comment]
Please review https://github.com/georgringer/news/commit/5661e8d578a073e391598c9dc5315bdc83009cc1#commitcomment-42190291
