### ISSUE TITLE
Custom templateLayouts not working

### ISSUE THREAD

**Issue by m-nicklas** [georgringer/news#1309]
**Current Behavior**
I am adding some templateLayouts, but nothing showing in the selectbox in Backend Plugin

TsConfig
tx_news.templateLayouts {
    1 = News
    2 = List
    3 = Group
}

**Environment**
- TYPO3 version(s): 10.4.3
- news version: 8.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

Do i have to make further settings?

**Comment by georgringer** [comment]
that looks ok. can you check the info modul > page tsconfig if it is available?

**Comment by m-nicklas** [comment]
Oh, i am sorry. I added the Typoscript on the wrong file. Everything works fine!
Thank you!
