### ISSUE TITLE
After activating archive functionality content of all news detail view keep the same

### ISSUE THREAD

**Issue by mathias-noethiger** [georgringer/news#131]
We are using TYPO3 7.6 and news system 4.2.1. We switched on the archive functionality. After clearing all caches and opening a detail view of a first news item, all other detail views showed the content of the first opened news item too. The URL changed but not the content / detail view of the other news items. 
Our work around: switch off the caching l for news pages:

https://www.bms-zuerich.ch/schule/aktivitaeten/aktuell/

 Is there a better way to solve this? Is this a know issue? 

An update of news system version 5 lead to several errors and needed too many adjustments, that we switched back. Our impression was, that the update would not have solved that issue anyway.

**Comment by georgringer** [comment]
IMO this is more a realurl/core issue and not news related? For checking: does it work without realurl enabled?

**Comment by georgringer** [comment]
Closing this issue because of no feedback. Feel free to reopen if still valid
