### ISSUE TITLE
Not yet published news are crawled by crawler and show up in search results leading to 404 

### ISSUE THREAD

**Issue by topsnet-holgerd** [georgringer/news#1313]
## Feature Request
We found that the content of news, that have not yet been published (time scheduled publishing), is crawled by the crawler and will show at the search results. Following these links will lead to 404, since the article has not been published yet.

I like to suggest, to have a switch at the news module, to define, if the contents of a single news will be indexed by crawler and indexed_search or not (maybe as 'no_search'-field similar to the pages table and backend administration of a page).

We are using Typo3 9.5.18 with news 8.3.0

**Comment by georgringer** [comment]
maybe @tomasnorre can help out there?

**Comment by tomasnorre** [comment]
This sounds more like a crawler issue than a News issue, I would like to know how your crawler configuration looks like. There might be a missing "hidden = 0" param. 

Take a look here https://github.com/AOEpeople/crawler/issues/516#issuecomment-627420688
We are having some issues with the 9.0.x version of the Crawler, but the comments here can help you have it running, I think :) 

If you are still having problems I think the issue should be closed here and continued at the crawler issue tracker. 

Please correct me if I'm wrong @georgringer.

**Comment by topsnet-holgerd** [comment]
That seems to work, even if hidden field is 0 and publishing is managed by starttime field. Thanks a lot.

**Comment by georgringer** [comment]
thx @tomasnorre

**Comment by tomasnorre** [comment]
You're welcome.
