### ISSUE TITLE
"Save and Close" not redirecting

### ISSUE THREAD

**Issue by marvin-martian** [georgringer/news#132]
Everytime I was saving and closing a news record via the backend News Administration module I was getting:  "/typo3/'/typo3/index.php was not found on this server." 

My fix was in Resources/Private/Templates/Administration/Index.html 
Line: 182
--  T3_THIS_LOCATION = "{requestUri}";
++ T3_THIS_LOCATION = {requestUri};

It seems the wrapping single quotes in the requestUri variable were  getting URL encoded in the returnUrl GET var:

Browser:  Chrome 53.0.2785.143 m (64-bit)
Typo3: 7.6.11 
EXT: news 5.2.0

**Comment by fjacobi** [comment]
This is fixed with: https://github.com/georgringer/news/commit/12971ed04b7cfeed6f75b0ad4c0465829e239666

**Comment by marvin-martian** [comment]
Ahh.. excellent!
