### ISSUE TITLE
Wrong equal Labels for Media Preview

### ISSUE THREAD

**Issue by cmichael-de** [georgringer/news#1321]
I updated from TYPO3 8 to TYPO3 10.4.5 and I use News 8.3.0 I  have wrong equal labels for Media Preview:

![image](https://user-images.githubusercontent.com/6968063/88337398-f9bc0b80-cd36-11ea-9d40-341bb4692763.png)

**Comment by JarvisH** [comment]
I just tested this in Typo3 10.4.6, and I can not confirm this issue. Have you updated your language packs in the "Maintenance/Wartung" area of the Typo3 Backend?
