### ISSUE TITLE
Exception with time restrictions fields in non-english backends / wrong documentation

### ISSUE THREAD

**Issue by akiessling** [georgringer/news#1322]
## Bug Report

**Current Behavior**
The german translation for e.g. settings.timeRestriction in the plugin flexform shows this string in the CSH:

> Angabe einer Zeitrestriktion. ist die Angabe eine Zahl, wird sie als Sekunden interpretiert. Die Angabe von "86400" entspricht einem Tag (60 * 60 * 24). Alternativ ist die Angabe von "-4 Tagen", "-3 Stunden" möglich. Es ist wichtig, das Minus ("-") anzugeben. Es werden nur die Artikel angezeigt, deren Datum über der angegeben Zeitrestriktion liegt.

Since the field is parsed through strtotime, only english values work and the documented string throws an exception:
`Oops, an error occurred! Code: 20200804125920de05c36c - {"exception":"Exception: Time limit Low could not be resolved to an integer. `

**Expected behavior/output**
An unresolvable field input should be validated and throw an error after saving the plugin, an editor might just set this wrongly and screw up the frontend output. Also the documentation needs to be adapted to only allow valid strtotime inputs.

**Environment**
- news version: 8.3

**Comment by georgringer** [comment]
thanks, changed the translation. will be available in couple of hours
