### ISSUE TITLE
Save & Preview not working on TYPO3 9.5

### ISSUE THREAD

**Issue by bocianl** [georgringer/news#1323]
“Save & Preview” for news records not working on TYPO3 9.5.X

- TYPO3 version(s): 9.5.20
- news version: 8.3
- Is your TYPO3 installation set up with Composer (Composer Mode): NO
- OS: Linux Centos

**Comment by JarvisH** [comment]
Have you followed the directions found here: https://docs.typo3.org/p/georgringer/news/master/en-us/AdministratorManual/BestPractice/PreviewOfRecord/Index.html

What error are you getting?

**Comment by bocianl** [comment]
Yes, I did.

When I click "view" then shows error:

Page Not Found
Reason: No news entry found.

**Comment by blueamerican** [comment]
Have you followed the directions found here: https://docs.typo3.org/p/georgringer/news/master/en-us/AdministratorManual/BestPractice/PreviewOfRecord/Index.html

> yes. But there appears no button "save and preview".
Therefore there is no error

**Comment by blueamerican** [comment]
https://forge.typo3.org/issues/89263

**Comment by simare** [comment]
I had the same problem. Reason was in my case that the news plugin preview-setting was set to "defined in typoscript" which then requires to set `plugin.tx_news.settings.enablePreviewOfHiddenRecords = 1` in TS.

**Comment by bocianl** [comment]
I found a solution for this by Jo Hasenau written on forge:
"While the slug generation itself is still broken, the preview is actually working as soon as you have the configuration on both, source and target page, which is due to #92409"
