### ISSUE TITLE
pagination widget: allow to transfer a configuration item through f:renderChildren

### ISSUE THREAD

**Issue by OpenIT-Projekt** [georgringer/news#1328]
## Feature Request

**Is your feature request related to a problem? Please describe.**

```
<!-- fluid variable x: {x} - has a value -->
<n:widget.paginate objects="{news}" as="paginatedNews" configuration="{settings.list.paginate}"
                                   initial="{offset:settings.offset,limit:settings.limit}">
   <f:for each="{paginatedNews}" as="newsItem" iteration="iter">
                 <!-- x: {x} - empty value -->
   </f:for>
</n:widget.paginate>
```
There is no simple way to transfer any value into the rendered body, like a set of flags (or even just _one_ flag) that influences the rendering, because currently nothing passes through the f:renderChildren wall.

**Describe the solution you'd like**
Allow to transfer a variable into the pagination widget:
* in template: initial='{...,extra:extra}' (fluid variable extra being an array of ['x' => 42 ])
* in widget's special Controller: make it accessible inside the body (i.e. transfer it further into f:renderChildren)
* {extra.x} renders as 42

This requires three simple changes in Classes/ViewHelpers/Widget/Controller/PaginateController.php:
* define a local variable extra
* store initial.extra into it in initializeAction (optionally: make sure that it is an array of only 'plain' values, so serialisation is guaranteed to succeed)
* push it to f:renderChildren container in indexAction

Example code in:
https://github.com/OpenIT-Projekt/news/tree/pb%40cf--202008--widget-paginate--render-children--pass-simple-parameter--master

**Describe alternatives you've considered**
One can of course multiply the n:widget.paginate for each flag combination, but that's rather... ugly.
Another alternative could be to add static properties to the rendered items and re-fetch the values inside the pagination, but that requires that all flags must be unconditionally constant during the whole rendering process (as they must be set before the rendering starts), so one cannot have multiple rendering subsets (e.g. unread and read news, where the unread/read is not stored with the news but sources from the logged in user...).

**Teachability, Documentation, Adoption, Migration Strategy**
Rather simple:
```
<n:widget.paginate ... initial='{...,extra:renderChildrenConfiguration}'>
   <!-- {extra} contains renderChildrenConfiguration -->
</n:widget.paginate>
```

**Comment by X-Tender** [comment]
I stumbled upon this requirement too and "solved" it via 
`<v:variable.register.set name="backgroundPattern" value="{backgroundPattern}"/>`
before the paginate widget and
`{v:variable.register.get(name:"backgroundPattern") -> f:variable(name:"backgroundPattern")}`
inside of it.
However, a native solution for this situation would be great 😄

**Comment by georgringer** [comment]
I am closing it as paginations are removed with TYPO3 11
