### ISSUE TITLE
Settings within flexform disappear after saving

### ISSUE THREAD

**Issue by RinyVT** [georgringer/news#1331]
## Bug Report

**Current Behavior**
When you place a new plugin all the `settings` fields are available, after saving a lot of them disappear because the `BackendUtility` kicks in and hides field based on the selected "What to display".
For example when you place the plugin you can select "List of articles" but after saving that field is not available anymore because that field is only available for the view "List of selected items" and not for "List" which gets saved by default.

**Expected behavior/output**
As the standard view selected is "List", I would suspect that only the fields are shown for that view and after changing the type the fields for the other (selected) view(s) get rendered.

**Environment**
- TYPO3 version(s): 10.4.6
- news version: 8.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**
Maybe instead of only showing/hiding the fields with BackendUtility, also work with `displayCond` within the flexforms?

**Comment by georgringer** [comment]
`displayCond` only can check for current sheets and not other tabs

**Comment by georgringer** [comment]
resolved in upgrade branch
