### ISSUE TITLE
Custom value "categories" ignored on the translated news

### ISSUE THREAD

**Issue by ccmbrother** [georgringer/news#1333]
## Bug Report

**Current Behavior**
We have news in two languages. We have subcategories exposed1, exposed2, etc. News on the front page are shown according to this values. But often we have other subcategories selected for translated news. Therefore we select option Translation behaviour "Custom value" Category on each news. But unfortunatelly this option doesn't work. News category selection from primary language overrides this setting. 

**Expected behavior/output**
We would expect custom value on translated news to work in a way that translated news can have its custom subcategory value and it is shown according to this value.

**Environment**
- TYPO3 version(s): 8.7.30
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Centos 7

**Additional context**

**Comment by ccmbrother** [comment]
Hi there. Is there any tip you can give me around the bug above I posted 1 month ago? 

You need any additional info? Is 7.3.1 version not supported any more? This is the latest version that works with 8.7.30.

Thank you and best regards

**Comment by georgringer** [comment]
I don't support that version for regular bugfixing anymore. You could try https://github.com/georgringer/news/commit/e16807909889336b3c510f4e30ec630492fdcfe3#diff-42ce33b451fdd68496c762462e39ce417b160f54db5433f7553a7953fb86dfffR142 if that works for you.

Feel free to contact me on slack or by mail for paid support
