### ISSUE TITLE
Creating and editing TYPO3 system categories fails with SiteNotFoundException when news extension is active

### ISSUE THREAD

**Issue by Abdull** [georgringer/news#1335]
## Bug Report

**Current Behavior**
Since we updated from TYPO3 9.5.20 to TYPO3 9.5.21, creating or editing a TYPO3 system category, then saving it, throws `#1534710048 TYPO3\CMS\Core\Exception\SiteNotFoundException No pseudo-site found in root line of page 228` within the backend.

It seems to be caused by `news`, as this exception does not happen when `news` is disabled.

Also see: 
* https://forge.typo3.org/issues/89400 (this gave me the hint this exception has to do with `news`; provides a workaround).
* https://stackoverflow.com/q/61316498/923560

**Expected behavior/output**
Creating and editing TYPO3 system categories should work.

**Environment**
- TYPO3 version(s): In our `news`-enabled environments, fiddling with categories works with TYPO3 9.5.20, but fails with TYPO3 9.5.21.
- news version:  7.3.1 and 8.4.0 both cause the reported exception when used in a TYPO3 9.5.21 environment
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10 and Debian

**Possible Solution**
* see https://forge.typo3.org/issues/89400
* disabling `news` :-/

**Comment by georgringer** [comment]
can you test latest version of news (dev-master)?

**Comment by Abdull** [comment]
> can you test latest version of news (dev-master)?

```
$ composer require georgringer/news:dev-master

# ...
Package operations: 0 installs, 1 update, 0 removals
  - Removing georgringer/news (8.4.0)
  - Installing georgringer/news (dev-master 868701f): Cloning 868701f131 from cache
# ... 868701f131 being the latest master commit as of this writing
```

Unfortunately, this doesn't fix the problem - which comes at no surprise, as only documentation has changed from `8.4.0` to 868701f131 ... ( `git diff tags/8.4.0 868701f131`).

**Comment by ShortSnow** [comment]
Problem is described here: https://forge.typo3.org/issues/92331#change-431685 and georg knows about.

**Comment by martin-git-kristensen** [comment]
In news 8.4 change line 144 in Configuration/TCA/Overrides/sys_categori.php to 'displayCond' => 'VERSION:IS:false' will correct this error I think. In Configuration/TCA/tx_news_domain_model_news.php in the 'path_segment' section this change is allreade made.
Martin

**Comment by georgringer** [comment]
resolved

**Comment by Abdull** [comment]
I can confirm that this issue does no longer exist with 8.4.1. Thank you for fixing!

**Comment by ShortSnow** [comment]
Thx a lot
