### ISSUE TITLE
Lightbox in Static Template "News Style Twitter Bootstrap" detail view / bootstrap_package

### ISSUE THREAD

**Issue by dbfischer** [georgringer/news#1340]
## Feature Request

Hi Georg,
in Static Template "News Style Twitter Bootstrap" there is no lightbox function for the image in detail view.
Typoscript for "detail.media" as described in Manual doesn't work.
I use the extension bootstrap_package (I think it's the most used distribution) with works without static template "fluid styled content" or "css styled content".

In /news/Resources/Private/Templates/Styles/Twb/Templates/News/Detail.html there is no code for a lightbox.

I assume it's not so much work to implement this function, is it? And it's not an exotic function. ;-)

I use the lates news 8.4.0 with TYPO3 9.5.
Static Templates:
- Bootstrap Package (Full Package)
- Bootstrap Package (Content Elements)
- Bootstrap Package (Bootstrap 3.x)
- News
- News Styles Twitter Bootstrap
- Indexed Search
- (nothing else)

Thanks in advance!

Best regards
Dirk

**Comment by danaron** [comment]
The solutions is discussed herer: [https://github.com/benjaminkott/bootstrap_package/issues/493](https://github.com/benjaminkott/bootstrap_package/issues/493)

**Comment by dbfischer** [comment]
This solution doesn't work because it uses
news/Resources/Private/Partials/Detail/MediaImage.html

As I can see in site source code the only file used for detail view in frontend is
/news/Resources/Private/Templates/Styles/Twb/Templates/News/Detail.html
This file includes the code for the image and not MediaImage.html.

**Comment by dahaupt** [comment]
Actually this issue is independent of ext:bootstrap_package, the lightbox configuration is simply missing in bootstrap styles.

@georgringer I'd like to create a PR for this using the partial `Detail/MediaContainer` (maybe adjust the styling) to fit bootstrap classes and try to reuse as much of the already existing logic inside those templates. Would you agree with the approach?

**Comment by georgringer** [comment]
I won't change the template as it will lead to more regressions and those can be fully customized anyway
