### ISSUE TITLE
conflit datetime and starttime

### ISSUE THREAD

**Issue by xbouillet** [georgringer/news#1342]
Hello,

We are using typo3 V7.6.46 and eventnews 1.1.1 and news 4.3.1.
Events are displayed in a calendar.

If we fill in the event start (datetime)  date for a event  news item and fill in a publication date (startime) , the contributor cannot click on the event in the calendar.
 If we remove the publication date, the contributor can click on the event in the calendar.

As an admin, you can always click on the events in the calendar.

It seems that there is a conflict between starttime and datetime in the calendar view when we are not in admin.

Any idea ? 

Thanks

**Comment by georgringer** [comment]
hi, no ideas but I don't support such old versions not anymore. please test with latest versions again
