### ISSUE TITLE
plugin.tx_news.settings.topNewsFirst = 1 not working

### ISSUE THREAD

**Issue by hempelta** [georgringer/news#1343]
## Bug Report

**Current Behavior**
Configuration via TypoScript, parameter topNewsFirst 0 or 1 does not seem to have any effect. Sorting in the FE remains unaffected. Class topnews is visible in the FE in the HTML code.
Setting via the plugin checkbox isTopNews works.

**Environment**
- TYPO3 version(s): 10.4.8
- news version: 8.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: MacOS 10.15

`plugin.tx_news {
    settings {
        orderBy = datetime
        orderDirection = desc
        categoryConjunction = or
        includeSubCategories = 0
        archiveRestriction = active
        defaultDetailPid = 35
        listPid = 24
        backPid = 24
        list.paginate.itemsPerPage = 10
        topNewsFirst = 1
        excludeAlreadyDisplayedNews = 1
        displayDummyIfNoMedia = 0
        cssFile >
        detail {
            showPrevNext = 1
            errorHandling = redirectToPage, 24
            media {
                image {
                    maxWidth = 800
                    maxHight = 600
                }
            }
        }
    }

    view {
        layoutRootPaths.100 = EXT:mysitepackage/Resources/Private/Extensions/news/Layouts/
        templateRootPaths.100 = EXT:mysitepackage/Resources/Private/Extensions/news/Templates/
        partialRootPaths.100 = EXT:mysitepackage/Resources/Private/Extensions/news/Partials/
    }
}`

**Comment by georgringer** [comment]
`topNewsFirst` must then also be part of `overrideFlexformSettingsIfEmpty`
