### ISSUE TITLE
[FEATURE] Category Menu: Number of articles per category?

### ISSUE THREAD

**Issue by marvin-martian** [georgringer/news#136]
It would be nice to be able to extract the number of articles per category in the category menu list. You could even remove a category from the menu if it had zero articles assigned. No point in showing a category link if there is no articles in it. 

There is a 'items' field in sys_category table though it does not take into consideration hidden records.

UPDATE: Here is a SQL statement to get the count of articles in a category with a uid = {CATEGORY_UID} that are not deleted or hidden.

```sql
SELECT COUNT(`uid`) AS `article_count` FROM `tx_news_domain_model_news` WHERE `uid` IN (SELECT `uid_foreign` FROM `sys_category_record_mm` WHERE `uid_local` = {CATEGORY_UID} AND `tablenames` LIKE 'tx_news_domain_model_news' AND `fieldname` LIKE 'categories') AND `hidden` = 0 AND `deleted` = 0;
```

**Comment by georgringer** [comment]
Thanks for bringing this up but I am closing it because this solution fits your needs but not all use cases. In many use cases the count needs to check also the pid of the news records or if a news is archived or not and many other fields.
Use a custom ViewHelper to get the numbers you need!

**Comment by marvin-martian** [comment]
> fits your needs but not all use cases

With this statement you could apply to any feature that is submitted by anyone. It is a bit ai ja.. not really a reason. It seems more like you shut it down because the idea is not useful to you? 

The SQL was just an 'example' not a solution of how to get it, of course archive counts could also be easily catered for, it is not so difficult. But displaying a category menu by default that has no articles behind is not very user friendly, you are just creating redundant links in your website. 

The funny thing about extensions is that they are supposed to make our lives easier, not jump through hoops. I am not offended, just confused.  :-)

But fine.. I can do my own ViewHelper , it would have been nice though as an idea, if this was available out of the box for everyone, in the extension where it belongs. 

BTW sorting categories in the category menu is also sub optimal, particularly if your category records are stored in multiple page records.

**Comment by georgringer** [comment]
I am the one who needs to maintain the feature until the end of the life cycle and as I said: The reason is valid but it is not easy to do to fit for everyone. As you said: extensions should make the life easier but that would mean that the category menu plugin would get fully blown up with configurations need to be set to get the correct counts.

I still fully understand your reasons and concerns

**Comment by marvin-martian** [comment]
> category menu plugin would get fully blown up with configurations

As opposed to having no features and being sub-optimal? I don't buy the argument.. in that case you might as well just pull the entire category menu out and save yourself from having to maintain the feature at all... but easy.  :-)
