### ISSUE TITLE
Detailview - showPrevNext: Only switch between news with same "main"-category (get from news-plugin listview) and ignore the other set categories

### ISSUE THREAD

**Issue by enem-frir** [georgringer/news#1365]
**Current situation:**
We have four categories. The news records mostly have more of these categories, not only one.

For each category we have a page (with it's own detailpage) where the news-plugin with listview is integrated.
In the category selection we selected one of the five categories (which is the thema of the page) and for the category mode we defined "Show items with selected categories (AND)".
So only news which have the selected category get shown in the listview, but the news record itself can contain other categories as well.

<img width="1250" alt="news_listview_with_category-selection_category-1" src="https://user-images.githubusercontent.com/2862985/96103486-0e441600-0ed8-11eb-854b-f04fb0bb3eff.png">

On the detailview the function showPrevNext is activated so the user can switch between the news records.

<img width="1250" alt="news_detailpage_in_page_category-1" src="https://user-images.githubusercontent.com/2862985/96103481-0d12e900-0ed8-11eb-91f5-e74a29c2b7d9.png">

**Problem:**
Currently by switching between the records it happens that also records get shown which doesn't have the same "main"-category. This happens because the record has some other categories defined as well and the function consideres this also. 

Is there a possibility to consider the set category from the parent page with the listview, so you only can switch between records in this category and the other categories are ignored?

Thanks in advance.

**Comment by georgringer** [comment]
The VH is called *Simple* for a reason. It is impossible to cover every edge case. Please just copy the VH to your own namespace and adopt to your own needs
