### ISSUE TITLE
Fill in author automatically

### ISSUE THREAD

**Issue by r4fx** [georgringer/news#137]
Hi,

in reference to very old issue (https://forge.typo3.org/issues/33066) 

is there any chance to bring this feature to live ?
I could prepare Pull request if you think that this feature may be integrated.

**Comment by georgringer** [comment]
Use the TsConfig
```
tx_news.predefine.author  = 1
```

sadly not documented, does it work? I would update the docu then

**Comment by r4fx** [comment]
Yeah it works :)
I don't know if it's a bug, 
but it works even when `tx_news.predefine.author  = 0`

**Comment by georgringer** [comment]
yeah need to improve that, thanks!
