### ISSUE TITLE
maxitems configurable in selectedList 

### ISSUE THREAD

**Issue by Nostrabramus** [georgringer/news#1372]
## Feature Request

A client needs to use the news plugin in selectedList mode to choose specific news to show in a specific page, the limiti of 50 is hardcoded in the flexform
```
<!-- selectedList -->
<settings.selectedList>
   <TCEforms>
      <label>LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:flexforms_general.selectedList</label>
      <config>
         <type>group</type>
         <internal_type>db</internal_type>
         <allowed>tx_news_domain_model_news</allowed>
         <size>3</size>
         <maxitems>50</maxitems>
         <minitems>0</minitems>

      </config>
   </TCEforms>
</settings.selectedList>
```

It would be perfect to be able to configure this limit somehow.

We have evaluated to override the flexform on that site in our extension but not being able to be sure of the order in which those configurations are loaded we could not be sure that the override would take place. We have therefore directly modified the news flexform but obviously this modification will be lost when we update the extension.

**Comment by georgringer** [comment]
wanna do a pr and just remove the maxitems?

**Comment by Nostrabramus** [comment]
I didn't do it because I thought that if there was a maximum number of news this was to limit performance problem.
However I see that it has been made in the meantime by ayacoo.
Thanks for your work.

Regards

**Comment by georgringer** [comment]
merged.
