### ISSUE TITLE
Pagination: Link to page 1 is wrong

### ISSUE THREAD

**Issue by format-gmbh** [georgringer/news#1374]
**Current Behavior**
List view with 3 pages
Open page 2
The link to page 1 is wrong: /my-news-list/page/0/
It should be called: /my-news-list/page/1/ 
or
/my-news-list/

**Environment**
- TYPO3 version: 10.4.9
- news version: 8.5.0
- Composer Mode: no

**Comment by Geddo** [comment]
You can easily define 
`defaults:
      page: '1'`
within your sites config to prevent a page 0

**Comment by georgringer** [comment]
can't reproduce and no change planned - closing the issue
