### ISSUE TITLE
CategoryRepository->getSysLanguageUid() is empty on TYPO3 10.4

### ISSUE THREAD

**Issue by runner78** [georgringer/news#1379]
## Bug Report
$GLOBALS['TSFE']->sys_language_* are deprecated since TYPO3 9 and removed from TYPO3 10.

**Current Behavior**
CategoryRepository->getSysLanguageUid() return NULL on TYPO3 10.4

**Expected behavior/output**
Should return the language uid

**Environment**
- TYPO3 version: 10.4.*
- news version: 8.5.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: CentOS 6

**Possible Solution**
Migrate new Context API https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85543-Language-relatedPropertiesInTypoScriptFrontendControllerAndPageRepository.html

**Comment by georgringer** [comment]
fixed with #1404 and released, therefore issue closed
