### ISSUE TITLE
SQL Exeption with >2 selected categories

### ISSUE THREAD

**Issue by PaulMcGregory** [georgringer/news#138]
**switchableControllerActions** = News->list;News->detail or News->list
**categoryConjunction** = or | and 
2 or more selected categories or a main categegory with more than 2 subcategories and **includeSubCategories** = 1

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND (`tx_news_domain_model_news`.`sys_language_uid` IN (0, -1)) AND ((`tx_news' at line 1

**Comment by georgringer** [comment]
So which news version, which core versions are you using?

**Comment by PaulMcGregory** [comment]
TYPO3 8.4.0 (Upgraded directly from 7.x)
News 5.3.0
Bootstrap_package 7.1.0

**Comment by georgringer** [comment]
IMO this was an error of the core, related to the core changes, see https://review.typo3.org/#/c/50368/.
Please update to latest master of the core
