### ISSUE TITLE
News with custom types won't be listed any more

### ISSUE THREAD

**Issue by tomtom-berlin** [georgringer/news#1381]
## Bug Report

**Current Behavior**
added 2 custom types to tx_news_domain_model-news as described here:

https://docs.typo3.org/p/georgringer/news/8.3/en-us/DeveloperManual/ExtendNews/AddCustomType/Index.html

When the editor choose one of this custom types for a news item, the list module does not show that item.

**Expected behavior/output**
The custom type news item shall be listed.

**Environment**
- TYPO3 version(s): 10.4.9
- news version: 8.4.0, 8.4.1, 8.5.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Ubuntu 18.04.5 LTS

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by heluk** [comment]
I have the same issue.
@tomtom-berlin Did you find a solution?

**Comment by georgringer** [comment]
resolved
