### ISSUE TITLE
Adding media, e.g. an image, to a translated news item fails iff the corresponding default language news item does not have an image yet

### ISSUE THREAD

**Issue by Abdull** [georgringer/news#1383]
## Bug Report

**Current Behavior**
On a translated news item, adding a media image fails iff the default-language news item does not have a media image yet.

Example: 
* Create default language (German) news item.
* From this news item create English translation.
* In the English translation, select tab "Medien" -> "Mediendatei [fal_media]" -> "Mediendatei hinzufügen" -> The "Dateiauswahl" modal opens. Browse to existing image in fileadmin. Select this image by clicking on it. THe "Dateiauswahl" modal closes. Back in the "Medien" tab, it appears that the image was added correctly. Click "Speichern"/"Save". Unexpectedly, the image has not been added to the translated news item.

**Expected behavior/output**
Images should be able to be added to news item independently from the "already-has-a-media-image-linked-to-it" state of the default langauge news item.

**Environment**
- TYPO3 version(s): 9.5.22
- news version: 8.5
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian

**Comment by georgringer** [comment]
this is a core issue if still valid, closing it
