### ISSUE TITLE
Incorrect news sorting by title

### ISSUE THREAD

**Issue by p380** [georgringer/news#1385]
News headlines contain utf-8 characters.
Sorting news by title is not displayed correctly, utf-8 is not considered.

regards

**Comment by agendartobias** [comment]
Hmmm same here. Our db is set to utf8mb4 unicode

**Comment by georgringer** [comment]
Is the collation correct? https://stackoverflow.com/questions/10446787/how-can-i-control-utf-8-ordering-in-mysql

**Comment by agendartobias** [comment]
no correct order is; AB**CČ**DEFGHIJKLMNOPR**SŠ**TUV**ZŽ**

**Comment by georgringer** [comment]
so which collation do you use? IMO this is no issue of ext:news

**Comment by georgringer** [comment]
closed as lack of feedback and proposed solution should work fine
