### ISSUE TITLE
Category menu wrong entry level with alternative languages since 8.5.0

### ISSUE THREAD

**Issue by mmunz** [georgringer/news#1387]
## Bug Report

**Current Behavior**
Starting with release 8.5.0 the display of selected categories is wrong on translated pages. With this category tree:

```
- cat-1
  - cat-1-1
- cat-2
```

the categories cat-1 and cat-2 are selected in the plugin configuration.

If viewing the page in default language, the category menu shows cat-1 and cat-2. But if shown in an alternative site language, it shows the subcategories now, in this case cat-1-1

**Expected behavior/output**
The behaviour before was correct, i.e. consistent behaviour between languages.

**Environment**
- TYPO3 version(s): 10.4.x-dev | 10.4.9
- news version: 8.5.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Comment by Aero91** [comment]
I've got a similiar issue. Everything works just fine if the default language is selected, but if I view the translated page it says that thare are now categories available at all. Plugin settings for default language and translatation are identical. Catgories are translated. 


    TYPO3 version(s): 10.4.10
    news version: 8.5.0
    Is your TYPO3 installation set up with Composer (Composer Mode): no
    OS: Linux

**Comment by echavaillaz** [comment]
Fixed with https://github.com/georgringer/news/commit/c3944732b002417b9692c873705321135356e7fd
So this one can be close.

Thanks
