### ISSUE TITLE
sql default '0' for fe_group

### ISSUE THREAD

**Issue by pniederlag** [georgringer/news#1390]
Why is it that field 'fe_group' has a default of '0' and not '' in ext_tables.sql?

Is this intentional? From my understanding fe_group should be '' by default, with the meaning of : "no fe_group related access control intended at all".

**Comment by georgringer** [comment]
thanks @pniederlag, fixed

**Comment by ste101** [comment]
This causes now problems with TYPO3 12.4 and news 11.
News with fe_group=0 leads to a 404.
It worked in TYPO3 10.4.
The news having this problem were imported from tt_news ages ago.
Maybe this could be fixed via 'Update wizard'?

**Comment by ste101** [comment]
Unfortunatelly the issue is not old it occurs after an update from 10.4 to 12.4
