### ISSUE TITLE
Extending showinpreview with a new type

### ISSUE THREAD

**Issue by plojewski** [georgringer/news#1393]
Hi, is there any possibility to add news option to Show in views:

1. Show only in detail views [0]
2. Show in all views [1]
3. Show only in list views [2]
4. Show only in gallery [3]
5. etc.

?

**Comment by georgringer** [comment]
As this is just a regular TCA field you can extend it either with TCA/overrides oder by using tsconfig - there is nothing special by news here:
```
TCEFORM.sys_file_reference.showinpreview {
   # Add another header_layout option:
   addItems.123 = Something else
}
```

**Comment by plojewski** [comment]
Oh right, thank you!
