### ISSUE TITLE
T3 v10: flux element in content_elements not working as expected

### ISSUE THREAD

**Issue by richyr45** [georgringer/news#1394]
## Bug Report

**Current Behavior**
Flux multicol element is insertable but not editable afterwards.
The settings of the flux element opens insted of the content.
In normal content everything works fine, so it seems related to the news extension.

**Expected behavior/output**
In T3 v9 flux content used in contenent_elements were editable and eraseable.

**Environment**
- TYPO3 version(s): 10.4.9
- news version: 8.5.0
- flux: 9.4.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: linux

**Additional comments**
Somehow it seems to connect to the new "Fluid based page module" option in v10 (Feature toggles). If it is active even the insertion if a text element within a flux container fails.

**Comment by georgringer** [comment]
I don't do any special thing here, therefore I am closing issue. this doesn'T mean that this is invalid though
