### ISSUE TITLE
Meta data overwritten with data from news detail

### ISSUE THREAD

**Issue by gtedv** [georgringer/news#1395]
## Bug Report

**Current Behavior**
Meta data of a page, for instance description, title and every og-data will be overwritten with meta data from details of a single news, when a news detail page is integrated in any page. 

**Expected behavior/output**
Meta data should be set only on a single detail page.

**Environment**
- TYPO3 9.5
- news version: 8.5.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

**Possible Solution**
In typo3conf\ext\news\Resources\Private\Templates\News\Detail.html could be a condition which check if a single detail page is rendered. Only in this case should be the partial Detail/Opengraph rendered.

**Additional context**

**Comment by georgringer** [comment]
So when is this not the case?

**Comment by gtedv** [comment]
When for instance list view and detail view is on the same page. This works with a detail view of a selected news.

**Comment by georgringer** [comment]
I am currently not planning to change the implemention. feel free to provide a 3rd party extension which uses of the events to modify the behaviour
