### ISSUE TITLE
Tags not considered in Workspaces

### ISSUE THREAD

**Issue by AnatoliZich** [georgringer/news#1397]
Good Morning 👋 
one of our editors reported that adding or swapping a tag on a news record doesn't show the expected output in the workspace preview of the page. Referenced tags seem to always be taken from the live record, which is different from news and link records as those are properly displayed as changed in the workspace module and preview when actually changed. Thats the case for Extension Version 8.5 running on TYPO3 10.4.10 at least.

I found out that the TCA for the tag does not implement the key `versioningWS`, but news and link do. So i thought i found the culprit but adding the option throws an exception with an SQL error, so i guess this goes a little deeper. Thats the exception i get when adding the option:
`An exception occurred while executing 'SELECT `uid_local`, `uid_foreign`, `sorting`, `uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `deleted`, `hidden`, `t3ver_oid`, `t3ver_id`, `t3_origuid`, `t3ver_wsid`, `t3ver_label`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `title`, `sys_language_uid`, `l10n_parent`, `l10n_diffsource`, `l10n_source`, `slug`, `seo_title`, `seo_description`, `seo_headline`, `seo_text`, `notes`, `l10n_state` FROM `tx_news_domain_model_tag` WHERE (`t3ver_oid` = ?) AND (`t3ver_wsid` = ?) AND (`tx_news_domain_model_tag`.`deleted` = 0) LIMIT 1' with params [...]: Unknown column 'uid_local' in 'field list'`

Im not sure if this is intended or left out, so i guess this could also be a feature request. It would be great to have that implemented aswell.

**Comment by vicdev82** [comment]
Is there any news on this issue?

**Comment by georgringer** [comment]
added it now, thanks for the issue
