### ISSUE TITLE
Add new flexform setting for a "see all articles" button in list view

### ISSUE THREAD

**Issue by christophbee** [georgringer/news#1398]
## Add a possibility to the plugin's flexform in order to enable displaying a button with link to news list page below/above news items 

**Current situation**
When I use the news list on a page where I only display the latest X articles I always add a button below/above saying "See all/further articles". Currently I do this with a default content element. Regarding to this it's quite inconvenient most of the time to adjust the styling of it to integrate the button within list view.

**Display a button with a link to news list page if checkbox is checked in plugin**
Therefore it would be quite useful to provide a checkbox in plugin's flexform that enables a button below/above the X articles saying something like "See all news articles"

**Comment by georgringer** [comment]
I would use this "Page ID for list display"
<img width="412" alt="grafik" src="https://user-images.githubusercontent.com/1905663/100498430-6f5f3a80-3162-11eb-9847-00c8b12c693b.png">
