### ISSUE TITLE
v10 Deprecation: Accessing a cache with the "cache_" prefix as in "news_category" is not necessary anymore

### ISSUE THREAD

**Issue by ayacoo** [georgringer/news#1399]
## Bug Report

I hope that this issue has not yet been reported.

**Current Behavior**
The news extension uses a cache called "cache_news_category". This is no longer necessary as of v10.

https://github.com/georgringer/news/blob/master/ext_localconf.php#L64

**Environment**
- TYPO3 version(s): 10.4.x
- news version: 8.5
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian

**Possible Solution**
Remove the cache_ prefix

**Additional context**
https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Deprecation-88366-DefaultCachingFrameworkCacheNamesChanged.html

**Comment by georgringer** [comment]
thanks. as v9 is still supported I won't change the behaviour until I drop its support

**Comment by ayacoo** [comment]
No problem. I will contact you in 2022 ;-)

**Comment by georgringer** [comment]
:) I guess I will start with migration mid 2021. Checkout https://typo3.org/article/a-first-glimpse-of-typo3-v11 which means v11 will come in 10/2021 and news will be available then as well.
