### ISSUE TITLE
How to deal with the current optional return type in NewsController::detailAction

### ISSUE THREAD

**Issue by AMartinNo1** [georgringer/news#1402]
Currently the `detailAction` has no return type as per declaration yet has an optional return type as seen here:
https://github.com/georgringer/news/blob/master/Classes/Controller/NewsController.php#L392

Due to these issues this error handling may be obsolet:
- https://github.com/georgringer/news/issues/1018
- https://github.com/derhansen/sf_event_mgt/issues/676

How should this be handled? Just add a return hint via phpDoc or …?

**Comment by georgringer** [comment]
phpdoc could be added but wit 11 a proper response needs to be returned anyway
