### ISSUE TITLE
Translation of categories with TYPO3 10 LTS

### ISSUE THREAD

**Issue by cehret** [georgringer/news#1405]
Category -> List does not return category if there is a translation in the selected language in TYPO3 10 LTS

possible fix:

CategoryRepository.php

    `/**
     * Get the current sys language uid
     *
     * @return int
     */
    protected function getSysLanguageUid()
    {
        $sysLanguage = 0;
        if (isset($GLOBALS['TYPO3_REQUEST'])) {
            $sysLanguage = $GLOBALS['TYPO3_REQUEST']->getAttribute('language')->getLanguageId();
        } elseif (isset($GLOBALS['TSFE']) && is_object($GLOBALS['TSFE'])) {
            $sysLanguage = $GLOBALS['TSFE']->sys_language_content;
        } elseif ((int)GeneralUtility::_GP('L')) {
            $sysLanguage = (int)GeneralUtility::_GP('L');
        }

        return $sysLanguage;
    }`

**Comment by toco3** [comment]
A short fix, because the code above breaks the backend module:

`    /**
     * Get the current sys language uid
     *
     * @return int
     */
    protected function getSysLanguageUid()
    {
        $sysLanguage = 0;
        if (isset($GLOBALS['TYPO3_REQUEST']) && TYPO3_MODE != 'BE') {
            $sysLanguage = $GLOBALS['TYPO3_REQUEST']->getAttribute('language')->getLanguageId();
        } elseif (isset($GLOBALS['TSFE']) && is_object($GLOBALS['TSFE'])) {
            $sysLanguage = $GLOBALS['TSFE']->sys_language_content;
        } elseif ((int)GeneralUtility::_GP('L')) {
            $sysLanguage = (int)GeneralUtility::_GP('L');
        }

        return $sysLanguage;
    }`

**Comment by georgringer** [comment]
can you test if it works with release from today (or change from #1404)

**Comment by georgringer** [comment]
closed as no feedback and IMO resolved
