### ISSUE TITLE
Problem with inline core content elements since TYPO3 Update from v10.4.9 to v10.9.11

### ISSUE THREAD

**Issue by q-bic** [georgringer/news#1406]
When trying to edit core content elements in the inline content element tab of the news article, there seems to be a problem with the input fields, for example the header field. If there is already a value in the input fields, the value is not shown in the field, but the value is shown in the title of the inline element. If you try to change or set a new value for the input fields, the change does not happen:
![image](https://user-images.githubusercontent.com/7699805/102352863-9e6e0c80-3fa8-11eb-94c1-2f8c040e6984.png)

It seems the problem is a change in the file from TYPO3v 10.4.10 to v 10.4.11: `typo3_src\typo3\sysext\backend\Resources\Public\JavaScript\FormEngine\Container\InlineControlContainer.js`
When using the same file from the TYPO3 v10.4.10 and everything works just fine. When using the v10.4.11 version of this file, the following JS error occurs:
![image](https://user-images.githubusercontent.com/7699805/102352918-b0e84600-3fa8-11eb-936f-b22a2271c7d8.png)

**Environment**
- TYPO3 version: 10.4.11
- news version: 8.5.0
- OS: Windows 10
- Browser: Chrome 87 & Firefox 84 (didn't try in other browsers)

**Comment by FlorianSpiegel** [comment]
I have the same problem after I updated TYPO3 from 10.4.10 to 10.4.11
Server: Mittwald
news Version: 8.5.0

**Comment by olegkarun** [comment]
Same for me. Few projects same problem. Different Webservers

**Comment by georgringer** [comment]
Please open an issue in core tracker, not a news problem

**Comment by olegkarun** [comment]
@q-bic Could you add this to https://forge.typo3.org/issues or I can do it?

**Comment by olegkarun** [comment]
Done https://forge.typo3.org/issues/93167?next_issue_id=93165

**Comment by georgringer** [comment]
fixed with https://github.com/georgringer/news/pull/1412, sorry guys
