### ISSUE TITLE
Textmedia content elements clear imagewidth and imageheight after save

### ISSUE THREAD

**Issue by kveldscholten** [georgringer/news#1410]
## Bug Report

**Current Behavior**
When i create a textmedia content elements in news it is not possible to define a width and height.
When saving, the fields imagewidth and imageheight are cleared.

**Environment**
- TYPO3 version(s): 10,4,11
- news version: 8.5.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10 with Google Chrome

**Comment by olegkarun** [comment]
Its the same problem https://github.com/georgringer/news/issues/1406

**Comment by georgringer** [comment]
Please open an issue in core tracker, not a news problem

**Comment by olegkarun** [comment]
Done https://forge.typo3.org/issues/93167?next_issue_id=93165

**Comment by georgringer** [comment]
fixed with https://github.com/georgringer/news/pull/1412, sorry guys
