### ISSUE TITLE
Preview link in backend causes RTE fields to disappear

### ISSUE THREAD

**Issue by cehret** [georgringer/news#1423]
**Current Behavior**
I configured the preview functionality in the backend of news records.
Everything works as expected but after clicking the preview button (a new tab opens with the preview and I return to the tab with the backend) the richtext fields in the news edit form disappeared (the headline of the fields are still there, but the RTE is gone and there is no "regular" textarea instead - the content completely disappeared. 

**Expected behavior/output**
I expected the RTE fields to stay ;-) 

**Environment**
- TYPO3 version(s): 10.4.12
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: tested on several OS and Browsers

Bevor clicking on preview:
![image](https://user-images.githubusercontent.com/5031075/104712227-98438b00-5722-11eb-8736-a08b9ef8be12.png)

After clicking on preview and returning to the browser tab with the backend:
![image](https://user-images.githubusercontent.com/5031075/104712378-c1fcb200-5722-11eb-9db2-cd17195883f5.png)

**Comment by georgringer** [comment]
I couldn't reproduce the issue. if still valid in latest news + core, please open an issue at https://forge.typo3.org/projects/typo3cms-core/issues
