### ISSUE TITLE
Improved preview of content element relations has a problem with nested Elements

### ISSUE THREAD

**Issue by cehret** [georgringer/news#1424]
## Bug Report

**Current Behavior**

I enabled the "Improved preview of content element relations".
If I now add a Content Element which also uses IRRE I cannot use the controls of the nested elements because the click on the controls opens or closes the collapsible of the parent element. Only the + button still works.

I tried several nested Elements, e.g.:
![image](https://user-images.githubusercontent.com/5031075/104731710-663f2280-573c-11eb-8323-fc32d757a3bf.png)

If I now click on e.g. the edit icon of a nested element the parent element opens/closes:
![image](https://user-images.githubusercontent.com/5031075/104731862-9d153880-573c-11eb-94fc-0cbb808df913.png)

If I right click on the icons an choose open in new window/tab the right form is loaded and I can edit the element.

**Expected behavior/output**
The default behavior of the nested content elements should be triggered

**Environment**
- TYPO3 version(s):  10.4.12
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: tested on several OS and Browsers

**Comment by georgringer** [comment]
that won't work because of not having JS initialized and I don't plan to add more work here.
