### ISSUE TITLE
Wrong module path in 5.2.0

### ISSUE THREAD

**Issue by schiran** [georgringer/news#143]
Steps to reproduce the bug:
- take a fresh installation typo3 7.6.11
- install news 5.2.0
- create a sysfolder
- with News Administration, create a news in sysfolder
- save and close.
- open the news again.
- save and close
- => the styling of the right frame looks strange
- inspect the path of the right frame: it is: localhost/typo3/'/typo3/index.php?M=web_NewsTxNewsM2...

the path should be: localhost/typo3/index.php?M=web_NewsTxNewsM2...

**Comment by zelcode** [comment]
Hi,

solved with #107, please read the closed issues first.
