### ISSUE TITLE
Hiding contentelements in page view stopped working.

### ISSUE THREAD

**Issue by lennsa** [georgringer/news#1430]
## Bug Report

**Current Behavior**
Contentelements from news entries apper in page view and list view in Typo3 9/10.
The code implemented in 18f742af3d75f7828db5c327651e09446f34ccf3 doesn't seam to work in Typo3 9/10

**Expected behavior/output**
The Hook implemented in 18f742af3d75f7828db5c327651e09446f34ccf3 should hide the contentelements in the page view.

**Environment**
- TYPO3 version(s): 10.4.12
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: docker on ubuntu and debian (bullseye) server

**Possible Solution**
idk

**Additional context**
I checked older installations. The contentelements started to appear with Typo3 9.5.
I am not ruling out an error on my side. But I a was not able to find differences in the configurations between the installations.

**Comment by georgringer** [comment]
works in latest version
