### ISSUE TITLE
News without translation generate page for tranlation with "The news record is not available anymore." displayed...

### ISSUE THREAD

**Issue by cmartin6** [georgringer/news#1432]
## Bug Report

**Current Behavior**
News-entries without translation generate page for translation with "The news record is not available anymore." displayed. The "translated" page is a dead link...

**Expected behavior/output**
News-entries without translation should not have a page for translation?

**Environment**
- TYPO3 version(s): 8.7.30
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX 11.1

**Possible Solution**

**Additional context**

**Comment by georgringer** [comment]
> News-entries without translation generate page for translation

news does not generate pages, what do you mean?

**Comment by cmartin6** [comment]
Of course not. But if we create news-entries without a translation and click the language switcher on the news-detail page in the frontend, the translated news-detail plugin only shows the message "The news record is not available anymore.". The issue here is, that there is no translation for the news record... 

Is there a possibility to check whether the given news record has a translation?

**Comment by georgringer** [comment]
this has been improved with 8.5, see https://docs.typo3.org/p/georgringer/news/master/en-us/Misc/Changelog/8-5-0.html
