### ISSUE TITLE
Error when editing sys_category in sysfolder that is not within a Site

### ISSUE THREAD

**Issue by NamelessCoder** [georgringer/news#1433]
## Bug Report

**Current Behavior**
When editing a sys_category record that exists in a sysfolder that for example is at pid=0, a SiteNotFound exception is thrown. Only relevant for 9.5, source of problem is not applied to config on 10.4+

**Expected behavior/output**
Records from sys_category can be edited regardless of within site or not.

**Environment**
- TYPO3 version(s): 9.5.24
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- MacOS catalina (bug not dependent on OS version though)

**Possible Solution**
The source of the problem is the USER displayCond added to TCA of sys_category when TYPO3 version is < 10.4. This user function uses the site finder to load the current site, which would normally fall back to the pseudo-site, but because there is no Site in the root-line when the containing sysfolder is outside any Site, you get a SiteNotFoundException instead.

Swallowing the exception and making the user function return FALSE in this case, should serve the intention of the displayCond (do not show slug when there is no site).

**Comment by georgringer** [comment]
this has been fixed in one of the latest releases
