### ISSUE TITLE
German Dates in March (März) are not displayed at all, when locale is set to de-DE

### ISSUE THREAD

**Issue by pgr1973** [georgringer/news#1440]
## Bug Report

**Current Behavior**
When the language of the site-configuration is set to 'de-DE' (instead of 'de-DE.UTF8'), fluids dateformatter does not show dates in März (march) at all.

**Expected behavior/output**
Also dates in march (März) should be displayed correctly when using fluids date-viewhelper

**Environment**
- TYPO3 version(s): 10.4.12
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): independent
- OS: Linux (Docker)

**Possible Solution**
Set the language in the site-config to 'de-DE.UTF8'

**Additional context**
This should at least be mentioned in the documentation or maybe even refactored, so that it also works with just 'de-DE'.

**Comment by DavidBruchmann** [comment]
While on Linux 'de-DE' is an ISO-8859 charset it's on Windows an UTF-8 charset whereas 'de-DE.UTF8' never exists on Windows.  
So the OS isn't independent concerning the configuration and has to be switched when changing the OS.

**Comment by pgr1973** [comment]
> While on Linux 'de-DE' is for an ISO-8859 charset it's on Windows for an UTF-8 charset whereas 'de-DE.UTF8' never exists on Windows.
> So the OS isn't independent concerning the configuration and has to be switched when changing the OS.

Sorry, you're probably right. It runs inside of docker-container here, and it skipped my mind that it then has nothing to do with the OS docker is running on. :-)

**Comment by georgringer** [comment]
closing this issue as totally not related to ext:news
