### ISSUE TITLE
Unexpexted behaviour with settings.offset

### ISSUE THREAD

**Issue by maslme** [georgringer/news#1441]
## Bug Report

**Current Behavior**
I have several news in one folder News1, News2, News3, News4 and so on...
I have three tx_news plugins on one page, every plugin is configured the same way, expect the offset (settings.offset) - at the first plugin there is nothing in it, the second plugin is settings.offset = 1 and the third plugin is settings.offset = 2
The three plugins show me now News1, News3 and News4

**Expected behavior/output**
I had expected to get News1, News2 and News3

**Environment**
- TYPO3 version: 10.4.12
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
are you using any language overlays? I guess the limit is set to 1 in every plugin?

**Comment by maslme** [comment]
This Bugreport can be closed. There was an entry in an typoscript template which caused this behaviour - by search for any reason with the language overlays I found that.
Thanks for helping.

**Comment by benwalch** [comment]
I think this is an issue with the new pagination. The offset and limit get rewritten by TYPO3's QueryResultPaginator.
To reproduce:
* Place two news Plugins on the same page, make sure "exclude already displayed news" is not checked.
* Set the limit on the first to 1.
* Set the offset on the second plugin to 1
You will see that the first news entry will be displayed in both plugins.
