### ISSUE TITLE
Own Pagination File does not work

### ISSUE THREAD

**Issue by ursforrer** [georgringer/news#145]
I have written that in the Template under Constans according the documentation.
```
plugin.tx_news {
        view {
                widget.GeorgRinger\News\ViewHelpers\Widget\PaginateViewHelper.templateRootPath = fileadmin/templates/extensions/news/Templates/
        }
}
```

But always the file from the extension will be taken (typo3conf).  The own pagination file is placed under  `fileadmin/templates/extensions/news/Templates/ViewHelpers/Widget/Paginate/Index.html`.

**Comment by georgringer** [comment]
Which TYPO3 version are you using?

**Comment by ursforrer** [comment]
We are using TYPO3 in the version 6.2.27. The used news version is 3.2.6.

**Comment by georgringer** [comment]
I am closing it as 6.2 is not supported anymore. in 8 this is broken currently but pagination template can always set with `configuration="{templatePath:'fileadmin/pagination.html'}"` in the pagination VH

**Comment by lenjka01** [comment]
configuration="{templatePath:'fileadmin/pagination.html'}" 
**doesn't work!**

plugin.tx_news.settings.list.paginate.templatePath = EXT:myExt/news/Private/Templates/Paginate/MyPaginate.html
**doesn't work!**

How can I use my own templatefile?
