### ISSUE TITLE
overwriteDemand[categories] ignored

### ISSUE THREAD

**Issue by clivebeckett** [georgringer/news#1461]
## Bug Report

**Current Behavior**
The links generated in template Category/List.html by:
```
<f:link.page title="{category.item.title}" class="active" pageUid="{settings.listPid}"
    additionalParams="{tx_news_pi1:{overwriteDemand:{categories: category.item.uid}}}">{category.item.title}
</f:link.page>
```
return a URL like:
`?tx_news_pi1[overwriteDemand][categories]=4`

However, this category selection is completely ignored in the list view which still shows all news records regardless of their categorisation.

In contrast the following overwriteDemand works:
```
additionalParams="{tx_news_pi1:{overwriteDemand:{order: 'title desc'}}}
→ output: 
?tx_news_pi1[overwriteDemand][order]=title desc
```

**Expected behavior/output**
The category selection should be respected by the list view.

**Environment**
- TYPO3 version(s): 10.4.9 + 9.5.22
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: macOS 10.14.6 (locally), and some Linux distribution/apache web server (don’t know the details)

**Comment by georgringer** [comment]
Did you set a category mode in the plugin?

**Comment by clivebeckett** [comment]
> Did you set a category mode in the plugin?

No, I hadn’t – and now that I did it works as expected. Thanks a lot … and sorry: I guess I had only associated this setting with the category selection from within the News/List plugin itself.

**Comment by georgringer** [comment]
glad it works now
