### ISSUE TITLE
How do I set a fixed storage PID for new records (newRecordStoragePid)?

### ISSUE THREAD

**Issue by hieblmedia** [georgringer/news#1481]
I need a fixed storage pid for newly created news items.

How i can solve this?
I tried following, but it does not work.
```
plugin.tx_news {
  persistence {
    classes = {
      GeorgRinger\News\Domain\Model\News {
        newRecordStoragePid = 46
      }
      GeorgRinger\News\Domain\Model\NewsDefault {
        newRecordStoragePid = 46
      }
      GeorgRinger\News\Domain\Model\NewsExternal {
        newRecordStoragePid = 46
      }
      GeorgRinger\News\Domain\Model\NewsInternal {
        newRecordStoragePid = 46
      }
    }
  }
}
```

Thanks in advance for any feedback.

**Comment by zelcode** [comment]
Maybe you need this:

https://docs.typo3.org/p/georgringer/news/master/en-us/AdministratorManual/Configuration/TsConfig/Index.html#defaultpid

**Comment by hieblmedia** [comment]
Thanks for the hint.. This basically does the job combined with allowedPage.
https://docs.typo3.org/p/georgringer/news/master/en-us/AdministratorManual/Configuration/TsConfig/Index.html#allowedpage
