### ISSUE TITLE
Can't get detail

### ISSUE THREAD

**Issue by zelcode** [georgringer/news#1482]
## Bug Report

**Current Behavior**
Hey Georg, testing news-11 and can't get news detail, error is:
`(1/1) TypeError`
`Return value of GeorgRinger\News\Domain\Model\News::getRelated() must be of the type array, object returned`

Clean install, introduction package, news and numbered_pagination.

News detail plugin on separate page (and no related news)

![TypeError](https://user-images.githubusercontent.com/7383830/111137092-b1c84e00-857e-11eb-8a1d-7f64ef351001.png)

**Environment**
- TYPO3 version(s): 10.4.13
- news version: 9-dev
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Mint (Ubuntu), Nginx, PHP 7.4.16

**Comment by georgringer** [comment]
thx, fixed
