### ISSUE TITLE
RSS/Atom feed: set page type with setting

### ISSUE THREAD

**Issue by t3easy** [georgringer/news#1491]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We have multiple feeds of news each at it's own page type. The type 9818 is hardcoded in the templates.
https://github.com/georgringer/news/blob/master/Resources/Private/Templates/News/List.atom#L5
https://github.com/georgringer/news/blob/master/Resources/Private/Templates/News/List.xml#L24
So we would have to create own templates just because of this value.

**Describe the solution you'd like**
Add a setting to set the page type, default should be 9818.

**Comment by georgringer** [comment]
please go ahead @t3easy
