### ISSUE TITLE
Pagination: Avoid duplicate url to page-1

### ISSUE THREAD

**Issue by tieupmedia** [georgringer/news#1497]
## Bug Report

**Current Behavior**
Currently the first page of pagination is available via two urls - "/newslist/" and "/newslist/page-1/" - but none has a canonical tag to the other.

**Expected behavior/output**
The link to the first page of pagination should not contain the segment "/newslist/page-1/" or should be related with a correct canonical tag to "/newslist/".

**Environment**
- TYPO3 version(s): 10.4.14
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian

**Possible Solution**

**Additional context**
It seems to be related to the <n:widget.paginate> view helper, <f:widget.paginate> doesn't append a segment for the first pagination page.

**Comment by georgringer** [comment]
switched to the new pagination API and IMO issue solved, otherwise the routing configuration needs to be improved. closing the issue for now

**Comment by medarob** [comment]
the error also happens without the numbered_pagination extensions

The first page of the pagination has the path segment `page-1`

**Comment by riegeo** [comment]
Has this ever been solved?
We have the same problem in TYPO3 12.4.16 and news 11.4.2 
Used the standard configuration from news documentation 

`  
News:
    type: Extbase
    namespace: tx_news_pi1
    limitToPages:
      - 3
      - 26
    routes:
      - routePath: '/'
        _controller: 'News::list'
      - routePath: '/{page-label}-{page}'
        _controller: 'News::list'
        _arguments: {'page': 'currentPage'}
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      - routePath: '/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      - routePath: '/{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
    defaultController: 'News::list'
    defaults:
      page: ''
    requirements:
      page: '\d+'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      page-label:
        type: LocaleModifier
        default: page
        localeMap:
          - locale: 'de_DE.*'
            value: seite
          - locale: 'it_IT.*'
            value: pagina
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
      tag-name:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_tag
        routeFieldName: slug
`

**Comment by mtness** [comment]
Yeah that is still an issue.

I solve this by removeing "/page-1" in the canonical tag on that page:

```
[page && page["uid"] == {$YOUR_NEWS_LIST_PAGE}]
	# Remove original canonical tag
	config.disableCanonical = 1
	# Add adjusted canonical tag for newslist/page-x
	page.headerData.20 = TEXT
	page.headerData.20 {
			stdWrap {
				typolink {
					parameter.data = TSFE:id
					forceAbsoluteUrl = 1
					returnLast = url
					parameter.intval = 1
					addQueryString = 1
				}
			}
			htmlSpecialChars = 1
			wrap = <link href="|" rel="canonical" />
	}
[ page && page["uid"] == {$YOUR_NEWS_LIST_PAGE} && traverse(request.getQueryParams(), 'tx_news_pi1/currentPage') == 1 ]
        #remove /page-1 from canonical if present
	page.headerData.20.stdWrap.typolink.addQueryString.exclude = tx_news_pi1[currentPage]

[end]
```
