### ISSUE TITLE
Use language aspect since TYPO3 9 instead of 10

### ISSUE THREAD

**Issue by sypets** [georgringer/news#1499]
## Bug Report

**Current Behavior**

news/Classes/Domain/Repository/CategoryRepository.php
```
if (GeneralUtility::makeInstance(Typo3Version::class)->getMajorVersion() === 10) {
            $sysLanguage = GeneralUtility::makeInstance(Context::class)->getPropertyFromAspect('language', 'id');
} elseif (isset($GLOBALS['TSFE']) && is_object($GLOBALS['TSFE'])) {
            $sysLanguage = $GLOBALS['TSFE']->sys_language_content;
} elseif ((int)GeneralUtility::_GP('L')) {
            $sysLanguage = (int)GeneralUtility::_GP('L');
}
```

This will log a deprecation notice in 9. 

`  54876  Property $TSFE->sys_language_content is not in use anymore as this information is now stored within the language aspect. in /var/www/www.uni-oldenburg.de/htdocs/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php line 5196 
`

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85543-Language-relatedPropertiesInTypoScriptFrontendControllerAndPageRepository.html

**Expected behavior/output**

Reduce deprecation logs in 9.

**Environment**
- TYPO3 version(s): 9.5.26 (latest)
- news version: 8.5.2 (latest)
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: irrelevant

**Possible Solution**

The new code could be used since v9 instead.

**Additional context**

**Comment by georgringer** [comment]
solved in the meantime
