### ISSUE TITLE
MetaTag Type must fit given argument

### ISSUE THREAD

**Issue by AlexVossBu** [georgringer/news#1507]
https://github.com/georgringer/news/blob/ee889f83f92afa3fb427d5614d0adb4f1a205402/Classes/ViewHelpers/MetaTagViewHelper.php#L90

If  `$arguments['name']` is given, please set metaTag Type to 'name' e.g. `$pageRenderer->setMetaTag('name', $arguments['name'], $content);`

Referring to https://www.w3schools.com/tags/tag_meta.asp#:~:text=The%20tag%20defines%20metadata,the%20document%2C%20and%20viewport%20settings and other sources

**Comment by chesio** [comment]
It seems this issue has been fixed, but only in 11 branch: https://github.com/georgringer/news/commit/e42d3705330ab4ab5c20c8303f9c258c1cecdb70

**Comment by georgringer** [comment]
solved with #1425
