### ISSUE TITLE
CategoryController OverwriteDemand

### ISSUE THREAD

**Issue by develth** [georgringer/news#1508]
## Bug Report

**Current Behavior**
Cannot overwrite Category $idList in `CategoryControler -> list`

**Expected behavior/output**
Able to set settings via overwriteDemand

**Environment**
- TYPO3 version(s): 9.5.26
- news version: 8.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian Stretch

**Possible Solution**
Replace
https://github.com/georgringer/news/blob/ee889f83f92afa3fb427d5614d0adb4f1a205402/Classes/Controller/CategoryController.php#L47

with e.g.

`$idList = is_array($demand->getCategories())?$demand->getCategories():explode(',', $demand->getCategories());`

getCategories() is defined as array, but IMHO also could be a string

**Comment by georgringer** [comment]
merged
