### ISSUE TITLE
Wizard "Updates slug field "path_segment" of EXT:news records" fails on PHP 7.4

### ISSUE THREAD

**Issue by arktiklite** [georgringer/news#1516]
## Bug Report

**Current Behavior**
During an upgrade from TYPO3 8 LTS to TYPO3 9 LTS, the Install Tool wizard "Updates slug field "path_segment" of EXT:news records" fails. 

**Expected behavior/output**
The following expcetion occurs:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Runtime Deprecation Notice: Array and string offset access syntax with curly braces is deprecated in {PATH}/typo3conf/ext/news/Classes/Service/Transliterator/Transliterator.php line 357 | TYPO3\CMS\Core\Error\Exception thrown in file {PATH}/typo3_src-9.5.27/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 124. Requested URL: {TLD}/typo3/install.php?install[controller]=upgrade&install[context]=backend`

**Environment**
- TYPO3 version: 9.5.27
- news version: 8.5.2

**Possible Solution**
A workaround was do temporarily downgrade PHP from 7.4 to 7.2

**Comment by georgringer** [comment]
this service has been removed with b9aedf7abef7f31d16c21c17b9e2f0d1ec6725f5 and is not needed anymore. therefore I am closing this issue
