### ISSUE TITLE
PHP 7 warning in eventnews 1.1.1, still present

### ISSUE THREAD

**Issue by via-lars** [georgringer/news#152]
Hello,

on adding a News System plugin as a content element, we get

"Declaration of GeorgRinger\Eventnews\Hooks\BackendUtility::updateFlexforms(&$params, &$reference) should be compatible with GeorgRinger\News\Hooks\BackendUtility::updateFlexforms(array &$dataStructure, array $row) in /html/typo3/typo3conf/ext/eventnews/Classes/Hooks/BackendUtility.php line 51"

This was fixed in https://github.com/georgringer/news/issues/68 ?

No unwanted consequences apparently. 

Our system:

Operating system:	Unix
PHP version:	7.0.9
PHP CGI detected:	Yes

eventnews 1.1.1
News 5.2.0

Typo3 7.6.11

**Comment by georgringer** [comment]
yes fixed and a problem of eventnews, not news. so if still valid, open an issue there
