### ISSUE TITLE
Use default image loading property of fluid_styled_content

### ISSUE THREAD

**Issue by t3easy** [georgringer/news#1522]
## Feature Request

**Describe the solution you'd like**
The default templates could use the loading property of fluid_styled_content
Only some small changes are necessary.

1. Add a TypoScript setting which use the constant `{$styles.content.image.lazyLoading}`
2. Set the constant with a condition in TYPO3 9.5 `[typo3.branch == "9.5"]`
3. Add `additionalAttributes="{loading: settings.media.lazyLoading}"` to all f:image tags to be compatible with TYPO3 9.5

**Comment by t3easy** [comment]
If this gets accepted I could send a PR.

**Comment by georgringer** [comment]
accepted, go ahead
