### ISSUE TITLE
Control (no)index and (no)follow of each news

### ISSUE THREAD

**Issue by t3easy** [georgringer/news#1525]
## Feature Request

**Is your feature request related to a problem? Please describe.**
If i set the `index this site` switch of a news detail page to noindex, it gets removed from the core seo sitemap but all news also habe noindex in the head.
If i set it to index, the detail page is in the pages sitemap without any news to display and ext:news sends 404 header because no news is given.
Google search console is unhappy because I send pages that send 404.

**Describe the solution you'd like**
I want to remove the detail page without a displayed news from the sitemap and set it to noindex but let search engine index the news.
Therefore each news should have (no)index and (no)follow settings that overrules the page settings.

**Comment by ste101** [comment]
You could leave no_index = 0 an add this to the sitemap config:
```
            pages {
                config {
                    additionalWhere := appendString( AND uid != 54)
                }
            }
```
But I would also like to see no_index in the seo tab of news because there are some news that are not worth to get indexed because they are only temporary like 'new year greatings'.
In this case the no_index meta would be useful.

**Comment by christophlehmann** [comment]
I do it like this

* Set no_index on detail pages
* Use in pages sitemap `additionalWhere = AND no_index=0`

This way, detail pages are not in the sitemap. And then activate index,follow for the news detail view

```
[traverse(request.getQueryParams(), 'tx_news_pi1/news') > 0]
    page.meta.robots = TEXT
    page.meta.robots {
        value = index,follow
        replace = 1
    }
[global]
```

Would you like add it in the documentation if it fits your needs?

**Comment by ste101** [comment]
> Would you like add it in the documentation if it fits your needs?

You can find this already here:
https://docs.typo3.org/p/georgringer/news/8.5/en-us/AdministratorManual/BestPractice/Seo/Index.html#robots-allow-indexing-of-news-records-but-set-noindex-to-the-detail-page

**Comment by christophlehmann** [comment]
Great. We don't to add it ;)

**Comment by georgringer** [comment]
@t3easy should we close the issue?

**Comment by t3easy** [comment]
I would leave it open to implement a per news (no)index and (no)follow setting.

**Comment by georgringer** [comment]
I am closing this issue as I don't plan to implement it.

if someone needs it, feel free to sponsor it and contact me in private
