### ISSUE TITLE
Routing with multiple categories filter

### ISSUE THREAD

**Issue by bavarianbytes** [georgringer/news#1527]
## Bug Report

**Current Behavior**
If i use multiple categories as filter as [described](https://docs.typo3.org/p/georgringer/news/master/en-us/Tutorials/Templates/MultiCategorySelection/Index.html) in the docs the [routing](https://docs.typo3.org/p/georgringer/news/master/en-us/AdministratorManual/BestPractice/Routing/Index.html#basic-setup-including-categories-tags-and-the-rss-atom-feed) only uses one category.

**Environment**
- TYPO3 version(s): 10.4.17
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: MacOS

**Possible Solution**
Maybe there is a way to configure the routing so that it also works with multiple category values in one URL GET parameter. Then it is maybe a good idea to add that as an example to the docs.

**Comment by ste101** [comment]
I made a custom aspect. It works but a link to a none existing news results in an error:
```Parameter "b5328cd702ab53e1ee8275c963410e1" for route "tx_news_pi1_1" must match ".+" ("" given) to generate a corresponding URL.```

```
<?php

declare(strict_types=1);

namespace Buepro\UserPizpalue\Routing\Aspect;

use TYPO3\CMS\Core\Routing\Aspect\StaticMappableAspectInterface;
use TYPO3\CMS\Core\Site\SiteLanguageAwareTrait;
use TYPO3\CMS\Extbase\Utility\DebuggerUtility;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Database\Connection;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class CategoriesValueMapper implements StaticMappableAspectInterface
{
    use SiteLanguageAwareTrait;

    /**
     * {@inheritdoc}
     */
    public function generate(string $value): ?string
    {
        //DebuggerUtility::var_dump($value, 'generate');
        $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable('sys_category');
        $categories = $queryBuilder->select('uid', 'slug')
            ->from('sys_category')
            ->where(
                $queryBuilder->expr()->in('uid', $queryBuilder->createNamedParameter(GeneralUtility::intExplode(',', $value, true), Connection::PARAM_INT_ARRAY)),
            )
            ->orderBy('parent')
            ->execute()
            ->fetchAll();
        //DebuggerUtility::var_dump($categories);

        $routing = $categories[0]['slug'];
        if($categories[1]) {
            $routing .= "_" . $categories[1]['slug'];
        }

        if (isset($routing)) {
            return (string)$routing;
        }
        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function resolve(string $value): ?string
    {
        //DebuggerUtility::var_dump($value, 'resolve');
        $categorieIDsArray = explode('_',$value);
        $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable('sys_category');
        $categories = $queryBuilder->select('uid', 'slug')
            ->from('sys_category')
            ->where(
                $queryBuilder->expr()->in('slug', $queryBuilder->createNamedParameter($categorieIDsArray, Connection::PARAM_STR_ARRAY)),
            )
            ->orderBy('parent')
            ->execute()
            ->fetchAll();
        $routing = strval($categories[0]['uid']);
        if($categories[1]) {
            $routing .= "," . strval($categories[1]['uid']);
        }

        if (isset($routing)) {
            return (string)$routing;
        }
        return null;
    }
}
```

**Comment by bavarianbytes** [comment]
Thank you! That means, this way it works, but results in an TYPO3 error instead of an 404 if somebody types a non-existing news URL?

**Comment by ste101** [comment]
> 
> 
> Thank you! That means, this way it works, but results in an TYPO3 error instead of an 404 if somebody types a non-existing news URL?

Yes.
I hope that some knows a way to fix this.
Site config is the same as here:
https://docs.typo3.org/p/georgringer/news/8.5/en-us/AdministratorManual/BestPractice/Routing/Index.html#basic-setup-including-categories-and-tags
Only difference:
```
      category-name:
        type: CategoriesValueMapper
```
instead of
```
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
```

**Comment by ste101** [comment]
Did you try it?
It worked in a test installation an till now I don't know why.

**Comment by ste101** [comment]
I found out that it is working if the detail page is on the same level as the list page.
```
- news
- - list
- - detail
```
If the detail page is below the list page then it does not work
```
- news
- - list
- -- detail
```
Strange thing. If the detail page is below the list page and I strip the list page out of the slug of the detail page it works also.
Slug `'/news/list/detail'` does not work
Slug stripped `'/news/detail'` works.

If I analyze the exception message a bit I can see other strange things:
`, array('parameter' => 108, 'additionalParams' => '&tx_news_pi1%5Baction%5D=list&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5BoverwriteDemand%5D%5Bcategories%5D=', 'language' => 0, 'linkAccessRestrictedPages' => false))`

I can see the UID (108) of the list page and the action is also 'list' but I'm on the detail page!!
Does anything of this makes sense?

**Comment by bavarianbytes** [comment]
> Did you try it?
> It worked in a test installation an till now I don't know why.

Not yet, but i will try your solution in the upcoming week and let you know.

**Comment by bavarianbytes** [comment]
I tried it. My RouteEnhancers:
```
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      -
        routePath: '/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
```

The first two categories seam to work correctly (add and remove them). But not more than two. If i try to filter for a third category, it's not applied.

And i have the same exception as you mentioned.

**Comment by ste101** [comment]
The custom aspect handles only two categories.
It is easy to change this.

**Comment by bavarianbytes** [comment]
> The custom aspect handles only two categories.
> It is easy to change this.

Thx, here is the optimized code for up to 30 categories:
```
<?php

namespace CD\Sitebase\Routing\Aspect;

use TYPO3\CMS\Core\Routing\Aspect\StaticMappableAspectInterface;
use TYPO3\CMS\Core\Site\SiteLanguageAwareTrait;
use TYPO3\CMS\Extbase\Utility\DebuggerUtility;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Database\Connection;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class CategoriesValueMapper implements StaticMappableAspectInterface
{
	use SiteLanguageAwareTrait;

	/**
	 * {@inheritdoc}
	 */
	public function generate(string $value): ?string
	{
		$queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable('sys_category');
		$categories = $queryBuilder->select('uid', 'slug')
			->from('sys_category')
			->where(
				$queryBuilder->expr()->in('uid', $queryBuilder->createNamedParameter(GeneralUtility::intExplode(',', $value, true), Connection::PARAM_INT_ARRAY)),
			)
			->orderBy('parent')
			->execute()
			->fetchAll();

		$routing = $categories[0]['slug'];

		// additional categories (up to 29)
		for($i = 1; $i <= 29; $i++) {
			if($categories[$i]) {
				$routing .= "," . $categories[$i]['slug'];
			}
		}

		if (isset($routing)) {
			return (string)$routing;
		}
		return null;
	}

	/**
	 * {@inheritdoc}
	 */
	public function resolve(string $value): ?string
	{
		$categorieIDsArray = explode(',', $value);

		$queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable('sys_category');
		$categories = $queryBuilder->select('uid', 'slug')
			->from('sys_category')
			->where(
				$queryBuilder->expr()->in('slug', $queryBuilder->createNamedParameter($categorieIDsArray, Connection::PARAM_STR_ARRAY)),
			)
			->orderBy('parent')
			->execute()
			->fetchAll();
		$routing = strval($categories[0]['uid']);

		// additional categories (up to 29)
		for($i = 1; $i <= 29; $i++) {
			if($categories[$i]) {
				$routing .= "," . strval($categories[$i]['uid']);
			}
		}

		if(isset($routing)) {
			return (string)$routing;
		}
		return null;
	}
}
```

**Comment by bavarianbytes** [comment]
> Strange thing. If the detail page is below the list page and I strip the list page out of the slug of the detail page it works also.
> Slug `'/news/list/detail'` does not work
> Slug stripped `'/news/detail'` works.

I don't get it to work, no matter if i strip list view from the detail views slug, if i locate detail view after list view or if try to separate list and detail view in two `routeEnhancers` with different `limitToPages`.

**Comment by georgringer** [comment]
I close this as not really relevant to news itself and I don't plan to change anything in that regard.

would be very happy if the ones who need it contribute or at least document if a custom mapper is created which supports this
