### ISSUE TITLE
"include subcategories" in Backend Module filter

### ISSUE THREAD

**Issue by ursbraem** [georgringer/news#153]
I had this question: 

> If I have a category tree with say three levels: Should I instruct editors to assign the entire "category rootline" to each news? Like check "ancestor, parent, child" or just the deepest node ("child")? My intention  is that that filtering in frontend AND backend works recursively, so if you filter for "parent", also all children will be listed.

The answer is yes, just check the lowest category node. In the frontend, there is the option "include subcategories". 

In the backend module, the subcategories are not included when filtering.

I propose adding this feature to the backend module as checkbox.

**Comment by georgringer** [comment]
solved with https://github.com/georgringer/news/commit/2c6779a3bd31e57d6784c337201aa7ded6bcf19a
