### ISSUE TITLE
Do not add alternative language meta tags on pages without news.

### ISSUE THREAD

**Issue by guelzow** [georgringer/news#1532]
## Bug Report

**Current Behavior**
News adds alternative language meta tags to every page and does not care if the page shows any news records.
This is harmful when the page is not translated to all the other languages, or when there is a detail plugin involved whose record is not translated.

**Expected behavior/output**
When there are no news records, I expect that news does not display these links.

**Environment**
- TYPO3 version(s): [10.4.17]
- news version: [8.5.2]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Linux server]

**What is happening in the code**
Here:
https://github.com/georgringer/news/blob/8.5.2/Classes/Seo/NewsAvailability.php#L44
and here:
https://github.com/georgringer/news/blob/8.5.2/Classes/Seo/NewsAvailability.php#L53
errors get thrown when either the language is not available, or the news record  is not detectable.
Then here:
https://github.com/georgringer/news/blob/8.5.2/Classes/Seo/HrefLangEvent.php#L55
this error is  caught.
The error handling then does nothing to remove the faulty language.

**Possible Solution**
Do not throw these errors, and simply return a `false`.

**Alternative solution**
Unset the faulty language in the catch clause.

Tobi

**Comment by georgringer** [comment]
thanks for the report, solved now
