### ISSUE TITLE
In Detail View is not possible to show related news sorted manually

### ISSUE THREAD

**Issue by robertvonhackwitz** [georgringer/news#1545]
## Feature Request

In the "Detail" view there is currently no possibility to view the "related news" sorted with the manual method.
I implemented it through an "extension" with which the following methods are added to the "news" model which consequently allow to use the RelatedSortedForeign array in the Fluid Template "Detail.html"
Just my two cent.

/**
     * @var array
     */
    protected $sortingForeign;
    
    /**
     * @return array
     */
    public function getSortingForeign()
    {
        return $this->sortingForeign;
    }
    
    /**
     * @param array $sortingForeign
     */
    public function setSortingForeign($sortingForeign)
    {
        $this->sortingForeign = $sortingForeign;
    }
    
    /**
     * Return related items sorted by sorting
     *
     * @return array
     */
    public function getRelatedSortedForeign()
    {
        $items = $this->getRelated();

        if ($items) {
            $items = $items->toArray();
            usort($items, function ($a, $b) {
                return $a->getSortingForeign() < $b->getSortingForeign();
            });
        }
        return $items;
    }

**Comment by georgringer** [comment]
do you wanna push a PR?

**Comment by robertvonhackwitz** [comment]
Ok. Gladly
