### ISSUE TITLE
List of selected items does not use selected Template-Layout

### ISSUE THREAD

**Issue by Scopestyle** [georgringer/news#1546]
## Bug Report

**Current Behavior**
Selecting the display `List of selected items` only outputs the items using the default news layout, even though a custom layout is selected and works fine on normal list view. There seems to be no way to influence the output with custom template-layouts. Tested in multiple client installations.

**Expected behavior/output**
An output of selected news items, with a custom template-layout defined in the module.

**Environment**
- TYPO3 version(s): 10.4.16
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
I coulnd't reproduce this one and therefore closing the issue. the ´templateLayout` is just a setting and is available in every template.
