### ISSUE TITLE
AdministrationController Permission error in typo3 11

### ISSUE THREAD

**Issue by gromschmidt** [georgringer/news#1547]
## Bug Report

**Current Behavior**
News Administration View has Error: Call to a member function edit Content Permission Is Granted() on int

**Environment**
- TYPO3 version(s): [11.3.1]
- news version: [ 9.0.0-dev ]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

**Possible Solution**
/public/typo3conf/ext/news/Classes/Controller/AdministrationController.php:382  
      $dblist->calcPerms =  new Permission();

**Comment by georgringer** [comment]
this is now fixed
