### ISSUE TITLE
Not-translated news doesn't respect the order of the fallback languages

### ISSUE THREAD

**Issue by JeppeDonslund** [georgringer/news#1558]
## Bug Report

**Current Behavior**
In the Hungarian site configuration, I have set de fallback languages to first English and the  Default language (Danish). If I do not translate a news to Hungarian it shows it in Danish and not English.

**Expected behavior/output**
It should show English first if that translation exists

**Environment**
- TYPO3 version(s): 9.5.24
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Unix

**Comment by JeppeDonslund** [comment]
I have just updated tx_news, but I still have the same problem.

**Comment by georgringer** [comment]
closing this issue because this is extbase behaviour and not news
