### ISSUE TITLE
Visible deprecation error in ExtensionManager

### ISSUE THREAD

**Issue by nhovratov** [georgringer/news#1581]
## Bug Report

**Current Behavior**
When activating the extension in the ExtensionManager a deprecation error is printed in the backend.

**Expected behavior/output**
Deprecation errors should only be logged.

**Environment**
- TYPO3 version(s): 11.5-dev
- news version: master
- Is your TYPO3 installation set up with Composer (Composer Mode): yes (TYPO3 installed via git)

**Additional context**
Not sure if TYPO3 bug or News.

![Screenshot 2021-09-28 at 10-49-47 Extensions · Installed Extensions · TYPO3 MASTER  TYPO3 CMS 11 5 0-dev](https://user-images.githubusercontent.com/19343425/135056068-3f613015-6ce3-4a68-afd4-c12e885bf108.png)

**Comment by georgringer** [comment]
fixed and merged
