### ISSUE TITLE
Extending NewsController not working

### ISSUE THREAD

**Issue by cdaecke** [georgringer/news#1584]
## Bug Report

**Current Behavior**
When installing an extension for example `ext:eventnews`, which extends the `NewsController`, the proxy class is not generated correctly.

Extending the controller:

    $GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Controller/NewsController'][] = 'eventnews';

Error:

> ParseError: syntax error, unexpected '$newsRepository' (T_VARIABLE), in file .../public/typo3temp/var/cache/code/news/tx_news_controller_newscontroller.php:824

Looking into the generated class, I see the following (wrong parenthesises):

    public function __construct()
    {
        NewsRepository $newsRepository,
        CategoryRepository $categoryRepository,
        TagRepository $tagRepository,
        ConfigurationManagerInterface $configurationManager
    ) {
        $this->newsRepository = $newsRepository;
        $this->categoryRepository = $categoryRepository;
        $this->tagRepository = $tagRepository;
        $this->configurationManager = $configurationManager;
    }

**Expected behavior/output**
The constructor of the class needs to be generated correctly:

    /**
     * NewsController constructor.
     * @param NewsRepository $newsRepository
     * @param CategoryRepository $categoryRepository
     * @param TagRepository $tagRepository
     * @param ConfigurationManagerInterface $configurationManager
     */
    public function __construct(
        NewsRepository $newsRepository,
        CategoryRepository $categoryRepository,
        TagRepository $tagRepository,
        ConfigurationManagerInterface $configurationManager
    ) {
        $this->newsRepository = $newsRepository;
        $this->categoryRepository = $categoryRepository;
        $this->tagRepository = $tagRepository;
        $this->configurationManager = $configurationManager;
    }

**Environment**
- TYPO3 version(s): 11.4.0
- news version: 9.0.0-dev
- Is your TYPO3 installation set up with Composer (Composer Mode): both

**Comment by DavidBruchmann** [comment]
it's a know issue.
You've to write declaration, parameters and opening bracket all in one line, like this:
```
public function doSomething(a, b, c, d) {
```

**Comment by cdaecke** [comment]
@DavidBruchmann Thanks for your quick feedback!

I am not sure, if I get you right. Extending the `NewsController` was possible before the change in #1503. In the commit 77af776eed33b4761e7aff89f238d69f53f19f5f the dependency injection was changed. Everything was moved to the `__construct` method.

 When I change the construct method of the `NewsController` in the news extension like you suggested (having everything in one line, declaration, parameters and opening bracket), the generated code in `tx_news_controller_newscontroller.php` looks like the following:

    public function __construct()
    {
        $this->newsRepository = $newsRepository;
        $this->categoryRepository = $categoryRepository;
        $this->tagRepository = $tagRepository;
        $this->configurationManager = $configurationManager;
    }

As you can see, the parameters are missing and now I get this error:

> Error, code #0, file .../public/typo3temp/var/cache/code/news/tx_news_controller_newscontroller.php, line 231: Call to a member function findDemanded() on null

Obviously `$this->newsRepository` is not available.

As I read in the [TYPO3 docs](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/DependencyInjection/Index.html), the recommended way of injecting dependencies is to use constructor injection, but this does not seem to work with extending the controller of this extension anymore.

**Comment by stigfaerch** [comment]
@cdaecke Maybe you could try my branch to see if it fixes it for you?

**Comment by cdaecke** [comment]
@stigfaerch A quick check looks promising, it is working for me. Thanks!
