### ISSUE TITLE
Ajax pagination

### ISSUE THREAD

**Issue by echavaillaz** [georgringer/news#161]
Hi,

It would be great if it was possible to sets the pagination with Ajax instead of full request.

Thanks!

**Comment by georgringer** [comment]
What about using something like http://jscroll.com/ for that?

**Comment by echavaillaz** [comment]
It is a possibility, but I think it is not the concern here.

The feature request is really to "ajaxify" the pagination.

For exemple, if you have a list view on an home page with 3 news and a pagination, it would be great to not reload all the page when passing from page to page... With jscroll, it can be a solution for a page like "all news" but not on an home page.

Thanks

**Comment by georgringer** [comment]
Yeah I know, but it would be really easy to just follow the link, load all HTML and get the snippet you need and you are done.

**Comment by echavaillaz** [comment]
I agree that's an easy solution.

But I think it would be better and an amazing feature to allow ajax for the pagination (and by the way make an exemple for all other extensions)

I will think about an implementation and maybe make a PR.

Thanks
