### ISSUE TITLE
v9: Autowiring new Events fail

### ISSUE THREAD

**Issue by foobar13372** [georgringer/news#1616]
I updated to v9, changed my Signals to Events and get this:

> Uncaught TYPO3 Exception Cannot autowire service "GeorgRinger\News\Event\NewsListActionEvent": argument "$assignedValues" of method "__construct()" is type-hinted "array", you should configure its value explicitly.
> thrown in file vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php

How do I solve this?

Yes, I cleared all caches (var folder and DB).

**Comment by georgringer** [comment]
this is already now don, excluding the models
