### ISSUE TITLE
Too few arguments to function GeorgRinger\News\Controller\NewsController::__construct()

### ISSUE THREAD

**Issue by de4123** [georgringer/news#1624]
## Bug Report

**Current Behavior**
I recently installed your news extension version 9.0.0 (before I had news version 8.6.0) and I got the following error in the frontend: 

```
ArgumentCountError

Too few arguments to function GeorgRinger\News\Controller\NewsController::__construct(), 0 passed in /Applications/MAMP/htdocs/www.dev.zwph.de/typo3_10LTS/typo3_src-10.4.21/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3509 and exactly 4 expected
```

In the backend I get the following error: 

```
ArgumentCountError

Too few arguments to function GeorgRinger\News\Hooks\Backend\RecordListQueryHook::__construct(), 0 passed in /Applications/MAMP/htdocs/www.dev.zwph.de/typo3_10LTS/typo3_src-10.4.21/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3477 and exactly 1 expected
```

**Expected behavior/output**
I expected the extension would run without problems. I really have no idea how I could solve the problem. I would be glad if somebody could help me. Thank you very much!

**Environment**
- TYPO3 version(s): 10.4.21
- news version: 9.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: OSX 10.14.6
- PHP: 7.4.2

**Comment by georgringer** [comment]
Please clear caches in install tool

**Comment by bzgaLindner** [comment]
Clearing TYPO3 Cache, Frontend Cache AND Flushing Cache in Install tool did not help here.

**Comment by ineswillenbrock** [comment]
Clearing cache in the install-tool helps here, thanks
