### ISSUE TITLE
Workaround for the combination of TYPO3 10.4.21 and news extension 9.0.0?

### ISSUE THREAD

**Issue by de4123** [georgringer/news#1625]
## Bug Report

**Current Behavior**
I also get the following error in the frontend: 

```
#1407060572 TYPO3Fluid\Fluid\Core\Parser\Exception

Fluid parse error in template News_action_list_5eff6838a7c4412013f27394ace13d4c25fa55ef, line 22 at character 30. Error: The ViewHelper "<n:widget.paginate>" could not be resolved. Based on your spelling, the system would load the class "GeorgRinger\News\ViewHelpers\Widget\PaginateViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <n:widget.paginate objects="{news}" as="paginatedNews" configuration="{settings.list.paginate}" initial="{offset:settings.offset,limit:settings.limit}">
```

Is there any workaround for the combination of TYPO3 10.4.21 and news extension 9.0.0? Or should I not install news 9.0.0 with TYPO3 10.4.21? Its better to wait and to install news 9.0.0 after the migration of TYPO3 10 LTS to TYPO3 11 LTS?

**Environment**
- TYPO3 version(s): 10.4.21
- news version: 9.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: 10.14.6
- PHP: 7.4.2

**Comment by georgringer** [comment]
the widget viewhelpers have been removed, adopt your templates
