### ISSUE TITLE
PHP Warnings in Typo3 11 with PHP 8

### ISSUE THREAD

**Issue by SSFGizmo** [georgringer/news#1630]
## Bug Report

**Current Behavior**
User (right top corner) => User Settings

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "newsoverlay" in /Classes/Hooks/ItemsProcFunc.php line 232

**Environment**
- TYPO3 version(s): 11.5.1
- news version: 9.0.0
- Composer: yes
- OS: Ubuntu
- PHP 8.0

**Comment by SSFGizmo** [comment]
maybe it's enough

ItemsProcFunc.php
```php
$newsoverlay = $GLOBALS['BE_USER']->uc['newsoverlay'] ?? 0;
foreach ($languages as $language) {
	$selected = ((int)$newsoverlay === (int)$language['uid']) ? ' selected="selected" ' : '';
```

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "TSFE" in /Classes/Controller/NewsBaseController.php line 44

```php
if (isset($GLOBALS['TSFE']) && is_object($GLOBALS['TSFE'])) {
```

**Comment by SSFGizmo** [comment]
Menu (left) => News Administration

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "properties" in /Classes/Controller/AdministrationController.php line 130

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "allowedPage" in /Classes/Controller/AdministrationController.php line 582

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Trying to access array offset on value of type null in /Classes/Controller/AdministrationController.php line 317

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "alwaysShowFilter" in /Classes/Controller/AdministrationController.php line 343

```php
if ((isset($this->tsConfiguration['alwaysShowFilter']) && !(bool)$this->tsConfiguration['alwaysShowFilter']) || !$this->isFilteringEnabled()) {
```

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined property: GeorgRinger\News\Backend\RecordList\NewsDatabaseRecordList::$counter in /Classes/Controller/AdministrationController.php line 380

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "controlPanels" in /Classes/Controller/AdministrationController.php line 392

```php
$dblist->noControlPanels = isset($this->tsConfiguration['controlPanels']) ? !(bool)$this->tsConfiguration['controlPanels'] : true;
```

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "columns" in /Classes/Controller/AdministrationController.php line 394

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined property: GeorgRinger\News\Backend\RecordList\NewsDatabaseRecordList::$HTMLcode in /Classes/Controller/AdministrationController.php line 407

old code?
```php
//if (!$tableRendering) {
	// todo can be remove when 9.5 supported dropped
	//$tableRendering = $dblist->HTMLcode;
//}
```

**Comment by SSFGizmo** [comment]
Menu (left) => News Administration => Folder with news

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined property: GeorgRinger\News\Backend\RecordList\NewsDatabaseRecordList::$thumbs in /Classes/Backend/RecordList/NewsDatabaseRecordList.php line 37

* https://api.typo3.org/10.4/_database_record_list_8php_source.html
* https://api.typo3.org/master/_database_record_list_8php_source.html

```php
//if ($this->thumbs) {
//    $urlParameters['imagemode'] = $this->thumbs;
//}
```

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined property: GeorgRinger\News\Backend\RecordList\NewsDatabaseRecordList::$firstElementNumber in /Classes/Backend/RecordList/NewsDatabaseRecordList.php line 52

```php
//if ($this->firstElementNumber) {
//    $urlParameters['pointer'] = $this->firstElementNumber;
//}
```

**Comment by SSFGizmo** [comment]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Trying to access array offset on value of type null in /Classes/Backend/RecordList/NewsDatabaseRecordList.php line 77

```php
if (isset($demand['demand'])  && is_array($demand['demand'])) {
```

**Comment by SSFGizmo** [comment]
News Folder => Edit => Behaviour => Use as Container Contains Plugin [module] 
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "showContentElementsInNewsSysFolder" in /Classes/Hooks/Backend/RecordListQueryHook.php line 54

**Comment by georgringer** [comment]
do you plan to provide a PR? otherwise I will look into it

**Comment by SSFGizmo** [comment]
> do you plan to provide a PR? otherwise I will look into it

Yes, this one.
https://github.com/georgringer/news/pull/1631
Open points: 
- parts with "old code"
- code style

**Comment by SSFGizmo** [comment]
News folder => Edit
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Array to string conversion in /typo3/sysext/core/Classes/Imaging/IconFactory.php line 190

**Comment by nhovratov** [comment]
Hi, just wanted to add another one I found in Backend User Module:

An error occurred trying to process items for field "Allowed excludefields" (PHP Warning: Undefined array key "tt_content" in /var/www/html/typo3conf/ext/news/Classes/Hooks/BackendUtility.php line 138).

**Comment by nigelmann** [comment]
I am having a similar issue as @nhovratov except in my case ` PHP Warning: Trying to access array offset on value of type null in /var/www/html/private/typo3conf/ext/news/Classes/Hooks/BackendUtility.php line 138`

I was able to solve it this way
replacing `if (is_array($getVars['tt_content'])) {`
by `if ($getVars !== null && is_array($getVars['tt_content'])) {`

To solve the undefinex array key I would add ` ?? null`

so the line 138 would look like this
`if ($getVars !== null && is_array($getVars['tt_content'] ?? null)) {`

Hope this helps

**Comment by ratron** [comment]
I found another one:
List View => (any folder/page) => add Category 

 **#1476107295  TYPO3\CMS\Core\Error\Exception**

PHP Warning: Undefined array key "newsoverlay" in typo3conf/ext/news/Classes/Service/CategoryService.php line 129:

` $overlayLanguage = (int)$GLOBALS['BE_USER']->uc['newsoverlay'];`

**Environment**
- PHP 8.0.8
- Typo3 11.5.5
- News 9.2.0

**Comment by ecosmox36** [comment]
I guess there are another bunch of issues,

- PHP version: | 8.0.13
- TYPO3: 11.5.6
- News 9.2.0

If the debug develop preset mode ist activated, the warnings will break the frontend :(

PHP Warning: Undefined array key 
 in /var/www/html/public/typo3conf/ext/news/Classes/Controller/NewsController.php


- "categories"  line 148
- "categoryConjunction"  line 149
- "tags"  line 151
- "topNewsRestriction"  line 153
- "timeRestriction"  line 154
- "timeRestrictionHigh"  line 155
- "archiveRestriction"  line 156
- "excludeAlreadyDisplayedNews" line 157
- "limit"  line 167
- "offset"  line 168
- "startingpoint" line 176
- "recursive"  line 177
- "disableOverrideDemand"  line 234

Hope this info will help you

**Comment by georgringer** [comment]
closing this issue. there still can be some issues but those can be all fixed with little effort
