### ISSUE TITLE
[DOCS] Start Page like Guide Getting started

### ISSUE THREAD

**Issue by linawolf** [georgringer/news#1632]
I would propose to use a modern starting page like the getting started Guide (https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Index.html)

for the news extension manual. I could make a PR for this.

The current starting page looks very dry: https://docs.typo3.org/p/georgringer/news/9.0/en-us/Index.html

I would suggest to move the information supplied there to a sitemap and an about page.

**Comment by georgringer** [comment]
Yeah please go ahead
