### ISSUE TITLE
[DOCS] Review Docs Page "Save & Preview"

### ISSUE THREAD

**Issue by linawolf** [georgringer/news#1633]
https://docs.typo3.org/p/georgringer/news/9.0/en-us/AdministratorManual/BestPractice/PreviewOfRecord/Index.html

**Comment by DavidBruchmann** [comment]
Auf dieser Seite:

![image](https://user-images.githubusercontent.com/999146/140042372-0645c241-f9a6-4253-b925-4cdca5a1242b.png)
