### ISSUE TITLE
[DOCS] Explain concept of "Demands"

### ISSUE THREAD

**Issue by linawolf** [georgringer/news#1635]
Demands are mentioned in numerous places throughout the Documentation but they are nowhere  explained really. It is probably also a level of abstraction as a developer would need to know more about demands then an administrator. 

Is this a generally known concept, like a software pattern or such? I cannot find it in the official TYPO3 documentation. The word is generally hard to search for as everyone is writing about "demands" in the software world.

**Comment by DavidBruchmann** [comment]
Its part of one extbase guide, but I agree that a good explanation would be good!

**Comment by linawolf** [comment]
@DavidBruchmann could you post the link here?

**Comment by DavidBruchmann** [comment]
The demand-Model: https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/7-Controllers/1-Creating-Controllers-and-Actions.html?highlight=demand

Explanation about that step: https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/6-Persistence/3-implement-individual-database-queries.html?highlight=demand
```
We encapsulate the requirements in their own Demand object that basically consists of the properties age, organization, region, category and searchWord, plus their getters and setters. In addition to the restrictions for the user’s needs, there comes a request to show the current offers. This example request denotes a date constraint at most one week ago. In the method findDemanded() of the offerRepository, the request is implemented:
```

I don't think that this is sufficient and appreciate your request for more / better explanation -- even if it's related only to news currently.

**Comment by DavidBruchmann** [comment]
I'm astonished that the version in the links seems changing, I found all links here:
https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/search.html?q=demand&check_keywords=yes&area=default

**Comment by DavidBruchmann** [comment]
Just a remark on this:  
I never got close with the concept of demands but I remarked the benefit that it's possible to enable/disaple all demands at once. Anyway, the reflection in the URLs of that model smells somehow fishy for me.

**Comment by georgringer** [comment]
it is just a configuration object which is better than having e.g. an array

**Comment by linawolf** [comment]
I gave it a try @georgringer, see attached PR.
