### ISSUE TITLE
'contentElementRelation' => '0' breaks detail view

### ISSUE THREAD

**Issue by olivermeckel** [georgringer/news#1641]
## Bug Report

**Current Behavior**
Changing the settings in "settings -> extension configuration -> news" for "contentElementRelation" to false ('contentElementRelation' => '0' in LocalConfiguration.php), breaks the detail view of news with error message:

`Oops, an error occurred!
Return value of GeorgRinger\News\Domain\Model\News::getContentElements() must be an instance of TYPO3\CMS\Extbase\Persistence\ObjectStorage, null returned`

**Environment**
- TYPO3 version(s): [10.4.21]
- news version: [9.0.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]

**Comment by chesio** [comment]
This is duplicate of #1629 - it has already been fixed in a4ff4ac6b3f7eacce52a2d9d5d6e493801003783, the fix however has not been released yet.

**Comment by olivermeckel** [comment]
You are absolutely right. thanks for the tip
