### ISSUE TITLE
constants for lightbox settings are missing

### ISSUE THREAD

**Issue by olivermeckel** [georgringer/news#1642]
## Bug Report

**Current Behavior**
There are no constants for the lightbox settings for media on detail views.

Configuration/TypoScript/setup.typoscript

***
lightbox {
  enabled = {$styles.content.textmedia.linkWrap.lightboxEnabled}
  class = {$styles.content.textmedia.linkWrap.lightboxCssClass}
  width = {$styles.content.textmedia.linkWrap.width}
  height = {$styles.content.textmedia.linkWrap.height}
  rel = lightbox[myImageSet]
}
***

On the detail view images have the class

`class="{$styles.content.textmedia.linkWrap.lightboxCssClass}"`

**Environment**
- TYPO3 version(s): [10.4.21]
- news version: [9.0.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes, no]
- OS: [e.g. OSX 10.13.4, Windows 10]

**Possible Solution**
define constants in the constants.typoscript

**Comment by georgringer** [comment]
those constants are defined in EXT:fluid_styled_content. wanna include that?

**Comment by olivermeckel** [comment]
ok, i don't use fluid_styled_content
Should there be a fallback?

**Comment by georgringer** [comment]
there is currently no way to define fallbacks. please provide those constants yourself. I won't change anything for the timebeing as any change would be breaking for others.

what about adding fsc as suggestion? would that be ok for you?

**Comment by olivermeckel** [comment]
It's fine for me. I can provide those constants myself.
We're using boostrap_package, which is in conflict with fsc.
so, i just wanted to report it at all.
