### ISSUE TITLE
`ul.f3-widget-paginator li.current` should perhaps not be linked

### ISSUE THREAD

**Issue by xerc** [georgringer/news#1651]
https://github.com/georgringer/news/blob/bae5fb388c290605bc829a5e58f3f496e3b8c8d5/Resources/Private/Partials/List/Pagination.html#L28-L29

**Comment by georgringer** [comment]
I don't find any resource which says this shouldn't be done. as every change in template is potentially breaking (e.g. people relying on having an a tag) and it can be easily changed by integrators I won't change the implementation.

still of course thanks for creating the issue!

**Comment by xerc** [comment]
https://github.com/georgringer/news/blob/923b96496cb054a6b3c678b48c19755fbb9b2276/Resources/Private/Templates/ViewHelpers/Widget/Paginate/Index.html#L62-L66

**Comment by xerc** [comment]
the "old" behavior was not linking `.current` and therefore more usability friendly; link/click expects change of view
