### ISSUE TITLE
[BUG] AddNewsToMenuProcessor behaviour in hierarchical menus

### ISSUE THREAD

**Issue by linawolf** [georgringer/news#1654]
## Bug Report

**Current Behavior**
When you use AddNewsToMenuProcessor with a hierarchical Menu and you are on a news Single view the news will be added to the very end of the first level of the menu. When you are not on the Single view of a news it is not added at all.

**Expected behavior/output**
I would expect the News items be added in the place where the single detailPid lies (depending on singlePid of category or generally
definded SinglePids from the settings)

**Environment**
- TYPO3 version(s): [11.5.3]
- news version: [9.0.0]
 TypoScript:

```
40 = TYPO3\CMS\Frontend\DataProcessing\MenuProcessor
40 {
    levels = 3
    as = myMenu
    expandAll = 1
    includeSpacer = 1
    titleField = nav_title // title
}

50 = TYPO3\CMS\Frontend\DataProcessing\MenuProcessor
50 {
    as = breadcrumbMenu
}
60 = GeorgRinger\News\DataProcessing\AddNewsToMenuProcessor
60.menus = breadcrumbMenu,myMenu
```

**Possible Solution**
If the AddNewsToMenuProcessor  was never meant to be used for hierarchical menus It should at least not appear at the bottom of the first level. The name is misleading and the fact needs to be documented.

**Additional context**
```
 myMenu => array(5 items)
      0 => array(8 items)
      1 => array(8 items)
      2 => array(8 items)
      3 => array(8 items)
         data => array(83 items)
         title => 'Über das Portal' (16 chars)
         link => '/ueber-das-portal' (17 chars)
         target => '' (0 chars)
         active => 1 (integer)
         current => 0 (integer)
         spacer => 0 (integer)
         children => array(6 items)
            0 => array(7 items) <--- It should be found as child of this one
               data => array(83 items)
               title => 'Alle Nachrichten' (17 chars)
               link => '/ueber-das-portal/alle-nachrichten' (34 chars)
               target => '' (0 chars)
               active => 1 (integer)
               current => 0 (integer)
               spacer => 0 (integer)
            1 => array(7 items)
            2 => array(7 items)
            3 => array(7 items)
            4 => array(7 items)
            5 => array(7 items)
      4 => array(6 items)      <------------- News is found here
         data => array(87 items)
         title => 'Ich bin eine Testnachricht' (26 chars)
         active => 1 (integer)
         current => 1 (integer)
         link => 'https://xyz.ddev.site/ueber-das-portal/alle-nachrich
            ten/artikel/ich-bin-eine-testnachricht' (114 chars)
         isNews => TRUE
````

**Comment by georgringer** [comment]
it was never meant to be for hierachical menus and there is no way to check that in the dataprocessor. what is the usecase of your menu?

**Comment by linawolf** [comment]
My customer needs a mega menu where we have different pages that are the news single pid of categories. 
For each of these pages we want to list the 10 most recent news within the mega menu.

**Comment by georgringer** [comment]
after thinking about it I will still close this issue. a solution is to use a custom dataprocessor
