### ISSUE TITLE
Ajax based Paginate

### ISSUE THREAD

**Issue by typo3max** [georgringer/news#1659]
Please i need a method to Ajax Paginate news
the Plugin is included per typoscript
i n manual explain the way how to use ajax paginate BUT:
The list plugin must be inserted as content element and not by TypoScript.
Is there a way to use Ajax paginate with content element with typoscript

PLEASE

**Comment by georgringer** [comment]
I would suggest using JS for that, e.g. https://infinite-scroll.com/ 

as the widgets have been removed in TYPO3 11, I also removed the ajax pagination in latest version
