### ISSUE TITLE
Polish translation files are empty 

### ISSUE THREAD

**Issue by atnetws** [georgringer/news#1660]
Hi Georg,
it seems that the polish translation files are corrupt. After fetching translations for news 8.6.0 in TYPO3 10.4.20, all files located in var/labels are okay except for the polish ones - they simply don't contain any translated strings.
I've attached a file that I've retrieved a few minutes ago. 
[pl.locallang_db.txt](https://github.com/georgringer/news/files/7597493/pl.locallang_db.txt)

Cheers
Marcus

**Comment by georgringer** [comment]
sorry for the late response. when I check out https://crowdin.com/project/typo3-extension-news/pl only one file is translated which I also just accepted. 
if you got more translations, please send them to me or add translations on https://crowdin.com/project/typo3-extension-news/pl
