### ISSUE TITLE
In Models with properties of type DateTimeInterface all return type annotations should be nullable

### ISSUE THREAD

**Issue by bfzgaier** [georgringer/news#1665]
## Bug Report

**Current Behavior**
Accessing an optional DateTime property like starttime or endtime of a news throws a TypeError. 
```
(1/1) TypeError
Return value of GeorgRinger\News\Domain\Model\News::getStarttime() must be an instance of DateTime, null returned
```
```
(1/1) TypeError
Return value of GeorgRinger\News\Domain\Model\News::getEndtime() must be an instance of DateTime, null returned
```

**Expected behavior/output**
Accessing the properties should return null.

**Environment**
- TYPO3 version(s): 10.4.21
- news version: 9.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Possible Solution**
Change all DateTime return types to nullable.

**Additional context**
This issue is related to https://github.com/georgringer/news/issues/1656

The core property mapper only sets the property for a valid value:
```php
            if ($propertyValue !== null) {
                $object->_setProperty($propertyName, $propertyValue);
            }
```
https://github.com/TYPO3/typo3/blob/68b9560ee1a28d92daaba500aeeb096e1a5a06a9/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php#L278

DateTimeInterface properties are run through DataMapper::mapDateTime().
```php
                        if (is_subclass_of($propertyType, \DateTimeInterface::class)) {
                            $propertyValue = $this->mapDateTime(
                                $row[$columnName],
                                $columnMap->getDateTimeStorageFormat(),
                                $propertyType
                            );
```
https://github.com/TYPO3/typo3/blob/68b9560ee1a28d92daaba500aeeb096e1a5a06a9/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php#L261
 This functions return null, if the database value is "empty".
```php
        // Invalid values are converted to NULL
        if (empty($value) || $value === '0000-00-00' || $value === '0000-00-00 00:00:00' || $value === '00:00:00') {
            return null;
        }

```
https://github.com/TYPO3/typo3/blob/68b9560ee1a28d92daaba500aeeb096e1a5a06a9/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php#L310

Therefore all getter return type annotations should be nullable.

**Comment by georgringer** [comment]
thanks for your detailed report!

**Comment by bfzgaier** [comment]
Hi, was the news model forgotten? At least getStarttime & getEndtime should also be nullable.
