### ISSUE TITLE
[DOCS] Link broken to "fear-driven versioning"

### ISSUE THREAD

**Issue by sypets** [georgringer/news#1673]
There is a link broken to the "fear driven versioning": https://docs.typo3.org/p/georgringer/news/main/en-us/AdministratorManual/Update/Index.html

Perhaps the term "semantic versioning" and link can be used instead. However it is a little different. On the page now, minor reflects "minor breaking changes", in semver this is different: "MINOR version when you add functionality in a backwards compatible manner"

https://semver.org/

So, not sure how to proceed here.

**Comment by georgringer** [comment]
I would go with semver, thanks!
