### ISSUE TITLE
Wrong types while getting available TemplateLayouts

### ISSUE THREAD

**Issue by julianhofmann** [georgringer/news#1676]
## Bug Report

**Current Behavior**
Restricting template layouts to a colPos (Feature introduced 6.3.0) fails since "[TASK] Replace deprecated string util methods" (https://github.com/georgringer/news/pull/1583/commits/0b4ad5302d7257357dd54b9b384d8eeaae57e92f#diff-2473de5cca434765cb14938276c4580866cca4195bc7632cf32e564cc282df97R40). You get an error: "Argument 1 passed to str_starts_with() must be of the type string or null, array given, called in .../typo3conf/ext/news/Classes/Utility/TemplateLayout.php on line 40"

**Expected behavior/output**
`TemplateLayout::getAvailableTemplateLayouts()` should make a distinction whether there is really only a template name in the TypoScript array, or whether there are sub-properties (i.e. an array) there. 
The formerly used `GeneralUtility::isFirstPartOfStr()` is not declare type-strict and handles arrays, too. The now used `str_starts_with()`of PHP 8 expects strings. 

**Environment**
- news version: master (9.1.0)

**Comment by georgringer** [comment]
wanna provide a patch and add a typecast?

**Comment by julianhofmann** [comment]
Yes. Will care about it.

Another question: 
`str_starts_with()` is part of PHP 8.0, but EXT:news requires "typo3/cms-core": "^10.4 || ^11" which means PHP ^7.2 or PHP ^7.4 || ^8.0. This part of EXT:news won't be supported by any TYPO3 v10.4 and won't be supported by TYPO3 v11 with PHP 7.4...

**Comment by chesio** [comment]
> str_starts_with() is part of PHP 8.0, but EXT:news requires "typo3/cms-core": "^10.4 || ^11" which means PHP ^7.2 or PHP ^7.4 || ^8.0. This part of EXT:news won't be supported by any TYPO3 v10.4 and won't be supported by TYPO3 v11 with PHP 7.4...

Both TYPO3 10.4 and TYPO3 11.5 require [symfony/polyfill-php80](https://packagist.org/packages/symfony/polyfill-php80) which provides this function on older PHP versions.

**Comment by georgringer** [comment]
@julianhofmann still wanna create a pr? Or can you check if still valid and how to reproduce? Thx

**Comment by julianhofmann** [comment]
Sorry, hadn't found (and will not find) the time to fix (and write tests for it) :-(

To reproduce, you need an "advanced" TSconfig for `templatelayouts` like the [example in the docs](https://docs.typo3.org/p/georgringer/news/main/en-us/Reference/TsConfig/General.html#templatelayouts):

```
tx_news.templateLayouts {
   1 = Foobar
   2 = Another one
   2.allowedColPos = 1,2,3
}
```

- "1" will work, because it's a string
- "2" (or "2.") will **not** work because  it's an array (`'2.' => ['allowedColPos'=>'1,2,3']`)
