### ISSUE TITLE
caching and starttime endtime configuration

### ISSUE THREAD

**Issue by ToGetATockenOnly** [georgringer/news#1685]
this is for documentation only .. unless anyone has a comments.. 

working with EXT:news v7.3.1 on TYPO3v9.5

In the context of caching the list plugin does not out-of-the-box work with the above named starttime endtime. If a 24h cache is generated shortly befort a starttime of another news ... well the news is not considered and does not show up for close to 24 hours.

One has to configure such by hand. Which may be tedious for big sites and/or changing plugin/record folders. Of course, it would be nice, if EXT:news would handle this out-of-the-box. The solution with the below linked sources is the cache expiration is reduced from 86400 (secs ~ 1day ~ or until midnight, if set so) to the amount of seconds until the first relevant starttime. Too many starttime/endtime dates may split the caching in short intervals. 

https://www.comuno.net/blog/detail/veroeffentlichungsdatum-und-cache-bei-extensions-z-b-tx-news/
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Setup/Config/Index.html#cache

**Comment by georgringer** [comment]
some more examples have been added to the documentation https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/BestPractice/ClearCache/Index.html?highlight=caching#cache-lifetime-and-auto-publishing-by-setting-start-date
