### ISSUE TITLE
Not able to override pagination anymore

### ISSUE THREAD

**Issue by drogu02** [georgringer/news#1686]
## Bug Report

**Current Behavior**
I try to override pagination in news 9.1.1 but I am not able anymore.

I tried in typoscipt with these 2 lines : 
(This line is working in typo3 10.4.22 and news 8.5.2)
plugin.tx_news.list.paginate.templatePath = fileadmin/template/extensions/news/Templates/ViewHelpers/Widget/Paginate/Index.html

(Another try i did with news 9.1.1)
plugin.tx_news.view.widget.GeorgRinger\News\ViewHelpers\Widget\PaginateViewHelper.templateRootPath = fileadmin/templates/extensions/news/Templates/

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 11.5.4
- news version: 9.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): No
- OS: Linux

**Comment by georgringer** [comment]
The pagination is now a normal partial just like any other one

**Comment by drogu02** [comment]
Tx!!  That was my problem!  Solved!
