### ISSUE TITLE
Typo3 v11.5.3  News 9.1.0  Imported news will not be shown in backend 

### ISSUE THREAD

**Issue by gm-dtit** [georgringer/news#1697]
I set up a new typo3 installation with typo3v11.5.3 and news extention 9.1.0.

If I add a new **"News"** in the backend, it worked well. 

As I have lots of news from an older typo3 installation, I exported these news, adapted it to the new db schema and  imported it into the new installation without any errors. I imported the following db-tables

- tx_news_domain_model_news
- sys_file_reference
- sys_file

In the frontend I could see the imported news. Unfortunately the imported **news** will not be diplayed in the backend. So it is not possible to edit these **news**. Changes are only possible via SQL commands. 

What should I do to display the **news** in the backend?

Is there another way to import **news** from an older (not more supported) typo3 installation.

Kind Regards

GM

**Comment by georgringer** [comment]
something needs to be different so that those records are not listed.
