### ISSUE TITLE
news 9.1.1 News Search Plugin Results throws an error -> $currentPageNumber must be greater than 0

### ISSUE THREAD

**Issue by daUhradone** [georgringer/news#1710]
## Bug Report

**Current Behavior**
plugin of news to present search results throws an error 

```
core/Classes/Pagination/AbstractPaginator.php line 177
$currentPageNumber must be greater than 0

```
next error refference: extbase/Classes/Pagination/Query/ResultPaginator.php line 41.

This also happens when pagintaion (above and below) in the list.html template is commented.

**Expected behavior/output**
present search results

**Environment**
- TYPO3 version(s): [10.4.23]
- news version: [9.1.1]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [OSX]

**Possible Solution**
changed line 177 of the core class **for a test** to set at this stadium the current page number to 1 instead of throwing an errror.

AbstractPaginator.php line 177

`if($currentPageNumber<1) {$currentPageNumber = 1;}`

now it works as expected

**Additional context**
normal pagination works, only in search results the problem appears

**Comment by georgringer** [comment]
the `AbractPaginator` is not part of ext:news, a change must be happen in `NewsController` at e.g. line 243
```php
  $currentPage = $this->request->hasArgument('currentPage') ? (int)$this->request->getArgument('currentPage') : 1;
```

wanna do a PR?

**Comment by daUhradone** [comment]
Yes, I know the `AbstractPaginator` is part of the core. For a test it was the easiest way to test from the point where the error occurs.

But tried to understand how you extend or inherit from the `AbstractPaginator` and didn't find my way through. 
Probably beyond my skills.

In the class of the core (AbstractPaginator) is a comment that says, if there is only one page, the current page number goes 0.

comment in core:

        ```If the total amount of items is zero, then the number of
         pages is mathematically zero as well. As that looks strange
          in the frontend, the number of pages is forced to be at least one.```


So if `NewsController` line 243 is the cruical point in the news core one would just have to make sure that `$currentPage` is allways 1 or bigger.
Thats as far as I understood it.

**Comment by daUhradone** [comment]
changed `NewsController` Line 243 to:

`$currentPage = max(1, $this->request->hasArgument('currentPage') ? (int)$this->request->getArgument('currentPage') : 1);
`
works

**Comment by daUhradone** [comment]
Hello Georg,
do you think this could go into the original code?
Still have to change it manually after every upgrade.

Thanks!

**Comment by georgringer** [comment]
thanks for the reminder, just fixed it
