### ISSUE TITLE
<n:widget.ajax.paginateAdditionalParams> still available in templates

### ISSUE THREAD

**Issue by medarob** [georgringer/news#1711]
## Bug Report
In EXT:news 9 the pagination viewhelpers `<n:widget.paginate>` and `<n:widget.ajax.paginateAdditionalParams>`  were removed.

I noticed that in 
https://github.com/georgringer/news/blob/main/Resources/Private/Templates/Styles/Twb/Templates/ViewHelpers/Widget/Paginate/IndexAjax.html#L51

the `<n:widget.ajax.paginateAdditionalParams>` viewhelper is still available in multiple conditions.

Example:
```
<f:widget.link arguments="{currentPage: pagination.previousPage}" data="{container:recordId,link:'{t:uri.ajaxAction(contextRecord:\'tt_content:{recordId}\', pluginName: \'pi1\',additionalParams:\'{n:widget.ajax.paginateAdditionalParams(page:pagination.previousPage)}\')}'}">
   <f:translate key="paginate_previous" />
</f:widget.link>
```

**Environment**
- TYPO3 version(s): 10.4.23
- news version: 9.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10

**Comment by medarob** [comment]
Thank you for the fast fix.
I noticed the following change in the fix

`<f:render partial="List/Item-special" arguments="{newsItem: newsItem, settings:settings}"/>`

Where can I find the Partial `Item-special`?
It seems to be not in the one of the following 3 locations:

![grafik](https://user-images.githubusercontent.com/33951787/150684781-812a3a02-4558-4739-9f90-66fe5127f1cb.png)

![grafik](https://user-images.githubusercontent.com/33951787/150684894-ece7e0eb-ad41-4fdd-903e-173c804b09e7.png)

![grafik](https://user-images.githubusercontent.com/33951787/150684917-a36cbb9f-8fae-48f0-9e9f-737a0687dadf.png)

**Comment by georgringer** [comment]
this is just an example

**Comment by medarob** [comment]
Ah, I understand. Ok
