### ISSUE TITLE
Offset ignored in version 9.1.1

### ISSUE THREAD

**Issue by karelkuijpers** [georgringer/news#1712]
## Bug Report

**Current Behavior**
The plugin of News has as additional option "Starting with given news record"= 9
With version 8 the first 9 news records were skipped. With version 9 it starts with the first record.

**Expected behavior/output**
Expect to start with news record 9 

**Environment**
- TYPO3 version(s):10.4.23
- news version: 9.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: ubuntu 20.4

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by karelkuijpers** [comment]
When I hide pagination it starts with record 9. So it has something to do with the combination of pagination and skipping of first record.

**Comment by georgringer** [comment]
this is an open issue in the core pagination, see https://forge.typo3.org/issues/95802 and write a comment there

**Comment by karelkuijpers** [comment]
The more I think about this issue the more I think it is not the problem of
the pagination but of the system which supplies records to the pagination
system. When I hide pagination the News system is perfectly able to select
settings.limit records starting from settings.offset. But as soon as
pagination is enabled the News system ignores the offset and selects
settings.limit records starting from 0. I think that is an error of the
News system.

_________________________________

Karel Kuijpers

Valenberg 53

2716 LR Zoetermeer

The Netherlands

Teleph: 00 31 79 3229184

Mobile: 00 31 6 36545057


Op zo 23 jan. 2022 om 11:07 schreef Georg Ringer ***@***.***>:

**Comment by karelkuijpers** [comment]
I have added a comment there with a solution, but I am afraid we have to
wait for months before the bug is corrected. In the meantime you can
replace the paginator in module listAction of the NewController with the
array paginator:
        $paginator = new ArrayPaginator( $newsRecords->toArray(),
$currentPage, $itemsPerPage);
That works also fine.

_________________________________

Karel Kuijpers

Valenberg 53

2716 LR Zoetermeer

The Netherlands

Teleph: 00 31 79 3229184

Mobile: 00 31 6 36545057


Op zo 23 jan. 2022 om 11:07 schreef Georg Ringer ***@***.***>:
