### ISSUE TITLE
syntax error by parsing fault of extending class

### ISSUE THREAD

**Issue by DavidBruchmann** [georgringer/news#1714]
An extending class with constructor is still parsed wrong:

![image](https://user-images.githubusercontent.com/999146/151008837-0787e71c-1add-40e9-a090-fd2200d918de.png)

**Comment by DavidBruchmann** [comment]
not related to news, sorry

**Comment by georgringer** [comment]
please give me some examples how to reproduce

**Comment by DavidBruchmann** [comment]
can be dismissed, I can change the syntax in my extension, then it's working.
