### ISSUE TITLE
BE module: news title not clickable to edit article

### ISSUE THREAD

**Issue by liayn** [georgringer/news#1720]
## Bug Report

**Current Behavior**
It is not possible to click on the news' title in the news administration module in the backend.

**Expected behavior/output**
The title should be clickable for faster editing.

**Environment**
- TYPO3 version(s): 11
- news version: 9.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Possible migration steps are necessary to adjust the list rendering to v11 requirements.

**Comment by georgringer** [comment]
@liayn fixed now in main, can you recheck?

**Comment by liayn** [comment]
Confirmed, works. Thanks.
