### ISSUE TITLE
sys_language_uid=1 not shown if empty l10n_parent @ LIST

### ISSUE THREAD

**Issue by xerc** [georgringer/news#1723]
typo3 10.4.24 | news 9.2.0

given there are multible news ; EN sys_lng_uid = 0 & DE sys_lng_uid = 1
create a NEWS with sys_lng_uid = 1 w/o having a EN original referenced
it will not be shown within LIST => working but hack`i PATCH @ https://github.com/georgringer/news/commit/1d6195efdcbaac111f63e0424187d35a58cc7f1d

**Comment by georgringer** [comment]
Use https://github.com/georgringer/extbase_with_no_l10n_parent, nothing to be changed in news

**Comment by xerc** [comment]
fyi/ `findDemanded` third option `$disableLanguageOverlayMode` is never used ; RegEx `findDemanded\(.+,.+,.+\);`
