### ISSUE TITLE
Filtering by multiple categories breaks since version 9.1

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [georgringer/news#1729]
With the change in https://github.com/georgringer/news/commit/770c2ee25c14b384de1a005bca388f3b8161207c filtering by multiple categories doesn't work anymore.

Reason: Categories set in the plugin and its children are not delivered anymore, but only the demanded categories that the user clicked.

before:
![news_cat_works](https://user-images.githubusercontent.com/51790093/155361225-c9d66eab-7734-4c53-a6fa-ffd623592ff8.png)

after:
![news_cat_breaks](https://user-images.githubusercontent.com/51790093/155361262-105dbd03-cb5d-43ed-a767-1e648ce5be84.png)

I reverted the change with a patch but a native solution would be of course better.

Thanks in advance.

**Environment**
- TYPO3 version(s): 10.4.23
- news version: 9.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10

**Comment by georgringer** [comment]
what about changing it to something like this

```php
        $idList = is_array($demand->getCategories()) ? $demand->getCategories() : explode(',', $demand->getCategories());
        if (empty($idList)) {
            $idList = explode(',', $this->settings['categories']);
        }
```

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thanks for your thoughts.

This doesn't work, because it's not about empty lists. If the user clicked one or more categories, then the $idList is not empty and the condition wouldn't be true. To make the multi filtering work, all categories that are set in the plugin and its children have to be there at all time, independent from what the fe-user clicked. See first screenshot -> it worked before the commit. After the commit you cannot show all other categories anymore.

I'm not sure what improvement the mentioned commit is, but it breaks the multi filtering. If the commit is important, then I can only imagine to have both array versions in fluid.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
For example like this:

categories -> Like it was before including children, so it doesn't break things.
categoriesDemand -> Like it is now.

**Comment by georgringer** [comment]
related https://github.com/georgringer/news/pull/1555#issuecomment-993800234

**Comment by PascaleBeier** [comment]
@h-e-l-l-o-w-o-r-l-d 

We solved it like this, using `(cweagans/composer-patches)[https://github.com/cweagans/composer-patches]`. Maybe it helps you:

1. Save the following patch file to `patches/category-menu-news.patch` in your project root

```patch

---
 Classes/Controller/CategoryController.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Classes/Controller/CategoryController.php b/Classes/Controller/CategoryController.php
index 7f376fece..8907e0c7c 100644
--- a/Classes/Controller/CategoryController.php
+++ b/Classes/Controller/CategoryController.php
@@ -30,7 +30,7 @@ public function listAction(array $overwriteDemand = null)
             $demand = $this->overwriteDemandObject($demand, $overwriteDemand);
         }
 
-        $idList = is_array($demand->getCategories()) ? $demand->getCategories() : explode(',', $demand->getCategories());
+        $idList = explode(',', $this->settings['categories']);
 
         $startingPoint = null;
         if (!empty($this->settings['startingpoint'])) {
```


2. Add the patch to our composer.json

```json
{
    "extra": {
        "patches": {
            "georgringer/news": {
                "Revert category menu bugfix": "patches/category-menu-news.patch"
            }
        }
    }
}
```

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thanks @PascaleBeier for the help, but I installed the exact same patch already as written in my inital post. Now hoping for a native solution from @georgringer .

**Comment by derghostface** [comment]
For my purpose (filtering by multiple categories in search) I changed line 211 in NewsController from
`if (in_array($propertyName, ['categories'], true)) {`
to
`if (in_array($propertyName, ['categories'], true) && !is_array($propertyValue)) {`

**Comment by develth** [comment]
This is still a issue, or?
