### ISSUE TITLE
On 9.2.0, the detail page error handling does not work any more.

### ISSUE THREAD

**Issue by mkarulin** [georgringer/news#1730]
## Bug Report

**Current Behavior**
On 9.2.0, the detail page error handling does not work any more.

**Expected behavior/output**
Missing news should return error, determined in the deail.errorHandling configuration

**Environment**
- TYPO3 version(s): 10.4
- news version: [e.g. 9.2.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: all

**Possible Solution**
Remove the line that overwrites the parameter $configuration: https://github.com/georgringer/news/blob/26c9807a25e1af51276997897f66df82d0c2d77f/Classes/Controller/NewsBaseController.php#L97

**Comment by georgringer** [comment]
this has been changed again, sry
