### ISSUE TITLE
News and manual sorting

### ISSUE THREAD

**Issue by jansass** [georgringer/news#1731]
Hello,

when a news record is translated to more than one language and we use manual sorting to display those news records, all records share the same sorting INTeger. This sorting integer is used for manual sorting (read: decreased if pushed up, increased if pushed down).

At some point in time those ints got mangled in one of our systems. When pushing up a record, only the first language get re-sorted, the rest remains, see:

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/4060287/156142862-1972b0f4-0f90-495c-af7a-80461e5c92e0.png">

… the first is broken, the second works. When i push up the first, only first Sorting INT changes, when pushing up the second, ALL INTs change.

Is this a known bug? Do we need to fix the integers only ?

**Comment by georgringer** [comment]
thanks for creating the issue. as this is a core functionality and not news itself, please report at https://forge.typo3.org/projects/typo3cms-core/issues - tested with records like tt_content
