### ISSUE TITLE
Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by xperseguers** [georgringer/news#1734]
## Bug Report

**Current Behavior**

When I put the plugin in mode list on my website, MariaDB makes the generation crash with `Commands out of sync; you can't run this command now`.

The plugin is configured to take news from 2 starting points, one being a standard folder, the second being a whole hierarchy of multiple websites (depending on the page, from 70 to 110 sites, each known for having 1 folder dedicated to news).

**Expected behavior/output**

No crash!

**Environment**
- TYPO3 version(s): 9.5
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu LTS Focal

**Possible Solution**

After debugging a bit it turns out the starting point expansion leads to a list of 2722 pages to be searched for news. Somehow this doesn't feel good.

1st (side) remark: although this is not related to the crash I encounter, expanding the list is done each time the plugin is rendered (or the corresponding page is flushed, which would happen when a news has been updated). This is really inefficient as it eats a few seconds to compute that list of 2722 uids.

I tried to patch the starting point expansion to filter out non-news folders. The result is only 110 pages to be taken into account instead of 2722 and "somehow" this prevents the crash.

Note: I found this: https://forge.typo3.org/issues/86986 with a similar crash related to a sysext but playing around with `sort_buffer_size` didn't help in my case.

There must be something which could be queried better because the error message is explained as be related to some wrong way of doing multiple queries against a DB, without properly reading results but this could be tricky to debug and unfortunately I can't reproduce it with a local MySQL server, either really related to MariaDB or some other environment context. And possibly nothing you could fix in your own code but possibly related to Extbase.

Anyway, in case it helps someone, here's my patch for EXT:news:

```patch
--- Page.orig.php	2021-08-27 06:38:55.000000000 +0200
+++ Page.php	2022-03-02 13:38:10.000000000 +0100
@@ -10,10 +10,12 @@
  */
 use TYPO3\CMS\Backend\Tree\View\PageTreeView;
 use TYPO3\CMS\Backend\Utility\BackendUtility;
+use TYPO3\CMS\Core\Database\ConnectionPool;
 use TYPO3\CMS\Core\Imaging\Icon;
 use TYPO3\CMS\Core\Imaging\IconFactory;
 use TYPO3\CMS\Core\Utility\GeneralUtility;
 use TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer;
+use TYPO3\CMS\Frontend\Page\PageRepository;
 
 /**
  * Page Utility class
@@ -41,6 +43,7 @@
         foreach ($storagePids as $startPid) {
             if ($startPid >= 0) {
                 $pids = $queryGenerator->getTreeList($startPid, $recursive, 0, 1);
+                $pids = self::filterNewsFolders($pids);
                 if (strlen($pids) > 0) {
                     $recursiveStoragePids .= ',' . $pids;
                 }
@@ -50,6 +53,48 @@
     }
 
     /**
+     * Returns a list of folders marked as using the module "news".
+     *
+     * @param string $pids
+     * @return string
+     */
+    protected static function filterNewsFolders(string $pids): string
+    {
+        $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
+            ->getQueryBuilderForTable('pages');
+
+        $pids = explode(',', $pids);
+
+        // To be on the safe side even if newer version of MySQL/MariaDB
+        // do not seem to suffer from that limit anymore
+        $chunkSize = 1000;
+        $inConstraints = [];
+        while (!empty($pids)) {
+            $chunk = array_slice($pids, 0, $chunkSize);
+            $inConstraints[] = $queryBuilder->expr()->in('uid', $chunk);
+            $pids = array_slice($pids, count($chunk));
+        }
+
+        $rows = $queryBuilder
+            ->select('uid')
+            ->from('pages')
+            ->where(
+                $queryBuilder->expr()->orX(...$inConstraints),
+                $queryBuilder->expr()->eq('doktype', PageRepository::DOKTYPE_SYSFOLDER),
+                $queryBuilder->expr()->eq('module', $queryBuilder->quote('news'))
+            )
+            ->execute()
+            ->fetchAll();
+
+        $pids = [];
+        foreach ($rows as $row) {
+            $pids[] = $row['uid'];
+        }
+
+        return implode(',', $pids);
+    }
+
+    /**
      * Set properties of an object/array in cobj->LOAD_REGISTER which can then
      * be used to be loaded via TS with register:name
      *

```

**Comment by LeoniePhiline** [comment]
You will have better performance by using `array_chunk()` rather than repeating `array_slice()`.

**Comment by LeoniePhiline** [comment]
The problem might be fixable via `max_allowed_packet`. See https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#operator_in 

Quote:

> The number of values in the IN() list is only limited by the [max_allowed_packet](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet) value.

**Comment by xperseguers** [comment]
Thanks for the remark regarding `array_chunk`. But the actual problem I got was not related to having more than 1000 items in the `IN ()` and having MariaDB fail, I tested it, the query runs just fine with more than 1000 items as indeed `max_allowed_packet` is large enough.

I knew this wasn't the problem since I wrote this in my patch for the `array_slice` part:

```patch
+        // To be on the safe side even if newer version of MySQL/MariaDB
+        // do not seem to suffer from that limit anymore
```

The problem is elsewhere, with some other queries doing something "wrong" but having a prefiltered list of folders where to search news (in my case 110 instead of possibly 2722) solves it because the kind of "database memory leak" is not large enough to trigger the fault.

**Comment by LeoniePhiline** [comment]
Simplified proposal:

```php
use Doctrine\DBAL\Connection;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Frontend\Page\PageRepository;

/**
 * Returns a list of folders marked as using the module "news".
 *
 * @param  string $pids
 * @return string
 */
protected function filterNewsFolders(string $pids): string
{
    $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
        ->getQueryBuilderForTable('pages');

    return implode(',', array_map(
        fn (array $record) => $record['uid'],
        $queryBuilder
            ->select('uid')
            ->from('pages')
            ->where(
                $queryBuilder->expr()->orX(
                    // Circumvent MariaDB flipping over with 'Commands out of sync; you can't run this command now (2014)'
                    ...array_map(
                        fn (array $chunk) => $queryBuilder->expr()->in('uid', $queryBuilder->createNamedParameter($chunk, Connection::PARAM_INT_ARRAY)),
                        array_chunk(GeneralUtility::trimExplode(',', $pids), 1024)
                    )
                ),
                $queryBuilder->expr()->eq('doktype', PageRepository::DOKTYPE_SYSFOLDER),
                $queryBuilder->expr()->eq('module', $queryBuilder->quote('news'))
            )
            ->execute()
            ->fetchAllAssociative()
    ));
}
```

In the end, this kind of workaround should be part of the DBAL, though. This is not application logic.

**Comment by georgringer** [comment]
I am not sure if I should enforce it in general to use the module directive but could be behind a feature flag, what do you think?

**Comment by tobiasschaeferptb** [comment]
Hello,

I had the same error in the powermail backend module when I tried to access a sysfolder with 1000 entries or more.
The error occured after an upgrade from MariaDB 10.2 to 10.5.
With MariaDB 10.3.18 they introduced a new parameter called in_predicate_conversion_threshold with a default value of 1000. 
[https://mariadb.com/kb/en/server-system-variables/#in_predicate_conversion_threshold](https://mariadb.com/kb/en/server-system-variables/#in_predicate_conversion_threshold)
After adding in_predicate_conversion_threshold = 4294967295 into the my.cnf and restarting MariaDB the "Commands out of sync; you can't run this command now" error didn't occur anymore. The maximum value is 4294967295. I can't understand why the MariaDB developers choose such a small value of 1000 as default.

Cheers, Tobias

**Comment by dominikmuellerwf** [comment]
Hello,

I have this error in combination with sys_categories. While saving an entry with a category selected, TYPO3 updates the refindex and throws the error, but only if extension news is installed and active.

Perhaps this part:
call_user_func(array(object(TYPO3\CMS\Core\Database\RelationHandler), 'purgeVersionedIds'), 'tx_news_domain_model_news', array('r', 'S'))

or something here:
TYPO3\CMS\Core\Database\RelationHandler->start(0, 'be_groups,be_users,pages,sys_category,sys_collection,sys_file,sys_file_collection,sys_file_metadata,sys_file_reference,sys_file_storage,sys_filemounts,sys_history,sys_language,sys_log,sys_news,tx_scheduler_task_group,backend_layout,fe_groups,fe_users,sys_domain,sys_template,tt_content,tx_extensionmanager_domain_model_extension,tx_extensionmanager_domain_model_repository,sys_redirect,sys_note,tx_cfcleague_club,tx_cfcleague_competition,tx_cfcleague_competition_penalty,tx_cfcleague_games,tx_cfcleague_group,tx_cfcleague_match_notes,tx_cfcleague_note_types,tx_cfcleague_profiles,tx_cfcleague_saison,tx_cfcleague_stadiums,tx_cfcleague_team_notes,tx_cfcleague_teams,tx_news_domain_model_link,tx_news_domain_model_news,tx_news_domain_model_tag,tx_t3sportstats_tags,tx_t3users_log,tx_gridelements_backend_layout,tx_dfbsync_data,tx_mksearch_configcomposites,tx_mksearch_indexerconfigs,tx_mksearch_indices,tx_mksearch_keywords,tx_kesearch_filteroptions,tx_kesearch_filters,tx_kesearch_index,tx_kesearch_indexerconfig,tx_powermail_domain_model_answer,tx_powermail_domain_model_field,tx_powermail_domain_model_form,tx_powermail_domain_model_mail,tx_powermail_domain_model_page', 'sys_category_record_mm', 2, 'sys_category', array('type' => 'group', 'internal_type' => 'db', 'allowed' => '*', 'MM' => 'sys_category_record_mm', 'MM_oppositeUsage' => array('pages' => array('categories'), 'sys_file_metadata' => array('categories'), 'tt_content' => array('categories'), 'tx_news_domain_model_news' => array('categories')), 'size' => 10, 'fieldWizard' => array('recordsOverview' => array('disabled' => true))))

or here:
TYPO3\CMS\Core\Database\ReferenceIndex->getRelations_procDB(0, array('type' => 'group', 'internal_type' => 'db', 'allowed' => '*', 'MM' => 'sys_category_record_mm', 'MM_oppositeUsage' => array('pages' => array('categories'), 'sys_file_metadata' => array('categories'), 'tt_content' => array('categories'), 'tx_news_domain_model_news' => array('categories')), 'size' => 10, 'fieldWizard' => array('recordsOverview' => array('disabled' => true))), 2, 'sys_category')

That are the only hints to "news" in the error message.

TYPO3 9.5.31
news 8.6.0

**Comment by einpraegsam** [comment]
I'm facing the same problem with a large pagetree in backend that an editor wants to see in a large installation. This is not related to the news extension! Nevertheless this is the only help that can be found at the moment. The hint from @tobiasschaeferptb works like a charm - thx.

**Comment by lisardo2** [comment]
I am facing the problem too and in more than one cases: 
- the same issue with news (starting point expansion)
- indexed_search: search results in this error
Uncaught TYPO3 Exception: Commands out of sync; you can't run this command now | Doctrine\DBAL\Driver\Mysqli\MysqliException thrown in file /typo3_src-9.5.31/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php in line 327. Requested URL: /typo3/index.php?route=%%2Fweb%%2FIndexedSearchIsearch%%2F&token=--AnonymizedToken--&id=39
- backend, modul index works only on subpages and throws this error when trying the root page or pages with many subpages
- backend search field (in header right top) does not work any more (only spinning wheel) 
Uncaught TYPO3 Exception: Commands out of sync; you can't run this command now | Doctrine\DBAL\Driver\Mysqli\MysqliException thrown in file /typo3_src-9.5.31/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php in line 327. Requested URL: /typo3/index.php?route=%%2Fajax%%2Flivesearch&token=--AnonymizedToken--&q=test

**Comment by georgringer** [comment]
this is not an issue of ext:news, therefore I am locking this issue

**Comment by georgringer** [comment]
closing this issue as I won't change anything in that regard
