### ISSUE TITLE
Setting "records.mediaPreview" in Extension Configuration has no effect in TYPO3 11

### ISSUE THREAD

**Issue by cnmarco** [georgringer/news#1736]
## Bug Report

**Current Behavior**
The setting "`Show thumbnails in backend list module`" (`records.mediaPreview`) has no effect in TYPO3 11 LTS anymore.

**Expected behavior/output**
Show thumbnails from fal_media in list view of news records, when setting is activated.

**Environment**
- TYPO3 version(s): [11.5.7]
- news version: [9.2.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Debian 10]

**Possible Solution**
Simplest solution is to remove the setting from Extension Configuration and TCA of tx_news_domain_model_news, as it may be confusing for users who don't know about the deprecation (see additional context below).

**Additional context**
`$GLOBALS['TCA'][$aTableName]['ctrl']['thumbnail']` has been dropped since TYPO3 11.5.0:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-92118-TCACtrlThumbailSettingDropped.html

**Comment by georgringer** [comment]
thanks for creating the issue!

**Comment by bocianl** [comment]
Hello,

Is there any chance to make this preview work again?

**Comment by georgringer** [comment]
> Hello,
> 
> Is there any chance to make this preview work again?

@bocianl use https://github.com/studiomitte/recordlist_thumbnail
