### ISSUE TITLE
"Disable required date field" [records.dateTimeNotRequired] is ignored in "List of selected items" [News->selectedList]

### ISSUE THREAD

**Issue by alsodenn** [georgringer/news#1737]
## Bug Report

**Current Behavior**
"Disable required date field [records.dateTimeNotRequired]" is ignored in "List of selected items". 
The following error message appears in the frontend: 
```
"Oops, an error occurred!
Return value of GeorgRinger\News\Domain\Model\News::getDatetime() must be an instance of DateTime, null returned".
```

**Expected behavior/output**
"Disable required date field [records.dateTimeNotRequired]" setting should also be respected in the List of selected items [News->selectedList]

**Environment**
- TYPO3 version(s): 10.4.26
- news version: 9.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by alsodenn** [comment]
Thank you for fixing it so quickly. It works now!

**Comment by AstCommodore** [comment]
All datetime properties could be null, so it makes sense to change the return type for those too?!

```
--- a/Classes/Domain/Model/News.php	2022-03-17 08:32:23.000000000 +0100
+++ b/Classes/Domain/Model/News.php	2022-04-05 10:08:33.000000000 +0200
@@ -1387,9 +1387,9 @@
     /**
      * Get start time
      *
-     * @return DateTime
+     * @return DateTime|null
      */
-    public function getStarttime(): DateTime
+    public function getStarttime(): ?DateTime
     {
         return $this->starttime;
     }
@@ -1448,9 +1448,9 @@
     /**
      * Get endtime
      *
-     * @return DateTime
+     * @return DateTime|null
      */
-    public function getEndtime(): DateTime
+    public function getEndtime(): ?DateTime
     {
         return $this->endtime;
     }

```

**Comment by georgringer** [comment]
fixed yesterday
