### ISSUE TITLE
List Tags (and maybe categories too) in News Administration Modul

### ISSUE THREAD

**Issue by GenerationU** [georgringer/news#1738]
At the moment its only possible to create tags at News Administration modul and list them at the list modul. It would be good to can list them at News Administration Modul too. Maybe same with categories. Its easier to work with then. And its better for giving editors rights. Then its possible to give editors only the newsadministration modul rights :)

**Comment by georgringer** [comment]
solved with #0495266ba0030e37da89a2e193300d4c17fe3e98
