### ISSUE TITLE
Bug in BE module after update to version 9.3.0

### ISSUE THREAD

**Issue by responseinformationsdesign** [georgringer/news#1748]
## Bug Report

**Current Behavior**
"No news found" in BE module even so there are articles in this sysfolder after update to version 9.3.0

**Expected behavior/output**
Show all articles (as in versions < 9.3.0) 

**Environment**
- TYPO3 version(s): 10.4.26
- news version: 9.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows Server 2012 R2

**Comment by georgringer** [comment]
which version did you have before?

**Comment by responseinformationsdesign** [comment]
No problems with version 9.2.0 (which was used before)
