### ISSUE TITLE
lightbox settings are taken from css-styled-content

### ISSUE THREAD

**Issue by scibile** [georgringer/news#175]
more and more this is switched of and fluid-styled-content is used, the solution given in the docs does not deal with the issue but gives a shortcut ... rather than that solution I overrode the settings which works very well: 
```

plugin.tx_news {
	settings {
		detail {
			media {
				image {
					# Get lightbox settings from css_styled_content
					lightbox {
						# maybe enabled can be a selected constant
						enabled = 1
						class = lightbox-group
						width = 
						height = 
						rel = lightboxGroup-[myImageSet]
					}
				}
			}
		}
	}
}
```

**Comment by georgringer** [comment]
It was about documentation only, in the actual TS; I checked for fsc already
