### ISSUE TITLE
News ignores recursive setting from TypoScript

### ISSUE THREAD

**Issue by IchHabRecht** [georgringer/news#1750]
## Bug Report

**Current Behavior**
- given a news list plugin with a storage defined as startingpoint and recursive selectbox set to "defined in typoscript"
- plugin.tx_news.persistence.recursive = 250 set in typoscript

**Expected behavior/output**
- news found in any subfolder of the startingpoint should be shown

**Environment**
- TYPO3 version(s): 10.4.26
- news version: 9.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Unix, Windows

**Possible Solution**
- care about framework settings in \GeorgRinger\News\Controller\NewsController::checkPidOfNewsRecord

Not sure if this is expected behaviour or needs to be fixed.

**Comment by georgringer** [comment]
thanks for creating the issue. I don't use the default persistence but you can use `plugin.tx_news.settings.recursive = 2` see https://docs.typo3.org/p/georgringer/news/main/en-us/Reference/TypoScript/PluginSettings.html#recursive-recursive
