### ISSUE TITLE
From Detailpage "backlink" to Pagination is always first page and Not page where comes from

### ISSUE THREAD

**Issue by GenerationU** [georgringer/news#1755]
It would be good if the user are on an News at detailpage and click at the backlink, he would comes to the pagination- page he was come from/ the news was listet. It have to check at wich pagination-site is the news listet and then redirect the user to that page.

**Comment by georgringer** [comment]
I don't plan to add more information to the link. it would also need to take in account if the previous page was a kind of a filter. i suggest using something like this https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/Templates/Snippets/Index.html?highlight=histori#improved-back-links
