### ISSUE TITLE
enablePreviewOfHiddenRecords on News 8.6.0

### ISSUE THREAD

**Issue by PowerAmbroz** [georgringer/news#1758]
Hello.
I'm trying to force the PreviewOfHiddenRecords to work. I've seen issue #395 but it didn't help me.
In my setup, I've set plugin.tx_news.settings.previewHiddenRecords = 1 and tryed even with plugin.tx_news.settings.enablePreviewHiddenRecords = 1 but I don't see any way to preview the hidden record.

On the List view, I have a hidden news and when I enter it I don't see any preview option.
Hope you can help me with this issue.
Best Regards.
![obraz](https://user-images.githubusercontent.com/9193428/159441569-03b2a0c3-20c0-4aee-ab9c-d19d11d715df.png)

**Comment by georgringer** [comment]
`plugin.tx_news.settings.previewHiddenRecords` is used to enable *rendering* hidden records in the frontend. to generate preview links in the *backend* you need to use the linkhandler https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/BestPractice/Linkhandler/Index.html
