### ISSUE TITLE
News Administration module: buttons "Download" and "Show Columns" do not work

### ISSUE THREAD

**Issue by cnmarco** [georgringer/news#1759]
## Bug Report

**Current Behavior**
Buttons "Download" and "Show Columns" have no effect in News Administration module

**Expected behavior/output**
Same behaviour as in list view expected (modals for options should open)

**Environment**
- TYPO3 version(s): 11.5.8
- news version: 9.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian 10

**Comment by georgringer** [comment]
yes need to look into that, sorry

Related to #1720

**Comment by georgringer** [comment]
solved already
