### ISSUE TITLE
Update from 9.2.0 to 9.3.1 failes

### ISSUE THREAD

**Issue by revilosun** [georgringer/news#1761]
## Bug Report

**Current Behavior**
After update via composer the news arcticle only shows in the list-icon, not in the news administration.
Under maintenance -> database analysis it will an update of the db:

ALTER TABLE `tx_news_domain_model_news` CHANGE `related_links` `related_links` INT DEFAULT 0 NOT NULL 
Current value: related_links TINYTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`

this command failed, because many articles have NULL in this row. An manual update of the db (set NULL with '0'), has no effect.

Error: Data truncated for column 'related_links' at row 6

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 10.4.26
- news version: 9.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu

**Possible Solution**

Downgrade to 9.2.0

**Additional context**
I have updated from 8.6 step by step with every version

**Comment by skrude61** [comment]
But here it is not the news plugin that is not working but the "News administration" module.
BTW: With TYPO3 11.5.8 the News administration module is working, so there must be an incompatibility of news 9.3.0 and 9.3.1 with TYPO3 10.4.26.

**Comment by revilosun** [comment]
Yes I confirm it. After update on TYPO3 11.5.8, the News run with 9.20 and 9.3.1 with the News administration module.

**Comment by skrude61** [comment]
Unfortunately there are extensions I need that are not yet compatible with TYPO3 11.

**Comment by Treedent** [comment]
Same here. After updating to news V9.3.1 from 9.2.0 on TYPO3 V10.4.26 under Debian, the news module does not displays news anymore.

**Comment by RudStar** [comment]
Also confirm the problem: TYPO3 10.4.26, PHP 7.4 and News 9.2.0 works. 
After the update to 9.3.1, there are no more entries in the News administration module.

**Comment by kc1de** [comment]
Here the same behavior. After the update to 9.3.1 no more news are displayed in the news administration module. The module shows "No news found" although there are news records in the corresponding folder. If you click on "See all pages containing news records", the correct number of news records is displayed.

As mentioned above, the database schema cannot be updated. The "Alter Table" command aborts with the error message "Database update failed - Error: Data truncated for column 'related_links' at row 2".

TYPO3 Version 10.4.26

**Comment by chesio** [comment]
> As mentioned above, the database schema cannot be updated. The "Alter Table" command aborts with the error message "Database update failed - Error: Data truncated for column 'related_links' at row 2".

See here for a (manual) fix: https://github.com/georgringer/news/pull/1436#issuecomment-971414394

**Comment by kc1de** [comment]
The above fix solves the problem with the "Analyze Database Structure" error. Unfortunately, the error that the news articles are not displayed is not fixed. It seems that the two problems have nothing to do with each other.

**Comment by milicj** [comment]
![Screenshot 2022-04-06 at 12 20 28](https://user-images.githubusercontent.com/87117603/161959061-ff029f9d-4f63-4e72-812f-1957e155f8c0.png)
That part breaks the BE Administration module in TYPO3 v10 version.
