### ISSUE TITLE
Condition on class_exists(NumberedPagination::class) is in wrong order

### ISSUE THREAD

**Issue by foobar13372** [georgringer/news#1765]
NewsController line 246:

`if ($paginationClass === NumberedPagination::class && $maximumNumberOfLinks && class_exists(NumberedPagination::class))`

You first access NumberedPagination::class as if it would exist and only _after_ then ask whether this class actually exists by `class_exists(NumberedPagination::class)`.

Either drop the `class_exists(NumberedPagination::class)` condition at all (it is _currently_ totally redundant to the first condition) or make it absolutely clean and clear by applying the `class_exists` condtion _first_.

**Comment by georgringer** [comment]
don't see a real issue here, $paginationClass is set in https://github.com/georgringer/news/blob/main/Configuration/TypoScript/setup.typoscript#L152 to `NumberedPagination`. 

but nevertheless the extension might not be installed. I highly recommend to use that extension but I don't want a dependency there

**Comment by foobar13372** [comment]
We don't have this extension installed, because we use a fully custom own pagination.

Then `$paginationClass === NumberedPagination::class` coming _first_ is the same error as accessing an undefined constant. You always have to check whether a constant or variable exists (`isset`, `??` or `class_exists`) if it _possibly_ is undefined. In this case the `class_exists` check has to come _first_, thus.

I know that `::class` is evaluated already on compile-time, not on interpret-time and thus fully transform into a string at interpret-time - this is why this does not throw a PHP error - semantically it is still wrong, however, and we all know that PHP behaviour may change from version to version and thus we should not rely on "lucky current behaviour that may be a PHP internal bug/misbehvaiour", but instead order our code in a way that it will work in any case in the future.
