### ISSUE TITLE
schema.org logical problem with list-item not beeing the article itself -> use "isBasedOn"

### ISSUE THREAD

**Issue by daUhradone** [georgringer/news#1766]
### schema.org improvement
**Is your feature request related to a problem? Please describe.**
news now pretendes that the list item is a full article by itself, but it should mark the list item as "isBasedOn" the real article in detail view.

**Describe the solution you'd like**
Two solutions are possible:

a. allow the text  `itemprop="url"` inside the n:link-viewhelper
This would allow to use e.g. the "read more" link for adding the missing schema.org tag inside List/Item.html:
```
          <span  itemprop="isBasedOn" itemscope itemtype="https://schema.org/CreativeWork">
		<n:link newsItem="{newsItem}" settings="{settings}" itemprop="url" class="more" title="{newsItem.title}" >
			<f:translate key="more-link"/>
		</n:link>
        </span>
```
output

```
<a class="more" title="headline" itemprop="url" href="/aktuelles/nachricht/headline-news-article">
    read more
</a>
```

The problem is here also that it is only a relative link. 
So if 'itemprop="url"' then output a full link.

**Describe alternatives you've considered**
b.

For the time being I have added the following construction, just bevore the closing div of List/Item.html:

   ```
 <span  itemprop="isBasedOn" itemscope itemtype="https://schema.org/CreativeWork">
        <meta itemprop="url" content='https://your-site.de<n:link newsItem="{newsItem}" settings="{settings}" uriOnly="true" ></n:link>' />
    </span>
```
The schema.org validator will show:

```
@type                   Article
  datePublished         2022-01-05
  headline              My article headline
  description           The teaser text I used is here
  isBasedOn
      @type             CreativeWork
      url               https://my-website.de/aktuelles/nachricht/single-news-item-headline
```

Please note that route enhancers are in place (site settings), so no cache numbers are part of the link etc.

**Teachability, Documentation, Adoption, Migration Strategy**
Best is to migrate the partial List/Item.html or to extend the n:link viewhelper

For schema.org to tag two articles with the same headline and body text is not so nice.

**Comment by georgringer** [comment]
thanks for creating the issue. the following is already possible:

```html
<n:link newsItem="{newsItem}" settings="{settings}" title="{newsItem.title}" additionalAttributes="{itemprop:'url'}">
	<span itemprop="headline">{newsItem.title}</span>
</n:link>
```

would that be enough and would it be good or produce possibly more harm if added to the default templates?

**Comment by daUhradone** [comment]
If the n:link viewhelper would give a full url it would help, if the outside area of "article", "isBasedOn" and "@type" is there.
I'm not sure how search engines deal with relative links coming from schema.org.

**Comment by georgringer** [comment]
what about using
```html
<n:link configuration="{forceAbsoluteUrl:1}" newsItem="{newsItem}" settings="{settings}" title="{newsItem.title}" additionalAttributes="{itemprop:'url'}">
				<span itemprop="headline">{newsItem.title}</span>
			</n:link>
```

then?

**Comment by daUhradone** [comment]
looks perfect for me!

**Comment by georgringer** [comment]
reading e.g. https://sergeyski.com/relative-urls-in-structured-data/ I don't currently know what I should do in the extension itself:

- leave it like it is. the proposed implementation can only be seen as a good start and not a 100% perfect solution for everyony
- add just the `itemprop="url"`
- add it as snippet to the docs?

I don't want to force absolut urls by default to avoid maybe other potential breaking changes. 

what do you think?

**Comment by daUhradone** [comment]
Do I see it right, that the n:link viewhelper doesn't have the "forceAbsoluteUrl" yet?

If someone is using an old template he will not have the "forceAbsolutUrl" and he will not have the additionalAttributes "itemprop: 'url'", so if it is not there it will not create a breaking change. The new version of the n:link viewhelper will still work fine with older templates since it is just an option that is not used.

Using newer templates on older versions of news is not likely to happen.

Since the full domain is derived via php from TYPO3 dynamically we don't have the problem of Sergeyski with static sites that should work in different domain areas.

For my understanding you could go full in with the absolute url plus itemprop = "url", or trust the test of Sergeyski for Google to stay with relative links. 
But we don't know how Bing and DuckDuckGo are  treating relative links.

**Comment by georgringer** [comment]
Will go with itemprop only I guess, just to avoid issues
