### ISSUE TITLE
Google News Sitemap Template not found

### ISSUE THREAD

**Issue by Michi01** [georgringer/news#1767]
## Bug Report

**Current Behavior**
When you want to set up the GoogleNews Sitemap it does not find the template for GoogleNews
Logfile is attached.

**Expected behavior/output**
A generated Google News Sitemap

**Environment**
- TYPO3 version(s): [e.g. 8.7.12, 9.2.0] 10.4.25
- news version: [e.g. 7.0.5] latest and 8.6.0
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes, no] yes
- OS: [e.g. OSX 10.13.4, Windows 10] OSX and Ubuntu

**Additional context**
Logfile
ed, 06 Apr 2022 10:10:13 +0000 [ALERT] request="47f6ca5c3ccfa" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 20220406101013829ce7fa - {"exception":"TYPO3Fluid\\Fluid\\View\\Exception\\InvalidTemplateResourceException: Tried resolving a template file for controller action \"Standard->eXT:news/Resources/Private/Templates/News/GoogleNews\" in format \".xml\", but none of the paths contained the expected template file (Standard/EXT:news/Resources/Private/Templates/News/GoogleNews.xml). The following paths were checked: /opt/homebrew/var/www/typo10/public/typo3/sysext/seo/Resources/Private/Templates/XmlSitemap/, /opt/homebrew/var/www/typo10/public/typo3/sysext/seo/Resources/Private/Templates/ in /opt/homebrew/var/www/typo10/vendor/typo3fluid/fluid/src/View/TemplatePaths.php:598\nStack trace:\n#0 /opt/homebrew/var/www/typo10/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(391): TYPO3Fluid\\Fluid\\View\\TemplatePaths->getTemplateSource('Standard', 'eXT:news/Resour...')\n#1 /opt/homebrew/var/www/typo10/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php(212): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->TYPO3Fluid\\Fluid\\View\\{closure}(Object(TYPO3Fluid\\Fluid\\Core\\Parser\\TemplateParser), Object(TYPO3\\CMS\\Fluid\\View\\TemplatePaths))\n#2 /opt/homebrew/var/www/typo10/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php(192): TYPO3Fluid\\Fluid\\Core\\Parser\\TemplateParser->parseTemplateSource('Standard_action...', Object(Closure))\n#3 /opt/homebrew/var/www/typo10/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(392): TYPO3Fluid\\Fluid\\Core\\Parser\\TemplateParser->getOrParseAndStoreTemplate('Standard_action...', Object(Closure))\n#4 /opt/homebrew/var/www/typo10/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(179): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->getCurrentParsedTemplate()\n#5 /opt/homebrew/var/www/typo10/public/typo3/sysext/seo/Classes/XmlSitemap/XmlSitemapRenderer.php(141): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()\n#6 /opt/homebrew/var/www/typo10/public/typo3/sysext/seo/Classes/XmlSitemap/XmlSitemapRenderer.php(69): TYPO3\\CMS\\Seo\\XmlSitemap\\XmlSitemapRenderer->renderSitemap(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), 'news', 'googleNewsSitem...')\n#7 [internal function]: TYPO3\\CMS\\Seo\\XmlSitemap\\XmlSitemapRenderer->render('', Array)\n#8 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(5720): call_user_func_array(Array, Array)\n#9 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php(43): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Seo\\\\X...', Array, '')\n#10 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(829): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#11 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(743): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#12 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(688): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array, '10')\n#13 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Http/RequestHandler.php(232): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet(Array)\n#14 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Http/RequestHandler.php(198): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageBodyContent(Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController))\n#15 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Http/RequestHandler.php(134): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageContent(Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController), Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#16 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/OutputCompression.php(48): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#17 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Frontend\\Http\\RequestHandler))\n#18 /opt/homebrew/var/www/typo10/public/typo3conf/ext/solr/Classes/Middleware/PageIndexerFinisher.php(54): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#19 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): ApacheSolrForTypo3\\Solr\\Middleware\\PageIndexerFinisher->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#20 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/ContentLengthResponseHeader.php(47): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#21 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\ContentLengthResponseHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#22 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/ShortcutAndMountPointRedirect.php(69): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#23 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\ShortcutAndMountPointRedirect->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#24 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/PrepareTypoScriptFrontendRendering.php(86): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#25 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PrepareTypoScriptFrontendRendering->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#26 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/TypoScriptFrontendInitialization.php(108): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#27 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\TypoScriptFrontendInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#28 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/PageArgumentValidator.php(131): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#29 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PageArgumentValidator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#30 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/PreviewSimulator.php(66): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#31 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PreviewSimulator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#32 /opt/homebrew/var/www/typo10/public/typo3conf/ext/solr/Classes/Middleware/PageIndexerInitialization.php(78): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#33 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): ApacheSolrForTypo3\\Solr\\Middleware\\PageIndexerInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#34 /opt/homebrew/var/www/typo10/public/typo3conf/ext/solr/Classes/Middleware/FrontendUserAuthenticator.php(80): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#35 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): ApacheSolrForTypo3\\Solr\\Middleware\\FrontendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#36 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/PageResolver.php(106): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#37 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PageResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#38 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/StaticRouteResolver.php(80): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#39 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\StaticRouteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#40 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/SiteBaseRedirectResolver.php(94): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#41 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\SiteBaseRedirectResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#42 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/FrontendUserAuthenticator.php(77): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#43 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\FrontendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#44 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/BackendUserAuthenticator.php(66): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#45 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#46 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/MaintenanceMode.php(55): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#47 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\MaintenanceMode->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#48 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/EidHandler.php(64): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#49 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\EidHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#50 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/SiteResolver.php(65): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#51 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#52 /opt/homebrew/var/www/typo10/public/typo3conf/ext/solr/Classes/Middleware/SolrRoutingMiddleware.php(123): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#53 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): ApacheSolrForTypo3\\Solr\\Middleware\\SolrRoutingMiddleware->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#54 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#55 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#56 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Middleware/TimeTrackerInitialization.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#57 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\TimeTrackerInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#58 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(78): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#59 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(85): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#60 /opt/homebrew/var/www/typo10/public/typo3/sysext/frontend/Classes/Http/Application.php(69): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#61 /opt/homebrew/var/www/typo10/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(97): TYPO3\\CMS\\Frontend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#62 /opt/homebrew/var/www/typo10/public/index.php(25): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#63 /opt/homebrew/var/www/typo10/public/index.php(26): {closure}()\n#64 {main}"}

**Comment by georgringer** [comment]
thanks for reporting. I adopted the documentation which fixes the issue
