### ISSUE TITLE
previewHiddenRecords not working

### ISSUE THREAD

**Issue by chris246** [georgringer/news#177]
Hi,

I can't get the preview of hidden news entries working.
I created an extension template with the setup: `plugin.tx_news.settings.enablePreviewOfHiddenRecords =1`, but previewing a hidden news returns: Page Not Found Reason: No news entry found

**Comment by martinhummer** [comment]
did you set the tsConfig settings:
https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/BestPractice/PreviewOfRecord/Index.html

if yes, how does your preview url look like?

**Comment by chris246** [comment]
Never mind. There seems to be an issue on my development server.
It works on production...
