### ISSUE TITLE
From TYPO3 10.4.26 to 11.5.8 image upload has no action

### ISSUE THREAD

**Issue by revilosun** [georgringer/news#1770]
## Bug Report

**Current Behavior**
After update from Typo3 10.4.26 to 11.5.8
Create news article -> Content elements -> Images -> Select & upload files 
This has no action, no window will appear.

**Expected behavior/output**
The other button "Add images" the window will appear

**Environment**
- TYPO3 version(s): 11.5.8
- news version: 9.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**

**Comment by georgringer** [comment]
Thanks for creating the issue. I couldn't reproduce it on latest news + 11.5. If this is still an issue, please open an issue at https://forge.typo3.org/projects/typo3cms-core/issues because ext:news does use complete normal TCA and nothing special in that regard

**Comment by revilosun** [comment]
Ok, but I don't know if this a problem only with Typo3 11.5.8.
Select an upload an image with a normal article the window will apear, with a news article only in Typo3 10.4.26.
In Typo3 11.5.8 there is no action:
Demo:
https://www.dropbox.com/sh/ul0z0wtw9zj7nhp/AADwv4W_ReSM67cDOq9A5YbMa?dl=0

Best Greets

**Comment by georgringer** [comment]
do you get any JS errors in the console?

**Comment by revilosun** [comment]
Yes.
By clicking on the button there is no message, but on create or edit a news article:

(shorten version)
Uncaught TypeError: autocomplete is undefined

initialize 
  /typo3conf/ext/news/Resources/Public/JavaScript/TagSuggestWizard.js?bust=XXX:12
jQuery 2
initialize 
  /typo3conf/ext/news/Resources/Public/JavaScript/TagSuggestWizard.js?bust=XXX:9
reinitialize 
  /typo3conf/ext/news/Resources/Public/JavaScript/TagSuggestWizard.js?bust=XXX:75
jQuery 11
reinitialize 
  /typo3conf/ext/news/Resources/Public/JavaScript/TagSuggestWizard.js?bust=XXX:74
execCb 
  /typo3temp/assets/compressed/require-990dbb4aef8500f2fe5c4d5a8760575e.js:5
...............

**Comment by georgringer** [comment]
seems to be a core issue, created an issue for it https://forge.typo3.org/issues/97676
