### ISSUE TITLE
Error/warning in ClassCacheManager

### ISSUE THREAD

**Issue by klodeckl** [georgringer/news#1776]
I updated from TYPO3 9 to 10 and latest version of tx_news and I get the following error in the frontend when debug preset is active:

PHP Warning: array_splice() expects parameter 1 to be array, null given in /var/cg/vhosts/dev/typo3conf/ext/news/Classes/Utility/ClassCacheManager.php line 181

Downgrading to tx_news 9.2 did not resolve the issue.
If I switch debug mode off it works.

**Comment by ervaude** [comment]
The problem is that within the ClassCacheManager the property `$this->constructorLines['doc']` does not seem to be set. Therefore we applied the following composer patch as a workaround, because I was not sure how to solve this "correctly". But with this hint, maybe @georgringer does know what to do to fix this properly.


```
diff --git a/Classes/Utility/ClassCacheManager.php b/Classes/Utility/ClassCacheManager.php
index 9dc85002..a04a6cbf 100644
--- a/Classes/Utility/ClassCacheManager.php
+++ b/Classes/Utility/ClassCacheManager.php
@@ -172,6 +172,7 @@ class ClassCacheManager
             if ($baseClass) {
                 $this->constructorLines['doc'] = explode("\n", $constructorInfo['doc']);
             } else {
+                $this->constructorLines['doc'] = $this->constructorLines['doc'] ?? [];
                 array_splice(
                     $this->constructorLines['doc'],
                     -1,
```

**Comment by cehret** [comment]
I have the same issue after an update of typo3 10.4 / news 8.5.2 -> typo3 12.4 / news 11.3.0

**Comment by georgringer** [comment]
imo fixed,
