### ISSUE TITLE
Error displaying Detail news if Related News. Only in PHP v8

### ISSUE THREAD

**Issue by aksenovaa** [georgringer/news#1777]
## Bug Report

Error displaying news if related news are specified. Only on PHP 8.0! On php 7.4 everything works fine!

**Environment**
- TYPO3 version(s): 11.5.9
- news version: 9.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

In log:
Exception: PHP Runtime Deprecation Notice: usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/c/cq05424/aksenovaa.ru/public_html/typo3conf/ext/news/Classes/Domain/Model/News.php line 623, 
....

**Comment by georgringer** [comment]
Solved
