### ISSUE TITLE
Pagination setting maximumNumberOfLinks not working

### ISSUE THREAD

**Issue by 0bitus** [georgringer/news#1778]
The pagination setting plugin.tx_news.settings.list.paginate.maximumNumberOfLinks do not affect to the number of pages and all pages are shown.

**Environment**
- TYPO3 version: 10.4.27
- news version: 9.4.0
- Composer Mode: no

**Comment by 0bitus** [comment]
Thanks for the hint, now it works fine.
Is there a suggestion in the official documentation? I didn't find anything.

**Comment by luisbecker-gh** [comment]
I couldn't find anything in the documentation too. The extension is suggested in the composer.json and ext_emconf.php.
Maybe it should mentioned in the documentation.

**Comment by georgringer** [comment]
@luisbecker-gh thanks for the idea. where would you expect such hint? in typoscript above the setting? in docs at the setting?

**Comment by luisbecker-gh** [comment]
@georgringer I would expect it in the docs and already made an adjustment yesterday, but had no time to create a pull request.
