### ISSUE TITLE
sys_category shared usage

### ISSUE THREAD

**Issue by SicorDev** [georgringer/news#178]
Dear Mr. Ringer,

in our extension we extended sys_category with the field tx_extbase_type, so in our datasets we can filter for our types and only show the categories desired for our modules and plugins.

Unfortunately the news extension doesn't seem to implement a similar mechanism, so it generally shows *all* categories, including the ones for our extension - which make no sense for news in our usecase.

Not sure what the best or the right solution for this would be, but I assume it'll get worse and worse the more extensions will use sys_category - especially when each assumes it's using sys_category exclusively?

Could you image using and filling a 'tx_extbase type' in the future as well?

Greetings,
Manuel Rotschkar

**Comment by martinhummer** [comment]
i'm not entirely sure if you refer to backend or frontend but for the backend this might help:
https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Configuration/ExtensionManager/Index.html#categoryrestriction

**Comment by SicorDev** [comment]
I guess I could kinda misuse this feature for the desired effect as well, but right now we solved that more globally by this hack:

`$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['config']['foreign_table_where'] = " AND tx_extbase_type = ''".$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['config']['foreign_table_where'];
`
I was just wondering if there was no official way for dealing with this situation, as I'd theoretically need such a hack for every extension using sys_category. Assuming for example I'd next add tt_address which now also uses sys_category, I'd already need the next hack for that, no? :-)

**Comment by georgringer** [comment]
In general sys_categories are meant to be used by every extension (if it makes sense) so that not every extensions needs to setup those itself. 
If you need records just for your extension, work with the `foreign_table_where` like you did or use TsConfig as stated in the manual
```
TCEFORM.tx_news_domain_model_news.categories.PAGE_TSCONFIG_IDLIST = 12,34
```

so that editors can change which records are allowed to be seen.

I won't certainly add the restriction to a field you are using
