### ISSUE TITLE
News Extension Information Leakage

### ISSUE THREAD

**Issue by kbenyedder** [georgringer/news#1793]
Please check when I call article/ 
I get a debug output  see screensot : 

![image](https://user-images.githubusercontent.com/66422450/171849204-426bd187-f179-4d6c-8fb8-cfca775ba72e.png)

Thanks for your help!

**Comment by kbenyedder** [comment]
Sorry real-url Config issues

**Comment by georgringer** [comment]
and wrong extension I guess
