### ISSUE TITLE
clear cache based on categories

### ISSUE THREAD

**Issue by jonakieling** [georgringer/news#1815]
## Feature Request

Hi there,

this is both a feature request and a question for anyone with a similar setup, how this could be solved. Maybe even with existing config.

**Pages with a list plugin and a large pool of potential sources for records are often uncached**
The following scenario leads to many uncache page renders:

- have a news list plugin on a page (in our case the home page)
- set the entry point to top most news folder and include all subfolders (in our case 6 branches and 2+ levels)
- ~~this requires to clear the cache~~ this triggers the cache clear for the page whenever any news is edited or created

In our case the news folders are structured by site which is the prefered and most usefull except when dealing with the home page.

**Setting and clearing cache tags based on categories**
The plugin could set cache tags based on the configured categories and sub-categories if enabled.
To use this effectivly, the page based cache clear should be disabled for this use case.

**Teachability, Documentation, Adoption, Migration Strategy**
As this changes the behaviour of news plugins, a setting to control this behaviour would be nice.

We currently add the clearCachePostProc and override the plugin for a single content element, that is then used as described above. We do not support the option "include subcategories". Maybe this would be a feature to include in the extension itself.

Kind regards,
Jona

**Comment by georgringer** [comment]
Thanks for creating the issue. Tbh I don't want to add more variants in the extension itself as it is really depending on the use case, especially for larger sites. If an event is missing or so this would be fine.
Feel free to publish your extension which might help others
