### ISSUE TITLE
Weird identifier for hreflang event in Services.yaml

### ISSUE THREAD

**Issue by akiessling** [georgringer/news#1822]
Looks like the identifier was copied from the documentation https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Events/Events/Frontend/ModifyHrefLangTagsEvent.html#example

While technically not required, my-ext should be switched with news :)

https://github.com/georgringer/news/blob/33e97073e79dadda8bb439db606c59653d0883b4/Configuration/Services.yaml#L32

**Comment by georgringer** [comment]
thanks for the issue, absolutly valid

**Comment by akiessling** [comment]
Thanks for taking care so fast! :)
