### ISSUE TITLE
PHP8.1 ICS-Generation failed

### ISSUE THREAD

**Issue by h3nn3s** [georgringer/news#1823]
## Bug Report

**Current Behavior**
When clicking a link to download a generated ICS the following exception occurs:
```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "domain" in /var/www/html/html/typo3conf/ext/news/Classes/Controller/NewsController.php line 670
```

**Expected behavior/output**
ICS file should be generated :-)

**Environment**
- TYPO3 version(s): 9.4
- news version: 9.4
- php version: 8.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Adding something like 
`isset($typoScriptArray[$key]) ?: $typoScriptArray[$key] = '';`
in line 666 :imp: bevor appling stdWrap could solve the issue.

**Comment by h3nn3s** [comment]
If this is the right solution, I would do for sure :-)

**Comment by georgringer** [comment]
resolved, closing issue
