### ISSUE TITLE
Error Message without news argument in route

### ISSUE THREAD

**Issue by devtroll** [georgringer/news#1835]
`Call to a member function getRouteArguments() on null`
File: `/typo3conf/ext/news/Classes/Seo/NewsAvailability.php line 133`

TYPO3 v11 with Composer
PHP 8.1
News 9.4.0

**Comment by georgringer** [comment]
Wanna do a PR?

**Comment by devtroll** [comment]
The PR is created ... :)

**Comment by georgringer** [comment]
thanks a lot!
