### ISSUE TITLE
[Bug] Google News Sitemap not working

### ISSUE THREAD

**Issue by bh-teufels** [georgringer/news#1839]
## Bug Report

**Current Behavior**
Getting following error on google news sitemap:
```
This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.
```

**Expected behavior/output**
Getting sitemap of the news with the Google News Template

**Environment**
- TYPO3 version(s): 11.5.14
- PHP 8.1.2
- news version: 9.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Configuration**
```
plugin.tx_seo {
    config {
        xmlSitemap {
            sitemaps {
                news {
                    provider = GeorgRinger\News\Seo\NewsXmlSitemapDataProvider
                    config {
                        # exclude internal & external news
                        excludedTypes = 1,2
                        additionalWhere =

                        sortField = datetime
                        lastModifiedField = tstamp
                        #Speicherort der Beiträge
                        pid = 123
                        recursive = 2
                        url {
                            #PageID der Detailseite
                            pageId = 124

                            #To enable the category detail page handling, set useCategorySinglePid = 1
                            useCategorySinglePid = 0

                            #add date to URL
                            #hrDate = 0
                            #hrDate {
                            #    day = j
                            #    month = n
                            #    year = Y
                            #}

                            fieldToParameterMap {
                                uid = tx_news_pi1[news]
                            }

                            additionalGetParameters {
                                tx_news_pi1.controller = News
                                tx_news_pi1.action = detail
                            }
                            useCacheHash = 1
                        }
                    }
                }
            }
        }
        googleNewsSitemap {
            sitemaps {
                news < plugin.tx_seo.config.xmlSitemap.sitemaps.news
                news {
                    config {
                        template = EXT:news/Resources/Private/Templates/News/GoogleNews.xml
                        googleNews = 1
                    }
                }
            }
        }
    }
}

seo_sitemap_news < seo_sitemap
seo_sitemap_news {
    typeNum = 1533906436
    10.sitemapType = googleNewsSitemap
}
```

**Comment by georgringer** [comment]
take a look at https://github.com/peterkraume/news/commit/4561cbd58ed4a04e5684caf89461bf5de5d2674a 
IMO it should be template=GoogleNews. can you test that with latest news main version?

**Comment by bh-teufels** [comment]
i tried with both
template = EXT:news/Resources/Private/Templates/News/GoogleNews.xml
template = GoogleNews

but has made no difference

with news 9.4.0 i am already on the latest version or should i use directly the main branch?

**Comment by georgringer** [comment]
please test main branch for that feature. btw the google news does have a restriction of 2 days. so the news must be max 2 days old!

**Comment by Zillion01** [comment]
Hi, there is 2 things going on here. The sortfield should be specified as tstamp and the template path for the SEO extension should be added. Then it works.

Georg maybe you can add this to the documentation.

Example typoscript : 

`plugin.tx_seo.config {
    xmlSitemap {
        sitemaps {
            news {
                provider = GeorgRinger\News\Seo\NewsXmlSitemapDataProvider
                config {
                    table = tx_news_domain_model_news
                    additionalWhere =
                    sortField = sorting
                    lastModifiedField = tstamp
                    changeFreqField = sitemap_changefreq
                    priorityField = sitemap_priority
                    pid = 107
                    recursive = 2
                    url {
                        pageId = 46
                        fieldToParameterMap {
                            uid = tx_news_pi1[news]
                        }

                        additionalGetParameters {
                            tx_news_pi1.controller = News
                            tx_news_pi1.action = detail
                        }

                        useCacheHash = 1
                    }
                }
            }

            googleNewsSitemap < plugin.tx_seo.config.xmlSitemap.sitemaps.news
            googleNewsSitemap {
                config {
                    sortField = tstamp
                    template = GoogleNews
                    googleNews = 1
                }
            }

            events < plugin.tx_seo.config.xmlSitemap.sitemaps.news
            events {
                config {
                    pid = 108
                    url {
                        pageId = 47
                    }
                }
            }
        }
    }
}

google_news_sitemap < seo_sitemap
google_news_sitemap {
    typeNum = 1533906436
    10.sitemapType = googleNewsSitemap
}
`

In constants:

`plugin.tx_seo {
    view {
        templateRootPath = EXT:news/Resources/Private/Templates/News/
    }
}`

In config.yaml :  

`routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    map:
      sitemap.xml: 1533906435
      google_news_sitemap.xml: 1533906436`

**Comment by Zillion01** [comment]
Instead of mentioning the tstamp as sortfield, another solution (maybe better) is to change news/Classes/Seo/NewsXmlSitemapDataProvider.php line 87

```
        if ($forGoogleNews) {
            $constraints[] = $queryBuilder->expr()->gt($sortField, (new \DateTime('-2 days'))->getTimestamp());
        }
```

in

```
        if ($forGoogleNews) {
            $constraints[] = $queryBuilder->expr()->gt('tstamp', (new \DateTime('-2 days'))->getTimestamp());
        }
```

**Comment by Zillion01** [comment]
The Google Sitemap stoppped completely working, just 0 found. TYPO3 11.5.27 and News 9 and 10.

**Comment by georgringer** [comment]
it worked last time I checked, therefore closing it for now
