### ISSUE TITLE
JS alert with exception when creating a new Tag on unsaved news

### ISSUE THREAD

**Issue by mtness** [georgringer/news#184]
When one creates a new news entry and creates a new Tag, a js alert box pops up, with the source of a TYPO3 Exception: 

> Uncaught TYPO3 Exception
> No news id given!
> 
> RuntimeException thrown in file
> /html/typo3/typo3conf/ext/news/Classes/Backend/TagEndPoint.php in line 70.
> 

however, the tag is created - on can select again as existing tag when entering it again.

I tested this behaviour in news v3, it worked there as expected.

[tagendpoint-exception.txt](https://github.com/georgringer/news/files/642437/tagendpoint-exception.txt)

![snap62](https://cloud.githubusercontent.com/assets/15540/21053058/077260b6-be28-11e6-8cb3-45e3aacff170.png)

**Comment by georgringer** [comment]
which news version and which core version?

**Comment by mtness** [comment]
News v5.3.1 and TYPO3 v7.6.14

**Comment by georgringer** [comment]
wanna test last combinations? didnt have any troubles

**Comment by mtness** [comment]
Oh, just saw the edit. Got to pull and test now - will update issue then!

**Comment by georgringer** [comment]
solved now
