### ISSUE TITLE
Preview link with target URL

### ISSUE THREAD

**Issue by plojewski** [georgringer/news#1840]
Hi there, I've got configuration like that:

<pre>
TCEMAIN.preview {
    tx_news_domain_model_news {
        previewPageId = 5
        useDefaultLanguageRecord = 0
        fieldToParameterMap {
            uid = tx_news_pi1[news]
        }
        additionalGetParameters {
            tx_news_pi1.controller = News
            tx_news_pi1.action = detail
        }
    }
}

plugin.tx_news {
  settings {
    previewHiddenRecords = 2
    enablePreviewOfHiddenRecords = 1
  }
}
</pre>

so preview link looks like:
http://domian/article/my-first-news-1/

It it possible to preview disabled item with target URL? Now I've got an 404 error.
It works only with:
<pre>
fieldToParameterMap {
    uid = tx_news_pi1[news_preview]
}
</pre>

Thanks.

**Comment by georgringer** [comment]
that is currently not possible as routing doesn't allow that

**Comment by plojewski** [comment]
@georgringer Thank you.
