### ISSUE TITLE
News on TYPO3 v11.5: List Module add new record corrupted - only news system entries left

### ISSUE THREAD

**Issue by ByteBandito** [georgringer/news#1843]
## Bug Report

**Current Behavior**
After enabling the extension news system the context-menu of typo3 under the List Module / Add Record breaks. Only the "new" entries of the news system are shown, not p. ex. Add new Page inside... only Internal Note, News System > News and New Tag are left.

I reproduced that problem on 2 Typo3-websites. And could not reproduce it on a v10.5 system.. so it seems to be just an issue for 11.5

**Expected behavior/output**
The new entries for news system should be shown additional to the normal add-record-items... not instead of them.

**Environment**
- TYPO3 version(s): 11.5.14
- news version: 9.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu

**Possible Solution**
None known yet.

**Comment by georgringer** [comment]
this is only if the tsconfig entry "EXT:news :: Restrict pages to news records" in the page record is selected. not a bug but a feature
