### ISSUE TITLE
Calling newsItem.starttime when no starttime isset throws 503 Error

### ISSUE THREAD

**Issue by macro64** [georgringer/news#1848]
## Bug Report

**Current Behavior**

The statement:
<f:debug>{newsItem.starttime}</f:debug>
called in mysitepackage/Resources/Private/Extensions/News/Partials/List/Item.html
produces an Error 503:
"GeorgRinger\News\Domain\Model\News::getStarttime(): Return value must be of type DateTime, null returned"

**Expected behavior/output**

The function getStarttime() should return false even when starttime is NULL 

**Environment**
- TYPO3 version(s): 11.5.15
- news version: 9.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: macOS 12.4

**Possible Solution**
change Z1392 in Classes/Domain/Model/News.php from
"public function getStarttime(): DateTime"
to
"public function getStarttime(): ?DateTime"

**Additional context**
I have no experience in typo development. It maybe a bug or it may be me misunderstanding basic typo templating principles.

**Comment by georgringer** [comment]
fixed already with https://github.com/georgringer/news/commit/b7a38244cf8c9f4c6bca81948c5debc26fb115c2
