### ISSUE TITLE
Call to undefined method MysqliStatement::fetchOne()

### ISSUE THREAD

**Issue by Teisi** [georgringer/news#1852]
## Bug Report

Update EXT:news from 9.4.0 to 10.0 via ExtensionManager (TYPO3 Backend).
Run "Rebuild PHP Autoload Information" and "Flush TYPO3 and PHP Cache" from Install-Tool -> Maintenance.
Then go to Install-Tool -> Upgrade -> Upgrade Wizard click on button "Run Upgrade Wizard" ---> Error message: Ajax error:

Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchOne()
/typo3conf/ext/news/Classes/Updates/RelatedLinkIntegerDefault.php line 76

**Environment**
- TYPO3 version(s): 10.4.32
- news version: 10.0
- PHP: 7.4.30
- MySQL: 5.7.38
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux CentOS

**Comment by georgringer** [comment]
@Teisi can you test the change? would be awesome. thanks

**Comment by Teisi** [comment]
Sry for the late response but yes it seems to work fine :) Thank you!
