### ISSUE TITLE
Adjustment of Pagination - after dispatching "NewsListActionEvent"

### ISSUE THREAD

**Issue by rasgor** [georgringer/news#1855]
By using the NewsListActionEvent to post-process the newsRecords the pagination doesn't behave correctly.

Is it possible to move the pagination block from NewsController.php line 230 behind the event dispatching - NewsListActionEvent line 274?

**Comment by georgringer** [comment]
thanks for creating the issue. wanna test https://github.com/georgringer/news/pull/1856?

**Comment by rasgor** [comment]
Thank you for your fast response and adoption. After testing there is one last issue. The `$event->getAssignedValues()['news']` must be the param (basis) for the creation of the paginator ` $paginator = GeneralUtility::makeInstance(QueryResultPaginator::class, $event->getAssignedValues()['news'], $currentPage, $itemsPerPage, (int)($this->settings['limit'] ?? 0), (int)($this->settings['offset'] ?? 0));`

**Comment by georgringer** [comment]
wanna do a PR?

**Comment by rasgor** [comment]
Yes, later today.

**Comment by georgringer** [comment]
I guess we can close it now
