### ISSUE TITLE
TagSuggestWizard BE js error

### ISSUE THREAD

**Issue by abvdveen** [georgringer/news#1857]
In Typo3 11 / news 9.4.0 opening a news record gives 'Uncaught TypeError: Cannot read properties of undefined (reading 'options')' in browser console.

This section of the code triggers it:
`var autocomplete = $(this).autocomplete();
var onSelectCallback = autocomplete.options.onSelect;
`
so autocomplete is not available.

**Comment by georgringer** [comment]
Please update to v10 and https://packagist.org/packages/georgringer/news-tagsuggest, fixed it there
