### ISSUE TITLE
Missing Parameters in Pagination

### ISSUE THREAD

**Issue by AlexVossBu** [georgringer/news#1859]
**Current Behavior**
The current `GeorgRinger\News\Pagination\QueryResultPaginator` does not contain the keys `hasLessPages` and `hasMorePages`, but were checked in the template `news/Resources/Private/Partials/List/Pagination.html`. Its not a Problem if there are only a few pages of news, but with a Newscount of 500+ and items per page of 10 the pagination displays 50+ pagelinks.

**Expected behavior/output**
The pagination behaviour of Version 8.X where the pagination shows `...` if there are more or less pages

**Environment**
- 11.5.16
- 9.4.0
- Yes
- Debian

**Possible Solution**
Provide the data like here https://github.com/georgringer/news/blob/9d9e944a47f727e43e9169bbd2fe59692105416a/Classes/ViewHelpers/Widget/Controller/PaginateController.php#L196

**Comment by georgringer** [comment]
please use https://github.com/georgringer/numbered_pagination
