### ISSUE TITLE
Error to show page with list news in workspace

### ISSUE THREAD

**Issue by robertotorresani** [georgringer/news#1860]
When viewing a page in a draft workspace with a news list, I get the following error:

PHP Warning: Trying to access array offset on value of type null in [...]/typo3conf/ext/news/Classes/ViewHelpers/LinkViewHelper.php line 257

I changed the line as follow:
            if ($record && $record['uid']) {

https://github.com/georgringer/news/blob/61e69e15a06983c3fc6b9a073f5740defe45fdb9/Classes/ViewHelpers/LinkViewHelper.php#L257

TYPO3 version 11.5.16
news version 10.0.1

**Comment by georgringer** [comment]
thanks, wanna test https://github.com/georgringer/news/pull/1861?
