### ISSUE TITLE
setStarttime() in migrator has to be DateTime

### ISSUE THREAD

**Issue by froemken** [georgringer/news#1865]
## Bug Report

**Current Behavior**
INT value of column starttime will be used as argument for setStarttime() in NewsImportService which is of type \DateTime() now.

**Expected behavior/output**
Two solutions:
- NewsImportService has to convert INT value to \DateTime() object and assign it as argument to setStarttime()
- NewsImportService has to check, if starttime is of type \DateTime() before using it as arguemnt for setStarttime()

**Environment**
- TYPO3 version(s): [e.g. 11.5.16]
- news version: [e.g. 10.0.1]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

**Comment by georgringer** [comment]
@froemken I guess we can close that, correct?

**Comment by froemken** [comment]
Yes. Don‘t know why this issue was not closed automatically. I have added the Ticket ID to PR title:

https://github.com/georgringer/news/pull/1866
