### ISSUE TITLE
Exception Call to undefined method TYPO3\CMS\Fluid\Core\Rendering\RenderingContext::getUriBuilder() 

### ISSUE THREAD

**Issue by georgringer** [georgringer/news#1869]
@ `typo3` 10.4.32 + `georgringer/news` 10.0.1

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Fluid\Core\Rendering\RenderingContext::getUriBuilder() | Error thrown in file source/typo3conf/ext/news/Classes/ViewHelpers/SearchFormViewHelper.php in line 151`

_Originally posted by @xerc in https://github.com/georgringer/news/issues/1805#issuecomment-1271736917_

**Comment by xerc** [comment]
THX

**Comment by georgringer** [comment]
@xerc thanks to you for reporting it (next time maybe a new issue), fixing it was easy.
