### ISSUE TITLE
PHP Runtime Deprecation Notice: usort

### ISSUE THREAD

**Issue by ecosmox36** [georgringer/news#1873]
## Bug Report

**Current Behavior**
If using more than one related news, the function `getAllRelatedSorted()` is executed
(/Classes/Domain/Model/News.php: 606)

But results in: 

`PHP Runtime Deprecation Notice: usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /var/www/html/public/typo3conf/ext/news/Classes/Domain/Model/News.php line 623`

**Expected behavior/output**
Showing the related news without Problems 

**Environment**
- TYPO3 version(s):11.5.16
- news version: 9.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): Yes
- OS: Linux but the OS has no impact here
- PHP: 8.0.21

**Possible Solution**

```
usort($all, function ($a, $b) {
                return $a->getDatetime() < $b->getDatetime();
            });
```
See https://3v4l.org/CMaOpI

should be

```
usort($all, function ($a, $b) {
                return $a->getDatetime() <=> $b->getDatetime();
            });
```
See https://3v4l.org/NPcWn

**Comment by georgringer** [comment]
fixed already with https://github.com/georgringer/news/pull/1779

please just update to latest version 10
