### ISSUE TITLE
TypeError when using SlugPrefix option to define a specific page for the backend preview

### ISSUE THREAD

**Issue by DkdTerbium** [georgringer/news#1886]
## Bug Report

**Current Behavior**
When a specific page-ID for the generation of the backend preview slug is set (slugPrefix [manual ref](https://docs.typo3.org/p/georgringer/news/main/en-us/Reference/TsConfig/General.html#example-show-url-to-a-detail-page)) the opening of a news record results in the following error Message:

> (1/1) TypeError
> 
> Argument 4 passed to GeorgRinger\News\Backend\FormEngine\SlugPrefix::generateUrl() must be of the type int, array given, called in <system_path>/typo3conf/ext/news/Classes/Backend/FormEngine/SlugPrefix.php on line 32

```
# Example PageTS conf
tx_news.slugPrefix = 123
```

**Expected behavior/output**
A news record can be opened without issues or error messages.
The shown SlugPrefix is correctly created based on the configuration from `tx_news.slugPrefix`.

**Environment**
- TYPO3 version(s): 10.4.32
- news version: 10.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): Yes
- OS: Ubuntu 18.04.5 LTS
- PHP: 7.4.28

**Possible Solution**
I wrote a small patch adding a check for `sys_language_uid` in EXT:news/Classes/Backend/FormEngine/SlugPrefix.php:20
```php
public function getPrefix(array $parameters): string
    {
        $row = $parameters['row'];
        $sysLanguageUid = is_array($row['sys_language_uid']) ? (int)$row['sys_language_uid'][0] : $row['sys_language_uid'];
        $pagesTsConfig = BackendUtility::getPagesTSconfig($row['pid']);
        $configuration = $pagesTsConfig['tx_news.']['slugPrefix'] ?? '';
        if ($configuration === 'none' || $configuration === '') {
            return '';
        }
        if ($configuration === 'default') {
            return $this->getPrefixForSite($parameters['site'], $sysLanguageUid);
        }
        if (MathUtility::canBeInterpretedAsInteger($configuration)) {
            $prefix = $this->generateUrl($parameters['site'], (int)$configuration, $row['uid'], $sysLanguageUid);
            return $this->stripNewsSegment($prefix, $parameters['row']['path_segment']);
        }

        return '';
    }
```
This seems to have fixed the issue for now.

**Additional context**
Depending on the TYPO3 setup and the current context `$row['sys_language_uid']` either contains an array with a single item containing the desired `sys_language_uid` or it may contain only an integer representing the desired `sys_language_uid`.
Most of the time its an array. Thats why `$row['sys_language_uid']` needs to be verified before accessing it.

<details>
  <summary>Debug of $row</summary>

![Bildschirmfoto 2022-10-17 um 22 34 56](https://user-images.githubusercontent.com/42413312/196460007-d6102854-cbb1-4362-976c-3c6e1003ea18.png)

</details>

**Comment by georgringer** [comment]
wanna do a PR with your patch? thanks!

**Comment by DkdTerbium** [comment]
Hey,
I create a PR with the the aforementioned patch above.
https://github.com/georgringer/news/pull/1890

**Comment by georgringer** [comment]
merged, thanks!
