### ISSUE TITLE
maxWidth does nothing if image contains special characters

### ISSUE THREAD

**Issue by joakim1** [georgringer/news#189]
If the image filename contains Norwegian letters æøå or other special but legal characters, then maxWidth does not work.

    <f:image src="{mediaElement.uid}" treatIdAsReference="1" maxWidth="150" />

Typo3 6.2.29 with news 3.2.6

**Comment by georgringer** [comment]
This has nothing to do with EXT:news but is either a core issue or a misconfiguration, see e.g. https://forge.typo3.org/issues/48583
