### ISSUE TITLE
No TemplateLayouts in Templateselector in news 5.3.1

### ISSUE THREAD

**Issue by Schwuuuuup** [georgringer/news#193]
Hi,

I'm aware of Issue TYPO3 Forge Issue 78019, but unfortunately I need compatibility6 because of simulatestatic (Having 50000+ Pages and 3000+ Users doesn't allow me to change the URL scheme out of nowhere).

Would it be possible to include compatibility to compatibility6?

Also, I'm not sure if t's only this: I patched the version like This:

in function user_templateLayout(array &$config) I changed

this:

` $pageId = $this->getPageId($config['flexParentDatabaseRow']['pid']);`

to:
` $pageId = $this->getPageId($config['row']['uid']);`

But this returns the ID of the tt_content record. 
I think there is a bug in getPageId.
I don't really understand the comment

`* Get page id, if negative, then it is a "after record"`
The condition does not check for "negaive" but for "greater then zero", so when I swap the > for an <, it works:
```
 protected function getPageId($pid)
    {
        $pid = (int)$pid;

        if ($pid < 0) {
            return $pid;
        } else {
            $row = BackendUtilityCore::getRecord('tt_content', abs($pid), 'uid,pid');
            return $row['pid'];
        }
    }
```

**Comment by georgringer** [comment]
do you wanna sponsor the support of EXT:compatibility6?

**Comment by Schwuuuuup** [comment]
Hello,

for further discussions, how can I contact you about costs etc.?
you can reach me via Mail: tmoll@uni-koeln.de
And I think we both speak German, do we? ;-)

Am 27.12.2016, 19:28 Uhr, schrieb Georg Ringer <notifications@github.com>:

>
> do you wanna sponsor the support of EXT:compatibility6?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Erstellt mit Operas E-Mail-Modul: http://www.opera.com/mail/
