### ISSUE TITLE
Provide filter by type

### ISSUE THREAD

**Issue by georgringer** [georgringer/news#194]
A filter by the `type` would be nice in the demand Object and the news repository. Especially if users add different types, this could be really nice

- [x] Demand object
- [x] News repository
- [ ] Flexforms?

**Comment by lorenzulrich** [comment]
Is it correct that this is "only" low-level support, but there is no configuration (TypoScript/FlexForm) to only display news of a certain type?

**Comment by georgringer** [comment]
correct
