### ISSUE TITLE
Wrong type casting for import_id and import_source

### ISSUE THREAD

**Issue by peuter** [georgringer/news#1949]
## Bug Report

**Current Behavior**
Check for existing news does not work for imported news anymore, so for every import you get duplicated news.

**Expected behavior/output**
The check that a news item has already been imported should work and the import service should update the existing entry instead of creating a new one

**Environment**
- TYPO3 version(s): 10.4.32
- news version: 10.0.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Possible Solution**
In 10.0.2 there is a wrong type cast for those values:
```
$news->setImportId((int)($importItem['import_id'] ?? ''));
$news->setImportSource((int)($importItem['import_source'] ?? ''));
```
should be:
```
$news->setImportId((string)($importItem['import_id'] ?? ''));
$news->setImportSource((string)($importItem['import_source'] ?? ''));
```

It seems to be correct in the main branch, but not in the release.

**Comment by georgringer** [comment]
in https://github.com/georgringer/news/blob/f0fa521219b28b7a42886fe125921a0b281f6ed1/Classes/Domain/Service/NewsImportService.php#L160 this is still wrong, does it? wanna do a PR or should I?

**Comment by peuter** [comment]
This is weird, I thought I saw it beeing correct in the main branch and no PR is needed. I don't know what I have seen, but sure I will create a PR to fix it.

**Comment by georgringer** [comment]
there are 2 places, categoryservice does it correct
