### ISSUE TITLE
[BUG] Order news list by `sorting` is missing

### ISSUE THREAD

**Issue by h3nn3s** [georgringer/news#1964]
## Bug Report
Due to the removal of switchingControllerActions it is currently not possible to order the list view by sorting field.

**Current Behavior**
The select item is missing.

**Expected behavior/output**
It should be possible to select `sorting` out of dropdown list.

**Environment**
- TYPO3 version(s): 12.x
- news version: dev-branch 11-12
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Do not check for a selected switchableControllerAction selected in Flexforms-Field. Instead we could use selected CType to differentiate between the ordering items.

**Comment by georgringer** [comment]
imo solved closing
