### ISSUE TITLE
[FEATURE] Add top/bottom move buttons in plugin's flexform for better UX

### ISSUE THREAD

**Issue by Idleworks** [georgringer/news#1969]
## Feature Request

In news plugin settings the flexform field 'List of articles' (settings.selectedList) in displayMode 'List of selected items' is missing the to-top and to-bottom buttons for quickly sort articles in list.
Especally in huge lists this is big pain for editors to move an article to top or bottom.

![image](https://user-images.githubusercontent.com/6685173/203820767-2eafd888-a374-44c5-a26a-f244bb8540a3.png)

To-top and to-bottom buttons should be added for a better user experience in backend. 
This is a no-brainer.

**Comment by Idleworks** [comment]
See pull request #1970

**Comment by georgringer** [comment]
thanks for the PR - I was not aware of this check which doesn't make much sense in the core.
I too the liberty to change it in the core with https://review.typo3.org/c/Packages/TYPO3.CMS/+/76827 which should be backported to 11.5 as well.

thanks for the great tip - learned something ;)
