### ISSUE TITLE
The same slug if news with the same title if a news applies to all languages

### ISSUE THREAD

**Issue by stephangrass** [georgringer/news#1974]
- TYPO3 version(s): [10.4.32]
- news version: [10.0.3]

If there are several news items with the same title, a news item that is set to the language "All" is not taken into account when generating the slug.

For example:

The news only for German with the title "Vertriebsmitarbeiter (m/w/d) im Außendienst" receives the slug "vertriebsmitarbeiter-m-w-d-im-aussendienst".

A news with the same title and language "All" gets the same slug.

This can be quickly remedied by giving the news a different title, which also makes sense, but the customer...

**Comment by georgringer** [comment]
this was a core issue and solved in latest versions

**Comment by kraemer-igroup** [comment]
I just had the same problem.
@georgringer, do you know the exact versions in which it was fixed?

**Comment by georgringer** [comment]
I guess with https://forge.typo3.org/issues/99529
