### ISSUE TITLE
Duplicate sub categories for backend users

### ISSUE THREAD

**Issue by chris246** [georgringer/news#198]
Hi,
assuming, I have the following category tree:
```
Category(root node)
- a
- b
  - 1
  - 2
  - 3
```

When checking all categories on the backend page for user group permissions (third tab "Mounts and Workspaces" aka "Freigaben und Arbeitsumgebungen"), backend users see the following available categories when editing news records:
```
Category(root node)
- a
- b
  - 1
  - 2
  - 3
- 1
- 2
- 3
```

This bug doesn't occur, when I grant the permissions for categories a and b only, although users are still allowed to assign groups 1, 2, and 3, too (which is intended in my case).

TYPO3: v7.6.14
tx_news: v5.3.1

Thanks
Christoph

**Comment by georgringer** [comment]
This is the same behaviour as you have it in normal TYPO3 as well. Imagine having every page as `DB mount`, then you would have that in the page tree as well. Ask Lorenz Ulrich who created an extension to circumvent that behaviour
