### ISSUE TITLE
useXclassedVersion preview of tt_content elements not working

### ISSUE THREAD

**Issue by pulponair** [georgringer/news#1981]
## Bug Report

**Current Behavior**
Setting useXclassedVersion to true does nothing

**Expected behavior/output**
Setting useXclassedVersion to true should make use of InlineRecordContainerForNews tt_content preview.

**Environment**
- TYPO3 version: 11.5
- news version: 9 to 10
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Any

**Possible Solution**
https://github.com/georgringer/news/commit/59d20395565627f9e79f07b67173826450118913 renames InlineRecordContainerForNews::renderForeignRecordHeader to _renderForeignRecordHeader 

The commit messages states "[TASK] Improve code quality with rector" so i am not sure if this has been done on purpose or by accident.

Renaming the method back and adjusting its signature to match the one of the parent class fixes the issue.

**Comment by georgringer** [comment]
I don't plan to bring this pack, in favor of https://docs.typo3.org/p/georgringer/news/main/en-us/Addons/NewsContentElements/Index.html

xclassing there did add some new issues

**Comment by pulponair** [comment]
@georgringer Ah ok, i was not aware of that. Thanks for the information :)
