### ISSUE TITLE
Update to Typo3 11.0.0. Invalid value "LANGUAGE" 

### ISSUE THREAD

**Issue by ness2828** [georgringer/news#1989]
Hi,

I was updating Typo3 from 10.4.34 to 11.0.0 and unfortunately the pages. that include the news plugin (version 9.4.0) show the frontend error "(1/1) #1381512761 TYPO3\CMS\Core\Type\Exception\InvalidEnumerationValueException
Invalid value "LANGUAGE" for enumeration "TYPO3\CMS\Core\DataHandling\TableColumnType" 

When I check a news article, the tab "language" reveals the error "Unknown type: language, render type: language".

I'm using two languages - German and English.

I'd love to use the news plugin and I can't seem to solve this. Would love to get help, please.

Kind regards!

**Comment by ness2828** [comment]
Thank yout for your quick reply. Yes, it's version 11.0.0. Wanted to update my way up to 11.5.22.

**Comment by georgringer** [comment]
don't use any version lower than 11.5, does are kind of preview snapshopts and only useful if the lts 11.5 is not yet published
