### ISSUE TITLE
Multi Category Selection: Translation

### ISSUE THREAD

**Issue by lauralang** [georgringer/news#1991]
## Bug Report

**Current Behavior**
Suggestion for updating docs. I'm using a variation of the example template for multi category selection.
https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/Templates/MultiCategorySelection/Index.html

I ran into an problem when I translated the news and filter. When I select categories the generated link uses the uid of the translated Category. With that, no results are found as it seems that the overwrite demand expects the original uid of the category. If I modify the Viewhelper to use `category.item.l10nParent` instead of `category.item.uid` it works for my translated page. Of course that's not working for my original language, so I have to work with an if-condition for these two different cases. Do you know this problem or do you have a better solution for it? Maybe modifying the Viewhelper php would be an option too?

**Expected behavior/output**
When I use the multi category selection template example it should work for translated pages/news/categories too. At least a hint on the example page would be great.

**Environment**
- TYPO3 version(s): 11.5.22
- news version: 9.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX 12.6

**Current Fix**
```
<f:variable name="categoryUid">{category.item.uid}</f:variable>
<f:if condition="{category.item.sysLanguageUid} == 1"><f:variable name="categoryUid"{category.item.l10nParent}</f:variable></f:if>
```
Adding the above to the categories foreach loop and replacing all following occurences of `{category.item.uid}` with `{categoryUid}`

Thank your for the great extension!

**Comment by georgringer** [comment]
hey. wanna do a PR?

**Comment by lauralang** [comment]
Hey, sure. I'll do it this evening.
