### ISSUE TITLE
Change templates using TypoScript constants - not working for Detail.html

### ISSUE THREAD

**Issue by derBoogie** [georgringer/news#1996]
I've got a strange behavior when overwriting the template path by constants in my sitepackage extension like described [here](https://docs.typo3.org/p/jweiland/maps2/10.0/en-us/AdministratorManual/Templates/Start/Index.html#change-the-templates-using-typoscript-constants).

Overwriting Templates/News/List.html is working fine.
Overwriting Templates/News/Detail.html works only if I delete or rename the template file (Detail.html) in news extension.

- TYPO3 version: 11.5.22
- news version: 10.0.3
- Composer Mode: no
- OS: Windows 10

**Comment by georgringer** [comment]
is the file system case sensitive? what does the TSOB say?

**Comment by derBoogie** [comment]
Hi @georgringer
you can see the TSOB in the attached screenshot. 
![news-config](https://user-images.githubusercontent.com/1611217/216716204-44ff6a65-256a-44fb-97ca-92e9fe612288.jpg)

**Comment by georgringer** [comment]
but the path would need to be EXT:sitepackage/Resources/Prviate/Templates/News/News/List.html!

**Comment by derBoogie** [comment]
@georgringer you are right, thanks a lot for the hint!
