### ISSUE TITLE
Not possible to override "previewPageId"

### ISSUE THREAD

**Issue by tmay-px** [georgringer/news#2001]
The setup:

- 2 different types of news articles ("news" and "events") in 2 different folders
- 2 separate detail pages ("news-detail" Uid 123 and "event-detail" UID 456)
- Page TSconfig in Root page is set: TCEMAIN.preview.tx_news_domain_model_news.previewPageId = 123
- On the folder that holds the "events" articles, Page TSconfig ist set in page settings: TCEMAIN.preview.tx_news_domain_model_news.previewPageId = 456

The problem:
"Preview" button in event articles has the correct link: domain.com/event-detail/...
But the article preview is not shown on the right page, instead the frontend opens domain.com/news-detail/...
And also the backend reloads and now the "Preview" button link is domain.com/news-detail/...

Expected behaviour:
Preview is shown on the configured page.

---

Environment

TYPO3 version): 11.5.22
news version: 9.4.0
Is your TYPO3 installation set up with Composer (Composer Mode): yes
PHP: 7.4

(Also tested in other installation with news version 10.0.3, same result).

**Comment by georgringer** [comment]
as the preview feature is a core feature and nothing from ext:news I suggest opening an issue at https://forge.typo3.org/projects/typo3cms-core/issues
