### ISSUE TITLE
Content elements with pagination

### ISSUE THREAD

**Issue by fishbone1** [georgringer/news#2002]
## Bug Report

**Current Behavior**
Content elements' pagination (e.g. Bootstrap Package gallery) doesn't work in the detail view. After clicking on the pagination the page will be reloaded and shows a message:

> The news record is not available anymore.

This probably is no surprise: The element changes its plugin state while ignoring the news detail's plugin state.

**Expected behavior/output**
Changing the "page" (plugin view state) of the content element while staying on the news detail page.

**Environment**
- TYPO3 version(s): 11.5.9
- news version: 9.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 18

**Additional context**
![grafik](https://user-images.githubusercontent.com/45480988/218452090-19dca485-d7f8-4b2d-8fa6-a5420f2bfa2e.png)

**Comment by georgringer** [comment]
the pagination is missing some addQueryString usage. 

I am closing this issue as this is not related to ext:news. if you need personal support, feel free to contact me in private

**Comment by fishbone1** [comment]
Ah, I'm sorry. There's already an issue here: https://github.com/benjaminkott/bootstrap_package/issues/1185
I thought it's a problem in general.
