### ISSUE TITLE
GeneralUtility::uniqueList deprecated in TYPO3v11

### ISSUE THREAD

**Issue by cstrizzolo** [georgringer/news#2003]
The following message gets appended to the deprecation log on TYPO3v11 with news 10.0.3:

Thu, 16 Feb 2023 09:24:40 +0100 [NOTICE] request="12d308c219178" component="TYPO3.CMS.deprecations": Core: Error handler (FE): TYPO3 Deprecation Notice: GeneralUtility::uniqueList() is deprecated and will be removed in v12. Use StringUtility::uniqueList() instead. in (...)/typo3_src-11.5.24/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 657 

That function is used by the extendPidListByChildren function in news/Classes/Utility/Page.php.

Maybe the above could be fixed even before v12 in order to avoid this annoyance.

Thanks in advance.

**Comment by georgringer** [comment]
has been fixed with https://github.com/georgringer/news/commit/ccbd8360ed52216e5c5ab3ccaab3a63fcf6f85dd please just use the branch `11-12` branch which will be released soon
