### ISSUE TITLE
Tag filter in list flexform

### ISSUE THREAD

**Issue by klodeckl** [georgringer/news#2013]
It would be nice if in the plugin flexform tags could be selected to filter for tags. To get it running I needed to set:
plugin.tx_news.settings.overrideFlexformSettingsIfEmpty = cropMaxCharacters,dateField,timeRestriction,orderBy,orderDirection, backPid,listPid,startingpoint, recursive,list.paginate.itemsPerPage,list.paginate.templatePath, tags
-> add tags
plugin.tx_news.settings.tags = 32

**Comment by georgringer** [comment]
wanna do a PR?

**Comment by klodeckl** [comment]
Okay. I will need a while.

**Comment by klodeckl** [comment]
There is no need for a PR as it is already there: Tab additional settings…
Maybe move it after category selection?
