### ISSUE TITLE
Search form frontend error

### ISSUE THREAD

**Issue by nwm-dev** [georgringer/news#2024]
## Bug Report

**Current Behavior**
using the "Search form" element leads to front-end error: 
"Call to undefined method TYPO3\CMS\Fluid\Core\Rendering\RenderingContext::getUriBuilder()"

**Environment**
- TYPO3 version: 12.2.0
- news version: 11.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10

**Comment by georgringer** [comment]
fixed with https://github.com/georgringer/news/commit/6cf1c42298d01d1f4ed94b83fae7cca8846e0dca

thanks for your report
