### ISSUE TITLE
The order of SEO page title

### ISSUE THREAD

**Issue by Zellwerker** [georgringer/news#2028]
Hello,

TYPO3 LTS 10,x, TYPO3 LTS 11.x
News 8.x, 9.x, 10.x

The order of the setting `plugin.tx_news.settings.detail.pageTitle.properties = title,teaser` seems to be not correct. Since the title is a mandatory field, there will never be the case that teaser appears in the title tag.

Correct should be with consideration of `alternativeTitle`.

`plugin.tx_news.settings.detail.pageTitle.properties = alternativeTitle,title`.

**Comment by georgringer** [comment]
wanna do a PR?
