### ISSUE TITLE
Plugin upgrade fails due to incomplete content element setup

### ISSUE THREAD

**Issue by akiessling** [georgringer/news#2029]
https://github.com/georgringer/news/blob/6cf1c42298d01d1f4ed94b83fae7cca8846e0dca/Classes/Updates/PluginUpdater.php#L181

One of my clients did not fully configure a news plugin --> no switchableControllerActions are stored in the flexform
Thus the upgrader fails with this 

<img width="874" alt="image" src="https://user-images.githubusercontent.com/2895543/224481670-a77ddc41-a149-46e0-8acc-80303e371491.png">

Should the upgrade then just skip this content element? In the page module, the message "No view yet configured" is shown

TYPO3 11.5.24
News: 11.0.0
PHP: 8.2

**Comment by georgringer** [comment]
yes. do you wanna provide a PR? thanks a lot!!

**Comment by akiessling** [comment]
switchableControllerActions seems to be always set? The non-migrated plugins then simply get "INVALID VALUE ("news_pi1")" when skipped
