### ISSUE TITLE
Typoscript - tt_content.list.20.news_pi1 does not work anymore

### ISSUE THREAD

**Issue by mbsued** [georgringer/news#2032]
## Bug Report

**Current Behavior**
The User-Object tt_content.list.20.news_pi1 in Typoscript does not work anymore (Still described in docomentation in the ICalendar). If i use tt_content.news_pi1 instead i get an error.

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1253191023: TypoScript object path "tt_content..20" does not exist | TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file /html/typo3/typo3_src-11.5.24/typo3/sysext/fluid/Classes/ViewHelpers/CObjectViewHelper.php in line 161. Requested URL: https://testumgebung.bfbn.de/schulaufsicht/mb-dienststelle-nordbayern/nachrichten/meldung-der-schulfremden-pruefer-1?type=9200`

**Environment**
- TYPO3 version(s): [11.5.24]
- news version: [11.0.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]

**Comment by derBoogie** [comment]
Can confirm the behavior.
I have no custom typoscript contents, just updated to 11.0.0.

- TYPO3 version: 11.5.25
- news version: 11.0.0
- Composer Mode: no

**Comment by MediKathi** [comment]
Can also confirm this behavior, just tried the update to 11.0.0

    TYPO3 version: 11.5.25
    news version: 11.0.0
    Composer Mode: no

**Comment by georgringer** [comment]
@mbsued how can I reproduce it?

**Comment by mbsued** [comment]
i use this Typoscript to print a news:
`news_print_file=PAGE
news_print_file {
  typeNum=9200
  config.index_enable = 0
  headerData.100 = TEXT
  headerData.100.value = <meta name="robots" content="noindex, nofollow" />
  bodyTag = <body onload="javascript:window.print()">  
  10 = COA
  10 {
    5=COA
    5 {
      10=TEXT
      10.value=<div style="text-align:center;  font-size:16pt; font-weight:bold">
      20=TEXT
      20.value=Nachricht der MB-Dienststelle {$text_regional}
      30=TEXT
      30.value=</div>
    }    
	10 < tt_content.news_pi1
    10 {
		switchableControllerActions {
        News {
        	1 = detail
      		}
    	}      
      	settings {
        	format = html
        	startingpoint={$uid_bayern},{$uid_regional},{$uid_termin}    
        	overrideFlexformSettingsIfEmpty := addToList(startingpoint)
        	displayDummyIfNoMedia=0
        	detail {
          	showSocialShareButtons=0
        	}
      	}
    	}
  }
}`
in my template i use the  link-viehhelper of news:
`						<n:link newsItem="{newsItem}" settings="{settings}" title="Nachricht drucken" configuration="{additionalParams:'&type=9200'}" additionalAttributes="{target:'_blank'}">
							Drucken
						</n:link>`

if i do this the error occors.

**Comment by derBoogie** [comment]
tt_content.list.20.news_pi1 is missing in TypoScript-Object-Browser
![news-11 0 0](https://user-images.githubusercontent.com/1611217/225025442-5ebdd020-20a5-4b59-8eee-152b821b6736.png)

**Comment by MediKathi** [comment]
Theres a new Upgrade Wizard for the news, to migrate the old records.
Did you run it?

**Comment by mbsued** [comment]
there is a new CType instead of tt_content.list.20.news_pi1.
![image](https://user-images.githubusercontent.com/5165597/225035808-2368efa6-b692-416c-a3be-1d6476d583b1.png)
 But using this CType leads to an error

**Comment by derBoogie** [comment]
Go it!
The Content Element "Plugin" has to be replaced by the new Content Elements "News-System".
![news-11 0 0-content](https://user-images.githubusercontent.com/1611217/225036643-589292ee-d544-454c-b3e3-ec8c2d29ec9a.png)
