### ISSUE TITLE
Upgrade Wizard "EXT:news: Migrate plugins" Undefined Array Key Warning

### ISSUE THREAD

**Issue by SWSGmbH** [georgringer/news#2033]
## Bug Report

**Current Behavior**
When I try to run the upgrade wizard from the backend, I get the following error message:

PHP Warning: Undefined array key "switchableControllerActions" in /private/typo3conf/ext/news/Classes/Updates/PluginUpdater.php line 118

If I then adjust the query:
$targetListType = $this->getTargetListType($flexForm['switchableControllerActions'] ?? "");

I get the next error:
PHP Warning: Undefined array key "*," in /private/typo3conf/ext/news/Classes/Updates/PluginUpdater.php line 180

**Environment**
- TYPO3 version(s): 11.5.25
- news version: 11.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Comment by georgringer** [comment]
thanks. a change has been pushed recently. can you retest with latest main?

**Comment by SWSGmbH** [comment]
Hi, thanks for the quick help. It continues with the error:

GeorgRinger\News\Updates\PluginUpdater::getTargetListType(): Argument #1 ($switchableControllerActions) must be of type string, null given, called in /private/typo3conf/ext/news/Classes/Updates/PluginUpdater.php on line 118

**Comment by dennismetz** [comment]
Hi, 
is there another update on this yet?
Unfortunately we still get the error, even with the latest version

**Comment by dennismetz** [comment]
It seems that the error also occurs if the news plugin was created once and saved but then the CType was changed - e.g. to Text or Textmedia

**Comment by georgringer** [comment]
i merged the change, IMO the issue can be closed, correct?

**Comment by dennismetz** [comment]
Theoretically yes, we have fixed all other bugs by hand so far.
You should still keep in mind that converted elements still trigger errors.

**Comment by schrej-zz** [comment]
Hi,
successfully checked and can be closed from my point of view

**Comment by georgringer** [comment]
thanks for your feedback!
