### ISSUE TITLE
Your dependencies have cycles

### ISSUE THREAD

**Issue by MediKathi** [georgringer/news#2034]
## Bug Report

**Current Behavior**
After the new extension was updated, I'm not able to create any new Content-Elements:
```Your dependencies have cycles. That will not work out```

**Environment**
- TYPO3 version(s): 11.5.25
- news version: 11.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
thanks for the report! however this is a bit hard to debug. is it because of the content element wizards from news and your project? can you reproduce it on a simple installation?

**Comment by MediKathi** [comment]
Hello,

I disabled my flux provider extension, and I was able to create content-elements again.
Somehow news seams to interfere with flux elements.

```
Your dependencies have cycles. That will not work out. Cycles found: ext-news.->common., ext-news.->forms., ext-news.->menu., ext-news.->plugins., forms.->medcalc., medcalc.->special., plugins.->forms., special.->common., special.->ext-news.
``` 
php states it comes from .../typo3/sysext/core/Classes/Service/DependencyOrderingService.php line 184

**Comment by MediKathi** [comment]
I did some reserach and this issue can be resolved:
In the file `typo3conf/ext/news/Configuration/TSconfig/ContentElementWizard.tsconfig` the element `mod.wizards.newContentElement.wizardItems.ext-news.after` had to be removed, in order to work with flux

**Comment by georgringer** [comment]
thanks for your support, really appreciated! I would however love to leave that: `after = common` can you recheck that?

**Comment by MediKathi** [comment]
I've tested it.
after = common works just fine.

for my configuration, it also works with: common,menu but anything else fails.

I think using only common at this point is more errorproof.
Maybe mention this behavior somewhere in the docs?
Someone could have modified their project in a way, that even 
```
after = common
before = special
```
can fail to execute

**Comment by georgringer** [comment]
thanks! simplified it
