### ISSUE TITLE
[FEATURE] Improved content element relations gives BE error with Gridelements

### ISSUE THREAD

**Issue by skydivematy** [georgringer/news#204]
[FEATURE] Improved content element relations
This feature gives me an Error in the backend when i try to open a news witch has an "Gridelement" as content element on a testing system 7.6.15 if this "Improved preview of content element relations" is activated in EM. But only with Gridelements CE not if the CE is a normal text&media.

Oops, an error occurred!
Call to undefined method TYPO3\CMS\Backend\Controller\EditDocumentController::contentIsNotLockedForEditors()

Gridelements is also the latest git

**Comment by georgringer** [comment]
fixed with https://github.com/georgringer/news/commit/9ac8056a5d4eb6f9addfef81f9118835e7d5922f
