### ISSUE TITLE
content elements are not translated

### ISSUE THREAD

**Issue by regioadmin** [georgringer/news#2059]
steps:
create a translation of a news item by clicking on a flag
open new item and translate a content element e.g. text
As long as there is an entry  in dropdown "Transl.Orig" under "Language",   text is displayed in original language on the website. 

**Environment**
- TYPO3 version(s): 11.5
- news version: 9.4
- OS: Linux

**Comment by georgringer** [comment]
IMO not a core issue, closing it now
