### ISSUE TITLE
Bug using the detail page error handling "redirectToListView"?

### ISSUE THREAD

**Issue by schmitzal** [georgringer/news#206]
Hey Georg,

I'm not quite sure if this is a bug or I am wrong...

I experienced the problem with a customer, that many website users run into 404s as the news were deleted or similar. Now the customer would like to redirect the users to the list view if the news can't be displayed.
I found your error handling feature. Thanks, just what I was looking for!

But, if I define the error handling to use "redirectToListView" configuration, I'm running into a 303 loop.
Somehow it ignores the action parameter in the url which after the first redirect is "list" so that it keeps calling the detail action and redirecting to list. Maybe a bug or maybe some missconfiguration in the setup of this customer.

However, wouldn't it be better to just pass the whole settings array to the "handleNoNewsFoundError" function and then redirect to the list page defined as "backPid"? Then we also would avoid possible duplicate content, as google could call a deleted news and then get the list view on a diferent url which would be duplicate content, I think.

I've created a patch. May you want to take a look at it?
And would you backport this also to version 3, if you accept the patch? This customer is still on 6.2.

Thanks in advance.

Best,
Alex

[_BUGFIX_303_loop_redirectToListView.zip](https://github.com/georgringer/news/files/693596/_BUGFIX_303_loop_redirectToListView.zip)

**Comment by NamelessCoder** [comment]
Patch looks okay to me - would you mind creating a pull request with that change, and perhaps use a subject á la `[BUGFIx] Respect backPid on noNewsFoundError redirect`. Thanks :)

**Comment by schmitzal** [comment]
Never contributed here... shall i create the pull request in my fork? im not able to create here a pull request based on my branch of the fork.

**Comment by NamelessCoder** [comment]
I've created the pull request for you (thanks for publishing your branch to your fork!)

To do this yourself there are two nice ways:

1. On your fork, select the branch you created - second/third button will be labeled "pull request" and clicking it should generally speaking just work, always.
2. Shortly after publishing your fork, visit the original repository's main page and you should see a yellow-background notification about your new branch - with a green "pull request" button next to it. This alert is only visible for around 30 minutes after creating a new branch, though.

Thanks for your contribution :)

**Comment by NamelessCoder** [comment]
I should also add: you can keep pushing new commits to your fork's branch if necessary - which it will be, see my review ;)

**Comment by schmitzal** [comment]
No problem and thanks for your support.

Fixed those two code style issues. No clue why the IDE indented with tabs there, as it should be set to PSR-2 :)

Have a nice weekend!

**Comment by schmitzal** [comment]
Btw. I'm sorry but I have no clue what's this travis about :D

Shall I do something so this build does pass also?

**Comment by NamelessCoder** [comment]
I've prepared a pull request from my fork to yours, which should solve the failing unit test.

https://github.com/schmitzal/news/pull/1

**Comment by NamelessCoder** [comment]
And another one - forgot to adjust for the changed redirect method.

https://github.com/schmitzal/news/pull/2

**Comment by schmitzal** [comment]
Looks like that wasn't the fix. At least I know now what travis does ;)

I must confess, to my shame, that I never worked with unit tests yet... something I must catch up as soon as possible.

I'm at bed now. Good night :)

**Comment by NamelessCoder** [comment]
No worries, tomorrow is another day :)

Thanks again for getting this one started.

**Comment by schmitzal** [comment]
Merged. Hope that's it. Else I'm back tomorrow :)

Thanks to you for your support with the build!

**Comment by georgringer** [comment]
code changed a couple of times, closing issue therefore. feel free to reopen a new one if still relevant
