### ISSUE TITLE
YouTube and other Video formats not allowed in v.11

### ISSUE THREAD

**Issue by kimchristiansen** [georgringer/news#2060]
In previous versions of the News Extension, file extensions of video formats were allowed, now only image formats are allowed.
However, the video palette is still included.

In the tx_news_domain_model_news.php file in the $imageConfigurationFalMedia array, 'common-image-types' is entered under 'allowed'.

Is this intentional? Can videos be included elsewhere? An update from v10 to v11 would cause problems if videos were included in previous news records under fal_media.

**Environment**
- TYPO3 version(s): 11.5
- news version: 11.0.0

**Comment by kimchristiansen** [comment]
By overriding the elementBrowserAllowed youtube, mp4 and other file endings can be enabled again:

`$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['fal_media']['config']['overrideChildTca']['columns']['uid_local']['config']['appearance']['elementBrowserAllowed'] = 'jpg,jpeg,png,mp4,youtube';`

**Comment by websi** [comment]
Within #2022 it was changed from `$GLOBALS['TYPO3_CONF_VARS']['SYS']['mediafile_ext']`to `$GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext']`

@georgringer Any reason for that change or can we provide an pr to allow media files again?

**Comment by georgringer** [comment]
@websi no, wanna do a PR?

**Comment by websi** [comment]
See #2133
