### ISSUE TITLE
Error on upgrade wizard

### ISSUE THREAD

**Issue by matin73** [georgringer/news#2061]
I get following error when running upgrade wizard:
Argument 1 passed to GeorgRinger\News\Updates\PluginUpdater::getTargetListType() must be of the type string, null given, called in /news/Classes/Updates/PluginUpdater.php on line 118

**Comment by chesio** [comment]
Hi @matin73,

I believe this has been reported already in #2033.

**Comment by georgringer** [comment]
closing issue
