### ISSUE TITLE
Code style mismatch: die should be used instead of die() in some files but not in others

### ISSUE THREAD

**Issue by sypets** [georgringer/news#2080]
This is just a fyi (for your information). It is not a severe problem. (but don't know if I should fix the code in my PRs or fix the CI configuration).

-----

Code style check (continuous-integration/styleci/pr) fails for `defined('TYPO3') or die();` in ext_localconf.php, but not in Configuration/TCA files.

The Style CI output shows the following diff for ext_localconf.php:

-defined('TYPO3') or die();
+defined('TYPO3') or die;

https://github.styleci.io/analyses/9b0weP?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

but nothing for the TCA files where this statement also exists.

Also, in official documentation `defined('TYPO3') or die();` is still used: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ExtLocalconf.html

**Expected behavior/output**

Either don't warn about `die()` (as this complies with current TYPO3 best practice) or warn in all files. (I am not familiar with the configuration, so I don't know how to fix this currently.).

**Comment by georgringer** [comment]
removed all checks
