### ISSUE TITLE
Date format is broken

### ISSUE THREAD

**Issue by t3premium** [georgringer/news#2086]
## Bug Report

**Current Behavior**
In the current news v11.0.0 with TYPO3 v12.3.0, the date format is broken.

**Expected behavior/output**
The date output looks like "%0/%23/%2023"

**Environment**
- TYPO3 version: 12.3.0
- news version: 11.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- PHP: 8.1.16
- OS: Linux 5.4.0-146-generic

**Possible Solution**
The translation files need to be set to new date format.
Old:
```
<trans-unit id="dateFormat" xml:space="preserve">
	<source>%m/%d/%Y</source>
</trans-unit>
```

New:
```
<trans-unit id="dateFormat" xml:space="preserve">
	<source>m/d/Y</source>
</trans-unit>
```

**Comment by georgringer** [comment]
this was an issue of the DateViewHelper in core, fixed with https://github.com/TYPO3/typo3/commit/17fde56d8bfd37431e9278756309917d53770100
