### ISSUE TITLE
Tag CountViewHelper counts hidden records

### ISSUE THREAD

**Issue by whiteroom** [georgringer/news#2099]
## Bug Report

**Current Behavior**
Tag CountViewHelper counts hidden records as well

**Expected behavior/output**
tagUsageCount ignores hidden records

**Environment**
- TYPO3 version(s): 11.5.26
- news version: 11.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Comment by georgringer** [comment]
wanna do a PR?

**Comment by whiteroom** [comment]
Further investigation shows that misleading behavior is due to data. 
tagUsageCount works as expected after a clean install. Suggest to close the issue
