### ISSUE TITLE
[DOC] Extend FlexForms, Provide a working example for News Version 11

### ISSUE THREAD

**Issue by whiteroom** [georgringer/news#2110]
The given tutorial on how to extend flexforms
[Extend FlexForms](https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/ExtendNews/Index.html)

seems not to work with the current version of News (Version 11)
Can you give an updated example?
thanks a lot, Georg

**Comment by georgringer** [comment]
@whiteroom check out https://github.com/georgringer/eventnews/blob/11-12/Classes/Hooks/FlexFormHook.php

**Comment by georgringer** [comment]
I guess your code does not work because you extend a different plugin?

**Comment by whiteroom** [comment]
Ok, that was quick. Thank you for the hint. I will close the issue
