### ISSUE TITLE
TagRepository->findByIdList() throws exception

### ISSUE THREAD

**Issue by web-it-solutions** [georgringer/news#2120]
## Bug Report

**Current Behavior**
`findByIdList()` in TagRepository fails because first argument must be of type `TYPO3\CMS\Extbase\Persistence\Generic\Qom\ConstraintInterface`, array given.

**Expected behavior/output**
`TagRepository->findByIdList()` works exact like `CategoryRepository->findByIdList()`.

**Environment**
- TYPO3 version(s): 12.4.1
- news version: 11.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: DDEV (Ubuntu), Linux

**Possible Solution**
Use splat operator.

**Comment by georgringer** [comment]
fixed with https://github.com/georgringer/news/commit/0c1d094c6793c8571e31b941783bbe8db1157f65
