### ISSUE TITLE
News DateMenu and List doesn't work on same page

### ISSUE THREAD

**Issue by gocher68** [georgringer/news#2124]
## Bug Report

**Current Behavior**
There is one plugin news_newsdatemenu and  one news_newsliststicky on same page, without any overwriteDemand values like year and month both plugins displays the expected content (DateMenu and NewsList), with overwriteDemand values both plugins displays the NewsList.

**Expected behavior/output**
The news_newsdatemenu plugin should display the DateMenu with active year month selection.

**Environment**
- TYPO3 version(s): 12.4.2
- news version: 11.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Additional context**
It looks like the action is being overwritten by the request parms.
This error appeared after an update from an older TYPO3 version.

**Comment by gocher68** [comment]
Sorry, no Bug it was a incorrect configuration

**Comment by georgringer** [comment]
just out of curiosity and because others might ask as well: what was the wrong configuration and what the solution? thanks for helping others

**Comment by gocher68** [comment]
The plugin configuration was overwritten in a other Extension.
```
ExtensionUtility::configurePlugin(
        'News',
        'NewsDateMenu',
        [
            NewsController::class => 'dateMenu, list',
        ],
        [
            NewsController::class => 'dateMenu, list',
        ],
        ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT
    );

```
