### ISSUE TITLE
Error on upgrade wizard migrate plugins

### ISSUE THREAD

**Issue by klodeckl** [georgringer/news#2125]
## Bug Report

I get the following error when running the upgrade wizard:

Wed, 14 Jun 2023 13:31:06 +0000 [CRITICAL] request="36147f0b75147" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: BE): TypeError, code #0, file /var/cg/vhosts/dev4/typo3conf/ext/news/Classes/Updates/PluginUpdater.php, line 181: trim(): Argument #1 ($string) must be of type string, null given - {"mode":"WEB","application_mode":"BE","exception_class":"TypeError","exception_code":0,"file":"/var/cg/vhosts/dev4/typo3conf/ext/news/Classes/Updates/PluginUpdater.php","line":181,"message":"trim(): Argument #1 ($string) must be of type string, null given","request_url":"https://dev4.oth-aw.de/typo3/install.php?install[controller]=upgrade&install[context]=backend","exception":null}

**Environment**
- TYPO3 version: 11.5.27
- news version: 11.0.0
- Composer Mode: no
- OS: Debian 10

**Comment by kaystrobach** [comment]
I can confirm it works.

**Comment by gyoengyoesi** [comment]
The patch works for me too.

**Comment by kaystrobach** [comment]
Will you do a release soon?

**Comment by georgringer** [comment]
yes, I try too but needs combinated releases with eventnews

**Comment by kaystrobach** [comment]
Awesome! 😘
