### ISSUE TITLE
Cannot use hook because the parameters don't have the CType of plugin

### ISSUE THREAD

**Issue by balatD** [georgringer/news#2126]
See this line, $actionTranslationKey doesn't have a value set. Therefore the hook cannot be used properly to render a custom plugins preview. 

https://github.com/georgringer/news/blob/0c1d094c6793c8571e31b941783bbe8db1157f65/Classes/Hooks/PluginPreviewRenderer.php#LL120C1-L120C1

**Comment by georgringer** [comment]
I guess I should remove the hook as now there are different plugins anyway, what you think https://github.com/georgringer/eventnews/blob/main/Classes/Hooks/PageLayoutView.php

but additionally with https://github.com/georgringer/news/commit/4a46f2b6cad5ca30672be16929522c626472acd9 I now also hand over the full item
