### ISSUE TITLE
Content elements shown in List Module in v12

### ISSUE THREAD

**Issue by derhansen** [georgringer/news#2127]
Currently, all content elements of a news article are shown in the list module.

`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS'][DatabaseRecordList::class]['modifyQuery'][]` has been removed in v12. Instead, `ModifyDatabaseQueryForRecordListingEvent` PSR-14 event must be used.

Tried to create a PR, but `$recordListConstraint->extendQuery()` function need refactoring. Since we have `getQueryBuilder()` and `setQueryBuilder()` in the event, I think it is possible to refactor the whole logic of `RecordListConstraint` to match into the event listener.

**Comment by georgringer** [comment]
but this is more a Feature, correct? as those content elements have always been shown?

**Comment by derhansen** [comment]
No, when the extension is configured to hide content elements in list view for folders containing news items, those are hidden in v11 using the `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS'][DatabaseRecordList::class]['modifyQuery'][]` hook. In v12 they are always shown, since the hook is not available any more.

**Comment by georgringer** [comment]
wanna review https://github.com/georgringer/news/pull/new/2127? thanks

**Comment by derhansen** [comment]
Thanks, works as expected
