### ISSUE TITLE
Regression: 11.1 breaks Detailview when CE is included

### ISSUE THREAD

**Issue by sandrotanner** [georgringer/news#2131]
## Bug Report

**Current Behavior**
Detail view of news with content element gives error (probably whenever it has to load something from tt_content, but I am not sure... see "Possible Solution" below).

```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1579965021: The type of property GeorgRinger\News\Domain\Model\TtContent::image could not be identified, therefore the desired value (0) cannot be mapped onto it. The type of a class property is usually defined via property types or php doc blocks. Make sure the property has a property type or valid @var tag set which defines the type. | TYPO3\CMS\Extbase\Persistence\Generic\Mapper\Exception\UnknownPropertyTypeException thrown in file /var/www/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php in line 215. Requested URL: http://localhost:8000/be/news/v?tx_news_pi1%5Baction%5D=detail&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Bnews%5D=21&cHash=f91b2f2853387ae74a778b5c88b27055 
```

**Expected behavior/output**
no error, since exact same configuration works wit ext:news 11.0 (I even tested it by downgrading again)

**Environment**
- TYPO3 version(s): 11.5.28
- news version: 11.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian Bullseye (php:8.1-apache-bullseye from dockerhub)

**Possible Solution**
Revert or fix https://github.com/georgringer/news/pull/2115 

**Additional context**
AS far as I can tell with my limited knowhow, having multiple property types annotaded is only supported in extbase v12.3+. See https://github.com/TYPO3-CMS/extbase/commit/b73926344fb821924e9afcd69853b5c3a83a122b

**Comment by echavaillaz** [comment]
Yes, it is linked to my comment. Union type is not supported in TYPO3 11.
