### ISSUE TITLE
Editing of a translated newsrecord fails

### ISSUE THREAD

**Issue by mweber1973** [georgringer/news#2135]
## Bug Report

Editing a translated Record fails. We converted some news from tt_news to tx_news. The first try to edit a translated news record works fine, all is stored. Editing again fails with some JS-Errors:

Uncaught (in promise) TypeError: Cannot set properties of null (setting 'disabled')
    at form-engine.js?bust=6cb49aea4000ffbbfcc98bccc996ef4f711309f6:13:12668
    at NodeList.forEach (<anonymous>)
    at Object.initializeLocalizationStateSelector (form-engine.js?bust=6cb49aea4000ffbbfcc98bccc996ef4f711309f6:13:12438)
    at Object.reinitialize (form-engine.js?bust=6cb49aea4000ffbbfcc98bccc996ef4f711309f6:13:12217)
    at form-engine.js?bust=6cb49aea4000ffbbfcc98bccc996ef4f711309f6:13:21565

We are working with Typo3 V12.4.2 and news 11.0,0 in newest Chrome.

**Comment by chesio** [comment]
@mweber1973, I believe this is a duplicate of #2093.

**Comment by georgringer** [comment]
this is a core issue, sorry but it is worked on
