### ISSUE TITLE
The page is not configured! [type=9818][]. This means that there is no TypoScript object of type PAGE with typeNum=9818 configured.

### ISSUE THREAD

**Issue by natalieweyda** [georgringer/news#2155]
I tried to use [Automatic RSS feeds - based on plugins](https://docs.typo3.org/p/georgringer/news/10.0/en-us/Tutorials/BestPractice/Rss/Index.html#automatic-rss-feeds-based-on-plugins) in a TYPO3 v10 Project but only always get "The page is not configured! [type=9818][]. This means that there is no TypoScript object of type PAGE with typeNum=9818 configured."
I used the exact same code as in the documentation. I also tried it in TYPO3 v12 which has thrown the same error.

**Comment by Karionis** [comment]
It seems that the condition
`[globalVar = TSFE:type = {$plugin.tx_news.rss.channel.typeNum}]`
does not work. Try
`[getTSFE().type == {$plugin.tx_news.rss.channel.typeNum}]`
instead. Or for TYPO3 12:
`[getTSFE()?.id == {$plugin.tx_news.rss.channel.typeNum}]`

**Comment by georgringer** [comment]
IMO everything should work. additionally the condition could even be removed as well
