### ISSUE TITLE
No Demand overwrite in Searchform

### ISSUE THREAD

**Issue by develth** [georgringer/news#2176]
I think this is not correct and results to true, when we want to disable it:

https://github.com/georgringer/news/blob/0cc224cc6b3269de126aa6dd8fe8250a629bf094/Classes/Controller/NewsController.php#L519

In other parts it looks like `$this->settings['disableOverrideDemand'] != 1;`

**Comment by georgringer** [comment]
wanna checkout https://github.com/georgringer/news/pull/2177?
