### ISSUE TITLE
Tab for Eventnews missing, with eventnews extension 6.0.0 installed

### ISSUE THREAD

**Issue by paptikant** [georgringer/news#2178]
## Bug Report

**Current Behavior**
In the 'List articles with details view' CType in the Plug-In settings the 'Eventnews' Tab is missing.
when using the CType 'Month view provided by ext:eventnews' the tab is there.

**Expected behavior/output**
I expect the Tab 'Eventnews' to be there in the news case, to select the options settings.eventRestriction:
-no restrictions, 
-only events, 
-everything except events

**Environment**
- TYPO3 version(s): 11.5.30
- news version: 11.1.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10

**Additional context**
I assume it's the combination with the version of 6.0.0 of Eventnews extension; the latest combination news 10.0.3 and eventnews 5.0.2 worked fine;

**Comment by georgringer** [comment]
can you test latest eventnews version from github, thx

**Comment by paptikant** [comment]
I tried:

  - Upgrading georgringer/news (10.0.3 => 11.1.2): Extracting archive
  - Upgrading georgringer/eventnews (5.0.2 => dev-main c333137): Extracting archive
  
and it looks good now, thanks.

**Comment by georgringer** [comment]
thanks for your feedback!
