### ISSUE TITLE
Translation of previous/next in pagination is not working as expected

### ISSUE THREAD

**Issue by web2date** [georgringer/news#2179]
## Bug Report

**Current Behavior**
The pagination (standard,Twb,Twb5) is using the translation for previous and next from EXT:fluid
`<li class="previous">
                    <a href="{f:uri.action(action:actionName, arguments:{currentPage: pagination.previousPageNumber},addQueryString:1)}" title="{f:translate(key:'pagination.previous')}">
                        {f:translate(key:'widget.pagination.previous', extensionName: 'fluid')}
                    </a>
                </li>`
**Expected behavior/output**
The pagination (standard,Twb,Twb5) is using the translation for previous and next from EXT:News, so it is possible to overwrite it per typoscript as before.
For example with:
`plugin.tx_news._LOCAL_LANG.de {
        paginate_previous = «
        paginate_next = » }`

**Environment**
- TYPO3 version(s): 11.5.30
- news version: 11.1.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: ddev

**Possible Solution**
`<li class="page-item previous">
                    <a class="page-link" href="{f:uri.action(action:actionName, arguments:{currentPage: pagination.previousPageNumber},addQueryString:1)}" title="{f:translate(key:'pagination.previous')}">
                        {f:translate(key:'paginate_previous', extensionName: 'news')}
                    </a>
                </li>`

`<li class="page-item next">
                    <a class="page-link" href="{f:uri.action(action:actionName, arguments:{currentPage: pagination.nextPageNumber},addQueryString:1)}" title="{f:translate(key:'pagination.next')}">
                        {f:translate(key:'paginate_next', extensionName: 'news')}
                    </a>
                </li>`

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
wanna do a PR?

**Comment by web2date** [comment]
I'll try...

**Comment by georgringer** [comment]
Thanks, 

i checkout the  changes and remember that I use fluid for a reason because it is possible to modify translations just once by overridng the strings by using plugin.tx_fluid. can you recheck that?

**Comment by web2date** [comment]
Hi, I can not find anything related to "plugin.tx_fluid." either in constants, setup or in the whole EXT:news...
I think in standard TYPO3 websites the pagination is seldom used, but Ext:news with pagination is offen used. So the first thought an integrator would have is to use your possibility to overwrite the locallang files as described in line 26-31 of /Configuration/TypoScript/setup.typoscript (as all years before...;-))

**Comment by georgringer** [comment]
just because there is nothing in constants, it doesn mean that does not work

tested it with
```
plugin.tx_fluid {
_LOCAL_LANG.default {
widget.pagination.next = now next
}
}
```

and will also add it to the docs
