### ISSUE TITLE
TYPO3 extension "newspreview"

### ISSUE THREAD

**Issue by wowawebdesign** [georgringer/news#218]
I found the extension **newsinpreview**, which implements a very cool feature for displaying the preview images.
https://github.com/georgringer/TYPO3.CMS.newspreview

Would it be possible to integrate this as a core feature in news?

I know someone, who is willing to do the coding (@t3easy) ;)

**Comment by georgringer** [comment]
should be doable

**Comment by t3easy** [comment]
I've prepared a feature branch:
https://github.com/t3see/news/tree/feature-218
Feel free to test.

**Comment by t3easy** [comment]
Hi @georgringer can you have a look at the branch to estimate if the implementation goes into the right direction?

**Comment by georgringer** [comment]
Looks good from mobile. Some notes: check out the new getters in master without the fal in the name and use array short hand syntax

**Comment by georgringer** [comment]
solved
