### ISSUE TITLE
ext:news not regognized as GPL-2

### ISSUE THREAD

**Issue by lolli42** [georgringer/news#2187]
## Bug Report

The LICENSE.txt file contains a "custom" header, github thus declares the project as "other" instead of GPL-2.

I guess ext:news has nothing todo with famfamfam (anymore?!), so I assume the same patch as done in https://github.com/TYPO3/cms-cli/pull/8 could be applied (I copied LICENSE.txt from core monorepo).

**Comment by georgringer** [comment]
thanks!
