### ISSUE TITLE
contentElementRelations Error 200 parsererror 

### ISSUE THREAD

**Issue by p-view** [georgringer/news#2201]
get the Error when i will add new contentElementRelations

- TYPO3 version(s):  8.7.43,
- news version: 7.3.1

Composer Mode no

**Comment by georgringer** [comment]
sorry but I don't support such old versions anymore, also TYPO3 8 is EOL since a long time. if you really need a solution, contact me in private for paid support

**Comment by p-view** [comment]
i had solve the problem by upgrade typo3 to 8.7.50
thx a lot for this great extension
