### ISSUE TITLE
CountDemanded not work

### ISSUE THREAD

**Issue by KrohnMi** [georgringer/news#2217]
## Bug Report

**Current Behavior**
I get the following error message when I try to determine the number of entries by a demand object

```
TYPO3\CMS\Extbase\Persistence\Generic\Query::logicalAnd(): Argument #1 must
      be of type TYPO3\CMS\Extbase\Persistence\Generic\Qom\ConstraintInterface, ar
      ray given, called in /var/www/vendor/georgringer/news/Classes/Domain/Reposit
      ory/AbstractDemandedRepository.php on line 181
```

**Expected behavior/output**
That i get the number of entries

**Environment**
- TYPO3 version(s): 12.4.6
- news version: 11.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Comment by georgringer** [comment]
add a comment at https://github.com/JAK0TA/news/commit/24160f4c6381c1426139044024e43a7dcfc42375, wanna test that?

**Comment by KrohnMi** [comment]
@georgringer Yes, I tested it, but I think we don't need it here anymore. The constraints are always set in the create query method.

**Comment by valentin-** [comment]
I'm experiencing the same issue using coundDemanded. The fix mentioned in https://github.com/JAK0TA/news/commit/24160f4c6381c1426139044024e43a7dcfc42375 works for me.
