### ISSUE TITLE
Problem with indexed_search

### ISSUE THREAD

**Issue by mweber1973** [georgringer/news#2228]
## Bug Report

I want to use indexed_search. When I put 

```
<f:form action="search" method="post" id="tx_indexedsearch" pageUid="63">
</f:form>
```

in my pagetemplate the error

GeorgRinger\News\Xclass\ExtensionServiceXclassed::getPluginNameByAction(): 
Argument #1 ($extensionName) must be of type string, null given, called in typo3_src-11.5.32/typo3/sysext/extbase/Classes/Mvc/Web/Routing/UriBuilder.php on line 557

occurs. 

Bug or my fault? 

**Environment**
- TYPO3 version(s): 11.5.32
- news version: 11.1.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
if you would rename the method in `ExtensionServiceXclassed` I guess you would get the same error from `ExtensionService`. if yes, this is your error.

why not provide the extensionName argument?

**Comment by mweber1973** [comment]
Where do I provide the extenion-argument?

**Comment by mweber1973** [comment]
For all who get the same error:

<f:form action="search" controller="Search" method="post" id="tx_indexedsearch"  extensionName="IndexedSearch" pluginName="Pi2" pageUid="..">
