### ISSUE TITLE
[TYPO 8.5.1] Problem with datetime of news article

### ISSUE THREAD

**Issue by c0d3b34n** [georgringer/news#223]
On news article record saving is only possible if you focus datetime field before. If not, it produces an exception:

Uncaught TYPO3 Exception: DateTime::__construct(): Failed to parse time string (2017-01-01T00:00:00+) at position 19 (+): Unexpected character

Input element without focus (throws error):
`<input type="hidden" name="data[tx_news_domain_model_news][3][datetime]" value="2017-01-21T17:34:00+00:00">`

After focus and blur (can be successfully saved):
`<input type="hidden" name="data[tx_news_domain_model_news][3][datetime]" value="2017-01-21T17:34:00Z">`

**Comment by georgringer** [comment]
solved in master already
