### ISSUE TITLE
Separate plugin settings

### ISSUE THREAD

**Issue by kitzberger** [georgringer/news#2231]
## Feature Request

Currently it's not possible to define individuals plugin settings per CType. All 6 news CTypes are using the TS settings defined under:

```
plugin.tx_news.settings {
   ...
}
```
An individual set of TS settings for (let's say) "category list" isn't considered at all:

```
plugin.tx_news_category.settings {
   startingpoint = 123
}
```

Would be great if in `NewsController->buildSettings()` the settings would be put together like this:

* TS settings from `plugin.tx_news`
* TS settings from `plugin.tx_news_<CType>` <-- new!
* FF settings from content element
* Hook via `$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['Controller/NewsController.php']['overrideSettings']`

**Comment by georgringer** [comment]
Wanna give it a shot?

**Comment by georgringer** [comment]
I currently don't see a real need for it, therefore closing issue to also cleanup issue tracker here. feel free to reopen a new issue if still relevant
