### ISSUE TITLE
Title from MenuProcessor not translated with TYPO3 12

### ISSUE THREAD

**Issue by websi** [georgringer/news#2236]
## Bug Report

**Current Behavior**
The title from MenuProcessor for a translated news show the title of the news at the default language.

**Expected behavior/output**
The title for a translated news shows the title for the current language.

**Environment**
- TYPO3 version(s): 12.4.7
- news version: 11.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**

Use the new Method [getLanguageOverlay](https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/core/Classes/Domain/Repository/PageRepository.php#L383) instead of "getRecordOverlay" or use the Extbase Repository to get the current News Object.

Our solution ist a own MenuProcessor wich use the Extbase Repository to fetch the News Record. 

**Additional context**

https://github.com/georgringer/news/blob/0099d5b7f07d6cbbbb6b32d38e59e1aba5297944/Classes/DataProcessing/AddNewsToMenuProcessor.php#L106

`getRecordOverlay` is called with the id of the language instead of the `LanguageAspect` Object. TYPO3 use the overlay mode "off" for these use case. See https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/core/Classes/Domain/Repository/PageRepository.php#L705

**Comment by georgringer** [comment]
> The title from MenuProcessor for a translated news show the title of the news at the default language.

you mean: The title from MenuProcessor for a translated news show the title of the default news at the other language.?

**Comment by websi** [comment]
On the englisch Page the german (Default language) title is shown. Sorry for the inaccurate information.
