### ISSUE TITLE
[DOC] Search fields - Content in relations - Foreign tables

### ISSUE THREAD

**Issue by soheibo-mcn** [georgringer/news#2240]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The clear relationship between tables doesn't seem to be clear for the `search.fields` plugin setting. Let's say I want to be able to search *Content Elements*' content associated to news. Based on current documentation, it would seem that `content_elements.bodytext` is the solution. After some observations, it would appear not to work. At this point, you could go through tables and find references to foreign tables such as `tt_content` or other keys such as `tx_news_related_news`, but it still wouldn't be clear which path is needed to get to the core idea of searching the text part of Content Elements.

**Describe the solution you'd like**
The documentation could use some improvements: I believe putting an example with foreign tables would help clear the subject for future users. The same way `categories.title` is popular enough to warrant an example, I believe  *Content Elements*' content as base is worth a shot.

**Teachability, Documentation, Adoption, Migration Strategy**
I believe an explanation of links between tables with the above example would be enough as base documentation.

**Comment by georgringer** [comment]
I pushed some changes. `contentElements.header` is the correct code
