### ISSUE TITLE
Cannot create backend records (Website User for instance) with News installed

### ISSUE THREAD

**Issue by vmans** [georgringer/news#2246]
TYPO3 12.4.7 and latest News.

With News installed:
![image](https://github.com/georgringer/news/assets/25581914/78180ac4-7ffe-4e8c-8267-afd9c8e639f8)

With News removed:
![image](https://github.com/georgringer/news/assets/25581914/c39df74c-8bc4-4a79-a99e-d507e6318317)

**Comment by georgringer** [comment]
this is if the module field is set to news
