### ISSUE TITLE
excludeAlreadyDisplayedNews doesn't work with NewsListSticky-plugin and detail view on the same page.

### ISSUE THREAD

**Issue by stephangrass** [georgringer/news#2247]
I have a page with a news detail view and a news list view integrated. The list view uses the NewsListSticky plugin. Now, it can happen that a news item is called up in the detail view that also appears in the list. The excludeAlreadyDisplayedNews option should help with this, but it doesn't. Is this not possible (anymore)?

i am using TYPO3 12 width news 11.2.0

Thanks 
Stephan

**Comment by stephangrass** [comment]
Can anyone replicate this behavior? Or am I doing something wrong?

**Comment by georgringer** [comment]
it works but it highly depends on the render order (!) and not on the visual order

**Comment by sonal36** [comment]
Yes, I have an issue with the News List plugin on the Detail page. I want to render the latest news at the bottom of the detail page.
But it gives this error,

The action "detail" (controller "GeorgRinger\News\Controller\NewsController") is not allowed by this plugin/module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php.
