### ISSUE TITLE
Why that odd plugin name? Sticky article list view

### ISSUE THREAD

**Issue by kitzberger** [georgringer/news#2255]
Hi,

our users are at first always confused by the odd name for the list plugin that comes without an detail view: "Sticky article list view"

Is there any particular reason behind that name? Why is it supposed to be sticky?

Wouldn't "List articles" be a simpler and better name because it'd align nicer with the default plugins name: "List articles with detail view" within the CType select field.

**Comment by georgringer** [comment]
I just didn't have a better idea and "list view" without any information felt wrong

**Comment by kitzberger** [comment]
Ahhh, it is "sticky" in the sense of being stuck to the list view and cannot change to the detail view, right?

What about these names and descriptions?

| CType | Title | Description |
| --- | -- | -- |
| news_pi1 | News article list (+ detail view) | Listing of news articles chosen by various properties like storage folder, categories, time constraints, etc. This plugin is capable of rendering the detail view as well. |
| news_newsstickylist| News article list | Listing of news articles chosen by various properties like storage folder, categories, time constraints, etc. This plugin cannot render the detail view of news articles. |
| news_newsdetail | News article detail view | Rendering the detail view of a news article. |

I think "news" should be part of the titles, so they make sense outside of the new element wizard as well.

**Comment by georgringer** [comment]
looks good to me

**Comment by kitzberger** [comment]
@georgringer, I've prepared a PR for this. My goal was to find names that I backend user would easily understand without further explanation. What do you think?
