### ISSUE TITLE
Error 503 after Update

### ISSUE THREAD

**Issue by weiseger** [georgringer/news#2259]
I am running a TYPO3 project under TYPO3 11.5.13. By updating to news 11.2.0 I get an error 503 with:
`The Fluid template files "/mysite/public/typo3conf/ext/mypackage/Resources/Private/Extensions/news/Partials/General/AdditionalInformation.html", "/mysite/public/typo3conf/ext/mypackage/Resources/Private/Extensions/news/Partials/General/AdditionalInformation", "/mysite/public/typo3conf/ext/news/Resources/Private/Partials/General/AdditionalInformation.html", "/mysite/public/typo3conf/ext/news/Resources/Private/Partials/General/AdditionalInformation" could not be loaded.`

I am confused because I never defined AdditionalInformation.html in my sitepackage nor do see a folder "Partial/General" in the news extension.

Do you have any clou what thes error causes?

**Comment by georgringer** [comment]
it is kind of impossible to help here but I suppose to check the templates where the call to `AdditionalInformation` happens
