### ISSUE TITLE
Proxy Class Generation: extending contructor not working for tags

### ISSUE THREAD

**Issue by kitzberger** [georgringer/news#2272]
## Bug Report

**Current Behavior**
When extending a model class and using a `__construct()` method in the own class is only working when that method exists in original class, e.g. `Tag`.

There's no real exception thrown though.

**Expected behavior/output**
Constructor can be set in own model class.

**Environment**
- TYPO3 version(s): 11
- news version: 11
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: linux

**Possible Solution**
Maybe add an empty constructor to all model classes?

**Comment by georgringer** [comment]
wanna add a PR with empty constructor + a comment that this is intentional?
