### ISSUE TITLE
"Navigation loading error. Got unexpected response from the server. Please check logs for details." when category tree is still loading while saving

### ISSUE THREAD

**Issue by ToGetATockenOnly** [georgringer/news#2276]
TYPO3v12 loading of bigger category tree show AJAX error. 

This is mentioned in Forge tickets:

https://forge.typo3.org/issues/99455
( https://forge.typo3.org/issues/97003 )
https://forge.typo3.org/issues/100219

**Comment by georgringer** [comment]
IMO not a news issue, also https://forge.typo3.org/issues/100219 seems to be that this is more a core.

closing issue here to cleanup issue tracker
