### ISSUE TITLE
Table printed in documentation for tags is broken

### ISSUE THREAD

**Issue by instruccionesaldorso** [georgringer/news#2284]
Table over this page is broken:
https://docs.typo3.org/p/georgringer/news/main/en-us/UsersManual/Records/Tag/Index.html

This block should be removed: https://github.com/georgringer/news/blob/main/Documentation/UsersManual/Records/Tag/Index.rst?plain=1#L25-L29

And these blocks should be left-indented: https://github.com/georgringer/news/blob/main/Documentation/UsersManual/Records/Tag/Index.rst?plain=1#L30-L52

**Comment by georgringer** [comment]
added a commit, wanna check?
