### ISSUE TITLE
TYPO3 12 eventnews plugin xml configuration is lost after upgrade wizard "txNewsPluginUpdater"

### ISSUE THREAD

**Issue by luisbecker-gh** [georgringer/news#2298]
## Bug Report

**Current Behavior**
The configuration for the plugin settings settings.eventRestriction is lost, when running the upgrade wizard  "txNewsPluginUpdater" because it is not part of the returned array from `getAllowedSettingsFromFlexForm` in PluginUpdater.php.

**Expected behavior/output**
Wizard should not delete parts of the plugin configuration

**Environment**
- TYPO3 12.4
- news version: [11.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Add the additional Flexform settings to the allowed settings, if eventnews is loaded.

**Additional context**
I know its more an EXT:eventnews bug, but I think it could be resolved in the Plugin Updater Class in EXT:news with `ExtensionManagementUtility::isLoaded('eventnews')`. Alternatively, it could also be solved with an Xclass in EXT:eventnews.
I am happy to write a fix and pull request.

**Comment by georgringer** [comment]
please use main version of both exts

**Comment by luisbecker-gh** [comment]
ah i only looked at the tagged versions and github issues. Thanks!
