### ISSUE TITLE
Workspace only records are not shown in list action

### ISSUE THREAD

**Issue by Sonja-Schubert** [georgringer/news#230]
When I create a news record in workspace there will be two new records in db: one placeholder with pid = 123 and t3ver_wsid = 8 and one record with pid = -1 and t3ver_id = 1 and t3ver_wsid = 8. The first record is a placeholder and the second one contains all data and relations. 

Problem: I have a news plugin with listAction configured which shows recods correctly in live mode. In workspace mode it only shows the live records but not the new generated workspace only news as the placeholder does not have any relations to categories which is a condition by flexform. As soon as I remove the "show only selected categories" condition in flexform the workspace records are shown in list action

I know workspace overlay is done by extbase basically, but extbase does not know the category constraints... so do I have a missunderstanding or a local wrong configuration? Would be nice to know if this workspace preview thing does work in your environment as I thought it worked in earlier TYPO3 / news extension versions. I testet with TYPO4 7.6.15 and news 5.3.2

Thank you for your feedback and help

**Comment by georgringer** [comment]
I am pretty sure that this has never worked as the DB call is just done with the wrong ids. I don't do there any magic. The chance IMO is only to solve that once forever with 8.

**Comment by Sonja-Schubert** [comment]
Hi Georg
Thank you very much for your fast reply. I expected this answer but hoped... ;-) Would be great if there would be a good extbase solution in TYPO3 8.
Wish you a nice day
Greetings

Sonja

**Comment by georgringer** [comment]
as this is an extbase issue, I am closing this finally.
