### ISSUE TITLE
News flexform still features switchableControllerAction

### ISSUE THREAD

**Issue by smichaelsen** [georgringer/news#2302]
## Bug Report

**Current Behavior**
https://github.com/georgringer/news/blob/a81398060ff206bc7c7c1aff4b148e2ceadc7499/Configuration/FlexForms/flexform_news.xml#L16
`flexform_news.xml` still features the switchableControllerAction field, using the `GeorgRinger\News\Hooks\ItemsProcFunc->user_switchableControllerActions` function to generate items, but this function does not exist anymore which yields this error for me:
![Screenshot 2024-01-04 at 11 13 02](https://github.com/georgringer/news/assets/912435/9fea9922-b535-40eb-aff7-1709cbed0dcd)

**Environment**
- TYPO3 version(s): 11.5.33
- news version: 11.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by georgringer** [comment]
wanna do a PR and just remove it?
