### ISSUE TITLE
Infinite scroll bug with tx_news pagination

### ISSUE THREAD

**Issue by wolfgang007** [georgringer/news#2310]
Hello guys, 

I set up the template like in documentation and the ajax load **works correctly** for the first click on the button, but on the second click there comes an error "GET url 404 not found".

The pagination without infinite scroll plugin works correctly.

https://docs.typo3.org/p/georgringer/news/10.0/en-us/Tutorials/BestPractice/InfiniteScroll/Index.html#templating

Any ideas? 

Thankful for every help.

**Environment**
- TYPO3 version: 11.5.33
- news version: 9.2.0

**Comment by froemken** [comment]
You have to configure `routeEnhancers` for news first like described here:

https://docs.typo3.org/p/georgringer/news/11.4/en-us/Tutorials/BestPractice/Routing/Index.html#common-routeenhancer-configurations

Infinite Scrolling needs a number as last part of the URL. Without configured `routeEnhancers` the last part of the URL is something like `chash=tcmh4859thc489th`. So, there is nothing to use as number to increase the page numbers.

IMO that information should be part of the documentation
