### ISSUE TITLE
ProxyClassRebuildCommand is not symfony/* 7.0 compatible

### ISSUE THREAD

**Issue by sfroemkenjw** [georgringer/news#2312]
## Bug Report

**Current Behavior**
I got following error:
```
Fatal error: Declaration of GeorgRinger\News\Command\ProxyClassRebuildCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/georgringer/news/Classes/Command/ProxyClassRebuildCommand.php on line 26
```

**Expected behavior/output**
No error message

**Environment**
- TYPO3 version(s): [12.4.10]
- news version: [e.g. 11.3.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

**Possible Solution**
- Do not support symfony/* packages 7.0
- Make `execute` compatible to new symfony version

**Comment by oliverklee** [comment]
In general, I'd recommend using explicit dependencies (e.g., on `symfony/console`) in the `composer.json` when the extension relies on components/packages instead of depending on transitive dependencies (which caused this problem).

**Comment by andreaskienast** [comment]
> In general, I'd recommend using explicit dependencies (e.g., on `symfony/console`) [...].

This, and tools like Rector would've identified this beforehand. The offending change is known since Symfony 5.x (no offense, tho).
