### ISSUE TITLE
Backend record list update button not working

### ISSUE THREAD

**Issue by ralfk33098** [georgringer/news#232]
I'm getting a js error when clicking the update button in administration module, please see image, this happens in version 5.3.1

best regards

Ralf

![listbug](https://cloud.githubusercontent.com/assets/25345404/22292031/b5c7e0a4-e309-11e6-82f1-a2838da39583.jpg)

**Comment by georgringer** [comment]
can you test latest master?

**Comment by georgringer** [comment]
closed as no response
