### ISSUE TITLE
News Content Element view: "unused elements" in translated news records

### ISSUE THREAD

**Issue by SeBigBoss** [georgringer/news#2339]
## Bug Report

**Current Behavior**
* I've news records, base language is DE, translated (connected mode) to EN
* I've installed "news_content_elements"
* When I view a news record via the "Link to page module" Button, at the DE record everything is OK
* When I make this view for the translated EN record, I get all the EN elements doubled at the bottom of the page in an "unknown" column and get the usual TYPO3 warning:

![image](https://github.com/georgringer/news/assets/33515558/9ab2cc21-4704-4817-8c0e-fa15686b46a7)

**Expected behavior/output**
The doubled view of the related content elements should disappear.

**Environment**
- TYPO3 version(s): 11.5.33
- news version: 11.3.0
- news_content_elements version: 1.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: 	Linux 5.10.0-26-amd64

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
can' reproduce that on latest versions, therefore closing issue
