### ISSUE TITLE
Symfony issue with PHP 8.2

### ISSUE THREAD

**Issue by emileblume** [georgringer/news#2340]
## Bug Report

**Current Behaviour**
Updating my TYPO3 12 installation to the latest version results in an error:
`Fatal error: Declaration of GeorgRinger\News\Command\ProxyClassRebuildCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /vhosts/xxx/vendor/georgringer/news/Classes/Command/ProxyClassRebuildCommand.php on line
26`

**Expected behaviour/output**
The default TYPO3 backend login page

**Environment**
- TYPO3 version(s): 12.4.10
- news version: 11.3.0
- symfony: 7.0.2
- Is your TYPO3 installation set up with Composer (Composer Mode): Yes
- OS: OS X 14.2.1

**Possible Solution**
Make the InputInterface & OutputInterface compatible with the Symfony Command
`protected function execute(InputInterface $input, OutputInterface $output)`
should be:
`protected function execute(InputInterface $input, OutputInterface $output): int`

**Comment by emileblume** [comment]
Reference: https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/Console/Command/Command.php

**Comment by georgringer** [comment]
already fixed in upstream. plan to do an update until monday

**Comment by PeterProell** [comment]
And there it is again ..... This time with:

- TYPO3 12.4.10
- news 11.3.0
- Symfony: 7.0.3
- composer mode yes

**Comment by cehret** [comment]
> And there it is again ..... This time with:
> 
> * TYPO3 12.4.10
> * news 11.3.0
> * Symfony: 7.0.3
> * composer mode yes
> * PHP 8.2

Should be fixed with: https://github.com/georgringer/news/commit/990150d7dc2d4de6835717e6777390364ae4f22e 

(I added :int in my installation and it works)

**Comment by PeterProell** [comment]
Thanks Christian! Me dummy not req dev-main ..... :/
