### ISSUE TITLE
RSS feed not working in version 11

### ISSUE THREAD

**Issue by emileblume** [georgringer/news#2346]
## Bug Report

**Current Behaviour**
The page that should show the XML-feed (/rss.xml) stays empty

**Expected behaviour/output**
The RSS feed should show

**Environment**
- TYPO3 version(s): 11.5.33 / 11.5.34
- news version: 11.2.0 / 11.3.0
- PHP 7.4 / 8.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Sonoma 14.3

**Possible Solution**

**Additional context**
When I downgrade news to version 10.0.3 the RSS feed re-appears

**Comment by emileblume** [comment]
@marvinm96 Thanks for the pointer. Completely forgot about this change. I managed to restore my feeds by calling the new plugin in a slightly different way though. Would be good if the documentation for this was updated

**Comment by georgringer** [comment]
but is fine in the docs, https://docs.typo3.org/p/georgringer/news/11.3/en-us/Tutorials/BestPractice/Rss/Index.html#automatic-rss-feeds-based-on-plugins isnt it?

**Comment by emileblume** [comment]
@georgringer Based on the suggestion from @marvinm96 it should be but for me this isn't working. I will keep using my solution

**Comment by georgringer** [comment]
closing as works for me and haven't found what could be wrong
