### ISSUE TITLE
News v11.3.0 search results: empty 2nd page [pagination]

### ISSUE THREAD

**Issue by wolfgang007** [georgringer/news#2347]
**Current Behavior**
Hi guys, the pagination for list view works great. But on search results the 2nd, 3rd,.. page is empty. 

Any ideas? or is this a bug?

Thx for help.

**Environment**
- TYPO3 version(s): 11.5.34
- news version: 11.3.0

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
If you use the bootstrap templates, just overwrite the SearchForm template and add method="get" to the form:

`<n:searchForm class="news-search-form" object="{search}" name="search" pageUid="{settings.listPid}" method="get">`

See https://github.com/georgringer/news/issues/2486

**Comment by georgringer** [comment]
fixed in the meantime

**Comment by georgringer** [comment]
<img width="516" alt="Bildschirmfoto 2024-11-13 um 20 52 38" src="https://github.com/user-attachments/assets/958483bd-7aee-4e75-beaf-3c0f34c05eaa">
yes works here

**Comment by wolfgang007** [comment]
Thx @georgringer now it works. 

addQueryString = untrusted did the job :-)

Is it good or bad to add "tx_news_pi1[search][subject]" to "[FE][cacheHash][excludedParameters]"?

**Comment by georgringer** [comment]
this is good
