### ISSUE TITLE
PluginUpdater.php fails with data lost for plugin that extends news

### ISSUE THREAD

**Issue by specialistaweb** [georgringer/news#2353]
Hi thank yo for your work, 
I suppose the problem is linked to your file:

Classes/Updates/PluginUpdater.php

as I can see there are some lines that modify the pi_flexform DATA existing  into the tabel tt_content

To be more precise it shoul be  the following code:

            // Clean up flexform
            $newFlexform = $this->flexFormTools->cleanFlexFormXML('tt_content', 'pi_flexform', $record);
            $flexFormData = GeneralUtility::xml2array($newFlexform);
            // Remove flexform data which do not exist in flexform of new plugin
            foreach ($flexFormData['data'] as $sheetKey => $sheetData) {
                // Remove empty sheets
                if (!count($flexFormData['data'][$sheetKey]['lDEF']) > 0) {
                    unset($flexFormData['data'][$sheetKey]);
                }
            }

This should happen wth all plugins that extendes news system.

In my case, migrating from v.10.x  to v11.3 all the DATA of my extension NewsStylist was deleted,

Please investigate to avoid  data lost.

**Comment by georgringer** [comment]
wanna do a PR?

**Comment by specialistaweb** [comment]
Forgive me, what is a PR?!?

   Alessandro Tuveri
   cell. +39 379 2306014
     _________________________________________________________________

   http://www.specialistaweb.it 
   Realizzazione e gestione di siti web di qualità, dinamici e professionali; portali per aziende, e-commerce, qualsiasi interazione; marketing e gestione social
   Giulia Tuveri - cell. +39 339 711 5662
   Da "Georg Ringer" ***@***.***
   A "georgringer/news" ***@***.***
   Cc "Alessandro Tuveri" ***@***.***,"Author" ***@***.***
   Data Sun, 11 Feb 2024 22:19:50 -0800
   Oggetto Re: [georgringer/news] PluginUpdater.php fails with data lost for plugin that extends news (Issue #2353)

   wanna do a PR?

**Comment by georgringer** [comment]
sorry no I mean "pull request"

**Comment by specialistaweb** [comment]
sorry, I can't pull a request

thank you, I'm not a great programmer, but I think that best way to resolve this problem, should be to use an utility to analyze the  field " pi_flexform" within tt_content then extract extra content respect the flexForm definition for news system and keep it doing a merge at the end of process. This is very hard, in my opinion. because I can't do this with an Updater running from my extension.
Another way is to avoid to use the Upgrade, better do not run the Updater.php and modify manually (tell me if I'm wrong) the plugin typo3 under General menu. 
If I forced to modify manually each plugin, maybe this is very annoying.
I suggest you, if you cannot modify the Update,php /(don't kwon if it is possibile) to push a flash message just launched the Updater to inform that the extracontent will be lost and two option: "Continue" or "exit"

**Comment by specialistaweb** [comment]
ok maybe the error is not linked to your Updater. I should inspect better. Please close this issue

**Comment by specialistaweb** [comment]
closed
