### ISSUE TITLE
Backend _savedokview button in preview workspase not working

### ISSUE THREAD

**Issue by alexjamp** [georgringer/news#237]
Hi Georg,

backend _savedokview button in preview workspase not working.

TYPO3: 7.6.14
News: 5.3.1
URL: 
typo3/index.php?M=web_WorkspacesWorkspaces&moduleToken=93a3cbdc0af349ceae0382549f9bba7c187dc373&tx_workspaces_web_workspacesworkspaces[action]=index&tx_workspaces_web_workspacesworkspaces[controller]=Preview&id=21&no_cache=1&tx_news_pi1[news_preview]=16&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail

Error: Fatal error: Uncaught TYPO3\CMS\Extbase\Mvc\Exception\NoSuchArgumentException: An argument "news" does not exist for this request. in /html/typo3/typo3_src-7.6.14/typo3/sysext/extbase/Classes/Mvc/Request.php:459 Stack trace: #0 /html/typo3/typo3temp/Cache/Code/news/tx_news_controller_newscontroller.php(563): TYPO3\CMS\Extbase\Mvc\Request->getArgument('news') #1 /html/typo3/typo3temp/Cache/Code/news/tx_news_controller_newscontroller.php(264): GeorgRinger\News\Controller\NewsController->handleNoNewsFoundError(Array) #2 [internal function]: GeorgRinger\News\Controller\NewsController->detailAction(NULL, 1) #3 /html/typo3/typo3_src-7.6.14/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(283): call_user_func_array(Array, Array) #4 /html/typo3/typo3_src-7.6.14/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(176): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod() #5 /html/typo3/typo3conf/ext/news/Classes/Controller/NewsBaseController.php(51): TYPO3\CMS\Extbase\Mvc\Controller\Ac in /html/typo3/typo3_src-7.6.14/typo3/sysext/extbase/Classes/Mvc/Request.php on line 459

**The same news in live workspace works but!**
URL; /index.php?id=21&no_cache=1&tx_news_pi1[news_preview]=6&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail

best regards
Alex

**Comment by georgringer** [comment]
IMO solved
