### ISSUE TITLE
Roadmap for `ext:news` in TYPO3 v13

### ISSUE THREAD

**Issue by ohader** [georgringer/news#2375]
Cheers from the TYPO3 SurfCamp 🏄 😃 
We most probably want to use `ext:news` in combination with TYPO3 v13, and also might help to make the extension compatible for the next mayor version.

Is there anything we should focus on in particular or be aware of? Otherwise we'd just go ahead, and focus on a way to have `ext:news` working in a hybrid way for TYPO3 v12 and TYPO3 v13. Fine?

**Comment by georgringer** [comment]
sorry for the late response and not being ready for v13. 
if you wanna give it a shot, feel free and make it compatible for v12+v13 - that would be awesome - I plan to concentrate after v13.1 is released!

**Comment by georgringer** [comment]
branch `12-13` is now being worked on ;)
