### ISSUE TITLE
Optimize backend-plugin-preview for small columns

### ISSUE THREAD

**Issue by stephangrass** [georgringer/news#241]
Hi,
the plugin-preview will "destroy" the layout of the backend-grids when using small columns:
![screenshot_2559](https://cloud.githubusercontent.com/assets/4489147/22473468/53e1eaa4-e7d9-11e6-888c-fbe5915467c8.png)

It would be nice, if this can be optimised.

**Comment by georgringer** [comment]
<img width="1027" alt="bildschirmfoto 2017-01-31 um 19 43 05" src="https://cloud.githubusercontent.com/assets/1905663/22479300/89798f28-e7ed-11e6-9647-6450f09bfd4a.png">

this is how it will look like in future
