### ISSUE TITLE
news and realurl 2.1.3 or higher

### ISSUE THREAD

**Issue by chequille** [georgringer/news#242]
Hi All,
wanted to share with you the following problem and maybe ask if somebody knows the solution for it.

Wanted to update Typo to 7.6.15 today and did as well some other updates like the realurl one to 2.1.5.
First everyything seems to be ok, but than I saw, that the date and the more link from my news is displayed not in German as it was before, but in english.
I found, that this is not the problem from tx-News but from RealUrl. It happens when RealURL 2.1.3 or higher is installed. Lower versions does not show this problem.

Does somebody know what must be changed in the real_url config file to make it working again.

Best regrds,
Jürgen

**Comment by chequille** [comment]
Wondering why nobody shares this problem!!

Or do all others have a correct realurl config which maybe can be shared?

Regards,
Jürgen

**Comment by georgringer** [comment]
There is nothing I can IMO do there. If the problem still exists, debug the TSFE->language varible
