### ISSUE TITLE
Error viewing history after changing 'Template Layout'

### ISSUE THREAD

**Issue by PeGuIwelt** [georgringer/news#2459]
## Bug Report

**Current Behavior**
I added an option to tx_news.templateLayouts as described in https://docs.typo3.org/p/georgringer/news/main/en-us/Reference/TsConfig/General.html#tsconfigTemplateLayouts:
```
tx_news {
	templateLayouts {
		1 = LatestArticles
	}
}
```
After saving a page object of type 'news article list' with a changed value in 'Plugin > Template > Template Layout' the history of the object cannot be viewed, the following error is displayed:
> GeorgRinger\News\Hooks\ItemsProcFunc::getPageId(): Return value must be of type int, null returned

**Environment**
- TYPO3 version: 12.4.14
- news version: 11.4.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by froemken** [comment]
I had the same issue. On main branch it was already fixed with:

https://github.com/georgringer/news/commit/4c41691f9289bfd8a4ba2f07bafe6c4672ecaf84

**Comment by PeGuIwelt** [comment]
I can confirm that https://github.com/georgringer/news/commit/4c41691f9289bfd8a4ba2f07bafe6c4672ecaf84 fixes my problem, thx.
