### ISSUE TITLE
TYPO3 Exception in BE: BackendUtility::wrapClickMenuOnIcon(): Argument #5 ($row) must be of type array, string given

### ISSUE THREAD

**Issue by mark-kirstein** [georgringer/news#2476]
## Bug Report
After configuring Plugin for Listview, an error occurs in Page module:
TYPO3\CMS\Backend\Utility\BackendUtility::wrapClickMenuOnIcon(): Argument #5 ($row) must be of type array, string given, called in /var/www/html/vendor/georgringer/news/Classes/Hooks/PluginPreviewRenderer.php on line 219

**Current Behavior**
Displaying Error.

**Expected behavior/output**
Seeing be preview without Error.

**Environment**
- TYPO3 12.4.15
- news version: 11.4.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian Linux 11

**Additional context**
Does not appear if detailview plugin is choosen.

**Comment by Finulin** [comment]
I can confirm

**Comment by hannesbochmann** [comment]
Can confirm, too. A new release with a fix would be awesome.

**Comment by criwe** [comment]
Can confirm the error and @christophlehmann´s patch works like charm :-)
