### ISSUE TITLE
Backend Error with TYPO3 12.4.15 LTS

### ISSUE THREAD

**Issue by mentis-webdesign** [georgringer/news#2479]
## Bug Report

**Current Behavior**
there is an error after installing latest security update 12.4.15 in Backend Module Site on sites with News Plugin article list:
TYPO3\CMS\Backend\Utility\BackendUtility::wrapClickMenuOnIcon(): Argument #5 ($row) must be of type array, string given, called in /html/typo3/typo3conf/ext/news/Classes/Hooks/PluginPreviewRenderer.php on line

**Environment**
- TYPO3 version: 12.4.15
- news version: 11.4.1

**Comment by georgringer** [comment]
fixed with https://github.com/georgringer/news/issues/2476, release on its way
