### ISSUE TITLE
Category list : ArgumentsViewHelper using GeneralUtility::intExplode with null value

### ISSUE THREAD

**Issue by geoffroycochard** [georgringer/news#2485]
## Bug Report

**Current Behavior**
When no override demand to print category list ArgumentsViewHelper pass a null value to GeneralUtility::intExplode

**Expected behavior/output**
Print as usual category list

**Environment**
- TYPO3 version(s):12.4.15
- news version: 11.4.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: [OSX 10.13.4]
- php version : 8.2.18

**Possible Solution**
Check value before
```php
$categoryList = GeneralUtility::intExplode(',', $arguments['list'] ?: '', true);
```

**Patch**
[ArgumentsViewHelper-issue-2485.patch](https://github.com/georgringer/news/files/15490321/ArgumentsViewHelper-issue-2485.patch)

**Comment by geoffroycochard** [comment]
ref from core : https://review.typo3.org/c/Packages/TYPO3.CMS/+/74599

**Comment by georgringer** [comment]
fixed in main
