### ISSUE TITLE
Not nullable setter for endtime

### ISSUE THREAD

**Issue by runner78** [georgringer/news#2487]
## Bug Report
The setter of the property "endtime" in the News Model has the non-nullable type "Datetime"

**Environment**
- news version: [11.4.2]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

**Possible Solution**
No type for the parameter or make it nullable.

**Comment by georgringer** [comment]
wanna make it nullable?

**Comment by runner78** [comment]
If you create/edit news in your own extension, this can lead to problems, because you can no longer delete endtime once it has been set, or in my case the field is sent as null and an exception is thrown during mapping.
It is also inconsistent with the other setters because other date fields do not have a typed setter and the setter does not correspond to the actual nullable property.
I would suggest either making all setters without types or all with the correct type.

**Comment by keessonnema** [comment]
+1. Running into the same issue as @runner78 when extending news models. 
It would be very helpful if endtime was nullable.

**Comment by georgringer** [comment]
be aware that extbase can handle null datetime values in setters only since 13.2, see https://review.typo3.org/c/Packages/TYPO3.CMS/+/83839
