### ISSUE TITLE
News Category menu and bootstrap V5

### ISSUE THREAD

**Issue by Torsie** [georgringer/news#2488]
## Bug Report

**Current Behavior**
I had an runnig page with news category menu in the left column and a news article list in the normal column. As template, I use modified bootstrap V5 templates from the news extension folder, which where adjusted to use fontawsome icons.
Upto now this working completly fine. 
But:
With the latest update of typo3 from 12.4.13 to 12.4.15 and news from 11.4.1 to 11.4.2, I get a 503 error on this page.
Clearing cache and maintenance work, deinstlling and installing news and bootstrap all did not change anything

I alway get: 503 and in the log or debug it states:  Core: Exception handler (WEB): Uncaught TYPO3 Exception: explode(): Argument #2 ($string) must be of type string, null given | TypeError thrown in file /www/htdocs/..(snip)../vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php in line 874. Requested URL: https://...(snip).../news-und-infos

The templates are and were included via typoscript constants as template, partial and layout root path via plugin.tx_news. view

I tried different aproaches to nail down the source and find the reson for the error. Howver it seems completely random to me.

- Standard (no bootstrap) templates coming with the news extension are working
- Bootstrap templates coming with the news extension are NOT working
- My modified bootstrap templates are NOT working
- if I deactivate the news category menu on the page everything works, standard news template, news bootstrap, my modfied templates
- if I delete my list.html under styles/twb5/templates/category/ and leave the directory empty or place the standard list.html from the new extension /news/templates/category/ there, it works if both news article list and news category menu are activated
- even more funny, if I navigate now to a filtered selection of my news records and change the list.html to the bootstrap version or to my modified version, everything works. But if I call the page from the site menue: Bam 503 error with the above exeption.

Sorry for the kind of chaotic description, but the behavior seems so random to me, that I have no clue which information would be essential or missing.

 
**Expected behavior/output**

A page containing news category menu in the left column and a news article list in the normal column should be rendered properly with bootstrap V5 based templates.

**Environment**
- TYPO3 version(s): 12.4.15
- news version: 11.4.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: unix-server
- php: 8.3.7

Thanks for your assistance and the effort you put into the news extension.

**Comment by bh-teufels** [comment]
have the same Error with news List + category menu on

TYPO3 12.4.15
news 11.4.2
Bootstrap 5
PHP 8.2.19

working with 11.4.1

**Comment by bh-teufels** [comment]
but this solution has problem https://github.com/georgringer/news/issues/2479

**Comment by Torsie** [comment]
Just as out of the box thught, i chcked if the issue is connected to route enhancers. My rout enhancer looks as follows:
routeEnhancers:
  News:
    type: Extbase
    limitToPages:
      - 158
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    aspects:
      news-title:
        type: NewsTitle
  Sitemap:
    type: Simple
    routePath: 'sitemap/{sitemap}'
    aspects:
      sitemap:
        type: StaticValueMapper
        map:
          pages: pages
          news: news
But removing does not sho any effect. The situation stays the same. It seems to be connected exclusive to existing or missing extension of the URL by news params http://domain/page**?tx_news_pi1[overwriteDemand][categories]=4&cHash=**....

**Comment by bh-teufels** [comment]
seems to related only on news list plugin 
me having new list on "Home" and news list + category menu on "News" both sites get Error 
```
503
Oops, an error occurred!
TYPO3\CMS\Backend\Utility\BackendUtility::wrapClickMenuOnIcon(): Argument #5 ($row) must be of type array, string given, called in vendor/georgringer/news/Classes/Hooks/PluginPreviewRenderer.php on line 219
```
on Backend Page view of the two sites

**Comment by Torsie** [comment]
I am working currently with a combination of bootstrap V5 and standard templates. I combined these in my own site-extension. For the news category menu, I use the standard list.html template from the news extension. For news details and for the news article list, I use a modified version of the bootstrap V5 templates.
Obviously, it doesn't look pretty with the text based category selection. However, at least it works.

**Comment by DrDBanner** [comment]
Same here. 

**Just an observation:**

If I put into News > Templates > Styles > Twb5 > Templates > News > List.html

```
<f:section name="content">
	<f:debug>{categories}</f:debug>
```
I get only one category (uid=1 with parentcategory id=14) listed when on page with pid=6. 

```
Extbase Variable Dump
TYPO3\CMS\Extbase\Persistence\Generic\QueryResultprototypeobject (1 items)
   0 => GeorgRinger\News\Domain\Model\Categoryprototypepersistent entity (uid=1, pid=13)
```

On a different page with pid=15 I get category (uid=5 with parentcategory id=15)

I'd expect rather 16 categories listed or none. But I get one. All my categories are stored on pid=13.

**Comment by DrDBanner** [comment]
A very hacky and temporary solution is to replace line 874:881 of cms-core/Classes/Utility/GeneralUtility.php

from originally
```
$result = explode($delimiter, $string);
        foreach ($result as $key => &$value) {
            if ($removeEmptyValues && trim($value) === '') {
                unset($result[$key]);
            } else {
                $value = (int)$value;
            }
        }
```

to

```
if (is_string($string) && $string !== '') {
            $result = array_filter(array_map('trim', explode($delimiter, $string)), function ($value) use ($removeEmptyValues) {
                return !$removeEmptyValues || $value !== '';
            });
            $result = array_map('intval', $result);
        } else {
            $result = [];
        }
```
That way the category menu gets rendered as expected. At least in my environment.
 
perhaps someone with much more knowledge can verify and create a proper PR with better code @georgringer ?

**Comment by DrDBanner** [comment]
Turns out this has follow-up implications. 

```
Core: Error handler (FE): PHP Warning: Undefined array key 0 in /usr/local/www/apache24/noexec/foo/bar/vendor/typo3/cms-frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php line 988
```
So, better do not change the core code and wait until someone with profound knowledge of the core and ext_news can put out a fix.

**Comment by worldwideweber** [comment]
Seems the current release 11.4.2 is missing this fix. https://github.com/georgringer/news/commit/8f2f7778743eae45af2007a53afb80c88ae70d16
since i have applied this fix and upgraded to 11.4.2 list and category filter works.

**Comment by Torsie** [comment]
I just tested the bugfix and modified the ../news/Classes/ViewHelpers/MultiCategoryLink/ArgumentsViewHelper.php in accordance with the fix 8f2f777 by exchanging the corresponding line.
And what should I say. It works. Bootstrap style category is back at work.
I am aware that this fiy will be gone as soon as I do an update.

**Comment by Torsie** [comment]
Will the fix 8f2f777 be included in the next version?

**Comment by georgringer** [comment]
sure, it is already inclded

**Comment by bh-teufels** [comment]
it is included in main branch but not versioned yet.
latest version ist still 11.4.2. 
can you already see when the new version will be released

**Comment by vnc-jboe** [comment]
@georgringer 
This bug still exists in powermail 12.4.1. 

When will the bugfix be released as it is already done in July?

**Comment by wakoch** [comment]
Yes, still the newest version is 11.4.2 without the fix.
