### ISSUE TITLE
Http error 503 after selecting a page with list of news items

### ISSUE THREAD

**Issue by wimr0001** [georgringer/news#2489]
## Bug Report

**Current Behavior**
TYPO3\CMS\Backend\Utility\BackendUtility::wrapClickMenuOnIcon(): Argument #5 ($row) must be of type array, string given, called in /home/ikonenmu/public_html/typo3conf/ext/news/Classes/Hooks/PluginPreviewRenderer.php on line 225

**Expected behavior/output**
Showing the content elements of the page

**Environment**
- TYPO3 version(s): 12.4.15
- news version: 11.4.1
- Is your TYPO3 installation set up with Composer (Composer Mode): NO
- OS: Debian

**Possible Solution**
On line 224 of the PluginPreviewRenderer.php I changed the '' to []
Problem solved

**Additional context**
Add any other context about the problem here

**Comment by Gentoo2k11** [comment]
I had the same problem. Updating the News Package to 11.4.2 fixed it for me.
