### ISSUE TITLE
Randomly getting the message "No news available" 

### ISSUE THREAD

**Issue by LiNgOtT** [georgringer/news#249]
TYPO3 v7.6.15
News 5.3.1

From time to time we are getting the message "No news available" instead of the
list of all available news. We are not able to reproduce it. I happens randomly.

In our configuration we are using Memcache which could be the origin of the issue, because
without Memcache we don't have this issue.

Are any issues known regarding the reported behavior?

**Comment by georgringer** [comment]
please test with 5.3.2

**Comment by LiNgOtT** [comment]
I have updated to 5.3.2 but the issue still exists.

**Comment by LiNgOtT** [comment]
@georgringer : Did you have a minute to check the issue so that we can plan how to proceed with the issue?

**Comment by georgringer** [comment]
i haven't had this issue but also don't have currently any setting with memcache. maybe exclude the news cache from memcache?

**Comment by georgringer** [comment]
Closing because no feedback. Feel free to reopen if still valid
