### ISSUE TITLE
Performance issue in paginator with over 230.000 news records

### ISSUE THREAD

**Issue by froemken** [georgringer/news#2490]
## Bug Report

**Current Behavior**
Currently, the list view slows down ~600 milliseconds, because of a COUNT query which can not use index. The COUNT query was executed by paginator section in `listAction`, although paginator is disabled in news plugin.

**Expected behavior/output**
If I deactivate pagination in news plugin I expect that no paginator related queries will be executed.

**Environment**
- TYPO3 version(s): [e.g. 10.4]
- news version: [e.g. 10.0.3]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]
- OS: [Linux. IMO CentOS]

**Possible Solution**
Wrap the paginator section in listAction into a condition asking against settings.hidePagination

**Additional context**
The problem increases as more records you have in news table.

**Comment by georgringer** [comment]
wanna do a PR? ;)
