### ISSUE TITLE
News administration module not shown in v12

### ISSUE THREAD

**Issue by sgrossberndt** [georgringer/news#2504]
## Bug Report

**Current Behavior**
Although `showAdministrationModule = 1` is set, the news administration module is not visible in the backend menu in TYPO3 v12.

**Expected behavior/output**
The news administration module is visible in the backend menu in TYPO3 v12.

**Environment**
- TYPO3 version(s): 12.4.17
- news version: 11.4.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian 12

**Possible Solution**
The module is registered in https://github.com/georgringer/news/blob/main/ext_tables.php#L54 using the method `\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerModule()`, but this method is empty in TYPO3 v12:

https://git.typo3.org/typo3/typo3/-/blob/12.4/typo3/sysext/extbase/Classes/Utility/ExtensionUtility.php?ref_type=heads#L171

```php
    /**
     * To allow extension authors to support multiple versions, this method is kept until
     * TYPO3 v13, but is no longer used nor evaluated from TYPO3 v12.0. To register modules,
     * place the configuration in your extensions' Configuration/Backend/Modules.php file.
     *
     * The method deliberately does not throw a deprecation warning in order to keep the noise
     * of deprecation warnings small.
     *
     * @deprecated The functionality has been removed in v12. The method will be removed in TYPO3 v13.
     */
    public static function registerModule($extensionName, $mainModuleName = '', $subModuleName = '', $position = '', array $controllerActions = [], array $moduleConfiguration = []) {}
```

As mentioned in the PHPDoc the registration has to happen in `EXT:news/Configuration/Backend/Modules.php` for TYPO3 >=v12

**Additional context**
The shown module will not contain the actual news administration but the hint to get EXT:news_administration instead: https://github.com/georgringer/news/blob/main/Resources/Private/Templates/Administration/Index.html but as this module is not shown this far from obvious currently.

**Comment by georgringer** [comment]
IMO solved in the 11-12 branch which will be merged soon
