### ISSUE TITLE
Make flexform settings exclude for detailed backend permissions

### ISSUE THREAD

**Issue by jonakieling** [georgringer/news#2506]
## Feature Request

Right now it is not possible to adjust backend permissions within the flexform settings of the plugins.

Is there a downside of adding exclude=1 to the flexform settings?

Happy to open a PR for this.

**Comment by georgringer** [comment]
yes, downside is that you need to check every setting manually for editors to allow settings. the usecase is kind of rare that editors are allowed to use the plugin but not allowed to set special settings. especially now with a flexform per type, it makes even less sense. what do you think?

I would only accept a PR if this would use kind of a hook and add the `exclude` dynamically

**Comment by jonakieling** [comment]
Ah, that is a good point. It rarely is needed for us, too.

We stick with hiding the fields via PageTS.
