### ISSUE TITLE
og:image not rendered in detail view

### ISSUE THREAD

**Issue by peterkraume** [georgringer/news#2509]
## Bug Report

**Current Behavior**
`og:image` is not rendered in detail view if `showinpreview` is set to 0 (Show only in detail views).

**Expected behavior/output**
`og:image` is always rendered if there is at least one image attached to a news record.

**Environment**
- TYPO3 version(s): 12.4.17
- news version: 11.4.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**
In `Resources/Private/Partials/Detail/Opengraph.html` there is a check for `{newsItem.firstPreview}` to render the `og:image`.

`{newsItem.firstPreview}` is set by `getMediaPreviews()` from `Classes/Domain/Model/News.php`.

But this method takes only images into account that have `showinpreview` 1 or 2 (which is "show in all views" and "show only in list views").

To fix this, I change the Fluid condition to `{newsItem.falMedia}` and if media exists, I use `{newsItem.falMedia.0.uid}` as image src instead.

I will provide a patch for this bug.

**Comment by georgringer** [comment]
I suggest checking for 1st preview and if that fails, check for any other media. benefits:
- no change in behavior
- 1st image might not be a preview image
