### ISSUE TITLE
Typo 13.2.1 "news  dev-12-13 search form

### ISSUE THREAD

**Issue by gmt-it** [georgringer/news#2513]
## Bug Report

**Current Behavior**
Crash when displaying the search form (Oops, an error occurred! Request: f0e5e92b764b4)

**Expected behavior/output**
The search form should be displayed

**Environment**13.2.1
- news version: dev-12-13
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS:  Windows 10]

[typo3_11f96f4e3a.log](https://github.com/user-attachments/files/16478617/typo3_11f96f4e3a.log)
**Additional context**

**Comment by georgringer** [comment]
works now, correct?

**Comment by gmt-it** [comment]
Yes. Thanks!
