### ISSUE TITLE
[FEATURE] Extend Live Search result to include more information

### ISSUE THREAD

**Issue by tkowtsch** [georgringer/news#2522]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Having multiple articles with similar titles makes that Editors that use the Live Search in Backend cry.

See sample screenshot:
![image](https://github.com/user-attachments/assets/90eeacf4-728b-4f4f-9e1f-7ba09ccd0812)
News records are used as Event... and the Editor needs to guess which of these records is the one that is to be updated. 

**Describe the solution you'd like**
Preview should include some more information. Minimum is to have date and time shown. Depending on the runtime, also a list of attached media could be shown. 

**Describe alternatives you've considered**
Alternative solution 1): use the List module, find the storage, sort records by date and click through the list until the record is found. 
Alternative solution 2): use the live search and open with trial & error: pick a record, check the date, if it's the wrong one open Live Search and select another record...

**Teachability, Documentation, Adoption, Migration Strategy**
This would be self-explaining as no new field or function is added. It's just to display some more Information.

**Comment by georgringer** [comment]
hey.

wanna maybe checkout https://github.com/studiomitte/live-search-extended as an idea?
