### ISSUE TITLE
extension shariff inside news produces big log files with errors

### ISSUE THREAD

**Issue by daUhradone** [georgringer/news#2528]
news: 11.4.2
PHP: 8.3
TYPO3 12.4.20

This is my Shariff.html Parial/Detail:

```
<div xmlns:rx="http://typo3.org/ns/Reelworx/RxShariff/ViewHelper">
    <rx:shariff services="linkedin,xing,twitter" enableBackend="true" />
</div>
```

Every time a user clicks on a shariff social media button an error is written in the log file: var/log/typo3_shariff_scexxxxxxx.log:

```
Wed, 18 Sep 2024 19:03:08 +0200 [WARNING] request="383ac3225d097" component="Reelworx.RxShariff.Shariff": Client error: `GET https://www.reddit.com/api/info.json?url=https%3A%2F%2Fwww.albdental.de%2F` resulted in a `403 Blocked` response:
<body class=theme-beta><div><style>.theme-light,:root{--rem360:22.5rem;--rem320:20rem;--rem192:12rem;--rem144:9rem;--rem (truncated...)
- ClientException: Client error: `GET https://www.reddit.com/api/info.json?url=https%3A%2F%2Fwww.albdental.de%2F` resulted in a `403 Blocked` response:
<body class=theme-beta><div><style>.theme-light,:root{--rem360:22.5rem;--rem320:20rem;--rem192:12rem;--rem144:9rem;--rem (truncated...)
, in file /html/typo3-12/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111 - {"exception":"GuzzleHttp\\Exception\\ClientException: Client error: `GET https://www.reddit.com/api/info.json?url=https%3A%2F%2Fwww.albdental.de%2F` resulted in a `403 Blocked` response:\n<body class=theme-beta><div><style>.theme-light,:root{--rem360:22.5rem;--rem320:20rem;--rem192:12rem;--rem144:9rem;--rem (truncated...)\n in
...
```

reddit is not active but it looks like it produces an error anyway.

At the footer of my normal page shariff set with a viewhelper is not producing any errors:

` <f:render partial="Shariff" />`

**Comment by georgringer** [comment]
@liayn something for you? 

closing issue as not related to news

**Comment by liayn** [comment]
@daUhradone This is not generated upon clicking an icon, but whenever a news record is rendered.
You have enabled "the backend" (`enableBackend="true"`), hence it tries to fetch sharing counts from the various providers. Reddit obviously blocks this.
So, either change this to `0` (or remove the attribute) or reconfigure shariff in the extension settings (Install Tool) and only enable the services you really want.

**Comment by daUhradone** [comment]
Thank you! Found the settings in Admin Tools settings to take Reddit out. Before I adjusted the social media platforms only in the news Parial for shariff.
But didn't find where I should find the 'enableBackend= "true"'? Is this a general setting, a news setting or a shariff setting? And where is it defined?

**Comment by liayn** [comment]
You have it in your Fluid template, as posted above:

```html
<div xmlns:rx="http://typo3.org/ns/Reelworx/RxShariff/ViewHelper">
    <rx:shariff services="linkedin,xing,twitter" enableBackend="true" />
</div>
```

You can define per shariff-usage whether it should contact the shariff-backend and ask for stats or not.
