### ISSUE TITLE
List Plugin: Selecting a translated sysfolder as a startingpoint leads to no items being available

### ISSUE THREAD

**Issue by derMatze82** [georgringer/news#2533]
## Bug Report

**Current Behavior**
Choosing a translated sysfolder as a startingpoint leads to no items being available, although translated articles are available

**Expected behavior/output**
The translated news should be shown

**Environment**
- TYPO3 version(s): 12.4.20
- news version: 11.4.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

In the LinkBrowser, Typo3 offers to select the page/SysFolder in a specific language. Is it intentional or a bug that when a translated SysFolder is selected as the startingpoint, the news contained therein are not displayed?

**Comment by georgringer** [comment]
confirmed. this is a core issue, see https://forge.typo3.org/issues/105547

closing it here
