### ISSUE TITLE
Installed News v12.0.0 and Getting error in News Administration backend module

### ISSUE THREAD

**Issue by HimanshuRamavat07** [georgringer/news#2534]
## Bug Report

**Current Behavior**
When I install a new version of the news extension compatible with TYPO3 V13.  
I am getting an error in the News backend module. like:

> Call to undefined method TYPO3\CMS\Backend\Template\ModuleTemplate::setContent()

**Expected behavior/output**
Should be display listing of blog

**Environment**
- TYPO3 version(s): 13.4.0
- news version: 12.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): Yes
- OS: MacOs

**Additional context**
I have attached a screenshot for you're reference:

![image](https://github.com/user-attachments/assets/49755ced-5403-4857-b728-637a3332c6b8)

**Comment by georgringer** [comment]
thanks, the news_administration extension will follow soon
