### ISSUE TITLE
Extended model broken if content elements are disabled

### ISSUE THREAD

**Issue by ghermens** [georgringer/news#2537]
After adding cusom fields to the news model and disabeling records.contentElementRelation in the extension configuration, the generated model in ~/var/cache/code/news/tx_news_domain_model_news.php does not provide a getter for $contentElements.
This causes an error in detail view:

```
#1546632293 RuntimeException
Could not get value of property "GeorgRinger\News\Domain\Model\NewsDefault::contentElements", make sure the property is either public or has a getter getContentElements(), a hasser hasContentElements() or an isser isContentElements().
in /var/www/sn-maschinenbau-2024/vendor/typo3/cms-extbase/Classes/Validation/Validator/AbstractGenericObjectValidator.php line 69
```
After reenabeling records.contentElementRelation and clearing Caches, everything works as expected.

**Environment**
- TYPO3 version: 12.4.22
- news version: 12.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian

**Comment by seirerman** [comment]
Can confirm after updating to TYPO3 12 and news 12. We've never used content elements in news records, but the error was gone after setting records.contentElementRelation=1. Unlike @ghermens we don't use custom news fields for that website.
