### ISSUE TITLE
Error in routing documentation

### ISSUE THREAD

**Issue by matthaa** [georgringer/news#2538]
## Bug Report

Hi,
in the routing documentation there is a small error in line 15: the indentation is not correct and if you copy paste the code a 503 error appears.
[https://docs.typo3.org/p/georgringer/news/12.0/en-us/Tutorials/BestPractice/Routing/Index.html#common-routeenhancer-configurations]
Matthias

**Comment by georgringer** [comment]
fixed just now, next time a PR would have fixed it way sooner, thx nevertheless for the issue!
