### ISSUE TITLE
News throws errors in TYPO3 13 if new TS-Object PAGEVIEW with PageContentFetchingProcessor is used 

### ISSUE THREAD

**Issue by kanow** [georgringer/news#2539]
## Bug Report

**Current Behavior**
I have an error (E_WARNING) in frontend on the news list view.

`Object of class TYPO3\CMS\Core\Collection\LazyRecordCollection could not be converted to int `

This happens because of the getDetailPidFromFlexform method in news LinkViewHelper.` $settings['detailPid']` is not the integer value from the flexform field of plugin but is `TYPO3\CMS\Core\Collection\LazyRecordCollection`. It doesn't matter whether I set a value for the `detailPid` or not.

Mmmh.. it seems to me that those error actually comes from here: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.3/Feature-103581-AutomaticallyTransformTCAFieldValuesForRecordObjects.html#des[…]ion

My colleague put me on the right track. In this LazyRecordColletions can be multiple values. Makes no sense for a detailPid. For the moment I use `$settings['detailPid']->offsetGet(1)` to get the first item/value if `$settings['detailPid']` is instanceof `TYPO3\CMS\Core\Collection\LazyRecordCollection`.

Issue exists due to the automatically processed flexform fields. `detailPid` is typed as group therefore the feature "Feature: #103581 - Automatically transform TCA field values for record objects" transform that setting to thet LazyRecordCollection. I'm not sure what is the best solution for this.

- set that flexformfield to input type? And just using a number for the pid?
- The record transformation should respect min/maxItems and if just one item it's not a collection?
- or something different?

The same problem is in detail template when backPid is set. `{settings.backPid}` in fluid template isn't working. Seems like a bigger issue.
**Expected behavior/output**
List view should be working. Detail page is shown with  backlink to the set page id in flexform.

**Environment**
- TYPO3 version(s): 13.4
- news version: 12.0
- Is your TYPO3 installation set up with Composer (Composer Mode):yes
- OS: local docker environment with apache

To reproduce the error it should be enough to use that new `PageContentFetchingProcessor` to render content (news plugin) on a page. I would say using that in `FLUIDTEMPLATE` the same issues should be there.

Probably there are another issues e.g. on using filter news list by categories. There are also `TYPO3\CMS\Core\Collection\LazyRecordCollection`'s instead of list of uids or category objects.

Ok, I checked filtering the news list by category(ies). In the old behaviour that setting was just a list of uid's and the new behaviour is that the setting for categories is an `LazyRecordCollection`. But that works like expected. With and without `LazyRecordCollection`.

**Comment by nhovratov** [comment]
Instead of changing the field to "input", you can try setting the new option `relationship` to `manyToOne`. See here: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.3/Feature-103581-AutomaticallyTransformTCAFieldValuesForRecordObjects.html#new-tca-option-relationship
