### ISSUE TITLE
tx_news.tagPid is not applied for news-edit -> web_list jumping

### ISSUE THREAD

**Issue by TobCube** [georgringer/news#254]
When setting the tagPid vis PageTS (tx_news.tagPid = 20), the tag overview icon in news-editing mode is still pointing to the web_list for page-id=1 (not tagPid)

![image](https://cloud.githubusercontent.com/assets/7976366/22796273/1e123ba4-eefa-11e6-9c1f-90f8cd0ea8cb.png)

**Comment by georgringer** [comment]
currently the pid is set globally by the configuration in the ExtensionManager. Is that already enough for you?

**Comment by TobCube** [comment]
OK thanks - it is fixed with the newest commit. :)
