### ISSUE TITLE
Type error in TypoScript Utility in TYPO3 13 on using the new record transformation

### ISSUE THREAD

**Issue by kanow** [georgringer/news#2541]
## Bug Report

**Current Behavior**
Sorry, I found the next bug in TYPO3 13 and using the new  PageContentFetchingProcessor with record transformation.

`strlen(): Argument #1 ($string) must be of type string, TYPO3\CMS\Core\Domain\RecordPropertyClosure given`

Error occurs in list view. I'm using the latest dev-main with the fix for #2539 from [PR-2540](https://github.com/georgringer/news/pull/2540).

The problem is in in lin 38 of `Classes/Utility/TypoScript.php`.

`$base[$fieldName]` is not a string in this case. It's a `TYPO3\CMS\Core\Domain\RecordPropertyClosure` 

**Expected behavior/output**
List viewl should be visible in frontend

**Environment**
- TYPO3 version(s): 13.4
- news version: 12.0
- Is your TYPO3 installation set up with Composer (Composer Mode):yes
- OS: local docker environment with apache

**Possible Solution**

Not sure. It's related to #2539 and [PR-2540](https://github.com/georgringer/news/pull/2540).

**Comment by nhovratov** [comment]
@kanow How do you render your templates? If you use the PageContentFetchingProcessor, there has to be a f:cObject call somewhere. You shouldn't provide the resolved Record to `data` as the Code in the controller action expects a raw record.

**Comment by nhovratov** [comment]
Here is an example I want to add to the documentation: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86651

**Comment by kanow** [comment]
Yeah, great :-) thy. That will fix it. 

The error occurs if I'm using this kind of code in my fluid template to render content elements (not only news plugins, just all content) 
```
<f:cObject typoscriptObjectPath="tt_content" data="{record}" table="tt_content" />
```
Maybe someone use it like this
```
<f:cObject typoscriptObjectPath="tt_content.{record.CType}"  data="{record}" table="tt_content"  />
```
or like this
```
<f:cObject typoscriptObjectPath="{record.fullType}" table="{record.mainType}" data="{record}"/>
```
With that code to render the content in TYPO3 13 in fluid templates, you have the problem with the record transformation. The important thing is to use `{record.rawRecord}` for the `data` attribute. That probably happens with other extensions too. Not only in news. The problem is not in the extensions, it is the rendering of content in fluid.

See the example from @nhovratov in the comment before.

Currently I'm using that code to render content elements and the error is gone.

```
<f:cObject typoscriptObjectPath="{record.mainType}" table="{record.mainType}" data="{record.rawRecord}"/>
```

I don't use the `{record.fullType}` for the typoScriptObjectPath due to avoid errors if no rendering for the CType is defined in TypoScript. For the moment I see no issues with that small change.

**Comment by nhovratov** [comment]
@kanow Cool, I didn't know it works without providing the full TS path. Thanks for the hint!
