### ISSUE TITLE
Sitemap generation: Call to undefined method

### ISSUE THREAD

**Issue by marekskopal** [georgringer/news#2542]
## Bug Report

**Current Behavior**
Sitemap generation throws error
```
Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::getTreeList()
in /var/www/html/vendor/georgringer/news/Classes/Seo/NewsXmlSitemapDataProvider.php line 81
```
because getTreeList() was deprecated in v12 and removed in v13 
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97027-ContentObjectRenderer-getTreeList.html

**Expected behavior/output**
Sitemap is generated with news records. 

**Environment**
- TYPO3 version(s): 13.4.0
- news version: 12.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: macOS 15.0.1

**Possible Solution**
Needs migrate to methods from `PageRepository`

**Comment by georgringer** [comment]
thanks for the detailed report! fixed it
