### ISSUE TITLE
Search problem after update to dev-main c1d8535.

### ISSUE THREAD

**Issue by gmt-it** [georgringer/news#2545]
## Bug Report

Typo3 13.4
PHP 8.2

**Current Behavior**
Hello,

I have a problem after the last update to dev-main c1d8535.

As soon as method="get" is added to line 11 of SearchForm.html Twb5, every search results in a 404 error. If I remove method="get" the search works.

TIA

Guido

**Comment by georgringer** [comment]
thanks for your feedback. if you remove the error handling, which error to you get?

**Comment by gmt-it** [comment]
404
Page Not Found
The page did not exist or was inaccessible. Reason: Request parameters could not be validated (&cHash empty)

**Comment by georgringer** [comment]
I added another commit, can you please test again?

**Comment by gmt-it** [comment]
Hello,

so far it works.

Thank you

Guido

**Comment by georgringer** [comment]
thanks for feedback!
