### ISSUE TITLE
Fatal Error with typo3 13.2.1 addCacheTags() on null

### ISSUE THREAD

**Issue by gmt-it** [georgringer/news#2546]
## Bug Report

**Current Behavior**
Call to a member function addCacheTags() on null

**Environment**
- TYPO3 version(s): 13.2.1
- news version: dev-main 4b3ca1f
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]
- OS: Windows 10 / WSL2 /DDEV

**Additional context**
See Logfile
[typo3_11f96f4e3a.log](https://github.com/user-attachments/files/17591705/typo3_11f96f4e3a.log)

**Comment by georgringer** [comment]
Please use 13.4 of TYPO3!
