### ISSUE TITLE
Error in Configuration/Sets/Twb4 / TWb5:

### ISSUE THREAD

**Issue by gmt-it** [georgringer/news#2549]
Error in Configuration/Sets/Twb4 / TWb5:

In the setup. and constants. typoscript files the import path is wrong.

EXT:news/Configuration/TypoScript/Twb/

should be:

EXT:news/Configuration/TypoScript/ -->Styles/<-- Twb/setup.typoscript

Best regards

Guido

**Comment by georgringer** [comment]
thanks!
