### ISSUE TITLE
Error in module News Administration

### ISSUE THREAD

**Issue by wimr0001** [georgringer/news#2551]
## Bug Report
Module News Administration gives the following error:
Call to undefined method TYPO3\CMS\Backend\Template\ModuleTemplate::setContent()
line 41

**Environment**
- TYPO3 version(s): 13.4.0
- news version: 12.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Comment by KC-Man** [comment]
Some ModuleTemplate methods are deprecated and removed in TYPO3 v13. One of these methods is the setContent function:
See: [https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-96903-DeprecateOldModuleTemplateAPI.html](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-96903-DeprecateOldModuleTemplateAPI.html)

**Comment by georgringer** [comment]
can you check the dev-main version? should be fixed there
