### ISSUE TITLE
[DOCS] Add hint to TCEMAIN linkhandler namespace changes

### ISSUE THREAD

**Issue by Alagts** [georgringer/news#2552]
Since I encountered this error 
`Class "TYPO3\CMS\Recordlist\LinkHandler\RecordLinkHandler" not found`
in the backend in a TYPO3 v13.4 instance when adding a link, I would recommend to add a small hint and link to this [reference](https://docs.typo3.org/m/typo3/reference-tsconfig/main/en-us/PageTsconfig/TceMain.html#pagetcemaintables-linkhandler) for example in "[known problems](https://docs.typo3.org/p/georgringer/news/main/en-us/Reference/MissingKnownErrors/Index.html)" that one has to change its namespace when using tsconfig settings for news.

Our Code snippet: News.tsconfig
```
TCEMAIN {  
    linkHandler {  
        news {  
            handler = TYPO3\CMS\Recordlist\LinkHandler\RecordLinkHandler
            ...
            }
        events {  
            handler = TYPO3\CMS\Recordlist\LinkHandler\RecordLinkHandler
            ...
            }
     }
}
```
 The correct namespace is `TYPO3\CMS\Backend\LinkHandler\RecordLinkHandler`.

**Comment by georgringer** [comment]
but is already correct in docs? https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/BestPractice/Linkhandler/Index.html
