### ISSUE TITLE
Localization of news data records

### ISSUE THREAD

**Issue by gmt-it** [georgringer/news#2553]
Hello.

Since I don't know if it's a bug or a kernel problem, I'll ask here before opening a new issue:

is it normal that the flags or at least the language are no longer displayed for folders and news records in the localization?

![image](https://github.com/user-attachments/assets/c6f67edd-e69c-484a-a193-8dda0dc0626d)

**Comment by georgringer** [comment]
IMO not normal and more an issue of your system but hard to know without knowing anything like core or news version

<img width="591" alt="Bildschirmfoto 2024-11-04 um 22 08 37" src="https://github.com/user-attachments/assets/5a2f58be-e356-4c1c-a92d-49217dd70c89">

**Comment by gmt-it** [comment]
Thanks. I found it. The folder must be within the page tree otherwise the languages/flags will not be displayed.
