### ISSUE TITLE
Using Admin Module in BE throws error

### ISSUE THREAD

**Issue by whiteroom** [georgringer/news#256]
setting `module.showAdministrationModule = 1`

throws error: 
`'Button "TYPO3\CMS\Backend\Template\Components\Buttons\LinkButton" is not valid'`

**Comment by georgringer** [comment]
can you debug it more or give me access to the project? I can't reproduce it

**Comment by whiteroom** [comment]
Hallo Georg
here you go

Eine simple Testinstallation:
http://architekturdialoge.ch/beta/typo3/

Adminzugang:
georgringer/Estobrevis




Neuinstallation TYPO3 CMS
Installation Extension News 5.3 von Repository
Artikel erstellen
Update auf Version 6 News
> News Admin Modul crasht
> Bilder und Header bleiben leer


Gruss
Daniel








Am 12.2.2017 um 20:31 schrieb Georg Ringer <notifications@github.com>:
