### ISSUE TITLE
Typo3 13.4.1 Runtime error with news and lots of categories

### ISSUE THREAD

**Issue by DTM-TYPO3** [georgringer/news#2561]
Hey there,
I have a project with lots of news categories und subcategories. When I choose lots of them (more then 25) in the plugin and include the subcategories then the page needs a lot of loading time until an error occurs: "Fatal error: Maximum execution time of 120 seconds exceeded in .../typo3_src-13.4.1/typo3/sysext/core/Classes/Database/Query/Expression/CompositeExpression.php on line 72"

Can you reproduce the error and fix it, please? 
It was working great in my former Typo3 12.4 system.

- TYPO3 version: 13.4.1
- news version: 12.0.0
- no composer installation

Thanks in advance.
Regards, Stefanie

**Comment by georgringer** [comment]
Hey,

I don't see what I can do here. I didn't change anything related to that in ext:news and it is more a core issue I guess because you are creating a too big query.

feel free to discuss that on slack
