### ISSUE TITLE
sets shipped with EXT:news have the same label

### ISSUE THREAD

**Issue by erredeco** [georgringer/news#2563]
## Bug Report

**Current Behavior**
Site management > Sites > (my site) > tab "General" > Sets for this site
on the list "available items" the "News" item is repeated 3 times. In fact, it is the same label "News" written on each config.yaml file for the three separate sets of EXT:news: News, Twb4, Twb5

**Expected behavior/output**
To avoid confusion, I would want more descriptive labels

**Environment**
- TYPO3 version: 13.4.1
- news version: 12.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX 15.0.1 

**Possible Solution**
Use more descriptive labels; possibly (just a suggestion) the same used on the TypoScript template > include typoscript sets:
- News
- News Styles Twitter Bootstrap
- News Styles Twitter Bootstrap V5

**Additional context**
I got the issue as I've installed EXT:news on a fresh TYPO3 13.4.1 and I wanted to include the sets of EXT:news in my site config

**Comment by georgringer** [comment]
thanks, fixed
