### ISSUE TITLE
TYPO3 13.4: News icons are black on black

### ISSUE THREAD

**Issue by linawolf** [georgringer/news#2577]
## Bug Report

**Current Behavior**
![image](https://github.com/user-attachments/assets/abe4b560-e90b-4527-aa8e-50f05bb973bd)

**Environment**
- TYPO3 version(s): 13.4
- news version: 12.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS:WSL

**Comment by georgringer** [comment]
can't confirm that, try to clear all caches, also the one of the browser. thanks

**Comment by linawolf** [comment]
Used a different browser, Chrome, firefox, all the same issue

**Comment by codemonkey1988** [comment]
@linawolf I had the same problem. For me the reason was a vite-server that provides assets for HMR in combination with CSP.
Disabling HMR solves the problem for me. I'm not sure what's missing in CSP because I added vite-server URLs to CSP, but maybe this will still help.

**Comment by georgringer** [comment]
thanks, I will close that issue, can't reproduce that and also never seen that on any site
