### ISSUE TITLE
#1579965021 UnknownPropertyTypeException

### ISSUE THREAD

**Issue by simonschaufi** [georgringer/news#2589]
## Bug Report

**Current Behavior**

I'm extending the News model with a custom class. This works fine locally but once I upload the code to a webserver running with PHP 8.3 (same locally!) I get an exception:

(1/1) #1579965021 TYPO3\CMS\Extbase\Persistence\Generic\Mapper\Exception\UnknownPropertyTypeException
The type of property GeorgRinger\News\Domain\Model\NewsDefault::related could not be identified, therefore the desired value (4) cannot be mapped onto it. The type of a class property is usually defined via property types or php doc blocks. Make sure the property has a property type or valid @var tag set which defines the type.

Since I only get the exception on a remote server, I can't debug the code.

**Environment**
- TYPO3 version(s): 12.4.23
- news version: 12.2.0
- PHP Version: 8.3
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu

**Additional context**

Maybe it has something to do with the Reflection but I'm just guessing. I have really now glue what this could be.

**Comment by simonschaufi** [comment]
invalid issue. It was a hoster issue. Restarted the webserver and error is gone.

**Comment by georgringer** [comment]
thanks!
