### ISSUE TITLE
Multilingual & FAL Media not show if not default language

### ISSUE THREAD

**Issue by in-session** [georgringer/news#260]
Hi,

we have some problems if we put an single news not in the default language, no images will be displayed. 

Examples: If we put a news inside the default language and we translate them to the other languages, the images are shown, works great. But if we put a news only in other language not the default languages, then no images will present in the article. We have also tried to put the news first in default language and made them invisible, but then the other languages of the news are also not displayed

Do you have a solution for this problem?

Configurations:

> config.sys_language_mode = strict
> config.sys_language_content = 0
> config.sys_language_uid = 0
> config.sys_language_overlay = 0

Versions: 

> Typo3 7.6.15
> News 5.3.2

Languages:

> 0 - Default DE
> 1 - EN

![unbenannt-1](https://cloud.githubusercontent.com/assets/16542619/23057194/4b37b1ea-f4ef-11e6-939e-abc5c4815cca.png)

**Comment by georgringer** [comment]
This is a problem of the core and not so much of the extension itself. If you are using strict, you must also change the tca of `sys_file_reference` to add the language select there.

**Comment by in-session** [comment]
ok many thanks and what is the solution if we change the sys_language_mode?

If we change that into:


> config.sys_language_mode = content_fallback
> config.sys_language_overlay = hideNonTranslated

Then we have the problem that the non translated news are shown in the default language.

**Comment by tmotyl** [comment]
note, this patch at last partially solves it https://review.typo3.org/#/c/31227/9
