### ISSUE TITLE
News import from custom source

### ISSUE THREAD

**Issue by gebeleisis** [georgringer/news#270]
Hi, 

I would like to switch from a custom made CMS to Typo3. I have about 1500 articles in a MySQL table which need to be imported in news format. How could i do this best? I looked over the Import module, but i don't understand if it is what i need. Thanks.

**Comment by georgringer** [comment]
You can either use that or just call the `NewsImportService`. As an example you can take a look at https://github.com/georgringer/news_importicsxml/blob/master/Classes/Jobs/ImportJob.php as well.

or a copy from what I just did
```
$news = [];
        $sorting = 1;
        foreach ($elements as $element) {
            $item = [
                'type' => '2',
                'title' => $element['header'],
                'datetime' => $element['datetime'],
                'teaser' => $flexforms['copytext'],
                'sys_language_uid' => $element['sys_language_uid'],
                'l10n_parent' => $element['l18n_parent'],
                'pid' => $element['pid'],
                'sorting' => $sorting++,
                'import_source' => 'news_press',
                'import_id' => $element['uid'],
            ];
}
$news[] = $item;
        }

        $newsImportService = $this->objectManager->get(NewsImportService::class);
        $newsImportService->import($news);
```

just to get an idea
