### ISSUE TITLE
News preview from workspace

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [georgringer/news#273]
Servus Georg!

Is previewing news items (single view) in workspace preview (using "save and view" on a news item in a workspace) supported for TYPO3 7.6?

I have following problems:

1. Allow display of *versioned single news items* (``pid=-1``) from workspace preview (see #271)

2. *Secure the preview page*
Using ``[globalVar = TSFE:beUserLogin > 0]`` won't work: workspace preview will once call the preview page with all required parameters ("workspace view") but use ``&ADMCMD_noBeUser=1&ADMCMD_prev=IGNORE`` for the "live view". ``&ADMCMD_noBeUser=1`` unsets all BE user info in TSFE, so we can't use ``TSFE:beUserLogin``. Best solution would be to implement a custom TS condition which uses the logic from \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::initializeBackendUser() (cookie, IP lock, BE group, etc.).

3. Display the correct *"LIVE" data*
Workspace preview will call both pages with the news uid of the current news item and thus compare each news item with itself. To display both, the real "LIVE" data and the versioned data I thought of using a slot for detailAction which fetches the original uid (``t3ver_oid``) for versioned items (``pid=-1``) and redirects to the original news item if called from workspace "live view" (check query string: ``tx_news_pi1[news_preview]={id to replace}&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&ADMCMD_noBeUser=1&ADMCMD_prev=IGNORE``).

4. Correct *relations* for versioned items
Extbase seems to not correctly overlay related data (falRelatedFiles, falMedia, etc.). Perhaps overlaying data could be done manually also in the detail slot, but this would also require to extend the News model and add some setter functions (setFalMediaPreviews, setFalMediaNonPreviews, etc.).

Thanks for your feedback and insights!

**Comment by georgringer** [comment]
hi. sorry IMO I can't do anything there as this is all extbase/core specific
