### ISSUE TITLE
Page module - PHP Fatal Error

### ISSUE THREAD

**Issue by matejmericnjak** [georgringer/news#277]
The following PHP Fatal Error is thrown when trying to view a page via page module which includes a news plugin (list view):

Fatal error: Call to a member function wrapClickMenuOnIcon() on a non-object in /../typo3conf/ext/news/Classes/Hooks/PageLayoutView.php on line 255

Tested on:
TYPO3 7.6.16
News System 3.2.2

**Comment by georgringer** [comment]
latest version is 5.3.2. use this version
