### ISSUE TITLE
Template-Layouts: pageID not set in Utility/TemplateLayout?

### ISSUE THREAD

**Issue by mazzefrie** [georgringer/news#283]
After an update to Typo3 7.6.16 and news (5.3.2) the field for selecting template layouts remains empty. According to Page / Info the TSPage configuration is correct: tx_news.templateLayouts is set.

But i figured out that in Utility/TemplateLayout::getTemplateLayoutsFromTsConfig the parameter $pageUid is NULL. When i change it manually, TSPage is loaded correctly. 

Is this a configuration problem?

**Comment by georgringer** [comment]
is the compat extension installed? can you recheck using the latest news version? I did some changes in that regard

**Comment by georgringer** [comment]
closed as no feedback came.
