### ISSUE TITLE
Using label_userFunc in my extension

### ISSUE THREAD

**Issue by ste101** [georgringer/news#288]
I have a similar problem like in #178 .
I want to use label_userFunc in my own extension but I am not able to override the label_userFunc that is defined in /news/Configuration/TCA/Overrides/sys_category.php.
Like mentioned in #178 wouldn't it be better to use an own sys_category extbase_type?

Is there a way to override label_userFunc?

Thanks in advance.

**Comment by georgringer** [comment]
If your extension is loaded after news, you can just override the TCA and your userfunc is loaded.

**Comment by ste101** [comment]
OK I was able to load my extension after news using 'suggests' in ext_emconf.php.
But now label_userFunc of news is lost.
Is there a way to configure label_userFunc only for one page or via the tx_extbase_type field that the extension builder defines in the file in the folder 'Overrides'?

**Comment by georgringer** [comment]
you can copy the code of news to your own extension and load it when you need it, e.g for speicifc page or type
