### ISSUE TITLE
missing switchableControllerActions "list2"

### ISSUE THREAD

**Issue by Uhradone** [georgringer/news#289]
Hello Georg,
I managed to install a second news-latest-Partial-Layout for my footer news:
[http://die-schwarzwald-werbeagentur.zazudesign.de/internet-programmierung/news-latest-typo3-extension-news-or-tx_news.html]
But since it is responsive I have to put outside all List-news-Partials some code into the List-Template (List.html). It is "wrapper" "clearfix" - things that make the news-block float in the responsive page-layout.
In the Footer-Latest-News (list-template + listLatest-partial) this code from the List.html-Template is now disturbing, so I should use a second List2.html-Template (list2), but there is no controller action to call it? Or it is beyond my abilities to code it.

I think the possibility to call easily different partials in combination with different templates is essential.
Thomas Hezel

**Comment by georgringer** [comment]
I don't really get what you need. IMO https://docs.typo3.org/typo3cms/drafts/github/georgringer/news/AdministratorManual/Templates/TemplateSelector/Index.html is the correct way to go. all can be achived by adopting templates + layouts and maybe adding additional layouts.
