### ISSUE TITLE
Translate the content elements in the news directly

### ISSUE THREAD

**Issue by JasikaN** [georgringer/news#290]
OK, my question is wether I can translate the content elements in the news directly. When I click the button, I get a response but nithing really happens. I can translate the elemnt manually but that is not user friendly.
![screenshot_1](https://cloud.githubusercontent.com/assets/9623966/24653871/e706fb00-1937-11e7-9bf8-c2a08e9af141.png)

**Comment by georgringer** [comment]
that has been a bug in core which should be fixed. therefore I am closing this issue
