### ISSUE TITLE
Checkbox for Preview Image gone after Update to Typo3 8.7 LTS

### ISSUE THREAD

**Issue by Bithie** [georgringer/news#292]
Hi Georg,

yesterday i made an upte from Typo3 7.6.16 LTE to 8.7 LTE. Since then in your News System the checkbox for choosen the Preview Image is gone. Is that a Bug or a Feature?
Thanks for helping. :)

Best regards
Maik

Typo3 8.7.0 LTS
![typo3_checkbox](https://cloud.githubusercontent.com/assets/5798000/24743410/61e49b1c-1aae-11e7-9e19-a9fb20b18c3d.png)

Typo3 7.6.16 LTS
![typo3_checkbox_7616](https://cloud.githubusercontent.com/assets/5798000/24756998/1b335fb6-1ade-11e7-9f6f-70e46d75d3de.png)

**Comment by georgringer** [comment]
fixed that yesterday already
