### ISSUE TITLE
v8.7 angle tags showing in labels

### ISSUE THREAD

**Issue by justibro** [georgringer/news#297]
I was looking into upgrading to v8 and I noticed on the news plugin that when I try to use overriding labels, that it will display the html code instead of making it html code.  I have looked at other plugins where I have done this and it respects the angle tags as html.  Here is the template code

plugin.tx_news._LOCAL_LANG.default.author = &lt;b>Written by&lt;/b> %s
plugin.tx_news._LOCAL_LANG.default.author_simple = &lt;b>Written by&lt;/b> 

it displays the &lt;b> on the page instead of bolding the text like it did in version 7

**Comment by georgringer** [comment]
try to wrap it in the template into the `<f:format.raw>` viewhelper
