### ISSUE TITLE
Preview on List View does not show up TYPO3 v8.6.0

### ISSUE THREAD

**Issue by AKaravas** [georgringer/news#298]
Show i tried to create a news record to test it on TYPO3 v8.6.0 and i came up across a problem. I added a relation (photo) on my record but the Preview checkbox did not appear. Should be this way or is it a bug?

Environment:
TYPO3 v8.6.0
Mamp Pro
Local installation

If you need more infos about the issue, just ask :)

http://image.prntscr.com/image/f054cb0f72cb4e5091e39ec233b4fbd7.png

**Comment by georgringer** [comment]
fixed in master already
