### ISSUE TITLE
News title is not always saved if only title is entered

### ISSUE THREAD

**Issue by tomasnorre** [georgringer/news#299]
Hi. 

I've experience a strange behaviour with the news title. It's not always saved if only title is filled out.

TYPO3: 7.6.15
News: 5.3.3
PHP 5.6.30

Steps to reproduce, see Screencast.
https://www.dropbox.com/s/oq2tj5q69xaqekp/NewsTitleNotAlwaysSaved.mov?dl=0

I haven't debugged the issue, but I can try to do so later if you can confirm the issue.

**Comment by georgringer** [comment]
this is a core isssue, IMO https://forge.typo3.org/issues/80632

**Comment by tomasnorre** [comment]
Looks like you're right.. Thanks for a fast response..
