### ISSUE TITLE
Unncesary duplicate code in NewsImportService

### ISSUE THREAD

**Issue by jdoubleu** [georgringer/news#301]
While working with the News Importer and its services I probably found a mistake in one of the classes.

For [`NewsImportService.php`](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php):
The [`hydrateNewsRecord` ](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php#L130) function creates a News Model object out of the provided data.

The `type` and `keywords` are set twice:
Compare [lines 155-156](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php#L155-L156) and [lines 170-171](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php#L170-L171).

Is there any reason for this or is it just a mistake?
May I create a MR.

**Comment by georgringer** [comment]
please create a PR!
