### ISSUE TITLE
Incomplete News Models after importing.

### ISSUE THREAD

**Issue by jdoubleu** [georgringer/news#302]
While writing an own importer for news and using the services and classes provided by this extension I noticed, that the import isn't complete.

The [`hydrateNewsRecord` ](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php#L130) function creates a News Model object out of the provided import data in the [`NewsImportService.php`](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php) class.

This function doesn't set the `description` field.

**Comment by georgringer** [comment]
can you provide a PR?
