### ISSUE TITLE
hiding a news shows error

### ISSUE THREAD

**Issue by eBornstein** [georgringer/news#304]
If you hide a news with the context menu, the following error appears. 
Hiding with button shows no error but the loading has no end.
![error](https://cloud.githubusercontent.com/assets/17193249/25118614/4a8ca64a-2417-11e7-9f54-9244c38b3c02.png)
![error2](https://cloud.githubusercontent.com/assets/17193249/25118616/4ab02f16-2417-11e7-8ce3-2951d1731b35.png)

**Comment by No5251** [comment]
Is PID 65 a root page? If so, it should be marked as root.
What is the error id (behind the link "online")?

**Comment by eBornstein** [comment]
Oh, sry. The pid 65 is the folder containing the news. No its not marked as root page.
Here is the errorpage behind the link: https://wiki.typo3.org/Exception/CMS/1309272922
And yes I use ext:solr but I do not see the connection between hiding a news and ext:solr. ^^

**Comment by georgringer** [comment]
this error is thrown by solr, I guess you should open an issue at https://github.com/TYPO3-Solr/ext-solr
