### ISSUE TITLE
Button media show in preview not visible for several news entries

### ISSUE THREAD

**Issue by c0d3b34n** [georgringer/news#306]
Hi there,

I'm using news extension 5.3.3 with TYPO3 8.7 LTS. Yes I know this version is not yet supported by this extension. But for supporting this version in future this issue should be fixed.

In some cases - I could not identify the clue responsible for this - the button for media show in preview is not visible. If I can help with some data please feel free to ask.

TYPO3-Version	8.7.0
Webserver	Apache/2.4.20
PHP-Version	7.0.6
Datenbank (Default)	MySQL 5.6.19

**Comment by brrrrrrrt** [comment]
same here, showinpreview button is missing: 
![bildschirmfoto von 2017-04-19 13-18-34](https://cloud.githubusercontent.com/assets/4489013/25177597/f6d1c034-2502-11e7-851e-512fe9c878bc.png)

when i manually lookup the entry in the 
sys_file_reference table and set showinpreview from 0 to 1 the button appears:
![bildschirmfoto von 2017-04-19 13-19-17](https://cloud.githubusercontent.com/assets/4489013/25177709/3512e2b0-2503-11e7-8066-82cba759f7a4.png)

**Comment by martinhummer** [comment]
The latest dev-master should solve your issue.

**Comment by brrrrrrrt** [comment]
@martinhummer thx!

**Comment by c0d3b34n** [comment]
Thx! Then I'll close this.
