### ISSUE TITLE
Proposal: Use DataMapper to create import news model

### ISSUE THREAD

**Issue by jdoubleu** [georgringer/news#308]
I've been working with the import feature/service. I "dived" deeper into the code and I wondered about the way the import service is handling data.

The function [`hydrateNewsRecord`](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php#L130), which actually [creates a Model and fills it with the provided import data](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php#L130-L305), manually sets the data using the Model's setter methods.

Why not using a data mapper? Or is it too inefficient, especially when dealing with many data?

A data mapper would have the advantage of being future compatible in means of adding new properties to the news Model while (mostly) staying backwards compatible.
Special properties like [categories](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php#L179-L194), [related files](https://github.com/georgringer/news/blob/master/Classes/Domain/Service/NewsImportService.php#L197-L240), etc.  can be converted by custom type converters.

**Comment by georgringer** [comment]
IMO it would be better to switch to using the DataHandler which is the only real future proof solution and which solves issues which extbase doesn't, like care about the refindex.

If you would like to work on that, please go on!

**Comment by georgringer** [comment]
I won't do it, therefore I am closing this issue
