### ISSUE TITLE
restrict categories in news plugin throw error

### ISSUE THREAD

**Issue by thomaskieslich** [georgringer/news#309]
PageTS setting:
tx_news.categoryRestrictionForFlexForms = 1
TCEFORM.tx_news_domain_model_news.categories.PAGE_TSCONFIG_IDLIST=**,**

Open Plugin in BE with Listview throw this error
Argument 1 passed to TYPO3\CMS\Backend\Form\FormDataProvider\TcaFlexProcess::addData() must be of the type array, null given, called in /Users/thomask/Aktuell/www-mamp/typo3/t3-8x-comp/vendor/typo3/cms/typo3/sysext/backend/Classes/Form/FormDataGroup/OrderedProviderList.php on line 59

What i find out:
1. NewsFlexFormManipulation addCategoryConstraints should return $result;
the error is gone, but no function

2. in the same function remove TCEforms from structure
$structure['sheets']['sDEF']['ROOT']['el']['settings.categories']['config']['foreign_table_where'] = $categoryRestriction . $structure['sheets']['sDEF']['ROOT']['el']['settings.categories']['config']['foreign_table_where'];
because you hook after TcaFlexPrepare.php

3.  foreign_table_where in $result is now 'AND sys_category.pid IN (###PAGE_TSCONFIG_IDLIST###) AND (sys_category.sys_language_uid = 0 OR sys_category.l10n_parent = 0) ORDER BY sys_category.sorting'
result: no restriction

4. Hardcoding foreign_table_where in flexform_news.xml > no restriction
add TCEFORM.tt_content.pi_flexform.PAGE_TSCONFIG_IDLIST = 53 to PageTS
= restricted categories in news Plugin

5. hardcoding Pids in CategoryConstraints dosn't help

This is the end of my Ideas, i hope it helps to fix it.

**Comment by georgringer** [comment]
the issue is too old and can't be reproduced anymore. feel free to reopen a new issue if still valid
