### ISSUE TITLE
Localization Images Multilanguage no function

### ISSUE THREAD

**Issue by in-session** [georgringer/news#310]
Localization of the images from the original news are not working, button is without function.
News 6.0.0, Typo3 7.6.18
![ashampoo_snap_2017 04 22_20h27m27s_003_](https://cloud.githubusercontent.com/assets/16542619/25307018/35127bba-279a-11e7-9a07-8d2e2ee64e8a.png)

**Comment by in-session** [comment]
We have found the problem on a test system. With Typo3 7.6.15 works fine, after upgrate on 7.6.18 the localization is without function.

**Comment by georgringer** [comment]
then it is more a core issue, maybe https://forge.typo3.org/issues/80855
