### ISSUE TITLE
Empty type field on using content elements

### ISSUE THREAD

**Issue by maikusch** [georgringer/news#314]
Hi, like discussed today on slack...
with TYPO3 7.6.15 and news 5.3.3 (and 6.0) the type field on using content elements in a news entry is empty. 
![2017-04-27_1051](https://cloud.githubusercontent.com/assets/2861624/25477142/caeb0166-2b3c-11e7-9d8b-81911c9513f1.png)

**Comment by georgringer** [comment]
if this happens with 5.3.3 as well, it is IMO nothing I can change. what if you create a new content element in the sysfolder of news? is the type set then?

**Comment by georgringer** [comment]
closing this because of no feedback
