### ISSUE TITLE
Backend Modul News throwing an error

### ISSUE THREAD

**Issue by chequille** [georgringer/news#316]
Hi Georg,
I am currently doing test with Typo3 Version 8.7.1 and latest news Version 6.0.0

Frontend is working fine for me.

Backend works OK, when I choose list view and my news directory.

But when using your Backendmodul News and selecting my news directory, it is throwing the following error:
**Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\Fluid\ViewHelpers\Be\Widget\PaginateViewHelper::render() must implement interface TYPO3\CMS\Extbase\Persistence\QueryResultInterface, string given | TypeError thrown in file ......./typo3/sysext/fluid/Classes/ViewHelpers/Be/Widget/PaginateViewHelper.php in line 69. Requested URL: https://......../typo3/index.php?M=web_NewsTxNewsM2&moduleToken=ea2367b1c7c3ecef478e866e39d0b24c8fdf5459&id=19**

This happens only when there are news entries in the directory. If it is empty, no error occurs.

Any idea what can be wrong?

Best regards,
Jürgen

**Comment by georgringer** [comment]
Can you check if you override any templates of the backend? can you debug the variable with using the f:debug VH what the string is?

**Comment by chequille** [comment]
Hi Georg,

this was the right hint. Of course, I have overrides of the templates. Because I am using the TBW templates, I could delete the normal views overrides.
No everything is OK.
Best regards,
Jürgen
