### ISSUE TITLE
Button "TYPO3\CMS\Backend\Template\Components\Buttons\LinkButton" is not valid

### ISSUE THREAD

**Issue by tmotyl** [georgringer/news#321]
When entering the news backend module in typo3 9-dev, an error is thrown 
"Button "TYPO3\CMS\Backend\Template\Components\Buttons\LinkButton" is not valid"
It is caused by refresh button title not being set in Administration controller ~line 230, 
```
->setTitle($this->getLanguageService()->sL('LLL:EXT:lang/locallang_core.xlf:labels.reload'))
```
because the xlf file location has changed in the lang module
see https://review.typo3.org/#/c/50584/
so the issue might also occurs in v8.7

**Comment by christian-fries** [comment]
FIxed with commit https://github.com/georgringer/news/commit/447701104f63fd38988b71197be0e1896cca427a
