### ISSUE TITLE
related links can't be localized with typo3 7.6.18

### ISSUE THREAD

**Issue by schiran** [georgringer/news#323]
With typo3 7.6.18  and news 6.0.0 or news 5.3.3 do:

- Have an installation with two languages (eg. de/en)
- create new news (de) with title and related link (de)
- save and close
- localize news to en
- localize header => ok
- localize related link => no reaction
- localize all records => no reaction
- synchronize with orig. language => no reaction

With typo3 7.6.16 everything works as expected

**Comment by glucka** [comment]
Confirmed, i have the same problem with media files too.

**Comment by georgringer** [comment]
Known core issue, use eg https://github.com/froemken/repair_translation

**Comment by schiran** [comment]
The issue seems to be fixed in TYPO3 7.6.20
