### ISSUE TITLE
Error on call hidden/deleted news under 7.6

### ISSUE THREAD

**Issue by bench-artwork** [georgringer/news#328]
getting following error on call a hidden/deleted news via url and the new default errorHandling:
`PHP Warning: filemtime(): stat failed for EXT:news/Resources/Private/Templates/News/DetailNotFound.html in /Applications/MAMP/htdocs/typo3_src-7.6.18/typo3/sysext/fluid/Classes/View/StandaloneView.php line 553`

affects only TYPO3 7.6.

**Comment by thorsten-krieger** [comment]
I have the same problem.
In NewsBaseController->handleNoNewsFoundError() is the handling of "EXT:" filenames not included.
If you change the line 120 to:
`$standaloneTemplate->setTemplatePathAndFilename(GeneralUtility::getFileAbsFileName($configuration[1]));`
no further error ist displayed.
But now I have the problem, that nothing of the template is rendered.

**Comment by Ceremony64** [comment]
This issue is still occurring for me on version 6.1.1:
`Core: Error handler (FE): PHP Warning: filemtime(): stat failed for EXT:news/Resources/Private/Templates/News/DetailNotFound.html in /var/www/typo3_src-7.6.21/typo3/sysext/fluid/Classes/View/StandaloneView.php line 553`

**Comment by georgringer** [comment]
I can't reproduce that. however you can change the behaviour by setting `plugin.tx_news.settings.detail.errorHandling = pageNotFoundHandler'
