### ISSUE TITLE
No errorHandling with list/detail mode and realurl

### ISSUE THREAD

**Issue by bench-artwork** [georgringer/news#329]
using list/detail on same page with realurl and action/controller bypass there is no errorHandling on faulty urls. Reproducible with the advanced realurl example from the documentation.

domain.com/newspage/news-title/ => news is displayed
domain.com/newspage/random-text/ => listview is displayed. No error page.

In some cases this could be a good scenario but an additional option for enabling errorHandling would be great!

**Comment by georgringer** [comment]
Can you please add your full realurl config?

**Comment by bench-artwork** [comment]
`<?php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']=array (
  '_DEFAULT' =>
  array (
    'init' =>
    array (
      'appendMissingSlash' => 'ifNotFile,redirect',
      'emptyUrlReturnValue' => '/',
    ),
    'pagePath' =>
    array (
      'rootpage_id' => '1',
    ),
    'preVars' =>
    array (
      array (
        'GETvar' => 'L',
        'valueMap' => array (
          'en' => 1,
        ),
        'noMatch' => 'bypass',
      ),
      array (
        'GETvar' => 'no_cache',
        'valueMap' =>
          array (
          'nc' => 1,
        ),
        'noMatch' => 'bypass',
      ),
    ),
    'fileName' =>
    array (
      'defaultToHTMLsuffixOnPrev' => 0,
      'acceptHTMLsuffix' => 1,
      'index' =>
      array (
        'sitemap.xml' =>
        array (
          'keyValues' =>
          array (
            'type' => 655,
          ),
        ),
        'robots.txt' =>
        array (
          'keyValues' =>
          array (
            'type' => 656,
          ),
        ),
        'feed.rss' =>
        array (
          'keyValues' =>
          array (
            'type' => 9818,
          ),
        ),
      ),
    ),
    'fixedPostVars' =>
    array (
      'newsDetailConfiguration' =>
      array (
        array (
          'GETvar' => 'tx_news_pi1[news]',
          'lookUpTable' =>
          array (
            'table' => 'tx_news_domain_model_news',
            'id_field' => 'uid',
            'alias_field' => 'coalesce(NULLIF(path_segment, ""), NULLIF(tx_newslocation_name, ""), title)',
            'addWhereClause' => ' AND NOT deleted',
            'useUniqueCache' => 1,
            'useUniqueCache_conf' =>
            array (
              'strtolower' => 1,
              'spaceCharacter' => '-',
            ),
            'languageGetVar' => 'L',
            'languageExceptionUids' => '',
            'languageField' => 'sys_language_uid',
            'transOrigPointerField' => 'l10n_parent',
            'autoUpdate' => 1,
            'expireDays' => 180,
          ),
        ),
      ),
      2 => 'newsDetailConfiguration',
      3 => 'newsDetailConfiguration',
      4 => 'newsDetailConfiguration',
      5 => 'newsDetailConfiguration',
    ),
    'postVarSets' =>
    array (
      '_DEFAULT' =>
      array (
        'controller' =>
        array (
          array (
            'GETvar' => 'tx_news_pi1[action]',
            'noMatch' => 'bypass',
          ),
          array (
            'GETvar' => 'tx_news_pi1[controller]',
            'noMatch' => 'bypass',
          ),
        ),
        'seite' =>
        array (
          array (
            'GETvar' => 'tx_news_pi1[@widget_0][currentPage]',
          ),
        ),
      ),
    ),
  ),
);
`

**Comment by georgringer** [comment]
I don't plan to change there something as it would probably add other side effects. therefore closing the issue
