### ISSUE TITLE
Missing typo3/class-alias-loader extra in composer.json in 4.3.0

### ISSUE THREAD

**Issue by dogawaf** [georgringer/news#330]
Hello

In news 4.3.0, the composer.json is missing an extra section for the autoloading of legacy class alias map.
This breaks TYPO3 installation in composer mode.

The composer.json should include this:
```
"extra": {
  "typo3/class-alias-loader": {
    "class-alias-maps": [
       "Migrations/Code/ClassAliasMap.php"
    ]
  }
},
```

As a workaround, adding this extra section in the global composer.json works.
In news 5, the legacy class alias map has been removed, so the issue is not existing.

I can make a pull request if it is OK.

Cheers.

**Comment by georgringer** [comment]
yeah pls PR

2017-05-19 10:11 GMT+02:00 Rémy DANIEL <notifications@github.com>:

**Comment by dogawaf** [comment]
I've created the pull request against the 4.3 branch.
Cheers.

**Comment by georgringer** [comment]
sorry for failing to change that but I won't support the old branches anymore. therefore I am closing this issue.
