### ISSUE TITLE
TYPO3 8.7.1 + frontend_editing: Breaks on details view

### ISSUE THREAD

**Issue by jdinse** [georgringer/news#331]
Hi,

I just installed the new frontend_editing extension on TYPO3 8.7.1 and since then, I can't watch the details view of news anymore. I just get the message:

> **Page Not Found**
> Reason: Request parameters could not be validated (&cHash empty)
> 

Any ideas?

(Notice: I don't want to use the frontend-editing for news at all. I just want so read a news in the frontend while the fronend_editing extension is activated and I'm logged in into the backend)

**Comment by alexjamp** [comment]
hello jdinse,

workaround:
[FE][disableNoCacheParameter] = false
[FE][pageNotFoundOnCHashError] = false

best regards
Alex

**Comment by georgringer** [comment]
This seems to be an issue of frontend_editing. Nothing I can do about that.
