### ISSUE TITLE
overwriteDemand is ignored

### ISSUE THREAD

**Issue by dpiskoric** [georgringer/news#332]
- latest 7.6
- tx_news: 6.0.0
- caching disabled
- category mode set
- cHash disabled

Example: links from template DateMenu.html always list all news

In a debug I can see that in GeorgRinger\News\Domain\Model\Dto\NewsDemand "month", "year" are empty

URL generated: index.php?id=162&no_cache=1&tx_news_pi1[year]=2016&tx_news_pi1[month]=12&tx_news_pi1[controller]=News

**Comment by georgringer** [comment]
fixed with https://github.com/georgringer/news/pull/439
