### ISSUE TITLE
Outdated ViewHelper

### ISSUE THREAD

**Issue by cedev-de** [georgringer/news#335]
Hi @georgringer ,

i determined that the PagniateViewHelper and it's Controller have been updated by the latest Fluid version. The main changes of the VieHelper are that it now not only accepts a QueryResultInstance but also a ObjectStorgae and most important an array.

I determined that by sorting the news with an own ViewHelper where i store the news in an array and got an error by committing them to the PaginateViewHelper of your news extension. It would be nice if you could updated these so we don't have to overwrite it in an extra extension.

Thank You!

**Comment by georgringer** [comment]
wanna create a PR for that?

**Comment by georgringer** [comment]
I currently don't plan any changes in that regard. you can just use the regular paginate VH of the core then for those array items.
