### ISSUE TITLE
Localization doesn't work proper in all configuration modes

### ISSUE THREAD

**Issue by thorsten-krieger** [georgringer/news#336]
Hi,
we are using for one project this mode:
sys_language_mode = strict

the translated news has its own media file, but this file is not shown in frontend.
![2017-05-24 10_48_52-typo3 cms 7 6 18](https://cloud.githubusercontent.com/assets/11457154/26394904/ba9cab92-406e-11e7-8266-7ad23d318fbb.png)

before the switch of the sys_language_mode the files had been shown.

**Comment by georgringer** [comment]
core issue, sorry

**Comment by SventB** [comment]
It even doesn't work with sys_language_mode=content_fallback. Is this still a core issue? Which core issue?

**Comment by SventB** [comment]
Seems to be only an issue in TYPO3 8.7, fixed in TYPO3 9.5.
