### ISSUE TITLE
Localization and limit doesn't work

### ISSUE THREAD

**Issue by thorsten-krieger** [georgringer/news#337]
Hi,
we are using for one project this mode:
sys_language_mode = strict

there are a few news, and the 3 newest has to be shown on the start page of a homepage.
but on the not default language version of the homepage, only the translated one which is not hidden are displayed.

Backend Modul with news entries
![2017-05-24 10_52_03-interhydraulik typo3 cms 7 6 18](https://cloud.githubusercontent.com/assets/11457154/26395130/757f54be-406f-11e7-969e-fdfea68fe68a.png)

Backend Plugin Configuration
![2017-05-24 10_52_32-interhydraulik typo3 cms 7 6 18](https://cloud.githubusercontent.com/assets/11457154/26395129/757f3326-406f-11e7-93fd-625f7a5f246c.png)

Frontend output
![2017-05-24 10_52_45-interhydraulik - interhydraulik](https://cloud.githubusercontent.com/assets/11457154/26395131/7582ff10-406f-11e7-9b46-ce229688dad2.png)

**Comment by georgringer** [comment]
strict and extbase is a core issue, nothing I will do about it. sorry. better use separate folders in that case
