### ISSUE TITLE
Styles/Twb/Layouts/General.html contains unnecessary fluid namespace

### ISSUE THREAD

**Issue by mediaessenz** [georgringer/news#341]
```
<div class="news" xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers">
	<f:render section="content" />
</div>
```

**Comment by georgringer** [comment]
can you please provide a bit more information like which version used of extension and core?

**Comment by mediaessenz** [comment]
https://github.com/georgringer/news/blob/master/Resources/Private/Templates/Styles/Twb/Layouts/General.html#L1

**Comment by georgringer** [comment]
again. please which core version are you using?

**Comment by mediaessenz** [comment]
8.7.1

**Comment by georgringer** [comment]
core issue since 8
