### ISSUE TITLE
limit pictures shown in Backend

### ISSUE THREAD

**Issue by rnakielski** [georgringer/news#343]
Since Version 6.0 of tx_news there are related pictures shown in the list module's list. This is a nice feature. But we have some news containing 20 to 30 or even more pictures. In the list module this makes a horizonntal scroll bar that is not very comfortable for the editors.
Is there a way to limit the amount of pictures shown in List modules's list - or to stop showing pictures at all there?

**Comment by georgringer** [comment]
you can unset 'thumbnail' in the CTRL section of the TCA to remove the thumbnails. I guess I make that configurable in next version

**Comment by rnakielski** [comment]
great - thank you - I could even replace "fal_media" to another pic-Column we added.
If this is made configurable in next version it would be cool to set a limit for something like 3 pictures and even better with some "and n more" that indicate the number of none displayed images.
