### ISSUE TITLE
Date changes in combination with realurl

### ISSUE THREAD

**Issue by webdevsli** [georgringer/news#348]
I found a bug, but i am not sure, if this a news or realurl bug ;) 
The following case will not working if you want to show the detail site of one news. 

1. Add a news like you want
2. The detail view will working correctly with realurl
3. Change the date of the news
4. The detail view will not be working. 
404 will be throw. Also if you delete the caches and the realurl tables, nothing work again. Any experience or infos about?

**Comment by georgringer** [comment]
I guess this is only if you have the date in the URL and course the URL is not valid anymore, same like changing the title. need to clear caches of realurl I guess. nothing I can do here.

**Comment by webdevsli** [comment]
No, i don't generate the url with the date into and to clear the caches has no effect. Can you help me to understand, why i have 3 or 4 entries for one news article? 

![bildschirmfoto 2017-06-13 um 10 03 23](https://user-images.githubusercontent.com/26410870/27072117-aad60300-501f-11e7-9f7c-632547ebab53.jpg)
