### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by kaufi02** [georgringer/news#355]
Hello!

The extension doesn't work with my postgresql database. Is there any way to fix it or is it only suitable with mysql?

Kind regards

**Comment by georgringer** [comment]
which TYPO3 version are you using? I use the regular DB API of TYPO3. Since CMS8, doctrine is used and should be fine for all extbase queries. However I do some custom queries as well, so would be happy to know what fails.

**Comment by kaufi02** [comment]
I'm using typo3 v8.7.2. First of all the installation works. But then, when you click on the News Andministration Panel there is an mysql Error: An exception occured in driver: MySQL server has gone away . Of course there is no mysql server because i'm using postgresql.

**Comment by kaufi02** [comment]
Any simple thing to fix this problem yet?

**Comment by sdelcroix** [comment]
It's because some custom queries use the old DatabaseConnection which only works with MySQL.
I'm trying to use adodb/dbal 8.4.0 as a workaround but have issues. 
@kaufi02 Did you try that ?

@georgringer Do you have any plans to replace custom queries with doctrine-dbal soon ? Or do you prefer to maintain some compatibility with TYPO3 7 until 9 is out ?

**Comment by georgringer** [comment]
I plan to still support 7 but imo could be possible with same code base. To you wanna do some pr for the issues

**Comment by sdelcroix** [comment]
I'd be happy to contribute but now I lack time and knowledge of the doctrine-dbal as we speak.
I'll give it a deep looking in future.

To be honest, I'm wondering how it could be possible to still support v7 with the same code base.
Would it need to add conditional statements of the TYPO3 version ? Or use a "wrapping" database connection that handles queries differently depending of the TYPO3 version ?
(sorry if these questions are naive, but I'm more an integrator than a developer)

**Comment by georgringer** [comment]
I would just check the TYPO3 version and the use some if/else ;)

**Comment by kaufi02** [comment]
@sdelcroix I'm afraid i did not. I already switched to another cms/framework

**Comment by sdelcroix** [comment]
@georgringer OK I see ;) I'll take a look at the parts that need to be rewritten when I get time.
@kaufi02 which one if you don't mind ?

**Comment by kaufi02** [comment]
@sdelcroix I'm using Django resp. Django CMS. More flexible to edit, in my opinion.

**Comment by georgringer** [comment]
I am closing this specific issue. work for support of doctrine DBAL with 9 is on its way
