### ISSUE TITLE
Content element preview causes "Invalid value" warning

### ISSUE THREAD

**Issue by fnagel** [georgringer/news#357]
When adding content elements, some display a warning about `INVALID VALUE ("some_element_type")`. This seems to happen for non core elements only, but not for all. I was not able to tell why. Integration of those CEs, incl. TCA, TS, TSconfig... everything seems almost identical.

Error is not present if `records.contentElementPreview` is disabled.

Any idea what I'm doing wrong here?

See this slack message for an screenshot: https://typo3.slack.com/messages/C03TG7QJT/p1493284220976149

Using TYPO3 8.7.2 and News 6.0.0

**Comment by kboss** [comment]
Just tried out News 6.1.0-dev on TYPO3 7.6.19 and the INVALID VALUE is still there.

**Comment by fnagel** [comment]
I'm using a custom `PageLayoutViewDrawItem` anyway so this is no longer an issue for my specific use case but I just tested v6.1.0 (with TYPO3 8.7.4) without my custom hook and the messages are still there. Seems not fixed yet.

**Comment by georgringer** [comment]
I can't reproduce that with various elements, therefore I am closing this issue until someone can build me an ext which shows the error.
