### ISSUE TITLE
Provide more data to fluid templates

### ISSUE THREAD

**Issue by georgringer** [georgringer/news#369]
It would be nice to add additional data to fluid templates, not only the current content element:

- TSFE->sys_language_uid
- TSFE->sys_language_content
- Current page

**Comment by DavidBruchmann** [comment]
Sure, wouldn't be bad but can be transferred to the templates by TypoScript only, can't it?
Question is if you still want to provide some feature perhaps on base of these data?

**Comment by georgringer** [comment]
IMO it can't be done by TS
