### ISSUE TITLE
Provide documentation for cropping

### ISSUE THREAD

**Issue by georgringer** [georgringer/news#371]
Add some documentation how to add cropping information to field `fal_media`

**Comment by wojtablo** [comment]
Ideally the documentation would relate to the description of [feature: #75880 ](https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.6/Feature-75880-ImplementMultipleCroppingVariantsInImageManipulationTool.html). For example answer question: how add multiple cropping variants

**Comment by Kleisli** [comment]
Hi @georgringer 
Can you give a little hint how to achieve this in a clean way? 
I managed it, by hacking the code below into the tx_news_domain_model_news-TCA file in ['fal_media']['config'], but I am unable to do it in a TCA/Overrides-File in my own extension.. :-(

```
'overrideChildTca' => [
    'columns' => [
        'crop' => [
            'config' => [
                'cropVariants' => [
                    'mobile' => [
                        'title' => 'Mobile',
                        'allowedAspectRatios' => [
                            '4:3' => [
                                'title' => '4 zu 3',
                                'value' => 4 / 3
                            ],
                            'NaN' => [
                                'title' => 'FREI',
                                'value' => 0.0
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
],
```
Vielen Dank und liebe Grüsse
Till

**Comment by Kleisli** [comment]
Nevermind, sometimes asking helps to find the solution yourself. :)

Here is a working (TYPO3 8.7 / news 6.0) snippet to have special cropping settings just for the news items, just create a file your_extension/Configuration/TCA/Overrides/tx_news_domain_model_news.php with 
```
<?php
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['fal_media']['config']['overrideChildTca']['columns']['crop'] = [
	'config' => [
		'cropVariants' => [
			'mobile' => [
				'title' => 'Mobile',
				'allowedAspectRatios' => [
					'4:3' => [
						'title' => '4 zu 3',
						'value' => 4 / 3
					],
					'NaN' => [
						'title' => 'FREI',
						'value' => 0.0
					],
				],
			],
		],
	],
];
```
and to use a specific cropVariant in your template add  cropVariant="mobile" to the f:image-viewhelper.

**Comment by wojtablo** [comment]
@Kleisli thanks, I've managed to do that by applying cropping conf globally

`TCEFORM.sys_file_reference.crop.config.cropVariants {
    default {
        title = Wariant domyślny
        selectedRatio = NaN
        allowedAspectRatios {
            NaN {
                title = Dowolna
                value = 0.0
            }
            21:9 {
                title = 21:9
                value = 2.3333333
            }
            16:9 {
                title = 16:9
                value = 1.7777777
            }
        }
    }
    special {
        title = Special variant
        selectedRatio = NaN
        allowedAspectRatios {
            NaN {
                title = Dowolna
                value = 0.0
            }
            21:9 {
                title = 21:9
                value = 2.3333333
            }
            16:9 {
                title = 16:9
                value = 1.7777777
            }
        }
    }
}`

**Comment by rowild** [comment]
@Kleisli Thanks, Till! For completeness, a fluid template example would be great, too.

**Comment by josefglatz** [comment]
### I will take over this task

As this is "just" an TYPO3 extension I would say it's not really the optimal place to add examples on how you can configure cropVariants in the TCA.

### But to get an compact overview for `EXT:news` I would suggest following:
- Howto set default cropVariants for `tx_news_domain_model_news.columns.column`
- Howto overwrite cropVariants for `tx_news_domain_model_news.columns.column` for a specific `tx_news_domain_model_news.type`

#### Each of the above mentioned points with:
- TCA configuration example
- Fluid example

---

*Does it suit almost everybody needs?* Did I forgot something?

**Comment by georgringer** [comment]
@josefglatz are you still interested in doing it?

**Comment by medarob** [comment]
@josefglatz @georgringer I just want to add some cropVariants to news images and I discovered this issue. Is a more detailed documentation about this topic still work in progress (I saw that the last entry is amlost 1 year old)? If not I will try it on my own and could share my findings.

**Comment by peterkraume** [comment]
I just tried to add an **additional** crop variant for images in the list view.

When using the above mentioned code snippet, the default cropVariants always vanished. So I ended up copying the default cropVariants from the TYPO3 core (typo3/sysext/backend/Classes/Form/Element/ImageManipulationElement.php) and then adding my stuff afterwards:

```
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['fal_media']['config']['overrideChildTca']['columns']['crop'] = [
    'config' => [
        'cropVariants' => [
            'default' => [
                'title' => 'LLL:EXT:core/Resources/Private/Language/locallang_wizards.xlf:imwizard.crop_variant.default',
                'allowedAspectRatios' => [
                    '16:9' => [
                        'title' => 'LLL:EXT:core/Resources/Private/Language/locallang_wizards.xlf:imwizard.ratio.16_9',
                        'value' => 16 / 9
                    ],
                    '3:2' => [
                        'title' => 'LLL:EXT:core/Resources/Private/Language/locallang_wizards.xlf:imwizard.ratio.3_2',
                        'value' => 3 / 2
                    ],
                    '4:3' => [
                        'title' => 'LLL:EXT:core/Resources/Private/Language/locallang_wizards.xlf:imwizard.ratio.4_3',
                        'value' => 4 / 3
                    ],
                    '1:1' => [
                        'title' => 'LLL:EXT:core/Resources/Private/Language/locallang_wizards.xlf:imwizard.ratio.1_1',
                        'value' => 1.0
                    ],
                    'NaN' => [
                        'title' => 'LLL:EXT:core/Resources/Private/Language/locallang_wizards.xlf:imwizard.ratio.free',
                        'value' => 0.0
                    ],
                ],
                'selectedRatio' => 'NaN',
                'cropArea' => [
                    'x' => 0.0,
                    'y' => 0.0,
                    'width' => 1.0,
                    'height' => 1.0,
                ],
            ],
            'newslistview' => [
                'title' => 'LLL:EXT:my_theme_ext/Resources/Private/Language/Tca.xlf:cropvariant.newslistview.title',
                'allowedAspectRatios' => [
                    '4:3' => [
                        'title' => 'LLL:EXT:core/Resources/Private/Language/locallang_wizards.xlf:imwizard.ratio.4_3',
                        'value' => 4 / 3
                    ],
                ],
            ],
        ],
    ],
];
```

Is this the way to go or is there a better solution?

By the way @josefglatz, I'd also appreciate a documentation of the cropVariants feature.

**Comment by georgringer** [comment]
I would go with extensions like melon_images, won't provide a documentation
