### ISSUE TITLE
Backend throws error

### ISSUE THREAD

**Issue by prentice87** [georgringer/news#375]
I upgraded (on a test system) from 7.6.20 to 8.7.3 using News 6.0.0 and Typo3 says everything is fine in general. When I got to the backend module "News" I get this error:

> #1407060572:` Fluid parse error in template Administration_action_index_08305693f47e8d10b7d380fb9961080bafd6dcc8, line 154 at character 1. Error: The ViewHelper "<n:be.multiEditLink>" could not be resolved. Based on your spelling, the system would load the class "GeorgRinger\News\ViewHelpers\Be\MultiEditLinkViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <n:be.buttons.icon uri="#" onclick="{n:be.multiEditLink(items:paginatedNews, columns:'title')}" icon="actions-document-open" /> (More information)
TYPO3Fluid\Fluid\Core\Parser\Exception thrown in file
/var/www/vhosts/scansail.de/typo3-sources/typo3_src-8.7.3/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php in line 156.

Any idea what I need to do? I cleared the cache and all the usual things.

**Comment by georgringer** [comment]
this ViewHelper is not used anymore, maybe you are using some old templates?

**Comment by mesurinna** [comment]
I am getting nearly same error : 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1407060572: Fluid parse error in template Administration_action_index_53c50d527c71e5b0901bae9ed7565cbfc8da3ee1, line 156 at character 1. Error: The ViewHelper "<n:be.multiEditLink>" could not be resolved. Based on your spelling, the system would load the class "GeorgRinger\News\ViewHelpers\Be\MultiEditLinkViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <n:be.buttons.icon uri="#" onclick="{n:be.multiEditLink(items:paginatedNews, columns:'title')}" icon="actions-document-open" /> | TYPO3Fluid\Fluid\Core\Parser\Exception thrown in file /var/www/t3sources/typo3_src-8.7.4/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php in line 156. Requested URL: https://TLD/typo3/index.php?M=web_NewsTxNewsM2&moduleToken=c80c32529b04bb4c32fa97cdf97aeb5f749c0b0a&id=1&

I am using TYPO3 8.7.4 News 6.1.0-dev.

**Comment by mesurinna** [comment]
Error can be reproduced if u copie all files under 

/typo3conf/ext/news/Resources/Private/Layouts
/typo3conf/ext/news/Resources/Private/Partials
/typo3conf/ext/news/Resources/Private/Templates 

to the fileadmin, and setting those Folders as your Root Folders. After deleting all files except those i edited, the error vanishs.

**Comment by georgringer** [comment]
The VH `n:be.multiEditLink` has been removed and is not used in any templates besides possibly your own which need to be adopted.
