### ISSUE TITLE
Date fields (crdate, date, tstamp) empty in related content elements array (within fluid template)

### ISSUE THREAD

**Issue by HVStechnik** [georgringer/news#382]
Dear community, dear Georg,

I'm a very passionate news fan and really like the extension. However, I encountered a strange behavior of the Related Content Element Feature:

**Setup**: PHP 7, Typo3 8.7.3, News: 6.0.0

**Issue**: I've the following code within my Detail.html fluid template to render related content elements within my detail view using inline fluid (following this example from the manual: https://docs.typo3.org/typo3cms/extensions/news/stable/singlehtml/Index.html#using-fluid). Within each content element's field array, the crdate field however is empty and nothing is shown for {element.crdate}. All the other date fields (tstamp, date) are empty as well, although all three fields are filled with date values in the database.

**Detail.html**
```html
    <f:if condition="{newsItem.contentElements}">
      <div class="obj_wrap style8">
        <f:for each="{newsItem.contentElements}" as="element">
          <p>
            <span class="font-bold color-red">{element.header} </span>
            {element.bodytext}
            <span class="comment-time">(<span class="timeago">{element.crdate}</span>)</span>
          </p>
        </f:for>
      </div>
    </f:if>
```
I tried to find the reason, why all the date fields are empty. But I can't find one within the news code. 
Does anyone know a reason or solution? Every hint is very much welcome!

Many thanks!
Max

**Comment by georgringer** [comment]
I guess because extbase misses some information in the tca about the field

**Comment by HVStechnik** [comment]
Unfortunately, I wasn't able to solve the problem so far. Do you think that this in a tca problem within the news extension or within fluid itself? Thanks, Max
