### ISSUE TITLE
Category created by user does not appear in list

### ISSUE THREAD

**Issue by melonmedia-zz** [georgringer/news#387]
The latest News extension version 6.0.0 is used in TYPO3 7.6.20. Further more an Editor role was customized that allows an editor user to maintain news records and also categories. Amongst others following settings were made for this role with respect to News extension:
<img width="665" alt="news_allwd_excld_fld" src="https://user-images.githubusercontent.com/30354615/28478735-f2496e22-6e59-11e7-8b78-a1ffe7304908.png">
So users of this role are authorized to create a new role through the back end, as it's illustrated by following screen shot:
<img width="619" alt="news_editor_create_category_view" src="https://user-images.githubusercontent.com/30354615/28478808-240d190e-6e5a-11e7-9822-e326bb65bcff.png">
In so doing a category creation leads to a weird side-effect. In case an editor creates a new category through above form, he's not able to select it's newly created category in a news entry under tab Options. Simply the new category is not displayed in the list for editor user. Only categories created by an administrator are displayed in that list correctly for the editor. Of course an administrator user can see all newly created categories. Please let me know if you want me to demo this issue.
Your help is very much appreciated.

**Comment by georgringer** [comment]
Can you compare categories created by editor and admin in the database if there is something which differs. without access to the system I don't have really a clue

**Comment by melonmedia** [comment]
Hey Georg, I can totally relate to that. So I checked table sys_category and created an INSERT SQL statement that represents two record sets. The first one (title = 20000) was created by the editor and the second one by the administrator (title = 2014-2015):
INSERT INTO `sys_category` (`uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `deleted`, `hidden`, `starttime`, `endtime`, `t3ver_oid`, `t3ver_id`, `t3ver_wsid`, `t3ver_label`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `t3_origuid`, `sorting`, `sys_language_uid`, `l10n_parent`, `l10n_diffsource`, `title`, `description`, `parent`, `items`, `fe_group`, `images`, `single_pid`, `shortcut`, `import_id`, `import_source`, `seo_title`, `seo_description`, `seo_headline`, `seo_text`) VALUES
(47, 82, 1503140382, 1503140371, 15, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 64, 0, 0, 0x613a343a7b733a353a227469746c65223b4e3b733a363a22706172656e74223b4e3b733a31313a226465736372697074696f6e223b4e3b733a353a226974656d73223b4e3b7d, '20000', '', 0, 0, '0', 0, 0, 0, '', '', '', NULL, '', NULL),
(39, 82, 1468600465, 1467660784, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 1024, 0, 0, '', '2014-2015', '', 0, 0, '0', 0, 0, 0, '113', 'TT_NEWS_CATEGORY_IMPORT', '', NULL, '', NULL);

Obviously a value for column import_source was not defined for the editor's record set. If the administrator creates a record set it defines the value TT_NEWS_CATEGORY_IMPORT automatically. So I tried to set this value but it does not change anything. 

Though I browsed around a bit and figured out, that new categories are always unchecked in section Category Mounts of a user-group. So if a user of this user-group creates a category it's unchecked initially and only if an administrator ticks that checkbox it's visible for the editor.
<img width="289" alt="categorymount" src="https://user-images.githubusercontent.com/30354615/29486437-f3ce1f8e-84e5-11e7-99e8-acb21c97fab8.png">
After I ticked that flag I can not see any real difference in database table sys-category only the tstamp value was updated but that should not make any difference.

**Comment by georgringer** [comment]
Can you do another test: After an editor creates a category, clear the tables  `cf_cache_news_category` and `cf_cache_news_category_tags` and retry. thanks for feedback!

**Comment by melonmedia** [comment]
Hey @georgringer I cleared both tables and checked whether the newly created category is displayed. Unfortunately the situation is the same as before. Categories created by the editor are not displayed in the tab Options. Would you like to have system access?

**Comment by greiling** [comment]
Same issue in my environment: TYPO3 7.6.23 || news 6.1.1: 
But I fiddled out: **uid**s > 19 will not be displayed for editors. There must be a configuration in tx_news overwriting the defaults for category tree listing. No differences in category records - manually modifying the **uid** to higher or lower values returns different trees. No problems viewing as an adminstrator.

**Comment by greiling** [comment]
It works fine!
But- it wasn't the point ... sorry ...
Categories have to be defined in be_group -> "Mounts and Workspaces" -> "Category Mounts" 
Even an editor enabled to set a new one, won't see it until it is blessed by admin if it is put in category root. A category set as a child to a blessed categorie works fine. Lesson learned...

**Comment by georgringer** [comment]
the issue is too old and can't be reproduced anymore. feel free to reopen a new issue if still valid
