### ISSUE TITLE
Content_element Inline option breaks system, if tt_content table is huge

### ISSUE THREAD

**Issue by AnuBN** [georgringer/news#388]
Hello..
Your extension is great, by the way. I recently installed tx_news v6.0.0 in my TYPO3 8.7.3 system. When 'Use content element relation' is checked in plugin settings, I tried to localize a news record. 
My system contains around 4,50,000 content elements.  Suddenly backend breaks with an exception 
`Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT `uid` FROM `tt_content` WHERE (`pid` = ?) AND (`uid` IN (?, ?, ?, ?, ### HERE ARE AROUND 4,50,000 PLACEHOLDERS!### , ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?))  ASC' with params [-1, 6877, ... ###HERE ARE AROUND 4,50,000 IDS!###, 0] Too many placeholders`

When I unchecked the option, every thing works perfectly.  What if I want to use inline content elements in news record with this much of content elements in system

**Comment by georgringer** [comment]
I don't really do this query in the extension itself, so I am sorry but this seems to be some core issue. as long as it is not fixed, just uncheck the option. sorry for that.

**Comment by AnuBN** [comment]
Reported as a core issue in TYPO3 forge. [Bug #81993](https://forge.typo3.org/issues/81993) .Thanks for your feedback.
