### ISSUE TITLE
SimplePrevNextViewHelper with custom sortField doesn't work

### ISSUE THREAD

**Issue by alsodenn** [georgringer/news#394]
If you set "sorting" or "title" as Sortfield then you get an error:

`Call to a member function getTimeStamp() on integer `

Because of line 191 of the Viewhelper:
`$whereClause .= sprintf(' AND %s %s %s', $sortField, $selector, $news->$getter()->getTimeStamp());`

A "title" or "sorting" has no TimeStamp...

**Comment by georgringer** [comment]
do you want to create a PR for that?

**Comment by ayacoo** [comment]
`            $whereClause .= sprintf(' AND %s %s "%s"', $sortField, $selector, $news->$getter());
            if (method_exists($news->$getter(), 'getTimestamp')) {
                $whereClause .= sprintf(' AND %s %s %s', $sortField, $selector, $news->$getter()->getTimestamp());
            }`

Is this maybe a solution?
- method_exists -> (PHP 4, PHP 5, PHP 7)
- String is default. If there is a integer, then set a integer

**Comment by georgringer** [comment]
maybe just check if the object is from type datetime, then use the getTimeStamp, otherwise just use it as it is and yes security is a must

**Comment by georgringer** [comment]
merged
