### ISSUE TITLE
enablePreviewOfHiddenRecords documentation

### ISSUE THREAD

**Issue by prdt3e** [georgringer/news#395]
https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Configuration/TypoScript/Index.html#previewhiddenrecords

Dont't work: plugin.tx_news.settings.enablePreviewOfHiddenRecords =1
Work fine: plugin.tx_news.settings.previewHiddenRecords = 1

**Comment by medarob** [comment]
I use this feature and saw that I still use `plugin.tx_news.settings.enablePreviewOfHiddenRecords =1` and it works.

I changed it to `plugin.tx_news.settings.previewHiddenRecords = 1` but then I got `Dieser Artikel ist nicht mehr verfügbar.`

Why is `plugin.tx_news.settings.previewHiddenRecords = 1` not working?

**Comment by prdt3e** [comment]
[https://github.com/georgringer/news/issues/500](#500 )
