### ISSUE TITLE
Add posibility of using image of backenduser

### ISSUE THREAD

**Issue by dpfahlbusch** [georgringer/news#401]
Is there a possibility that there will be a feature, which makes it possible to use the image of the backend user as image for the author of the news?

Like the prefill-feature for user and email?

**Comment by georgringer** [comment]
As there is currently no image field for the author and I don't plan to add that, I would say that this feature won't come into ext itself, however it would be easy to add that as custom extension. if you want me to develop that, contact me via slack/email
