### ISSUE TITLE
typo3 8.7 + tx_news

### ISSUE THREAD

**Issue by Finulin** [georgringer/news#405]
Hi, with Typo3 7.6 i can use TS to implement news in my footer:

``` 
page.10.variables{
	newsFooter < tt_content.list.20.news_pi1
	newsFooter {
		action = list
		switchableControllerActions.News.1 = list
		
		view {
			templateRootPaths >
			templateRootPaths {
				0 = EXT:news/Resources/Private/Templates/
				1 = EXT:uk_bootstrap_scrolling_nav/Resources/Private/Templates/news-footer/
			}
			partialRootPaths >
			partialRootPaths {
				0 = EXT:news/Resources/Private/Partials/
				1 = EXT:uk_bootstrap_scrolling_nav/Resources/Private/Partials/news-footer/
			}
			layoutRootPaths >
			layoutRootPaths {
				0 = EXT:news/Resources/Private/Layouts/
				1 = EXT:uk_bootstrap_scrolling_nav/Resources/Private/Layouts/news-footer/
			}
		}
		settings {
			limit = 3
			startingpoint = 11
			detailPid = 10
			hidePagination = 1
		}
	}
}
``` 
With Typo3 8.7 it shows the wrong Template on the same site with the inserted Plugin. All other site shows the correct template. Is this a bug or need i a special configuration?

Here are a example:
correct template view in footer:
https://t3.beritida.de/de/home/sichtweisen/
wrong template view in footer:
https://t3.beritida.de/de/aktuelles/

Thanks a lot for help

**Comment by georgringer** [comment]
that sounds like a regression in fluid. try with latest core version, however nothing special in news done in that regard
