### ISSUE TITLE
error message when adding a html CE to Container "Inhaltselemente"

### ISSUE THREAD

**Issue by blueamerican** [georgringer/news#406]
In the BE i get the message:
WERT IST NICHT ERLAUBT ("html")
see attached screen.

TYPO3 8.7.4
news 6.0.0
i've tested this on two environements

![news](https://user-images.githubusercontent.com/5647051/29553230-a6ae3144-871a-11e7-9292-afdfd942ebeb.jpg)

**Comment by blueamerican** [comment]
works in 6.0.1dev

**Comment by h3nn3s** [comment]
Hmm. 
I run in the same issue. HTML is not allowed in version 6.0.0 nor in 6.1.1

**Comment by georgringer** [comment]
can you check out master? thx

**Comment by Chriz74** [comment]
same here :(
TYPO3 7.6.23
news 6.1.1
Every CE under "Standard" is allowed. Others not (like HTML or own Mask-Elements).

**Comment by blueamerican** [comment]
same error in TYPO3 7.6.20
news 6.1.1
Error message in BE is shown: Wert ist nicht erlaubt ("html")
But the html CE works in the FE.

**Comment by georgringer** [comment]
duplicate of https://github.com/georgringer/news/issues/357
