### ISSUE TITLE
News records get wrong single pid URL in solr core for multilingual installation

### ISSUE THREAD

**Issue by AlexPixelant** [georgringer/news#412]
Typo3: 8.7.4
News: 5.3.3
Solr: 6.1.0

I have multilingual installation and news records which some of them are localized, and some of them are not. I faced situation when solr is indexing records correctly but urls are wrong.
plugin.tx_solr.index.queue.news.fields.url.typolink.parameter = myDetailPid
myDetailPid (single view page) is localized.

Scenario:
On my installation I have 4 languages: English (Default), Swedish, German, Dutch.
Content, title, teaser in German. But url is wrong, I got dutch single view page (/nl/nieuws/artikel/) instead of german one (/de/nachrichten/artikel/). Also indexing is correct as I got only German news records in German sorl core, Swedish news in Swedish solr core, so on.

Is it news extension bug or maybe missconfiguration? I have tried to play around with sys_language_mode but no effect.

**Comment by georgringer** [comment]
that is either a misconfiguration or an issue in solr, nothing in news
