### ISSUE TITLE
Search not working with pageNotFoundOnCHashError

### ISSUE THREAD

**Issue by SventB** [georgringer/news#413]
When activating option "pageNotFoundOnCHashError", the search plugin is not working, it is showing the 404 page after submitting the search form.

I'm using TYPO3 8.7.4 and news 6.0.0.
With TYPO3 7.6.21 and news 5.3.2 it seems fine.

**Comment by SventB** [comment]
By adding an arbitrary parameter (e.g. `<f:form arguments="{dummy: 1}" ...>`, a cHash is added to the form action and the error doesn't occure. This seems to be more a Fluid/Extbase bug.

**Comment by georgringer** [comment]
as this seems to be a fluid/Extbase bug I am closing this issue. somehow related issue https://github.com/georgringer/news/issues/433
