### ISSUE TITLE
expose / make templateLayout accessible

### ISSUE THREAD

**Issue by DanielRuf** [georgringer/news#416]
By default the `templateLayout` value is in the pi_flexform XML string but it would be good to have it already available in cases where you can not use Flux and only Fluid (directly in a template).

Otherwise it would be much harder to work with this one on a higher level as you would have to parse it in a controller / class file and deliver it to the view.

The values are in pi_flexform but not directly exposed in data or settings, eg `settings.categories` and the aforementioned `templateLayout` field.

**Comment by georgringer** [comment]
Sorry but I don't really get what you want. You can get the variable with `{settings.templateLayout}`. You can also set this variable in TS if you include the plugin just by TS.

I never used flux.

**Comment by DanielRuf** [comment]
When I try to access a content element which is a news record from the outside I just get some `pi_flexform` with some XML form / Flux but I can not directly access `templateLayout` from there, just if I would process the `pi_flexform` somehow which is not possible with only Fluid.

**Comment by georgringer** [comment]
Sorry but I don't see that as use case in news but project specific. Use a data processor or a vh (maybe vhs got one).

**Comment by DanielRuf** [comment]
We have a real use case here now.

We have some special list templates which need the header in the partial / template.

But the fsc Wrapper is around it which also outputs the header.
There is no way to determine that we deal with the specific templateLayout and thus we have the header twice.

Checking by list_type and CType is not enough here to be sure that we fetch the layoutTemplate and do not render the header in the wrapping fsc.

**Comment by DanielRuf** [comment]
So far I did not find a direct solution using vh. cc @NamelessCoder

**Comment by georgringer** [comment]
You can now access btw flexform data with stdwrap directly
