### ISSUE TITLE
not officially compatible anymore?

### ISSUE THREAD

**Issue by DanielRuf** [georgringer/news#417]
https://extensions.typo3.org/extension/news/
> Outdated extension This extension supports none of the currently supported TYPO3 core version

Was there some change related to the supported TYPO3 versions?

**Comment by chesio** [comment]
I guess this has been a temporary state due https://typo3.org/teams/security/security-bulletins/psa/typo3-psa-2017-001/

Version 6.1.1 is out since yesterday and works with TYPO3 7.6.13 - 8.7.99 as before the accident.

**Comment by DanielRuf** [comment]
It seems so. I'll lose this issue now.
