### ISSUE TITLE
Feature to disable/enable "Localization" field in the news list backend module.

### ISSUE THREAD

**Issue by arunspawoz** [georgringer/news#420]
Currently, there is no option to disable/enable the "Localization" field in the news list backend module.
Please see the screen below;

![news_modulelist 1](https://user-images.githubusercontent.com/20816321/30213267-f207bcce-94c5-11e7-93d9-b936e7ed10d7.png)

Please add a feature to manage this field.

Thank you.

**Comment by georgringer** [comment]
fixed
