### ISSUE TITLE
Add hint for FSC (Fluid-Styled-Content) to the RSS part of documentation

### ISSUE THREAD

**Issue by freshworkx** [georgringer/news#425]
To get a correct rendered RSS XML document in the frontend it´s necessary to adjust the layout path of fluidContent and provide a template without the "wrapping" things. This prevent an xml error like "XML declaration allowed only at the start of the document"

Please extend the RSS documentation part:

`lib.fluidContent {
    layoutRootPaths {
        10 = ext_sitepackage/Resources/Private/Layouts
    }
}`

**Comment by georgringer** [comment]
fixed
