### ISSUE TITLE
Extend news table - error 'Cannot access empty property'

### ISSUE THREAD

**Issue by p380** [georgringer/news#426]
Is there an example of a module or code to add a new field to the news table. The new field should be displayed from another custom module.

I tried to add following instructions, for example: https://github.com/cyberhouse/t3ext-newsauthor

if I set in the fluid <f: debug> {_ all} </ f: debug> displays additional fields from the custom module
in the debugger, displays as (persistent entity) with other (child) fields

how to define in the fluid to get a custom field from 'persistent entity'

kind regards

**Comment by georgringer** [comment]
e.g. https://github.com/georgringer/news_feuser
