### ISSUE TITLE
Problem with Predefine and Access

### ISSUE THREAD

**Issue by Power-Poler** [georgringer/news#427]
Hello,
I Install your extension. Now I try you set a Backend user for the Newsletter.
I use the following TsConfig:
tx_news.predefine.author = 1
tx_news.predefine.archive = +1 week
The new user have no access to the 3 predefine fields
If I login as the new user end create a new News, its all ok, the 3 fields are not visible.
If I go back to admin and lock in the new news, the 3 fields are emty. 
Make I a mistake?
Thanks for your Answere.

Laut deinem Profil kannst du Deutsch. Und da ich nicht gut englisch schreiben kann (lesen geht) schreibe ich mein Anliegen nochmal auf Deutsch, für den Fall das ich nur quatsch geschrieben habe :D. 

Ich möchte einen Backend user anlegen, der für die News verantwortlich ist.
Da dieser nur erstellen soll, aber kein Ablaufdatum oder anderen Namen setzen soll, habe ich die oben genannten Felder vor definiert.
In den Gruppen Einstellungen Felder für Archiv, Autor und E-mail nicht gesetzt (Er soll diese ja nicht bearbeiten)
Wenn ich jetzt als User eine News erstelle, ist alles wie es sein soll. erstellen Ja, die 3 Felder setzen, Nein.
Anschließend zurück auf dem Admin, die neue News Angeklickt, um die Felder zu Kontrolliren. Welche aber leider nicht gesetzt sind.
Wenn ich dem User Zugang zu den Feldern gewähre, werden diese natürlich bei User angezeigt, und beim Speichern auch gesetzt.
Mache ich einen Fehler?

Schonmal Danke für deine Antwort.
Mfg
Power-Poler

**Comment by georgringer** [comment]
The predifne works only if the user has got access to the field. if you don't want that, you must use a custom hook of the DataHandler to add such content to hidden fields
