### ISSUE TITLE
News Administration filter fields are gone on v6.1.1

### ISSUE THREAD

**Issue by josericardojunior** [georgringer/news#428]
After upgrading the news from version 6.0.0 to 6.1.1, the fields of the filter on admin module are not shown (only the 'search' button appears):

![image](https://user-images.githubusercontent.com/3043186/30502368-52aacea6-9a3c-11e7-96f3-47d35c173010.png)

**Comment by georgringer** [comment]
have you cleared caches? the file app/web/typo3conf/ext/news/Configuration/TSconfig/Administration.txt must be included, otherwise add its content to your tsconfig yourself

**Comment by josericardojunior** [comment]
Found the problem, there was an extension we're using that extends the AdministrationController but didn't updated the code. 

The TSConfig file wasn't included, but it worked before. Gonna insert it anyway. Thanks for the attention and sorry for opening the issue without a more deep analysis.

**Comment by georgringer** [comment]
thx for the update. all fine ;)
