### ISSUE TITLE
Icons should be registered in ext_tables.php file

### ISSUE THREAD

**Issue by morinfa** [georgringer/news#431]
When registered from ext_localconf.php file, the instantiation of IconRegistry class makes icons from other extensions fails to be displayed in the backend.
I guess this has to do with the handling of $GLOBALS['TCA'] in IconRegistry::initialize function.
When registered from ext_tables.php file, it is ok.

**Comment by georgringer** [comment]
I am not sure that this is correct, IMO the bug you have is somewhere else, because icon registration must be done in ext_localconf.

**Comment by morinfa** [comment]
If you look in workspaces module, it is done in ext_tables.php file.

**Comment by georgringer** [comment]
changed with https://review.typo3.org/#/c/54020/
