### ISSUE TITLE
It's not possible to localize FAL relations

### ISSUE THREAD

**Issue by weber-ebusiness** [georgringer/news#434]
If you localize a news record and then try to localize an image by pressing the "Localize all records" button, nothing happens.

![screenshot](https://user-images.githubusercontent.com/5400807/30753960-3520d71a-9fc1-11e7-8dcb-de05cdb25922.png)

**Comment by cptnk** [comment]
I have the same problem I added a pull request here.

[https://github.com/georgringer/news/pull/430](https://github.com/georgringer/news/pull/430)

**Comment by kevinlieser** [comment]
Having the same issue. Added some "additional Files" to my news. Using english as default and german as additional language. Translated the news, added the files in german but still showing the english related files in my german news post.

Also have no idea what the setting "translation behavior" is for...

![bildschirmfoto 2017-09-28 um 23 15 16](https://user-images.githubusercontent.com/17568217/30990837-01894cfc-a4a3-11e7-941f-e7e3178b3ef9.png)

**Comment by cptnk** [comment]
@kevinlieser Having translated file relations works for me. I still have a issue with FAL within the content elements, though. 

Can you elaborate how you set up the plugin? 
In my case I have a detail page with the plugin/detail embed in and a separate plugin/list view. 

These both have alternative page languages defined. Within the List setting I also set the PID as to where the detail view is located.

**Comment by georgringer** [comment]
this is a core issue, please use https://extensions.typo3.org/extension/repair_translation/ to solve it.

**Comment by kevinlieser** [comment]
I will try that! Thanks a lot!
