### ISSUE TITLE
[Question] Database field for title not long enough

### ISSUE THREAD

**Issue by Schnoop** [georgringer/news#438]
Version: 6.1.1

Hi there,

i have to import a lot of existing news into your news system. Some news titles are longer than 255 character, so the import will fail. What would be the best way to change the field from TINYTEXT to TEXT?

**Comment by georgringer** [comment]
I would say a PR ;)

**Comment by Schnoop** [comment]
Hehe :)

That would definitely fix my problem.

But i thought about a fix for my use case only, not the big thing.

**Comment by georgringer** [comment]
custom extension and changing the field there
