### ISSUE TITLE
dd_googlesitemap ignores sys_categories set to tx_news

### ISSUE THREAD

**Issue by gg-philipp-duell** [georgringer/news#440]
TYPO3 7.6.12
tx_news 4.3.0
dd_googlesitemap 2.1.3

Sitemaps generated from tx_news ignore sys_categories.
I got various news detail-pages which show only news from one sys_category. All news are stored in one sys-folder.
So creating sitemaps with dd_googlesitemaps from the news will generate different sitemaps with all news in each of this sitemaps.

e.g. using htaccess like this:
sitemap-newscat1.xml$ /index.php?eID=dd_googlesitemap&id=1&sitemap=txnews&singlePid=123&pidList=99&L=0
sitemap-newscat2.xml$ /index.php?eID=dd_googlesitemap&id=1&sitemap=txnews&singlePid=456&pidList=99&L=0

will generate sitemaps like:
**sitemap-newscat1**
```
<url>
<loc>https://www.domain.tld/path/detailpage123/example-news-title1-withcat1</loc><lastmod>2017-05-19T00:00:00+02:00</lastmod>
</url>
<url>
<loc>https://www.domain.tld/path/detailpage123/example-news-title2-withcat1</loc><lastmod>2017-05-19T00:00:00+02:00</lastmod>
</url>
<url>
<loc>https://www.domain.tld/path/detailpage123/example-news-title3-withcat2</loc><lastmod>2017-05-19T00:00:00+02:00</lastmod>
</url>
```

**sitemap-newscat2**
```
<url>
<loc>https://www.domain.tld/path/detailpage456/example-news-title1-withcat1</loc><lastmod>2017-05-19T00:00:00+02:00</lastmod>
</url>
<url>
<loc>https://www.domain.tld/path/detailpage456/example-news-title2-withcat1</loc><lastmod>2017-05-19T00:00:00+02:00</lastmod>
</url>
<url>
<loc>https://www.domain.tld/path/detailpage456/example-news-title3-withcat2</loc><lastmod>2017-05-19T00:00:00+02:00</lastmod>
</url>
```

but it should be
**sitemap-newscat1**
```
<url>
<loc>https://www.domain.tld/path/detailpage123/example-news-title1-withcat1</loc><lastmod>2017-05-19T00:00:00+02:00</lastmod>
</url>
<url>
<loc>https://www.domain.tld/path/detailpage123/example-news-title2-withcat1</loc><lastmod>2017-05-19T00:00:00+02:00</lastmod>
</url>
```

**sitemap-newscat2**
```
<url>
<loc>https://www.domain.tld/path/detailpage456/example-news-title3-withcat2</loc><lastmod>2017-05-19T00:00:00+02:00</lastmod>
</url>
```

Got any ideas on how to get different sitemaps for news on different detail-pages with different sys_categories?

**Comment by georgringer** [comment]
Can you test with the following changed method in `TxNewsSitemapGenerator`?

```
protected function getSinglePidFromCategory($newsId)
    {

        $query = 'SELECT sys_category.title,sys_category.single_pid
                    FROM tx_news_domain_model_news 
	                    LEFT JOIN  sys_category_record_mm on sys_category_record_mm.uid_foreign=tx_news_domain_model_news.uid 
                        LEFT JOIN sys_category ON sys_category_record_mm.uid_local = sys_category.uid
                    WHERE sys_category.deleted=0 AND sys_category.hidden=0 
                        AND sys_category_record_mm.tablenames="tx_news_domain_model_news"
                        AND sys_category.single_pid > 0 AND sys_category_record_mm.uid_foreign = ' . (int)$newsId . '
                    LIMIT 1
                   ';
        $res = $this->getDatabaseConnection()->sql_query($query);

        $categoryRecord = $this->getDatabaseConnection()->sql_fetch_assoc($res);

        return $categoryRecord['single_pid'] ?: null;
    }
```

**Comment by gg-philipp-duell** [comment]
Georg,
thank you very much. Sorry for not responding so long.
Tested this, and i still get all news in all sitemaps. 
News A has Categories 1,2,3
News B has Categories 4,5

Sitemap for Category 1 News:
- path/category1/News A
- path/category1/News B

Sitemap vor Category 2 News:
- path/category2/News A
- path/category2/News B

...

Sitemap vor Category 5 News:
- path/category5/News A
- path/category5/News B

Do you see any posibility to use the "firstCategory" for generating sitemaps?

I really appreciate your work on the news extension!

**Comment by georgringer** [comment]
there is no ordering you can influence regarding "first" category ... sorry
