### ISSUE TITLE
News archive template not working

### ISSUE THREAD

**Issue by ElSteffe** [georgringer/news#443]
Hello there,

in the german newsgroup. I've been advised me to post my problem here.

At first sight, it seemed to be an easy templating problem. Unfortunately, the documentation didn't lead to a solution.

Since T3 8.5 LTS, our news archive is displayed in a wrong way. The documentation hasn't really helped yet.

We updated to T3 8.7 LTS and use News 6.1.1, the site can be seen at  http://www.pfaelzischer-schachbund.de/thomas/psb_ganzneu/newsarchiv.html.

I'd like to get an archive with the year blocks at the top (already ok) followed by the listed titles of the news. The first 20 news are displayed by "max records".
Clicking a special month, this month shall be displayed in the same way. 

Up to now, we took two news modules for this page - one with a date menu view followeed by one with a list view. This works under T3 7.6 LTS / news 4.2.1 as can be seen at   http://www.pfaelzischer-schachbund.de/psb/newsarchiv.html.

I don't wanna update under 7.6. Makes no sense since the the archive doesn't work as expected. Also, we'd like to switch to 8.7 so better get it fully working there :-).  
 
Now the problem is that our template "Archivelist.html" seems to be consequently ignored. It's mentioned in the module under "Template" and placed where the Item.html is (Partials/List), but the code says that List.html is displayed instead...which is placed somewhere completely different.  
So I tried putting the Archivelist.html it into Templates/News, that doesn't work either.
My next idea was using both - i.e. <f:render partial="List/Archivelist.html" [...]> in the file under Templates/News...again no success.

I tried using an own template name as well, but I guess that was a step too much (?!) as I only want to render a different file using the list view.

Of course newer module versions mostly include changes. I think if  I've just missed something relevant, or is it really a bug ?  Can anyone help me ?

Thank you very much in advance  for all hints,

Steffen

**Comment by georgringer** [comment]
Thanks for creating the issue. without any code how you set and check the template it is impossible to support.

**Comment by ElSteffe** [comment]
Up to now, I think I didn't need any extra code. The template file is in the same folder where the Item.html is and I choose it in the module where I want it to be rendered for FE.

The result is fine: clicking a month in the DateMenu (where I mentioned to show the list on the same page), the list of dates and titles is showing up under the DateMenu.

Now, this doesn't work anymore. The files are the same as before. Maybe something has changed and I just don't find it or can't reproduce the hints in the manual. To be honest, I'm rather helpless at this point.

**Comment by georgringer** [comment]
So you try to load a custom partial which does not work? Than I guess your ts regarding template root paths is wrong

**Comment by ElSteffe** [comment]
Yes. I copied the module template folder structure to fileadmin, so the path is the same as with the item.html-file: fileadmin/templates/main/news/Partials/List, The path is mentioned in the TS setup and it even is the same base layout ("General").

I just looked up the html code in the FE again and have seen that, when a news is loaded on the archive page, now the Partials/List/Item.html is displayed...either I misread it when starting the thread or the system changed it without me having done anything (which I don't believe). Sorry for that mistake, maybe this clarifies something.

Strange anyway since, without knowing the template, nothing should be displayed (?!). So the module seems to know the path, it just ignores the archive template file. I already tried to mentioned both files separately in the Setup, but it doesn't work...I don't wonder about that - regarding the path, it should just be a different partial.

Confusion is total *lol*.

**Comment by georgringer** [comment]
sorry I don't get it, is it now fixed for you?

**Comment by ElSteffe** [comment]
unfortunately not, but maybe we find another "interim" solution choosing the item.html

In the detail view of older news, the preview picture is additionally displayed in some kind of footer in this way:

[back-link]
picture
-->

It seems to be a default news-img-wrap with a css-class called "mediaelement mediaelement-image". I don't need it there, but can't find any related code in the template. I outcommented the whole footer and generally don't use the preview anymore. We had a few problems with it and decided to to place the pics at the beginning of the text.

Looking through all the news would be a bit too much - and if someone wants to "reactivate" the preview pics, this starts agian. 

Can you tell me, why the module shows these pictures this way and how I can avoid it?

**Comment by georgringer** [comment]
This is done in `Resources/Private/Partials/Detail/MediaImage.html`.
