### ISSUE TITLE
Category selection/restriction for news detail view?

### ISSUE THREAD

**Issue by mmunz** [georgringer/news#445]
At the moment there is no possibility to restrict news showable in detail view to certain categories. That means, that possibly all news can be opened on one Detail page once a link was initially generated to the article. 

Use case: On a multisite it is possible to show news from different sites selecting the appropriate categories. But if we want to stop showing news from one category and remove the checkmark from the news categories, the news disappears in list views, but is still available with the known url on the detail view page.

So, would it make sense to also add category constraints to detail views (configurable via TypoScript and Flexform in the Backend)?

**Comment by georgringer** [comment]
thanks for reporting the issue. I would be in favor of doing a separate extension using the signal in the detailAction. If you need (paid) help for that, feel to get in contact with me
