### ISSUE TITLE
Update ical Configuration in manual for TYPO3 V8

### ISSUE THREAD

**Issue by anderlk** [georgringer/news#455]
The ical configuration described as https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/BestPractice/ICalendar/Index.html
not working on TYPO3 V8 because the additionalHeaders has changed.

The correct V8 Configuration is.

`[globalVar = TSFE:type = 9819]
config {
    disableAllHeaderCode = 1
    xhtml_cleaning = none
    admPanel = 0
    metaCharset = utf-8
    additionalHeaders.10.header = Content-Type:text/calendar;charset=utf-8
    disablePrefixComment = 1
}`

**Comment by 3615Yeye** [comment]
Works for me, thank you ;)
