### ISSUE TITLE
wrapping n:link not working as expected

### ISSUE THREAD

**Issue by DanielRuf** [georgringer/news#460]
Wrapping the LinkViewHelper around other tags directly closes the tag and places it over the others.

So something like `<n:link><article>...</article></n:link>` produced `<a href="..."></a><article></article>`.

**Comment by georgringer** [comment]
Sorry I can't reproduce that, having code like this
```
<n:link newsItem="{newsItem}" settings="{settings}" title="{newsItem.title}">
	<article><h3>{newsItem.title}</h3>
	</article>
</n:link>
```

works as expected. can you reproduce that on a clean installation without any possible magic?

**Comment by DanielRuf** [comment]
I had other viewhelpers in there like `f:`, `v:` and so on. But this did not work as expected.

**Comment by georgringer** [comment]
can you debug that a little but IMO it is not news

**Comment by DanielRuf** [comment]
Sure, will do so when I come to the news / events component in our project.

Other solutions like f:link and typolink work without any issues. This just happened in combination with the news extension afaik.

**Comment by georgringer** [comment]
I am closing this issue because of lack of feedback and because I can't reproduce that. Feel free to reopen if still valid
