### ISSUE TITLE
URL parameter for search

### ISSUE THREAD

**Issue by thomasengl** [georgringer/news#462]
Hi there,
is it possible to pass the search term to the URL of the search results page?
I'm trying to find a way to get back to the list of search results after opening one of the results in detail view (e.g. when using the back button of the browser or going back by window.history.back();).
Thanks!

**Comment by georgringer** [comment]
I would use JS by writing the search word into the local storage if a user clicks on a detail view link of the search results and if a user then uses a back button or back link, I would prefil the form and just submit it via JS. I don't plan any changes in that regard in the extension.
