### ISSUE TITLE
search in translations

### ISSUE THREAD

**Issue by FlorianX** [georgringer/news#464]
# Preconditions:
* TYPO3 v7.6
* News: 6.0.0
* Languages 
** German = Default = 0
** English = 1

# Testdata
* one news entry in DE and translated in EN
** Word in Title/Teaser/Body
*** DE: "testDe"
*** EN: "testEn"

# UseCase:
* Searching in EN with "testEn" leads to no search results.
* Searching in EN with "testDe" leads to the news entry shown in EN

# Debug
The search query looks like:

```
SELECT *
FROM tx_news_domain_model_news
WHERE
  (
    tx_news_domain_model_news.pid IN (205)
    AND
    (
      (
        tx_news_domain_model_news.teaser LIKE '%testEn%'
        OR tx_news_domain_model_news.title LIKE '%testEn%'
      )
      OR tx_news_domain_model_news.bodytext LIKE '%testEn%'
    )
  )
  AND
  (
    tx_news_domain_model_news.type = '0'
      OR tx_news_domain_model_news.type = '1'
      OR tx_news_domain_model_news.type = '2'
  )
  AND
  (
    tx_news_domain_model_news.sys_language_uid = -1
    OR
    (
      tx_news_domain_model_news.sys_language_uid = 1
      AND tx_news_domain_model_news.l10n_parent = 0
    )
    OR
    (
      tx_news_domain_model_news.sys_language_uid=0
      AND tx_news_domain_model_news.uid IN
        (
          SELECT tx_news_domain_model_news.l10n_parent
            FROM tx_news_domain_model_news
            WHERE tx_news_domain_model_news.l10n_parent>0
                  AND tx_news_domain_model_news.sys_language_uid=1
                  AND tx_news_domain_model_news.deleted=0
        )
    )
  )
```

The language query parts select only entries with language setting set to
* all
* entries created only in EN with no l10n_parent
* and DE entries which have translations in EN

But the EN entries aren't selected and so the EN text of this entries isn't searched through.

Is this a bug of the extension or of extbase?

Thanks for your help!

**Comment by georgringer** [comment]
this is extbase as the overlay happens there. it could be changed in the extension to search by a direct query, returning the uids of the records only and use that to fetch the news records

**Comment by georgringer** [comment]
actually I don't plan to do change this, as it is TYPO3 behaviour. if you need it, feel free to sponsor a custom extension developing that.

**Comment by maechler** [comment]
@FlorianX We are having the same issue. As the bug lies within Extbase we are also having the issue in our own extensions. I did only find an issue about how flawed the language handling in Extbase is in general (https://forge.typo3.org/issues/77298 ), but nothing explicitly mentioning this error.
Did you find another issue or did you come up with a good solution to this?

**Comment by maechler** [comment]
@FlorianX @georgringer 
I created a quite limited fix for that problem: https://gist.github.com/maechler/258f06f170c7138500e1a3c4a9b12725

It does only work when all the fields that you want to search e.g. title or categories are also set on the translated record. Although it solves not all the localization problems (which is quite a nightmare) it should be useful in certain use cases.
