### ISSUE TITLE
No preview image in list view mode

### ISSUE THREAD

**Issue by Sonezi** [georgringer/news#471]
Hello, 
i am using news extension normally in list view plugin mode, dummy image is showing no matter what.
What i mean by this, even if I add content elements or media relations to news, i can't get the preview image to be other then dummy. Typo CMS 8.7.7 and news ext 6.1.1. I tried to set the value directly to preview image, and removing the else part with dummy image, everything i get is a small cube in top left corner div tag for news-img-wrap. I think the value of location of preview image is not getting to partial/list/item.html

Any suggestion??
Thanks!

**Comment by Sonezi** [comment]
If i set 
plugin.tx_news.settings.displayDummyIfNoMedia = 0 ,
not getting any image rendering, even if i have content element and media relations set images?

**Comment by typoworx-de** [comment]
Is there any solution? Facing the same problem on TYPO3 v9 and news version 8.6.0 in list-mode.
