### ISSUE TITLE
DC page titles in paginated list view

### ISSUE THREAD

**Issue by t3premium** [georgringer/news#472]
To prevent dublicate content page titles in paginated list view. Would be nice to set a different page title every single paginated page.

_/typo3conf/ext/news/Classes/ViewHelpers/Widget/Controller/PaginateController.php_
public function indexAction()
```
    if ($this->currentPage > 1) {
        $pageLabel = \TYPO3\CMS\Extbase\Utility\LocalizationUtility::translate('page','news');
        $GLOBALS['TSFE']->page['title'] = $GLOBALS['TSFE']->page['title'].' - '.$pageLabel.' '.$this->currentPage;
    }
```
_typo3conf/ext/news/Resources/Private/Language/locallang.xlf_
```
			<trans-unit id="page" xml:space="preserve">
				<source>Page</source>
			</trans-unit>
```

**Comment by t3premium** [comment]
Pull request: https://github.com/georgringer/news/pull/473

**Comment by georgringer** [comment]
thanks for your PR. I solved it now
