### ISSUE TITLE
create an action to convert detail view into pdf

### ISSUE THREAD

**Issue by bluebyte1985** [georgringer/news#474]
I tried to implement a new action (pdfAction) while using EXT pdfviewhelpers to create a PDF out of the detail view. Can't get it working. Is there a possibility to get this working?

fluid link
`<f:link.action action="pdf" arguments="{news:newsItem}" class="btn btn-expose" target="_blank">PDF</f:link.action>`

NewsController.php
```

**
* action  #pdf
 *
 * @param \GeorgRinger\News\Domain\Model\News $news
 * @return void
 */
public function pdfAction(\GeorgRinger\News\Domain\Model\News $news = null){
        $demand = $this->createDemandObjectFromSettings($this->settings);
        $demand->setActionAndClass(__METHOD__, __CLASS__);

        $assignedValues = [
            'newsItem' => $news,
            'currentPage' => (int)$currentPage,
            'demand' => $demand,
        ];

        $assignedValues = $this->emitActionSignal('NewsController', self::SIGNAL_NEWS_PDF_ACTION, $assignedValues);
        $this->view->assignMultiple($assignedValues);

        Page::setRegisterProperties($this->settings['pdf']['registerProperties'], $news);
        if (!is_null($news) && is_a($news, 'GeorgRinger\\News\\Domain\\Model\\News')) {
            Cache::addCacheTagsByNewsRecords([$news]);
        }
}
```

**Comment by georgringer** [comment]
That doesn't seem like an issue in EXT:news. I would suppose to create a custom ext which handle the pdf creation. CHeck out https://docs.typo3.org/typo3cms/drafts/github/georgringer/news/DeveloperManual/ExtendNews/ExtensionBasedOnNews/Index.html

**Comment by maechler** [comment]
The extension `pdfviewhelpers` in `v2` ships with a built in template for `news` using the default detail action and a special page type.

See https://github.com/bithost-gmbh/pdfviewhelpers and https://docs.typo3.org/typo3cms/extensions/pdfviewhelpers/ConfigurationReference/ExtNews/Index.html
