### ISSUE TITLE
creating first tag not possible on overview page

### ISSUE THREAD

**Issue by sarah01mueller** [georgringer/news#475]
If there is no tag yet, the list (overview page) is empty and therefore no button to create a tag is visible. Only if i created already a tag (there are a lot of other ways to do that) there is a list of tags with a create button.

Button to get to overview page (in edit news entry):
![image](https://user-images.githubusercontent.com/26143515/33319662-c63feb48-d43f-11e7-9b08-8619c6e5402c.png)

Overview page (no tags yet):
![image](https://user-images.githubusercontent.com/26143515/33319697-db84d0e0-d43f-11e7-897a-ae7418df8141.png)
There is no possibility to add a tag at this page.

Overview page (at least one tag exists):
![image](https://user-images.githubusercontent.com/26143515/33319721-f0032954-d43f-11e7-9dbd-6a47fa6e3afa.png)

I think there should be a possibility to add a tag if I navigated to the overview page (and no tag exists yet). Otherwise I would have to navigate elsewhere to add the first tag. The user experience would be improved.

PS: I made the images with non-admin user but it looks similar for admin user.

Kind regards Sarah

**Comment by georgringer** [comment]
See image of TYPO3 master (9). A plus icon is there. <img width="412" alt="bildschirmfoto 2018-01-22 um 13 01 43" src="https://user-images.githubusercontent.com/1905663/35219844-75b2726c-ff74-11e7-8b2e-21f151031cd8.png">

As this is a core issue, I will close it here.
