### ISSUE TITLE
Tags assignment to localized news not working

### ISSUE THREAD

**Issue by sdesign6** [georgringer/news#476]
If a news is translated, it's not possible to assign an own tag to the translated version of the article. Also there is no possibility to translate a tag. If the translated article is unbind from the translation the assigned tag is shown, what seems to be logical.

![bildschirmfoto 2017-11-30 um 14 27 50](https://user-images.githubusercontent.com/34130871/33433219-0ffd32b2-d5db-11e7-9aa2-2436fdd85e37.png)

**Comment by konradio** [comment]
The problem is that the tag itself is not localizable. In the tag model and the tag tca there are no localization fields. Localizable tags would be very nice.

**Comment by steffenk** [comment]
+1

**Comment by georgringer** [comment]
tags can be translated since long time
