### ISSUE TITLE
Fluid namespace tag is display in frontend

### ISSUE THREAD

**Issue by beardcoder** [georgringer/news#478]
If you use the share buttons the fluid namespace will be visible

`<div xmlns:rx="http://typo3.org/ns/Reelworx/RxShariff/ViewHelper"><div data-backend-url="https://vop.mac4dev.de/blog/?eID=shariff" data-services="[&quot;facebook&quot;,&quot;xing&quot;,&quot;twitter&quot;]" data-lang="de" class="shariff"></div></div>`

**Comment by georgringer** [comment]
but shariff extension is installed?

**Comment by beardcoder** [comment]
Yes. After you install the extension this partial will be used. The problem is the visible namespace `xmlns:rx`. That should not be displayed.

**Comment by xerc** [comment]
![bildschirmfoto 2018-01-31 um 22 46 59](https://user-images.githubusercontent.com/1372590/35687278-91b827ca-076e-11e8-85d1-6123cd400c36.png)
```
-<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers">
+<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">
```
```
Layouts/General.html
Layouts/Detail.html
Partials/Category/Items.html
Partials/General/AdditionalInformation.html
```
