### ISSUE TITLE
TCA paletteNavTitle not in use

### ISSUE THREAD

**Issue by rowild** [georgringer/news#480]
Just pointing out: 
In the TCA of tx_news_domein_model_news there is a "paletteNavtitle", which holds the "alternative_title" field. It is no where in use. Same thing with "paletteArchive" (the archive_date" is in the "date" palette). Maybe they should be deleted?

The "alternative_title" field is also part of the "alternativeTitles" palette, along with "path_segment" (at least currently, but not in my current 6.1.1 installation). They are placed at the very end of the "default news" interface, which does not really make much sense to me - why is that?

I dare a suggestion: from the editor's point of view, "alternative_title" would probably better fit below the main title (maybe along with "path_segment", too). And for smaller screens it turns out to be quite useful to have "teaser" and "bodytext" in a separate tab... (I know: this can be done in TCA Override...)

**Comment by georgringer** [comment]
thanks for creating the issue.
I keep the order for now as I am thinking of completly restructure all fields
