### ISSUE TITLE
Couldn't set timeRestrictionHigh in Typoscript

### ISSUE THREAD

**Issue by MowWow** [georgringer/news#484]
Hi,

I'm trying to set a value to timeRestrictionHigh in my typoscript code, but for some reason, this value is never read in the NewsController. So i added some var_dump of $this->settings in the News Controller (in the listAction, initializeAction and createDemandObjectFromSettings) and i noticed that the value of timeRestrictionHigh is always empty.

I tried some stuff like this : 
```
plugin.tx_news.settings.test = 123
plugin.tx_news.settings.timeRestrictionHigh = 123
plugin.tx_news.settings.timeRestrictionHig = 123
```
And the results of my var_dump(s) is always the same : 

>  'test' => string '123' (length=3)
>  'timeRestrictionHigh' => string '' (length=0)
>  'timeRestrictionHig' => string '123' (length=3)

I'm not able to locate the reason, i don't know if it's a bug or a wanted behavior ?

Help!

Thanks a lot

**Comment by MowWow** [comment]
I forgot to mention that i use news 6.1.1 on TYPO3 8.7.8

Thanks

**Comment by georgringer** [comment]
you need to add it to `settings.overrideFlexformSettingsIfEmpty` otherwise it is overloaded by empt flexforms
