### ISSUE TITLE
Display mode "List view" shows single detail view instead of list

### ISSUE THREAD

**Issue by JavierYD** [georgringer/news#492]
I'm using Typo3 8.7.9 with latest news module version, all installed using composer.

Consider the configuration below:

- Page 33: news plugin 1 (list view), with page 82 for single news display.
- Page 82: news plugin 1 (detail view) and news plugin 2 (list view)

Page 33 shows a list of news items of a certain category. By clicking each item opens the news in the details view (82), this all works as expected. The problem is that the second news plugin also shows the detail view of the current item. If the display mode of this second news plugin to any other type (List view without overloading detail view, date menu, tag list, etc.) it works perfectly.

![capture1](https://user-images.githubusercontent.com/7314760/34103344-b6de0aa6-e3ec-11e7-817e-0a39e1a9bfa2.jpg)
![capture2](https://user-images.githubusercontent.com/7314760/34103345-b6f639a0-e3ec-11e7-8b0e-43fb0e013acb.jpg)
![capture3](https://user-images.githubusercontent.com/7314760/34103346-b70dfce8-e3ec-11e7-9f03-03b1e2d5ae54.jpg)
![capture4](https://user-images.githubusercontent.com/7314760/34103348-b7271b7e-e3ec-11e7-9e8f-634d1e251f3c.jpg)

**Comment by georgringer** [comment]
this is the reason why there is this "list view without overloading". everything works also for you as expected. where is the bug?

**Comment by georgringer** [comment]
closed because no feedback. feel free to respond later
