### ISSUE TITLE
Tags missing information about usage

### ISSUE THREAD

**Issue by steffenk** [georgringer/news#495]
For displaying Taglist, mostly it's wanted to sort by relevance. I did this with a slot where i added this relevance to tag records and added sorting. Would be cool if this information would be built-in.

**Comment by georgringer** [comment]
Do you mean with relevance how often it is used? that is completly project specific as it depends on which news records need to be counted and this is impossible to know in this action

**Comment by steffenk** [comment]
The intention is the simple count of usage. This is the well known tag cloud. I would even say that excluding news-types from this count is rather project specific, the absolute count is the common case.
