### ISSUE TITLE
TxNewsSitemapGenerator should respect news type

### ISSUE THREAD

**Issue by 0bserver** [georgringer/news#496]
Pages with the types "internal link" or "external link" will get the same paths as regular news. This is different from the behavior of LinkViewHelper which will `getInternalurl()` or `getExternalurl()` as a link parameter.

The proposed solution is as follows: In `getNewsItemUrl()` insert
```php
if ($newsRow['type'] == 1 && !empty($newsRow['internalurl'])) {
    $conf['additionalParams'] = $additionalParams;
    $conf['parameter'] = $newsRow['internalurl'];
}
if ($newsRow['type'] == 2 && !empty($newsRow['externalurl'])) {
    $conf['additionalParams'] = $additionalParams;
    $conf['parameter'] = $newsRow['externalurl'];
}
$link = htmlspecialchars($this->cObj->typoLink('', $conf));
```
The last line is from the original function right before the final `return` statement.

This has been successfully tested on TYPO3 8.7.8 with news 6.1.1 and internal news. We don't use external urls.

**Comment by georgringer** [comment]
Do you wanna add a PR?

**Comment by 0bserver** [comment]
Alright, there's a first time for everything. I created a branch called bugfix/sitemap which is ready to push.

**Comment by georgringer** [comment]
thx for the PR!
