### ISSUE TITLE
Please check previewHiddenRecords in documentation

### ISSUE THREAD

**Issue by stefanvar** [georgringer/news#500]
`plugin.tx_news.settings.previewHiddenRecords = 1 `
doesn't work with Version 6.1.1. but if I use 
`plugin.tx_news.settings.enablePreviewOfHiddenRecords = 1`
it works fine.

Please replace previewHiddenRecords with enablePreviewOfHiddenRecords in news/Documentation/AdministratorManual/Configuration/TypoScript/Index.rst or check, if there is an error in the Controller.

Thanks

**Comment by georgringer** [comment]
This deppends on the setting `previewHiddenRecords`. If this is set to 2 ("Defined in TypoScript"), then also `enablePreviewOfHiddenRecords` is checked. 
See `Classes/Controller/NewsController.php:346` for code
