### ISSUE TITLE
Incorrect integer value at row 1

### ISSUE THREAD

**Issue by stedmanDev** [georgringer/news#502]
when i remove the “archive date” in a news entry i get the error message 
`2: SQL error: 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'archive' at row 1' (tx_news_domain_model_news:5)` 
this is a problem with php7 and strict mode. 

I have TYPO3 v8.7.8 and news 6.0.0 running. Is there any way to fix this without disabling the strict mode with 
`'initCommands' => 'SET SESSION sql_mode=\'\';',` 
in the additional configuration ?

**Comment by georgringer** [comment]
as this is also happening with regular core fields, I am closing this issue
