### ISSUE TITLE
Invalid HTML of time tag

### ISSUE THREAD

**Issue by SventB** [georgringer/news#503]
You write:

```
<time datetime="{f:format.date(date:newsItem.datetime, format:'Y-m-d')}">
    <f:format.date format="{f:translate(key:'dateFormat')}">{newsItem.datetime}</f:format.date>
    <meta itemprop="datePublished" content="{f:format.date(date:newsItem.datetime, format:'Y-m-d')}" />
</time>
```

The time tag should not have children tags, so better write:

```
<time itemprop="datePublished" datetime="{f:format.date(date:newsItem.datetime, format:'Y-m-d')}">
    <f:format.date format="{f:translate(key:'dateFormat')}">{newsItem.datetime}</f:format.date>
</time>
```

Please note that I've added attribute "itemprop=datePublished" to the time tag.

**Comment by georgringer** [comment]
where can I read up about that?

**Comment by SventB** [comment]
Can't find an official source. But if the time tag has a children tag, the HTML validator throws an error.
And why do you want to use the meta tag, if you can add attribute "itemprop=datePublished" to the time tag?

Some examples and sources:
http://www.designhive.com/blog/using-schemaorg-microdata
https://stackoverflow.com/questions/33151280/the-datepublished-property-and-the-html-lang-attribute
https://webmasters.stackexchange.com/questions/106056/meta-content-or-time-datetime

**Comment by georgringer** [comment]
wanna do a PR for all usages?

**Comment by SventB** [comment]
There are 3 occurences of "itemprop=datePublished". I've described everything what has to be done. Estimated expenditure of time: 2 minutes. Sorry, no PR for this. Also, there are enough PRs not merged yet.

**Comment by georgringer** [comment]
thanks however for reporting the issue. 2min work you would have saved me

**Comment by liayn** [comment]
@SventB  Did you also validate the structured data?

I presume not, because itemprop=datePublished needs dateFormat Y-m-d or ISO.
Since you put the itemprop now on the time tag it uses the content of the time-tag which can be any weird custom rendering stuff.
This was the initial reason we added the meta-tag, as also described on schema.org.
So if nesting is an issue, put it below the time tag or above.
