### ISSUE TITLE
No Jobs in Importer-View in Version 5.3.3

### ISSUE THREAD

**Issue by 8bamo** [georgringer/news#504]
I got no Jobs displayed in the Importer-View. I got tt_news Entries in the Database, but i got no clue why I cant migrate the Entries.

**Comment by georgringer** [comment]
have you installed ext https://extensions.typo3.org/extension/news_ttnewsimport/?

**Comment by 8bamo** [comment]
Sorry for the late Respond ^^

No cause i thought it was now integrated with 5.3.3. 
I installed '**tt_newsimport'** but it throws the Exception "Class 'Tx_News_Utility_ImportJob' not found ".

**Im using TYPO3 8.7.9 and news_ttnewsimport 1.0.2**

**Comment by georgringer** [comment]
please use version 2.0.0 of the news_ttnewsimport ext
