### ISSUE TITLE
Fallback in Detail view shows oldest news record, not latest

### ISSUE THREAD

**Issue by ryan-howe** [georgringer/news#505]
I'm using Typo3 8.7.9 in my setup, and News 6.1.1

In adding the fallback setup as detailed in the most recent version of the manual (below) the single news record displayed defaults to the oldest record in my defined news sysfolder. From what I understand in the manual this should actually display the most recent news record, correct? 

`plugin.tx_news.settings {
        overrideFlexformSettingsIfEmpty = singleNews,cropMaxCharacters,dateField,timeRestriction,orderBy,orderDirection,backPid,listPid,startingpoint
        useStdWrap = singleNews

        singleNews.stdWrap.cObject = CONTENT
        singleNews.stdWrap.cObject {
                table = tx_news_domain_model_news
                select {
                        max = 1
                        orderBy = datetime
                        pidInList = 3
                }
                renderObj = TEXT
                renderObj.field = uid
        }
}`

**Comment by ryan-howe** [comment]
Figured it out by trying something from the iCalendar setup. It looks like I just needed an addition to the orderBy:

`orderBy = datetime DESC`

As most other instances of orderBy in the manual are followed up with a separate entry for orderDirection, which doesn't seem to work in the setup for the fallback view, should the manual be updated to include that control option for users who are more novices with Typoscript? Or even as the default configuration for the Fallback view as the most recent news items seems like it would be more useful than the oldest?

**Comment by georgringer** [comment]
thanks for reporting the issue! i changed the documentation
