### ISSUE TITLE
User limited to language can´t edit localised news record

### ISSUE THREAD

**Issue by ciakoller** [georgringer/news#538]
1. Create a News record and add a related Link in Relations Tab with admin-User.
2. Translate the News record to second language (in my case german) with admin-User.
3. Delete the related Link in the localized News record with admin-User.
4. BE-User limited to language german can´t edit the translated News record.

Following Message appears:

Sorry, you didn't have proper permissions to perform this change.
ERROR: Language was not allowed.

**Comment by georgringer** [comment]
this is a core issue and not solvable within the extension. therefore I am closing the issue.
