### ISSUE TITLE
Duplicated content elements rendering

### ISSUE THREAD

**Issue by Sonezi** [georgringer/news#545]
Hello. 
I am trying to make a news item with content elements (carousels, text, images) in two columns with grid element of 2 columns.
In Content Elements first step is adding grid element 2 columns, name it left and right.
Then add carousel element and assign it to left column, add text element assigned to right column, that's oke. 

The problem is when news gets rendered, content elements it makes two column element put carousel and text respectively were there are assigned and below two column element add carousel and text one below the other with same ids and everything in it.
![news2](https://user-images.githubusercontent.com/18620537/35347045-3d0ec1b0-0134-11e8-864d-cbd30b415ca0.png)
![news1](https://user-images.githubusercontent.com/18620537/35347046-3d34d0a8-0134-11e8-909c-1a7c22abd18e.png)

Is there a solution to this?

**Comment by georgringer** [comment]
I would extend news with custom extensions and add a 2nd content element relation and having one for left and one for right. But I don't see any bug in news here
