### ISSUE TITLE
Example RSS feed configuration in documentation is not working

### ISSUE THREAD

**Issue by maltisch** [georgringer/news#549]
Example RSS feed configuration in documentation is not working in template constants

> plugin.tx_news.settings.list.rss.channel

only 

`plugin.tx_news.rss.channel`

 in TYPO3 7.6.23 and news 6.1.1

**Comment by georgringer** [comment]
can you point me to the wrong documentation, I don't find that. thx

**Comment by maltisch** [comment]
[https://github.com/georgringer/news/blob/master/Documentation/AdministratorManual/BestPractice/Rss/Index.rst](url)

> RSS feed configuration
> 
> Don't forget to configure the RSS feed properly as the sample template won't fulfill your needs completely. Please look up the constants and change the mentioned settings.

```
plugin.tx_news.settings.list {
     rss.channel {
            title = Dummy Title
            description =
            link = http://example.com
            language = en-gb
            copyright = TYPO3 News
            category =
            generator = TYPO3 EXT:news
    }
}
```
Maybe i misunderstood it, but putting this in template constants doesnt work.
The default settings from 
`plugin.tx_news.rss.channel`
is used instead.

**Comment by cgpro** [comment]
2,5 years later... ;-)

In my case:
`
plugin.tx_news{
    rss.channel {
        title = CQSE Blog
        description = Newsfeed of CQSE
        link = https://www.cqse.eu
        language = en-gb
        copyright = CQSE GmbH
        category =
        generator = TYPO3 EXT:news
    }
}
`
doesn't work either. Any Ideas? TYPO3 9.5.15 / News 7.2
