### ISSUE TITLE
News Sitemap with image

### ISSUE THREAD

**Issue by stefanvar** [georgringer/news#555]
Hey,

it would be nice, if the sitemap hook for dd_googlesitemap could also deliver image-urls for a better news sitemap.

I modified (rough) the `/Classes/Renderers/NewsSitemapRenderer.php` in dd_googlesitemap and the `Classes/Hooks/TxNewsSitemapGenerator.php` in your news extension to get images to the sitemap.

Here is my modification:

line 158:
`if (($url = $this->getNewsItemUrl($row, $forceSinglePid))) {
            if (($image = $this->getImages($row['uid'],'tx_news_domain_model_news'))) {
                echo $this->renderer->renderEntry($url, $row['title'], $row['tstamp'],
                    '', $row['keywords'],'',$image);
            }
            else {
                echo $this->renderer->renderEntry($url, $row['title'], $row['tstamp'],
                    '', $row['keywords']);
            }
        }`

The function `$this->getImages($uid, $tablename)` should return the absolute uri of the news article image.

Hopefully this feature will be added in one the new versions.

Thanks

https://github.com/dmitryd/typo3-dd_googlesitemap/issues/92

**Comment by georgringer** [comment]
Thanks for bringing this up. however I believe that an image sitemap should be done by a custom extension to deliver https://support.google.com/webmasters/answer/178636?hl=en
