### ISSUE TITLE
Download via Ext Manager causes MD5 error

### ISSUE THREAD

**Issue by rowild** [georgringer/news#556]
As the title already describes, the download from TER causes an MD5 error.

TYPO3 8.7.9, News 6.3, php 7.1.13

**Comment by georgringer** [comment]
There is IMO nothing I can do, please open an issue at https://git-t3o.typo3.org/t3o/ter/issues

**Comment by rowild** [comment]
Happens only with "news" v6.3. Not going to post this issue again at any other place.
