### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by MS-Tech** [georgringer/news#557]
Hallo Georg,

ich habe Typo3 8.7.7 installiert. Ich wollte gerne deine News Extension verwenden und hab diese Installiert. Wenn ich aber dann das News-Plugin als Contentelement einfügen möchte erhalte ich die Fehlermeldung folgende Fehlermeldung.

Call to undefined method TYPO3\CMS\Compatibility6\Configuration\FlexForm\FlexFormTools::getDataStructureIdentifier() 

Was ist hier zu tun?

Viele Grüße
MS-Tech

**Comment by georgringer** [comment]
please deactive the extension `compatibility6`.
