### ISSUE TITLE
No images when changing original language

### ISSUE THREAD

**Issue by MarkusBausK** [georgringer/news#570]
Hi,

in my latest project I have some articles that don't exist in the default (german) language. Therefore I change the language of the original record from german to english. Everything is fine but if I change the language after integrating the images the images are not shown in the frontend anymore. If I remove them and add them once again everything is fine. If I check it by f:debug in fluid the objectstorage seems to be filled but the items inside are missing after changing the language.

**Comment by georgringer** [comment]
because the language in the sys_file_reference records is still wrong. there is nothing I can/want to do as extension here.
