### ISSUE TITLE
Translation of an article built up with content elements

### ISSUE THREAD

**Issue by SirIsaac-1** [georgringer/news#571]
Hello,

I have built up my news articles using "content elements". When I try to translate this article, the first content element within the article is replaced and linked to any content element on the page.

When I delete this content element, the linked content element is also deleted.

How can I solve the problem? If you need further information, please let me know.

`TYPO3 8.7.8` `tx_news 6.3.0`

**Comment by georgringer** [comment]
solved via personal support

**Comment by WillyRM** [comment]
Hello,

I have the same problem, hat can i please do?
