### ISSUE TITLE
bug: event end can be before event start

### ISSUE THREAD

**Issue by DanielRuf** [georgringer/news#582]
Currently events / news can be created with an end date that is before the start date.

Either we have discovered timetravel or it is a bug as it is not valid in general.

**Comment by georgringer** [comment]
but that is also currently possible for any record provided by the core... shouldn't that be covered in general by the core?

**Comment by DanielRuf** [comment]
> but that is also currently possible for any record provided by the core... shouldn't that be covered in general by the core?

If this is the case and the validation is done by the core then it is a bug in the core, right.

**Comment by DanielRuf** [comment]
Do we have a forge ticket for this or why was is closed without any further comment?

Please link to the forge ticket about this issie (in the core).

**Comment by georgringer** [comment]
https://forge.typo3.org/issues/83871

**Comment by DanielRuf** [comment]
> https://forge.typo3.org/issues/83871

Thanks.
