### ISSUE TITLE
Other fields for dateField

### ISSUE THREAD

**Issue by klodeckl** [georgringer/news#583]
I need another field for the dateField (for creating list views) e.g. event_end (with eventnews extension). But in the code there is only datetime and archive allowed for that.

**Comment by georgringer** [comment]
for security reasons I changed the implementation there to hardcoded checks.

**Comment by klodeckl** [comment]
Do you see a chance for that?
It is bad if there is an event not displayed anymore because the starttime (datetime) of the event is already in the past but the event is still running (event end not reached). Or if you want to mix news with events in a list (with a different datetime than event start, for this I created a new field eventstart).

**Comment by chris246** [comment]
Hi,

I am also interested in an additional date field, but for a different use case:
It would be really nice to have two date fields available: One for frontend news sorting (not visible for visitors) and one without additional functionality, that is visible for the visitors,

My current approach is to recycle the Author E-Mail field for this purpose, but as this is already used to display the location below the heading, I see no way of adding a datepicker to this backend field.

Our use case is to influence the order of news without modifying the visible date of the entry.
