### ISSUE TITLE
Problems while pasting text with emojis

### ISSUE THREAD

**Issue by stefanvar** [georgringer/news#591]
Hey,

if we use oembed in RTE to share for example tweets, there are often emojis in the tweet. This forces an error.

`1: These fields of record 101 in table "tx_news_domain_model_news" have not been saved correctly: bodytext! The values might have changed due to type casting of the database.`

Is it possible to change the database table column collation for bodytext from utf8 to utf8mb4?
Don't know, if there has to be changed more than that.

Thanks

**Comment by georgringer** [comment]
IMO this is more a general issue with the core, not really only news. does it occur in `tt_content` as well?

**Comment by georgringer** [comment]
see https://forge.typo3.org/issues/80398
