### ISSUE TITLE
Initial sorting in backend module is not working

### ISSUE THREAD

**Issue by retiolum** [georgringer/news#593]
The initial sorting in the backend module is not working as expected: it only sets the pre-selected items in the search field and direction dropdown, but is not applied to the data set loaded at start.

In my observation this is because the demand initially created is not handed over to the NewsDatabaseRecordList so that this object can take care of the initial sorting.

**Comment by georgringer** [comment]
sorry don't really understand what you mean, can you give bit more feedback?
