### ISSUE TITLE
AJAX based pagination not respecting category filter

### ISSUE THREAD

**Issue by kimchristiansen** [georgringer/news#594]
I am using the AJAX based pagination like documented here: https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Templates/AjaxBasedPagination/Index.html
Everything works fine. But if i have a filtered news list by categorie, the AJAX loader still loads all news.

The href of the next Link is correct:

`href="/index.php?id=7&amp;tx_news_pi1%5BoverwriteDemand%5D%5Bcategories%5D=9&amp;tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=2&amp;cHash=fe4d91b4ec30048fa42bdd310cc8675d"`

But the data attribute ignores the categories parameter

`data-link="/index.php?id=7&amp;tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=2&amp;tx_news_pi1%5Bcontroller%5D=ViewHelpers%5CWidget%5CPaginate&amp;tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_36%22%2C%22path%22%3A%22tt_content.list.20.news_pi1%22%7D&amp;cHash=3eca5db96c37c64eef0348c79f6a70b0"`

I am afraid, the AJAX Link also ignores the option excludeAlreadyDisplayedNews.

System:
TYPO3 8.7.10 (Composer based)
News 6.3.0
typoscript_rendering: 2.0.2

**Comment by anujaunds** [comment]
i am facing same problem if i used ajax pagination then new page not working. i follow your AJAX based pagination my code is: 
 plugin.tx_news.settings.list {
    paginate.templatePath = fileadmin/private/news/Templates/Styles/Twb/Templates/ViewHelpers/Widget/Paginate/IndexAjax.html
}
it's not showing the image if i remove this line from my TS config file the New page working fine.

**Comment by FlyKasual** [comment]
Hey. I'd like to add that it also doesn't respect date restrictions, i.e. tx_news_pi1[overwriteDemand][year]

**Comment by FlyKasual** [comment]
Alright, I think I found a solution to my specific problem. Now, I am terrible at PHP and I don't know much about the TYPO3 core, but maybe this can serve as a starting point for someone to come up with a better solution. My workaround is to edit the PaginateAdditionalParamsViewHelper's render funciton:
```

    /**
     * @param int $page
     * @return array
     */
    public function render($page = 0)
    {
        $additionalParams = [];
        if ($page !== 0) {
            $additionalParams['tx_news_pi1'] = [
                '@widget_0' => [
                    'currentPage' => $page,
                ],
            ];
        }
        if ($_GET['tx_news_pi1']['overwriteDemand']['year']) {
            $additionalParams['tx_news_pi1']['overwriteDemand'] = [
                'year' => $_GET['tx_news_pi1']['overwriteDemand']['year'],
            ];
        }
        return $additionalParams;
    }

So that it forwards more data. There is probably some way to do this in the controller, but I don't have the time to look that up ATM unfortunately.

**Comment by develth** [comment]
I recognized that it was missing in my list, too & set up all like in the docs. 

After checking all required parameters, i fixed it:

recordId was not set due two more render sections, where i did not defined this var.

**Comment by typo3ua** [comment]
I confirm too that AJAX-based pagination not respecting category filter

**Comment by georgringer** [comment]
closing this issue as I won't work on it and it is dropped in next version because the widget VH have been removed from core since 11
