### ISSUE TITLE
Do not show News in default language

### ISSUE THREAD

**Issue by Alexander-Hagemeier** [georgringer/news#596]
Hi all,

is there a way to prevent a news, which is not translated, to be displayed in its default language?

Example:

My default language is German and I have two additional languages (English and French). I create a news  and do not translate it into English or French. Now, if I visit the English or French news page, I see the previously created News in German (its default language).

**Comment by MarkusBausK** [comment]
Put this:

`config.sys_language_mode = strict
config.sys_language_overlay = 0`

to your typoscript setup to prevent the news from default language.

**Comment by Alexander-Hagemeier** [comment]
It works! Thanks a lot!
