### ISSUE TITLE
AjaxPagination PageID 7 hardcoded in Template

### ISSUE THREAD

**Issue by lsascha** [georgringer/news#599]
If you follow this Documentation
https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Templates/AjaxBasedPagination/Index.html

You might end up that the t:uri.ajaxAction viewHelper does not generate any Ajax uri.
Reason is that it includes the PageUid:7 parameter.

I think a better option is to just remove the PageUid parameter completely, since most likely the paginator will stay on the same TYPO3-Page anyway.

**Comment by georgringer** [comment]
solvd
