### ISSUE TITLE
Topnews in plugin only accepts default language value

### ISSUE THREAD

**Issue by MarkusBausK** [georgringer/news#601]
Hi,

I try to get different output in case of translated plugins and news with the "topnews"-feature. (Some news in default language are no topnews but translated they should it be). But if try to show a news that is only marked as "topnews" in a translated version and not in default it is not shown in plugin configured as "only show topnews". It is possible to set different values in the languageversions of an article but only the value of the default language version is decisive.

**Comment by georgringer** [comment]
that is not possible currently as this is how extbase works
