### ISSUE TITLE
No manual sorting in module "News Admin"

### ISSUE THREAD

**Issue by yurigargamel** [georgringer/news#605]
I activated manual sorting in the extension settings, but it only seems to affect the list module, not the "News Administration" module. So, manual sorting is not possible in the "News Administration" module.
TYPO3 7.6.19
tx_news 6.3.0.

**Comment by georgringer** [comment]
reopend to check with  8

**Comment by whiteroom** [comment]
Hi Georg
I still see no way to manually sort in the "News Administration" module,
while the list view does work as expected. Has this been fixed?

Sort options are and have always been: title,datetime,crdate,author
any attempt to configure filters (TSconfig) will fail

what I would expect: title,datetime,crdate,author,sorting

Thankx

**Comment by georgringer** [comment]
Yes this feature is currently missing. Can you sponsor its development?
