### ISSUE TITLE
Slow performance when adding news record with specific category

### ISSUE THREAD

**Issue by agendartobias** [georgringer/news#631]
Hello, we have problem with slow performance/saving news record if we add news record with specific category that have already 20k news record "linked" to that category.

I think that may be related to https://forge.typo3.org/issues/84558.

But this problem is related only to ext: news. We tried to replicate that problem with other ext so we created 20k record of tt_adddress and linked it to specific category. When we tried to add new tt_address record, performance/saving is very fast.

**Comment by georgringer** [comment]
where is the performance bad? in the news record or in the sys_category record?

**Comment by agendartobias** [comment]
In the news record. Every time i want to add new news record, and i select this "problematic" category (with 20k+ news record assigned to that category), and i hit Save button (for saving new news record) i wait and wait like 2min or i get time out.

**Comment by georgringer** [comment]
I can imagine some stuff. Can you disable the hooks in DataHandler and if fast check which one is faulty?

**Comment by agendartobias** [comment]
What do you mean by that? Where can i disable hook in datahandler?

**Comment by georgringer** [comment]
https://github.com/georgringer/news/blob/master/Classes/Hooks/DataHandler.php  the public methods > outcomment one after another, check performance and report back ^^

**Comment by agendartobias** [comment]
If helps, here is mysql query log from the second that i click "save" in news record
[mysql.log.gz](https://github.com/georgringer/news/files/1906490/mysql.log.gz)

**Comment by georgringer** [comment]
maybe wanna test https://github.com/NamelessCoder/asynchronous_reference_indexing if it is related to the sys_refinded

**Comment by agendartobias** [comment]
After installing this module it works fast. So this is not a tx_news bug?

**Comment by georgringer** [comment]
No it is not, sorry

**Comment by georgringer** [comment]
Thx however for report, will try to improve that in core
