### ISSUE TITLE
Get news by year and not month/year

### ISSUE THREAD

**Issue by jschrewe** [georgringer/news#633]
I'm trying to get all news (well, events really) for a specific year and for all month.

I am able to generate the following link: ?tx_news_pi1%5BoverwriteDemand%5D%5Byear%5D=2017&tx_news_pi1%5Bcontroller%5D=News&cHash=2c54dbf49d405d09616d67f56573637b

The only problem ist that this does nothing. It works fine for specific months. But there simply aren't enough events per month to actually make this useful.

Is there some way to get this working? I'm happy to provide a pull request but because I'm pretty new to Typo 3 in general and news in particular I would need a couple of pointers where to start.

Thanks!

**Comment by georgringer** [comment]
Can you debug it in https://github.com/georgringer/news/blob/master/Classes/Domain/Repository/NewsRepository.php line 190, start and end should fit. Thx for your support

**Comment by jschrewe** [comment]
While filtering by year is still not working and filtering by year and month is working, I don't think wrong query options are the cause. I get for beginning and end:

```php
demand => '2018' (4 chars)
begin => 1514764800 (integer)
begin_date => '2018-01-01T00:00:00+00:00' (25 chars)
end => 1546300799 (integer)
end_date => '2018-12-31T23:59:59+00:00' (25 chars)
```

and the generated $demand object looks like (I through out the protected, prototype and object annotations):

```php
array(2 items)
   pid => TYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison
   datetime => TYPO3\CMS\Extbase\Persistence\Generic\Qom\LogicalAnd
      constraint1 => protectedTYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison
         operand1 => protectedTYPO3\CMS\Extbase\Persistence\Generic\Qom\PropertyValue
            selectorName => 'tx_news_domain_model_news' (25 chars)
            propertyName => 'datetime' (8 chars)
         operator => 6 (integer)
         operand2 => 1514764800 (integer)
         parameterIdentifier => NULL
      constraint2 => protectedTYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison
         operand1 => protectedTYPO3\CMS\Extbase\Persistence\Generic\Qom\PropertyValue
            selectorName => 'tx_news_domain_model_news' (25 chars)
            propertyName => 'datetime' (8 chars)
         operator => 4 (integer)
         operand2 => 1546300799 (integer)
         parameterIdentifier => NULL
```

for filtering by year and 

```php
array(2 items)
   pid => TYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison
   datetime => TYPO3\CMS\Extbase\Persistence\Generic\Qom\LogicalAnd
      constraint1 => TYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison
         operand1 => TYPO3\CMS\Extbase\Persistence\Generic\Qom\PropertyValue
            selectorName => 'tx_news_domain_model_news' (25 chars)
            propertyName => 'datetime' (8 chars)
         operator => 6 (integer)
         operand2 => 1522540800 (integer)
         parameterIdentifier => NULL
      constraint2 => TYPO3\CMS\Extbase\Persistence\Generic\Qom\Comparison
         operand1 => TYPO3\CMS\Extbase\Persistence\Generic\Qom\PropertyValue
            selectorName => 'tx_news_domain_model_news' (25 chars)
            propertyName => 'datetime' (8 chars)
         operator => 4 (integer)
         operand2 => 1525132799 (integer)
         parameterIdentifier => NULL
```

for filtering by year and month.

**Comment by georgringer** [comment]
I can't reproduce that, testing on current master (core + news) and with URL
```
?id=25&tx_news_pi1%5BoverwriteDemand%5D%5Byear%5D=2017&tx_news_pi1%5Bcontroller%5D=News&cHash=78f0ef08e55b4a25249cf6b2c9e4efd0
```

I get the correct amount of news from 2017.

link is produced with `<f:link.action pageUid="{listPid}" arguments="{overwriteDemand:{year: year}}">extra {year}</f:link.action>`

**Comment by jschrewe** [comment]
Right. So after looking into it a bit more. It works fine if I deactivate the event news extension. With event news activated it doesn't filter.
