### ISSUE TITLE
Improve showinpreview

### ISSUE THREAD

**Issue by georgringer** [georgringer/news#640]
- [x] more getters 
- [x] add fallback for old behaviour
- [x] improve hooks for new behaviour
- [x] icons for new behaviour
- [x] docs

**Comment by brrrrrrrt** [comment]
seems broken now (7.0.5):

- when set to "Show only in list views" it is also shown in detail view
- German Translation: All Options are translated to "In Vorschau-Ansichten anzeigen"

**Comment by webdev2027** [comment]
see screenshot
![bildschirmfoto 2018-08-21 um 09 03 02](https://user-images.githubusercontent.com/5501876/44386888-23090700-a524-11e8-96a5-d3dfcdf19f2b.png)
