### ISSUE TITLE
Remove files added by IncludeFileViewHelper from concatenation

### ISSUE THREAD

**Issue by scoorpion88** [georgringer/news#645]
Hello, in class `\GeorgRinger\News\ViewHelpers\IncludeFileViewHelper` are CSS and JS files added to PageRenderer. They are included to concatenation. But these files (e.g. `news-basic.css`) are not included on every page, only where the plugin is used. Main CSS file is added to page from the default layout files (General, Detail).

I use this setting in the template:
**`config.concatenateCss = 1`**

Then I have two merged files - with `news-basic.css` on pages with the news plugin and without it on other pages. Visitors must download both of them, even there is a very little difference.

I think this is a bug and should be fixed:
* by setting the **`$excludeFromConcatenation`** variable to **`TRUE`** - `addJsFile()`, `addCssFile()`
* by include **`news-basic.css`** to all pages from `setup.txt`

**Comment by georgringer** [comment]
I would propose to set `settings.cssFile` to empty and just include the CSS file in your build process. I don't plan to change anything there as this is just a default template which is not intended to be used for production (you need modifications anyway)
