### ISSUE TITLE
Link to detail view should add type=0

### ISSUE THREAD

**Issue by spoonerWeb** [georgringer/news#647]
When creating a RSS feed with XML output under type x, the link to the detail view in the RSS feed have the same type.

Unfortunately it is not possible to set type=0 with the additionalParams, because of that the parameter with the news ID wouldn't be used.

Speaks anything against adding the parameter type=0 to the link view helper?

**Comment by georgringer** [comment]
I never had this issue and solving it that way sounds strange. woulnd't it make more sense to force type parameter e.g with TS `config.defaultGetVars` or something like that?

**Comment by georgringer** [comment]
problem was `config.linkVars = type`.
