### ISSUE TITLE
Tag creation fails if news record not store yet

### ISSUE THREAD

**Issue by Idleworks** [georgringer/news#649]
Creating a tag via suggestion throws an error if the news record hasn't been stored yet. 

This happens because the temporary record's uid is converted to integer and therefore is zero:
https://github.com/georgringer/news/blob/6284ecba0f8b4a06d0c9a5ee1d3105a1a8be7af9/Classes/Hooks/SuggestReceiver.php#L35
Removing this convertion would save this new tag and assign it to the unsaved record but that would lead to a regression while tag is saved to news' record pid which is requested via news record's uid (got that? :-) ), see https://github.com/georgringer/news/blob/6284ecba0f8b4a06d0c9a5ee1d3105a1a8be7af9/Classes/Backend/TagEndPoint.php#L84

Maybe there should be another way to retrieve tag's pid (defined in typoscript or TSconfig?).

**Comment by georgringer** [comment]
solved now
