### ISSUE TITLE
Problems with news sorting

### ISSUE THREAD

**Issue by AMTkkasprzyca** [georgringer/news#651]
I have news plugin included with TypoScript as RSS feed. I need a descending items but none of attempts to change `orderByAllowed` option works. Setting is cleared with Classes/Controller/NewsController.php line 509. Is it the correct behavior? I'm not use FlexForms here so regarding to the variable's name `orderByAllowed` should be ommited from exclusion

Extension version: 6.1.1
TYPO3 version: 8.7.13

Best regards
Krzysztof

**Comment by georgringer** [comment]
you can either include news as plugin. the settings should still be fine also if all set by TS. for further support please ask in slack
