### ISSUE TITLE
Autoloading of "Tx_News_ViewHelpers_HeaderDataViewHelper" not successful > News pages not visible

### ISSUE THREAD

**Issue by juliusobergassel** [georgringer/news#653]
#1289386765: Could not analyse class: "Tx_News_ViewHelpers_HeaderDataViewHelper" maybe not loaded or no autoloader? Class Tx_News_ViewHelpers_HeaderDataViewHelper does not exist (More information)

TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException thrown in file
/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php in line 37.

46 TYPO3\CMS\Extbase\Object\Container\ClassInfoFactory::buildClassInfoFromClassName("Tx_News_ViewHelpers_HeaderDataViewHelper")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Object/Container/Container.php:
00350:         $classInfo = $this->getClassInfoCache()->get($classNameHash);
00351:         if (!$classInfo instanceof \TYPO3\CMS\Extbase\Object\Container\ClassInfo) {
00352:             $classInfo = $this->getClassInfoFactory()->buildClassInfoFromClassName($className);
00353:             $this->getClassInfoCache()->set($classNameHash, $classInfo);
00354:         }

45 TYPO3\CMS\Extbase\Object\Container\Container::getClassInfo("Tx_News_ViewHelpers_HeaderDataViewHelper")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Object/Container/Container.php:
00171:             return $this->singletonInstances[$className];
00172:         }
00173:         $classInfo = $this->getClassInfo($className);
00174:         $classIsSingleton = $classInfo->getIsSingleton();
00175:         if (!$classIsSingleton) {

44 TYPO3\CMS\Extbase\Object\Container\Container::getInstanceInternal("Tx_News_ViewHelpers_HeaderDataViewHelper", array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Object/Container/Container.php:
00124:     {
00125:         $this->prototypeObjectsWhichAreCurrentlyInstanciated = [];
00126:         return $this->getInstanceInternal($className, $givenConstructorArguments);
00127:     }
00128: 

43 TYPO3\CMS\Extbase\Object\Container\Container::getInstance("Tx_News_ViewHelpers_HeaderDataViewHelper", array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Object/ObjectManager.php:
00097:             $instance = call_user_func_array([\TYPO3\CMS\Core\Utility\GeneralUtility::class, 'makeInstance'], $arguments);
00098:         } else {
00099:             $instance = $this->objectContainer->getInstance($objectName, $arguments);
00100:         }
00101:         return $instance;

42 TYPO3\CMS\Extbase\Object\ObjectManager::get("Tx_News_ViewHelpers_HeaderDataViewHelper")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/fluid/Classes/Core/Parser/TemplateParser.php:
00558:             throw new \TYPO3\CMS\Fluid\Core\Parser\Exception('Namespace could not be resolved. This exception should never be thrown!', 1224254792);
00559:         }
00560:         $viewHelper = $this->objectManager->get($this->resolveViewHelperName($namespaceIdentifier, $methodIdentifier));
00561:         $this->viewHelperNameToImplementationClassNameRuntimeCache[$namespaceIdentifier][$methodIdentifier] = get_class($viewHelper);
00562: 

41 TYPO3\CMS\Fluid\Core\Parser\TemplateParser::initializeViewHelperAndAddItToStack(TYPO3\CMS\Fluid\Core\Parser\ParsingState, "n", "headerData", array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/fluid/Classes/Core/Parser/TemplateParser.php:
00534:     {
00535:         $argumentsObjectTree = $this->parseArguments($arguments);
00536:         $this->initializeViewHelperAndAddItToStack($state, $namespaceIdentifier, $methodIdentifier, $argumentsObjectTree);
00537: 
00538:         if ($selfclosing) {

40 TYPO3\CMS\Fluid\Core\Parser\TemplateParser::openingViewHelperTagHandler(TYPO3\CMS\Fluid\Core\Parser\ParsingState, "n", "headerData", "", boolean)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/fluid/Classes/Core/Parser/TemplateParser.php:
00507:                 $this->textHandler($state, $matchedVariables[1]);
00508:             } elseif (preg_match($regularExpression_openingViewHelperTag, $templateElement, $matchedVariables) > 0) {
00509:                 $this->openingViewHelperTagHandler($state, $matchedVariables['NamespaceIdentifier'], $matchedVariables['MethodIdentifier'], $matchedVariables['Attributes'], ($matchedVariables['Selfclosing'] !== ''));
00510:             } elseif (preg_match($regularExpression_closingViewHelperTag, $templateElement, $matchedVariables) > 0) {
00511:                 $this->closingViewHelperTagHandler($state, $matchedVariables['NamespaceIdentifier'], $matchedVariables['MethodIdentifier']);

39 TYPO3\CMS\Fluid\Core\Parser\TemplateParser::buildObjectTree(array, 2)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/fluid/Classes/Core/Parser/TemplateParser.php:
00355:         $splitTemplate = $this->splitTemplateAtDynamicTags($templateString);
00356: 
00357:         $parsingState = $this->buildObjectTree($splitTemplate, self::CONTEXT_OUTSIDE_VIEWHELPER_ARGUMENTS);
00358: 
00359:         $variableContainer = $parsingState->getVariableContainer();

38 TYPO3\CMS\Fluid\Core\Parser\TemplateParser::parse("↵<f:layout name="General" />↵<!--↵	===============…/f:if>↵↵        </f:else>↵    </f:if>↵</f:section>")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/fluid/Classes/View/AbstractTemplateView.php:
00169:             $parsedTemplate = $this->templateCompiler->get($templateIdentifier);
00170:         } else {
00171:             $parsedTemplate = $this->templateParser->parse($this->getTemplateSource($actionName));
00172:             if ($parsedTemplate->isCompilable()) {
00173:                 $this->templateCompiler->store($templateIdentifier, $parsedTemplate);

37 TYPO3\CMS\Fluid\View\AbstractTemplateView::render()

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php:
00310: 
00311:         if ($actionResult === null && $this->view instanceof ViewInterface) {
00312:             $this->response->appendContent($this->view->render());
00313:         } elseif (is_string($actionResult) && $actionResult !== '') {
00314:             $this->response->appendContent($actionResult);

36 TYPO3\CMS\Extbase\Mvc\Controller\ActionController::callActionMethod()

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php:
00174:             $this->initializeView($this->view);
00175:         }
00176:         $this->callActionMethod();
00177:     }
00178: 

35 TYPO3\CMS\Extbase\Mvc\Controller\ActionController::processRequest(TYPO3\CMS\Extbase\Mvc\Web\Request, TYPO3\CMS\Extbase\Mvc\Web\Response)

/path/to/typo3/installation/webproduction/typo3conf/ext/news/Classes/Controller/NewsBaseController.php:
00047:     {
00048:         try {
00049:             parent::processRequest($request, $response);
00050:         } catch (\Exception $exception) {
00051:             $this->handleKnownExceptionsElseThrowAgain($exception);

34 GeorgRinger\News\Controller\NewsBaseController::processRequest(TYPO3\CMS\Extbase\Mvc\Web\Request, TYPO3\CMS\Extbase\Mvc\Web\Response)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php:
00084:             $controller = $this->resolveController($request);
00085:             try {
00086:                 $controller->processRequest($request, $response);
00087:             } catch (\TYPO3\CMS\Extbase\Mvc\Exception\StopActionException $ignoredException) {
00088:             }

33 TYPO3\CMS\Extbase\Mvc\Dispatcher::dispatch(TYPO3\CMS\Extbase\Mvc\Web\Request, TYPO3\CMS\Extbase\Mvc\Web\Response)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Mvc/Web/FrontendRequestHandler.php:
00067:         /** @var $response \TYPO3\CMS\Extbase\Mvc\ResponseInterface */
00068:         $response = $this->objectManager->get(\TYPO3\CMS\Extbase\Mvc\Web\Response::class);
00069:         $this->dispatcher->dispatch($request, $response);
00070:         return $response;
00071:     }

32 TYPO3\CMS\Extbase\Mvc\Web\FrontendRequestHandler::handleRequest()

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Core/Bootstrap.php:
00204:         $requestHandler = $requestHandlerResolver->resolveRequestHandler();
00205: 
00206:         $response = $requestHandler->handleRequest();
00207:         // If response is NULL after handling the request we need to stop
00208:         // This happens for instance, when a USER object was converted to a USER_INT

31 TYPO3\CMS\Extbase\Core\Bootstrap::handleRequest()

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Core/Bootstrap.php:
00191:     {
00192:         $this->initialize($configuration);
00193:         return $this->handleRequest();
00194:     }
00195: 

30 TYPO3\CMS\Extbase\Core\Bootstrap::run("", array)
29 call_user_func_array(array, array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
07313:                     ], [
07314:                         $content,
07315:                         $conf
07316:                     ]);
07317:                 } else {

28 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::callUserFunction("TYPO3\CMS\Extbase\Core\Bootstrap->run", array, "")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php:
00038:         }
00039:         $this->cObj->includeLibs($conf);
00040:         $tempContent = $this->cObj->callUserFunction($conf['userFunc'], $conf, '');
00041:         if ($this->cObj->doConvertToUserIntObject) {
00042:             $this->cObj->doConvertToUserIntObject = false;

27 TYPO3\CMS\Frontend\ContentObject\UserContentObject::render(array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00941:         // Render content
00942:         try {
00943:             $content .= $contentObject->render($configuration);
00944:         } catch (ContentRenderingException $exception) {
00945:             // Content rendering Exceptions indicate a critical problem which should not be

26 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::render(TYPO3\CMS\Frontend\ContentObject\UserContentObject, array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00857:                     $contentObject = $this->getContentObject($name);
00858:                     if ($contentObject) {
00859:                         $content .= $this->render($contentObject, $conf);
00860:                     } else {
00861:                         // Call hook functions for extra processing

25 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGetSingle("USER", array, "news_pi1")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/CaseContentObject.php:
00042:             $theValue = '';
00043:         } else {
00044:             $theValue = $this->cObj->cObjGetSingle($conf[$key], $conf[$key . '.'], $key);
00045:         }
00046:         if (isset($conf['stdWrap.'])) {

24 TYPO3\CMS\Frontend\ContentObject\CaseContentObject::render(array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00941:         // Render content
00942:         try {
00943:             $content .= $contentObject->render($configuration);
00944:         } catch (ContentRenderingException $exception) {
00945:             // Content rendering Exceptions indicate a critical problem which should not be

23 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::render(TYPO3\CMS\Frontend\ContentObject\CaseContentObject, array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00857:                     $contentObject = $this->getContentObject($name);
00858:                     if ($contentObject) {
00859:                         $content .= $this->render($contentObject, $conf);
00860:                     } else {
00861:                         // Call hook functions for extra processing

22 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGetSingle("CASE", array, "20")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00803:             if ((int)$theKey && strpos($theKey, '.') === false) {
00804:                 $conf = $setup[$theKey . '.'];
00805:                 $content .= $this->cObjGetSingle($theValue, $conf, $addKey . $theKey);
00806:             }
00807:         }

21 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGet(array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectArrayContentObject.php:
00039: 
00040:         $this->cObj->includeLibs($conf);
00041:         $content = $this->cObj->cObjGet($conf);
00042:         $wrap = isset($conf['wrap.']) ? $this->cObj->stdWrap($conf['wrap'], $conf['wrap.']) : $conf['wrap'];
00043:         if ($wrap) {

20 TYPO3\CMS\Frontend\ContentObject\ContentObjectArrayContentObject::render(array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00941:         // Render content
00942:         try {
00943:             $content .= $contentObject->render($configuration);
00944:         } catch (ContentRenderingException $exception) {
00945:             // Content rendering Exceptions indicate a critical problem which should not be

19 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::render(TYPO3\CMS\Frontend\ContentObject\ContentObjectArrayContentObject, array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00857:                     $contentObject = $this->getContentObject($name);
00858:                     if ($contentObject) {
00859:                         $content .= $this->render($contentObject, $conf);
00860:                     } else {
00861:                         // Call hook functions for extra processing

18 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGetSingle("COA", array, "list")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/CaseContentObject.php:
00042:             $theValue = '';
00043:         } else {
00044:             $theValue = $this->cObj->cObjGetSingle($conf[$key], $conf[$key . '.'], $key);
00045:         }
00046:         if (isset($conf['stdWrap.'])) {

17 TYPO3\CMS\Frontend\ContentObject\CaseContentObject::render(array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00941:         // Render content
00942:         try {
00943:             $content .= $contentObject->render($configuration);
00944:         } catch (ContentRenderingException $exception) {
00945:             // Content rendering Exceptions indicate a critical problem which should not be

16 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::render(TYPO3\CMS\Frontend\ContentObject\CaseContentObject, array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00857:                     $contentObject = $this->getContentObject($name);
00858:                     if ($contentObject) {
00859:                         $content .= $this->render($contentObject, $conf);
00860:                     } else {
00861:                         // Call hook functions for extra processing

15 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGetSingle("CASE", array, "tt_content")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00839:                 // Getting the cObject
00840:                 $timeTracker->incStackPointer();
00841:                 $content .= $this->cObjGetSingle($name, $conf, $key);
00842:                 $timeTracker->decStackPointer();
00843:             } else {

14 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGetSingle("CASE", array, "")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentContentObject.php:
00095:                         $this->cObj->lastChanged($row['tstamp']);
00096:                         $cObj->start($row, $conf['table']);
00097:                         $tmpValue = $cObj->cObjGetSingle($renderObjName, $renderObjConf, $renderObjKey);
00098:                         $cobjValue .= $tmpValue;
00099:                     }

13 TYPO3\CMS\Frontend\ContentObject\ContentContentObject::render(array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00941:         // Render content
00942:         try {
00943:             $content .= $contentObject->render($configuration);
00944:         } catch (ContentRenderingException $exception) {
00945:             // Content rendering Exceptions indicate a critical problem which should not be

12 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::render(TYPO3\CMS\Frontend\ContentObject\ContentContentObject, array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00857:                     $contentObject = $this->getContentObject($name);
00858:                     if ($contentObject) {
00859:                         $content .= $this->render($contentObject, $conf);
00860:                     } else {
00861:                         // Call hook functions for extra processing

11 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGetSingle("CONTENT", array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/FluidTemplateContentObject.php:
00261:             }
00262:             if (!in_array($variableName, $reservedVariables)) {
00263:                 $variables[$variableName] = $this->cObj->cObjGetSingle($cObjType, $variablesToProcess[$variableName . '.']);
00264:             } else {
00265:                 throw new \InvalidArgumentException(

10 TYPO3\CMS\Frontend\ContentObject\FluidTemplateContentObject::getContentObjectVariables(array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/FluidTemplateContentObject.php:
00095:         $this->setExtbaseVariables($conf);
00096:         $this->assignSettings($conf);
00097:         $variables = $this->getContentObjectVariables($conf);
00098:         $variables = $this->contentDataProcessor->process($this->cObj, $conf, $variables);
00099: 

9 TYPO3\CMS\Frontend\ContentObject\FluidTemplateContentObject::render(array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00941:         // Render content
00942:         try {
00943:             $content .= $contentObject->render($configuration);
00944:         } catch (ContentRenderingException $exception) {
00945:             // Content rendering Exceptions indicate a critical problem which should not be

8 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::render(TYPO3\CMS\Frontend\ContentObject\FluidTemplateContentObject, array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00857:                     $contentObject = $this->getContentObject($name);
00858:                     if ($contentObject) {
00859:                         $content .= $this->render($contentObject, $conf);
00860:                     } else {
00861:                         // Call hook functions for extra processing

7 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGetSingle("FLUIDTEMPLATE", array, "10")

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php:
00803:             if ((int)$theKey && strpos($theKey, '.') === false) {
00804:                 $conf = $setup[$theKey . '.'];
00805:                 $content .= $this->cObjGetSingle($theValue, $conf, $addKey . $theKey);
00806:             }
00807:         }

6 TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::cObjGet(array)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/Page/PageGenerator.php:
00208:         $timeTracker->incStackPointer();
00209:         $timeTracker->push($tsfe->sPre, 'PAGE');
00210:         $pageContent = $tsfe->cObj->cObjGet($tsfe->pSetup);
00211:         if ($tsfe->pSetup['wrap']) {
00212:             $pageContent = $tsfe->cObj->wrap($pageContent, $tsfe->pSetup['wrap']);

5 TYPO3\CMS\Frontend\Page\PageGenerator::renderContent()

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/Http/RequestHandler.php:
00214:                 // Content generation
00215:                 if (!$this->controller->isINTincScript()) {
00216:                     PageGenerator::renderContent();
00217:                     $this->controller->setAbsRefPrefix();
00218:                 }

4 TYPO3\CMS\Frontend\Http\RequestHandler::handleRequest(TYPO3\CMS\Core\Http\ServerRequest)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/core/Classes/Core/Bootstrap.php:
00305: 
00306:         // Execute the command which returns a Response object or NULL
00307:         $this->response = $requestHandler->handleRequest($request);
00308:         return $this;
00309:     }

3 TYPO3\CMS\Core\Core\Bootstrap::handleRequest(TYPO3\CMS\Core\Http\ServerRequest)

/path/to/typo3/installation/typo3_src-7.6.27/typo3/sysext/frontend/Classes/Http/Application.php:
00076:     public function run(callable $execute = null)
00077:     {
00078:         $this->bootstrap->handleRequest(\TYPO3\CMS\Core\Http\ServerRequestFactory::fromGlobals());
00079: 
00080:         if ($execute !== null) {

2 TYPO3\CMS\Frontend\Http\Application::run()

/path/to/typo3/installation/typo3_src-7.6.27/index.php:
00031: call_user_func(function () {
00032:     $classLoader = require rtrim(realpath(__DIR__ . '/typo3'), '\\/') . '/../vendor/autoload.php';
00033:     (new \TYPO3\CMS\Frontend\Http\Application($classLoader))->run();
00034: });

1 {closure}()

/path/to/typo3/installation/typo3_src-7.6.27/index.php:
00032:     $classLoader = require rtrim(realpath(__DIR__ . '/typo3'), '\\/') . '/../vendor/autoload.php';
00033:     (new \TYPO3\CMS\Frontend\Http\Application($classLoader))->run();
00034: });

**Comment by georgringer** [comment]
please use the namespaced version in your template, this is not a bug
