### ISSUE TITLE
news 7.0 - Oops error 

### ISSUE THREAD

**Issue by pauweh** [georgringer/news#654]
Using typo3 8.7.13 on php 7.2.3 and heavily used News 6.3.0 is working pretty well.
Update to News 7.0 results in an
+++
Oops, an error occurred!
Cannot access protected property GeorgRinger\News\Domain\Model\NewsDefault::$falMediaPreviews
+++
only on pages using news. 
Return to news 6.3 does all well again.

**Comment by georgringer** [comment]
Dont use `newsItem.falMediaPreviews` but use `newsItem.mediaPreviews` - the `fal`prefix has been dropped everywhere. you can also change that in 6.3 already

**Comment by georgringer** [comment]
releasing new version 7.0.1
