### ISSUE TITLE
news 7.0 will crash website if templates are not updated

### ISSUE THREAD

**Issue by pauweh** [georgringer/news#657]
Be aware that update from news 6.3 to 7.0 will crash your website 
if you use the newsItem.falMediaPreviews option in your own news templates.
Lots of extensions depending on tx_news do use falMediaPreviews in their templates, too.
You have to replace all occurencies of 
newsItem.falMediaPreviews 
with
newsItem.mediaPreviews
in all templates of all used extensions 
before updating the news-extension.

**Comment by georgringer** [comment]
which has been described in the release notes of 6.0.0, see https://docs.typo3.org/typo3cms/drafts/github/georgringer/news/Misc/Changelog/6-0-0.html#simplify-getters-for-fal-fields - a year ago.
