### ISSUE TITLE
Problem with items per page when use the search result option of tx_news

### ISSUE THREAD

**Issue by fiotakis** [georgringer/news#661]
Hello, I have used the search result option of tx_news and I want to limit the results to 10 per page.
Unfortunately this option (items per page) doesn't work for the search (for the list this option works perfectly) and all the results are loaded in the same page delaying the response of the server.

Also I have tried to solve the problem using the following typosript code but without any success.
**plugin.tx_news.settings.list.paginate.itemsPerPage=10**

My system uses 7.6.27 version of TYPO3.

Is there any known bug?

Thanks for help!!

**Comment by hhchrizzo** [comment]
There is still no pagination for Searchresults with news 7.0.7 and TYPO3 8.7.19
Maybe the flexformfields/settings for 'hidePagination' and 'itemsPerPage' should by disabled for the searchResult selection until they are finally supported.

**Comment by jokumer** [comment]
related to #871

**Comment by georgringer** [comment]
closing it in favor of #871

feel free to sponsor the development of this feature if it is very important to you
