### ISSUE TITLE
double <i class="fa fa-check"></i>

### ISSUE THREAD

**Issue by Hobokens** [georgringer/news#665]
Hi Georg,
In the file 'ext\news\Classes\Hooks\InlineElementHook.php' you find 

    <i class="fa fa-check"></i>

twice at line 79. Shouldn't be one enough?

Regards
Hobokens

    $extraItem = ['showinpreview' => ' <span class="btn btn-default" title="' . htmlspecialchars($label) . '"><i class="fa fa-check"></i><i class="fa fa-check"></i></span>'];

**Comment by ayacoo** [comment]
Also there is a duplicate $previewSetting === 1 condition in this file

**Comment by ayacoo** [comment]
see https://github.com/georgringer/news/commit/d472d0f43d5755444ca68d891aacb8a9555e9aae
