### ISSUE TITLE
i have problem with ajax pagination When i select news page pagination indexAjax.html then it's not working properly

### ISSUE THREAD

**Issue by anujaunds** [georgringer/news#669]
My Setup Ts code is:
plugin.tx_news.settings.list {
    paginate.templatePath = fileadmin/private/news/Templates/Styles/Twb/Templates/ViewHelpers/Widget/Paginate/IndexAjax.html
}

## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior/output**

**Environment**
- TYPO3 version(s): [e.g. 8.7.12, 9.2.0]
- news version: [e.g. 7.0.5]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes, no]
- OS: [e.g. OSX 10.13.4, Windows 10]

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
Closed because lack of feedback
