### ISSUE TITLE
Show media on detail page if VIEW_LIST_AND_DETAIL is chosen in the media dropdown

### ISSUE THREAD

**Issue by Figilano** [georgringer/news#670]
**Setup**
TYPO3 8.7.15 (composer mode), news 7.0.4
Create a new news article. Reference an image file and set "show in views" to "show in all views". 

**Current Behavior**
On the detail page of that article, the image is not shown. 

**Expected behavior/output**
The image should be shown on the detail page.

**Possible Solution**
The code that displays the images is f:render partial="Detail/MediaContainer" arguments="{media: newsItem.mediaNonPreviews, settings:settings}"

The image is not shown because getMediaNonPreviews() in the News Model is missing the configuration FileReference::VIEW_LIST_AND_DETAIL

Adding FileReference::VIEW_LIST_AND_DETAIL to the configuration in Line 815 of Classes/Domain/Model/News.php should fix this.

**Comment by georgringer** [comment]
Thanks for your issue report. Can you check out master as it has been changed with https://github.com/georgringer/news/pull/662

**Comment by georgringer** [comment]
closed because of no feedback

**Comment by rdk-pmis** [comment]
I can confirm this solved the issue. I ran into the same problem and was checking issues. Any idea when this will be live (for those using composer)?

**Comment by georgringer** [comment]
I try a release this or next week
