### ISSUE TITLE
A cache with identifier "news" does not exist.

### ISSUE THREAD

**Issue by schumiel** [georgringer/news#671]
I get the following error message if I want to empty the cache in the install tool:

> A cache with identifier "news" does not exist.

I use the news extension in a separate extension as follows:

`class News extends \GeorgRinger\News\Domain\Model\News {`

I do not understand the problem, why there is a cache problem.
Can you help, please.

**Comment by georgringer** [comment]
never had this issue
```
// Register cache frontend for proxy class generation
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['news'] = [
        'frontend' => \TYPO3\CMS\Core\Cache\Frontend\PhpFrontend::class,
        'backend' => \TYPO3\CMS\Core\Cache\Backend\FileBackend::class,
        'groups' => [
            'all',
            'system',
        ],
        'options' => [
            'defaultLifetime' => 0,
        ]
    ];
```
this is the cache configured in the `ext_localconf.php`

never had this error, therefore closing this issue
