### ISSUE TITLE
Use news title as page-title in correct language

### ISSUE THREAD

**Issue by Alexander-Hagemeier** [georgringer/news#672]
Hello,

I use this TS-configuration to use the news title/news alternative_title as the page-title:

```
    lib.metadata.20 >
    lib.metadata.20 = RECORDS
    lib.metadata.20 {
        source = {GP:tx_news_pi1|news}
        source.insertData = 1
        tables = tx_news_domain_model_news
        conf {
            tx_news_domain_model_news >
            tx_news_domain_model_news = TEXT
            tx_news_domain_model_news {
                field = alternative_title
                ifEmpty.field = title
                wrap = <title>|</title>
            }
        }
    }
```

Additionally, I have this configuration for the setup:
```
config.sys_language_mode = strict
config.sys_language_overlay = 0
```

Now, if i make a translation of a news and access it via the browser, the page-title is showing the title of the default language. So it seems, that in the above configuration is missing something to tell Typo3 to use the fields of the translated news and not the default one.

Does someone have an idea how i can achieve the desired behaviour?

Thanks a lot in anticipation!

**Comment by georgringer** [comment]
This has nothing to do with my extension. please ask in public TYPO3 slack channel.

However: news already provides the title and all kind of meta tags out of the box, no need to disable it and manually adding it again
