### ISSUE TITLE
Make use of backend users profile image

### ISSUE THREAD

**Issue by comi91** [georgringer/news#674]
Provide a way to use the avatar image in Fluid templates. Could be a nice feature to have the blog post author profile image (avatar) next to the author name.
See https://github.com/fnagel/t3extblog/issues/105
https://github.com/fnagel/t3extblog/commit/a56c21e225ae155becc6d4e3ce29760b3cfcf293

**Comment by georgringer** [comment]
currently there is no relation to be_users which would be required first

**Comment by georgringer** [comment]
closing it because no plans yet to add be_user relation
