### ISSUE TITLE
Tx_News Version 7.04 wanting tables that are obsolete 

### ISSUE THREAD

**Issue by zvenson69** [georgringer/news#675]
## Bug Report

**Current Behavior**

Front-End is giving errors: 
Table 'XXX.tx_news_domain_model_ttcontent' doesn't exist 
Table 'XXX.tx_news_domain_model_filereference' doesn't exist 

BackendModuk giving errors:
Table 'XXX.tx_news_domain_model_category' doesn't exist 

but these tables are not needed any longer and of course are not created. It's not an updated news version - i just installed v7.04 so im wondering why the extension wants tables that are obsolete...

**Expected behavior/output**:

no error should be showing / 

I have done Database Compare reinstalled the extension, downgraded, upgraded to github version and did everything i could think of... 

**Environment**
- TYPO3 version(s): 8.7.15
- news version:  7.0.4
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
It seems the default TS is not loaded in your enviroment (Which can have a lot of reasons).  Include all of that https://github.com/georgringer/news/blob/master/ext_typoscript_setup.txt in your TS and it will work.
