### ISSUE TITLE
Editing a localized news record won't clear the news detail cache

### ISSUE THREAD

**Issue by Nemo64** [georgringer/news#681]
## Bug Report

**Current Behavior**
I translated a news record and a news detail page. If I now edit the translated news, the cache of the detail page won't be cleared.

**Expected behavior/output**
All changes should be immediately visible in frontend.

**Environment**
- TYPO3 version: 8.7.15
- news version: 6.3.0
- Composer Mode: yes
- OS: ~linux (Mittwald) and docker/debian for local development

**Possible Solution**
I kind of created the egg before the chicken: #680

**Additional context**
The problem is that extbase only exposes the original uid and not the localized uid.

**Comment by georgringer** [comment]
solved IMO with https://github.com/georgringer/news/pull/680, therefore closing the issue
