### ISSUE TITLE
[DOC] Translation of content elements in tx_news

### ISSUE THREAD

**Issue by misterboe** [georgringer/news#682]
I found an "issue" in the translation handling of content elements of tx_news records. The translated content is only shown if `sys_language_overlay = 1` is set. 

Perhabs we could add this to the documentation. If you think we should add this and you tell me where this should be placed i would send a PR for that. 

Details: 
https://stackoverflow.com/questions/50871787/translation-of-content-elements-in-tx-news-shows-default-language

**Comment by georgringer** [comment]
code changed a couple of times, closing issue therefore. feel free to reopen a new one if still relevant
