### ISSUE TITLE
Call to a member function setTSlogMessage() on null

### ISSUE THREAD

**Issue by tomhatzer** [georgringer/news#685]
## Bug Report

**Current Behavior**
When saving a news entry following error occurs:
```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function setTSlogMessage() on null | Error thrown in file /var/www/typo3conf/ext/news/Classes/Service/CategoryService.php in line 104. Requested URL: --Anonymized--&edit[tx_news_domain_model_news][3299]=edit
```

**Expected behavior/output**
News will be saved and no error message will be shown.

**Environment**
- TYPO3 version(s): 8.7.16
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Suse Enterprise Linux 12
- PHP version: 7.0.7

**Possible Solution**
I created a PR for this: #684

**Additional context**
none

**Comment by georgringer** [comment]
Fixed, thx
