### ISSUE TITLE
Allow other extensions to add actions to the news administration module

### ISSUE THREAD

**Issue by dmitryd** [georgringer/news#687]
Sometimes it is necessary to add more news related activities for editors. Making a separate Backend module for that is not feasible. It makes sense to add functions to the existing news administration module instead. This can be achieved if the news administration controller has a way to extend its action menu by other extensions via signals. Than extensions will be able to add their actions to that menu and integrate extra functionality to the main news administration module.

**Comment by georgringer** [comment]
merged

**Comment by dmitryd** [comment]
Thank you :)
