### ISSUE TITLE
Limit Number of News Items does not work properly

### ISSUE THREAD

**Issue by tsurfer84** [georgringer/news#689]
## Bug Report

I use the news plugin module 3x on one site:

1. the first module should show a maximum number of news of 1, starting at news item 0 (for the last news item).
2. the first module should show a maximum number of news of 1, starting at news item 1 (for the second last news item).
3. finally, the third module should show a maximum number of news of 1, starting at news item 2 (for the third last news item).

Current behaviour is: first and second plugin module both showing news as they should. but the third plugin does not show up at all. For testing, I copied each elements in order to avoid any other configuration mistakes. I also tried other starting numbers as 4,5 and 6. But also this did not fix it.

The expected behaviour works fine with tx_news version 6.3 und lower.
The bug results since the update of version 7.0 and following up.

**Environment**
- TYPO3 version: [8.7.16]
- news version: [e.g. 7.0.5]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Windows 10]

**Comment by georgringer** [comment]
in which language are you working? does it work on default language 0 or fails only in translations and are all news translated?

**Comment by tsurfer84** [comment]
Default Language 0 is german, 1 is english und 2 is spanish. It fails in all three languages, independant from translated oder fallback content.

**Comment by tsurfer84** [comment]
Problem still exists, it's a pity!

**Comment by tsurfer84** [comment]
sorry, your extension ist not useable at all for me, despite no answer and concerning about my problem is no good attitude at all!

**Comment by tsurfer84** [comment]
No reaction is no good attitude. Have a good time with your buggy extension.
