### ISSUE TITLE
Tag List without specified sort order throws error

### ISSUE THREAD

**Issue by whiteroom** [georgringer/news#693]
## Bug Report

**Current Behavior**
When using "Tag List" without specifying a sort order (Last edited, Created, Title) TYPO3 CMS throws an error `Unknown column 'tx_news_domain_model_tag.datetime' in 'order clause'`
Reason: The default empty option in the form-wizards-element leads to passing datetime for validation 

**Environment**
- TYPO3 version:  8.7.16
- news version: 7.0.5
- Setup with Composer (Composer Mode): no

**Possible Solution**
Add a fallback with "Title" as default or add extra field `datetime` to the tx_news_domain_model_tag record

**Comment by georgringer** [comment]
I can't reproduce this and close the issue
