### ISSUE TITLE
Feature-Request: Dynamic back-link

### ISSUE THREAD

**Issue by DavidBruchmann** [georgringer/news#694]
## Feature Request

Currently the "back"-link is just going to the static configured page, without respect to the state of that page. That means it doesn't matter if I've been on page 3 or 5 of the list-view, it's always directed to the same page, the same view and the same state.
Also choice of any category is not respected.

**The solution you'd like**
If I browse page 4 of the list-view, open a detail-view and then the back button, I want to land on page 4 of the list-view again. And if I've chosen a category before, I want land on the list-view of that category too again.

**Describe alternatives you've considered**
JavaScript is nice but it would be nicer without the need.

**Comment by georgringer** [comment]
as this would leave to duplicate content I prefer this solution https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Templates/Snippets/Index.html#improved-back-links which uses JS historyback if on same domain and otherwise the regular backlink

**Comment by DavidBruchmann** [comment]
Thank's, your solution.
I can't follow the argument with duplicate content though. It's character of a typical blog that a post can be reached by several links (tag, category, archive, ...) So it doesn't matter if one link more or less especially if it's increasing usability, IMHO.

**Comment by georgringer** [comment]
I will think about solving it after my holidays

**Comment by georgringer** [comment]
I won't integrate it into ext:news, feel free to create a custom extension which brings support for that
