### ISSUE TITLE
Incorrect integer value at row 1

### ISSUE THREAD

**Issue by co-operate** [georgringer/news#695]
Duplicate / reopening issue #502

> when i remove the “archive date” in a news entry i get the error message
> `2: SQL error: 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'archive' at row 1' (tx_news_domain_model_news:5)`
> this is a problem with php7 and strict mode.

Should be solvable by casting the empty archive date as 'null'?
Currently there is no option whatsoever to remove an inadvertently entered (&saved) archive date.

**Comment by georgringer** [comment]
This is because of strict MySQL setting. Which version are you using

**Comment by co-operate** [comment]
> This is because of strict MySQL setting. 
Yes, as stated in the original issue :)

> Which version are you using
MySQL 5.7.22 with STRICT_TRANS_TABLES. That's the new default mode in MySQL 5.7.
(As well as TYPO3 8.7.15 and tx_news 7.0.5)

The default value for 'archive' in MySQL is '0' anyway, which is interpreted as an empty archive date in the BE. Wouldn't it be possible to reverse this behavior and cast an empty BE archive field as '0' for the database? I imagine one probably would have to bypass some type of datetime sanity check to accomplish this, though.
