### ISSUE TITLE
Duplicate wizard button for internalurl field

### ISSUE THREAD

**Issue by davidlemaitre** [georgringer/news#696]
## Bug Report

**Current Behavior**
For an internal page, the internalurl field has two buttons to open link browser.

**Expected behavior/output**
Only one button.

**Environment**
- TYPO3 version(s): 8.7.16
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Comment by echavaillaz** [comment]
Hi,

I can confirm this bug.
It is the same for the field "uri" in a "related_link".

It is due to the new behavior of an input in the TCA with the "renderType" set to "inputLink".

So to resolve this, you just have to remove the "wizards" section.

Thanks
