### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by AstCommodore** [georgringer/news#697]
Hi Georg,

I've got the following error when I want to open a single news in the Backend. I could use the list or the news module to reproduce the error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Unsupported operand types | Error thrown in file /html/typo3/typo3conf/ext/news/Classes/Hooks/InlineElementHook.php in line 81.
` 
The error is also described for event news https://github.com/georgringer/eventnews/issues/15

**Environment**
- TYPO3 version: 8.7.16
- news version: 7.0.4, 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
can you check what `$extraItem` is in this line? thx

**Comment by AstCommodore** [comment]
Hi Georg,

thanks for your hint, now it's much more clear to myself:

1. I enabled `records.advancedMediaPreview`
2. I added a new entry for advancedMediaPreview to do some magic for my own:
```sys_file_reference {
        showinpreview {
          addItems.20 = My config
        }
```
3. Every time a news record fails open it when media files are using my additional configuration.
4. In this case `$extraItem` is `NULL`

Maybe you could define a default return value for renderForeignRecordHeaderControl_postProcess?
