### ISSUE TITLE
Hi，all，how can make a new type to news system? thanks!

### ISSUE THREAD

**Issue by jooler** [georgringer/news#698]
Please see my screenshot , I want make a new type for news system, but I don't know how!
![tim 20180630214018](https://user-images.githubusercontent.com/25960405/42125701-3a427dd2-7cae-11e8-8a51-23defed9b5f5.png)

I want add a new type, like video
and in this type, add some fields

How can I do it
thanks for your help.

**Comment by DavidBruchmann** [comment]
In the [manual](https://docs.typo3.org/typo3cms/extensions/news/UsersManual/Records/News/Index.html) it's explained how to include many kind of media.
As general rule you can keep in mind that anything on the server where TYPO3 is installed should be linked from the tab "Media" and anything else from the tab "Relations". There might be cases where to break that rule but it's a good start.

**Comment by jooler** [comment]
@DavidBruchmann thanks , I found a way to do it and I'm trying.
