### ISSUE TITLE
Prev and next link

### ISSUE THREAD

**Issue by studiokaloa** [georgringer/news#699]
Hi,

`config.sys_language_mode  = strict`

When use of {paginated.prev} and {paginated.next} in detail template, the link should consider the current language.
Actually, in SimplePrevNextViewHelper.php > function getNeighbours(), sys_language_uid is hardcoded to default (0)

**Environment**
- TYPO3 version(s): 8.7.16
- news version: 7.0.5

**Comment by studiokaloa** [comment]
line 196 : 
`$queryBuilder->expr()->eq('sys_language_uid', $queryBuilder->createNamedParameter($GLOBALS['TSFE']->config['config']['sys_language_uid'], \PDO::PARAM_INT)),`
should do the trick…

**Comment by georgringer** [comment]
I don't want to change the behaviour there. please copy the VH to your own namespace und adopt it to your needs
