### ISSUE TITLE
Category filter

### ISSUE THREAD

**Issue by bhanika** [georgringer/news#701]
The category filter is displayed alphabetically in the default language (German) https://www.nemetschek.com/news/markennews/, but not in English https://www.nemetschek.com/en/news/brand-news/.

**Comment by topsnet-holgerd** [comment]
Dear bhanika,

I've got a similar problem, categories always show sorted by id but I need them in alphabetical order. How do you manage to sort your German categories alphabetically?
![image](https://user-images.githubusercontent.com/35534306/42811425-e00e1cda-89ba-11e8-9a99-affddef7c4f1.png)

**Comment by georgringer** [comment]
This is how it works in typo3 as overlay is happening later. Sort them by a custom vh

**Comment by bhanika** [comment]
Dear topsnet-holgerd -
I made one page with the categories and in that order they will disappear at the frontend.
Best Bettina
