### ISSUE TITLE
path_segment is not checked for news with same title

### ISSUE THREAD

**Issue by nemstaa** [georgringer/news#703]
We have a lot of news entries in our system. The editors will give the same title over and over again, because of repeating events or elections.
If the path segment is not checked, the frontend will show you a random news with the same news title.
Is it possible to check all path segements for an occurence on the same page ID and adapt the value with adding a number, like realurl does?
Thanks in advance.

**Comment by georgringer** [comment]
You could add eval unique to tca. Currently not done as configuration but would be easy

**Comment by nemstaa** [comment]
Ok. That is a validation and the editor sees a red marked field. Then I should make a custom validation rule or field, which checks and gives an correct output. Then this will replace the TCA field.
Thanks/Danke. ;-)
