### ISSUE TITLE
simplePrevNext pid based on content settings

### ISSUE THREAD

**Issue by in-session** [georgringer/news#704]
Would not it be better to set the "n: simplePrevNext" based on the detail flexform information?
Then then subfolders can be included, which are inserted via the record information of the detail view.

`
<n:simplePrevNext pidList="{f:if(condition: settings.startingpoint, then: settings.startingpoint, else: newsItem.pid)}" news="{newsItem}" as="paginated" sortField="datetime">

`
Or is there already a better approach for this?

**Comment by georgringer** [comment]
Most of the time this is not set in detail. Feel free to adopt the vh to your needs, the name simple is there for a reason
