### ISSUE TITLE
MultiCategorySelection

### ISSUE THREAD

**Issue by topsnet-holgerd** [georgringer/news#705]
Dear news experts,
I read the doc about selecting multiple categories in order to filter the news to them (news/Documentation/Tutorials/Templates/MultiCategorySelection/Index.rst). I understand, that with additionalParams="{n:multiCategoryLink.arguments you can add or remove a category to the filter. 
How can I combine two categories (first is dynamic and depends on dropdown item, second is fixed) in one URL call? I tried several syntaxes without success, for example comma separated:
`<option value='<f:uri.action action="show" pageUid="{settings.listPid}" additionalParams="{tx_news_pi1:{overwriteDemand:{categories: category.item.uid}}, n:multiCategoryLink.arguments(mode:'add',item:'100',list:overwriteDemand.categories)}"></f:uri.action>'>{category.item.title}</option>`
Best regards

**Comment by georgringer** [comment]
that is not possible out of the box and you would need to create a custom ext for that
