### ISSUE TITLE
category sorting

### ISSUE THREAD

**Issue by topsnet-holgerd** [georgringer/news#706]
Dear news experts,

As I replied to bhaniko (see four issues below), I like to sort the categories by title and not by id (in the backend plugin as well as in a frontend dropdown list).

For the list view of all categories (BE) the modification of ext/news/Configuration/TCA/Overrides/sys_category.php helped:
`$GLOBALS['TCA']['sys_category']['ctrl']['sortby'] = null;
$GLOBALS['TCA']['sys_category']['ctrl']['default_sortby'] = 'ORDER BY title';`

But this doesn't affect the sorting in the plugin:
![image](https://user-images.githubusercontent.com/35534306/42875517-413c88d8-8a84-11e8-89f6-395ee839f6ea.png)
Thanks for any proposal.

**Comment by georgringer** [comment]
Remove the tree rendering if you don't need the tree and then the order will work

**Comment by topsnet-holgerd** [comment]
Dear Georg Ringer,

sorry to ask again. I didn’t find anything on the web, how to manage to remove the tree rendering for categories.

Best regards,
Holger

Von: Georg Ringer <notifications@github.com>
Gesendet: Donnerstag, 19. Juli 2018 09:51
An: georgringer/news <news@noreply.github.com>
Cc: Holger Drosdek (tops.net) <hd@tops.net>; Author <author@noreply.github.com>
Betreff: Re: [georgringer/news] category sorting (#706)


Remove the tree rendering if you don't need the tree and then the order will work
