### ISSUE TITLE
BackPid not working / empty value

### ISSUE THREAD

**Issue by scriptserv** [georgringer/news#709]
## Bug Report

**Current Behavior**
Set BackPid in Backend - Debug in Frontend (ListView), the BackPid is showing up under "{settings.backpid}" - everything ok.
Now click on the News and get to the Detailview - "{settings.backpid}" is empty.

Plugin Listview - override plugin settings allowed
Plugin Detailview - override plugin settings allowed

**Expected behavior/output**
Getting the backpid to get back to the page where the Listview Plugin is.

**Environment**
- TYPO3 version(s): 8.7.15 - 17
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): No
- OS: Linux 4.4.0-122-generic 

**Possible Solution**
-

**Additional context**
-

**Comment by Andreas-Sommer** [comment]
Possible Solution
https://github.com/belsignum/news/commit/b64b9da8950a18fc44795750dcf0bbd659985448

**Comment by georgringer** [comment]
I won't add more logic there, so closing the issue
