### ISSUE TITLE
Categories not available in Workspace 

### ISSUE THREAD

**Issue by diealtebremse** [georgringer/news#710]
Hi,
I'm using TYPO3 8.7.16 and News 7.0.5.
I've setup some news and a news list view, which shows all news. In my news item partial I'm displaying the categories related to each news. The single view also shows the categories. As soon I switch to a workspace, the categories are not displayed any more. I added an <f:debug>{newsItem}</f:debug> to my Partial to get more details. I found out that for some reason the categories attribute is empty.
I don´t know if this is an news related issue or actually a problem with extbase. Maybe #230 isrelated to this?

**Comment by georgringer** [comment]
IMO this is a core issue, as I don't plan to change anything in that regard, I am closing this issue
