### ISSUE TITLE
Configurations TsConfig for the 'Category selection' not work

### ISSUE THREAD

**Issue by typo3ua** [georgringer/news#712]
On the `My page with list news` I have categories:
```
[1] Cat 1
[2] Cat 2
    [3] Cat 3
[4] Cat 4
[5] Cat 5
```
In the `TsConfig` On the `My page with list news` I did add this lines 
```
tx_news.categoryRestrictionForFlexForms = 1
tx_news.module.allowedCategoryRootIds = 2
TCEFORM.tx_news_domain_model_news.categories.PAGE_TSCONFIG_IDLIST = 2
```
 I took it from "https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Configuration/TsConfig/Index.html#allowedcategoryrootids"

I did insert `ext:news` on the page but I in the `Category selection` I see all tree
### Category selection
```
[1] Cat 1
[2] Cat 2
    [3] Cat 3
[4] Cat 4
[5] Cat 5
```
**I must see only...**
```
[2] Cat 2
    [3] Cat 3
```
What I did wrong?

I have last TYPO3 9.3.3, ext:news from git master, PHP 7.2

**Comment by hilburger** [comment]
Hi there! 

I have the same problem. 
Adding 
  tx_news.module.allowedCategoryRootIds = 10 (ID is only an example) 
in TSConfig field of User- or BE-group does not do anything. 

I am on 9.5.17

Any news on this?

Cheers,
Thomas

**Comment by Inf166** [comment]
Hi!

I am having the same Issue with almost the same configuration as above on 11.5 TYPO3

Cheerio,
Joel

**Comment by Inf166** [comment]
![image](https://user-images.githubusercontent.com/38419872/151342467-ec13aa14-2c04-4432-9e38-80b83c307546.png)
https://docs.typo3.org/p/georgringer/news/main/en-us/Reference/ExtensionConfiguration/Index.html#category-restriction-categoryrestriction

It seems that this feature is to this day not finished...

**Comment by typecat** [comment]
On TYPO3 11.5.14 with EXT:news v9.4.0:
* Restriction of categories in TCA: works
* Restriction of categories in Flexform using `tx_news.categoryRestrictionForFlexForms = 1`: **does not work**.

I went through the `GeorgRinger\News\Backend\FormDataProvider\NewsFlexFormManipulation::addCategoryConstraints`method with XDebug, but did not find, where it fails.

Also, I thought, maybe the restriction needs to be set for the felxform field explicitly via `TCEFORM.tt_content.pi_flexform.news_pi1.sDEF.settings\.categories.PAGE_TSCONFIG_IDLIST = 20,55`, but that didn't work either.

**Comment by akoenig-clickstorm** [comment]
With config.treeConfig.startingPoints in TsConfig you can define root categories for flexform and record like this:
```
TCEFORM {
  tx_news_domain_model_news {
    categories.config.treeConfig.startingPoints = 119
  }
  tt_content {
    pi_flexform.news_pi1.sDEF.settings\.categories.config.treeConfig.startingPoints = 119
  }
}

```

**Comment by georgringer** [comment]
code changed a couple of times, closing issue therefore. feel free to reopen a new one if still relevant
