### ISSUE TITLE
Documentation: Show the defaults in list of TypoScript settings

### ISSUE THREAD

**Issue by sypets** [georgringer/news#714]
## Feature Request

Currently, the default values are not listed in the description of the TypoScript settings, e.g. https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Configuration/TypoScript/Index.html#orderby

It is possible to show defaults and is common practice, for example in the TypoScript reference:
https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#cache-period

Showing the defaults in the documentation would make it easier to use the settings.

**Describe the solution you'd like**

Add the defaults to the current descriptions of TypoScript settings.

Example (from TypoScript reference):

```
cache\_period
=============

.. container:: table-row

   Property
         cache\_period

   Data type
         :ref:`data-type-integer`

   Default
         86400 *(= 24 hours)*

   Description
         The number of second a page may remain in cache.


```

**Advantage**

Makes it easier to use the settings. People who configure do not have to look in source code or in TypoScript object browser. 

**Disadvantage**

This solution needs to be maintained. If defaults change in default setup.txt, the docs need to be updated as well. 

**Migration Strategy**

I am willing to help with this, if you think it is a good idea

**Comment by georgringer** [comment]
absolutly a good idea! thanks for any help!
