### ISSUE TITLE
Deprecation Notice: Reference to "EXT:lang" has been moved to "EXT:core"

### ISSUE THREAD

**Issue by arndmesser** [georgringer/news#715]
## TYPO3 Deprecation Notice

Core: Error handler (BE): TYPO3 Deprecation Notice: There is a reference to "EXT:lang/Resources/Private/Language/locallang_general.xlf", which has been moved to "EXT:core/Resources/Private/Language/locallang_general.xlf". This fallback will be removed with TYPO3 v10. in /var/www/html/web/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 3961

**Current references**
There are 21 references to EXT:lang

**Environment**
- TYPO3 version: 9.3.3
- news version: dev-master
- Composer Mode: yes

**Comment by georgringer** [comment]
as long as 8.7 is supported by the current version, nothing will be changed.
