### ISSUE TITLE
Problems with templateLayout in widget paginate with 2 plugins in the same page

### ISSUE THREAD

**Issue by Nostrabramus** [georgringer/news#722]
## Bug Report

**Current Behavior**
if there are more news plugins on the same page in the fluid template ViewHelpers/Widget/Paginate/index.html the value of settings.templateLayout is always read from the first plugin and not from the following ones

**Expected behavior/output**
I want that each plugin reads the configurations from its flexform, as it already happens inside the fluid templates in Layouts - Partials - Templates

**Environment**
- TYPO3 version(s): 9.2.0
- news version: 7.0.4
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: CentOs

**Comment by typo3ua** [comment]
Interesting! For what do you have want more than one and different `Pagination` on the page?

**Comment by Nostrabramus** [comment]
I'm using two `news` plugins each of them with their own `Pagination` on the same page

**Comment by georgringer** [comment]
this is not really solveable but I suggest rendering e.g 20 news and then do the pagination by JS.
therefore I am closing the issue
