### ISSUE TITLE
PDF detail view

### ISSUE THREAD

**Issue by maechler** [georgringer/news#723]
Hi Georg,

We develop and maintain the extension `pdfviewhelpers`, it allows an easy creation of PDF documents using Fluid templates.
https://github.com/bithost-gmbh/pdfviewhelpers

I thought it would be nice if there was an integration with your news extension to be able to download the content of a news detail view as a PDF. If you are interested I would prepare a pull request for that. 

I would create a template with a default layout. It would probably be best to add it as a separate page type (e.g. `Detail.pdf`, although .pdf is probably not a good extension to use), similar to what you have done for the RSS feed.  In addition I could add a note to the documentation on how to enable the PDF creation and how a link to the PDF view can be created. 
If you have any improvements on that approach, feel free to tell me!

I would also offer to take care of issues that arise in this repository that are related to the PDF creation. You could simply mention me or assign the issue to me.

What do you think?

**Comment by maechler** [comment]
As I put more thought into this I think it is best to add such an integration completely to the extension `pdfviewhelpers`. There is most likely no need to extend the `news` extension. We could however add a note to the documentation of your extension if you are interested?

**Comment by maechler** [comment]
I added a template, TypoScript settings and a documentation chapter to our project. Feel free to have a look at it:

https://github.com/bithost-gmbh/pdfviewhelpers/blob/3930f80ee62b062b8429af110b32ee9e64a48477/Documentation/ConfigurationReference/ExtNews/Index.rst

https://github.com/bithost-gmbh/pdfviewhelpers/blob/3930f80ee62b062b8429af110b32ee9e64a48477/Resources/Private/Templates/Extensions/News/Templates/News/Detail.html

https://github.com/bithost-gmbh/pdfviewhelpers/blob/3930f80ee62b062b8429af110b32ee9e64a48477/Configuration/TypoScript/Extensions/News/setup.txt

If you have any suggestions to improve the integration, please let me know.  We will probably release `v2.0` of `pdfviewhelpers` in a week or two.
Do you think we could add a reference to your documentation?

**Comment by georgringer** [comment]
Hey. Thanks for your work. I don't want to maintain the pdf stuff, so it is great to have that in your extension.
Regarding the last question: I think this is not needed as users how to adopt templates and need to do that anyways
