### ISSUE TITLE
List.ical template: Output is not valid iCal format

### ISSUE THREAD

**Issue by hputzek** [georgringer/news#725]
## Bug Report

**Current Behavior**
The output from `Resources/Private/Templates/News/List.ical` is not valid. 

**Expected behavior/output**
Out should validate against https://icalendar.org/validator.html

**Environment**
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX

**Possible Solution**
I'll add a PR

**Comment by hputzek** [comment]
Added a PR: https://github.com/georgringer/news/pull/726

**Comment by georgringer** [comment]
solved
