### ISSUE TITLE
Multiple Tags with the same name in differente Storage Folders

### ISSUE THREAD

**Issue by develth** [georgringer/news#729]
Hi there,

i have two different Storage folders for News (Blog, Press) and i want to handle the Tags separate from them.

**Current Behavior**
If i name a tag with the same name as an existing tag in another storage folder, it appends a 0 

**Expected behavior/output**
The name shoudl be as provided, as long the pid is not the same.

**Environment**
- TYPO3 versio: [8.7.19
- news version: [7.0.5]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Debian 9]

Thanks,
Thomas

**Comment by zauni** [comment]
Maybe I have a solution. With a TCA Override it works:

File: `public/typo3conf/ext/[my_extension_name]/Configuration/TCA/Overrides/tx_news_domain_model_tag.php`

Content: 

```php
<?php
defined('TYPO3_MODE') or die();

$GLOBALS['TCA']['tx_news_domain_model_tag']['columns']['title']['config']['eval'] = 'required,trim';
```

The original config says: 'required,unique,trim'.
