### ISSUE TITLE
Misleading field title for bodytext in default news types 0 showitem  TCA

### ISSUE THREAD

**Issue by frankschuessler** [georgringer/news#730]
## Bug Report

**Current Behavior**
The bodytext field in TCA for `$GLOBALS['TCA']['tx_news_domain_model_news']['types']['0']['showitem']` has the headline `LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:rte_enabled_formlabel` which will be replaced with 'Rich Text Editor'.
Line 680 in news/Configuration/TCA/tx_news_domain_model_news.php

**Expected behavior/output**
I would expect the field name / label of the bodytext field which makes it easier to overwrite the label in an TCA override file.

**Environment**
- TYPO3 version: 8.7.19
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX 10.13.4

**Comment by georgringer** [comment]
wanna do a PR?
