### ISSUE TITLE
Setting alwaysShowFilter=0  not Working! Filter is still showing up.

### ISSUE THREAD

**Issue by SimonWentland** [georgringer/news#732]
Hi Georg,

Search-Filter in the News Administration still appears after setting
`tx_news.module.alwaysShowFilter = 0`
in pageTSConfig

I thought the Filter would not be shown at start. Only by clicking on the top left filter Icon. Or am I misunderstanding this setting?

Typo3 8.7.19
News 7.0.5
Composer no
OSX 10.13.6

![screenshot](https://user-images.githubusercontent.com/13437564/45425283-29a91b00-b699-11e8-8d13-f06447ed4e45.jpg)

**Comment by georgringer** [comment]
not relevant anymore
