### ISSUE TITLE
hidden / disabled news entry

### ISSUE THREAD

**Issue by ivgemeri** [georgringer/news#739]
## Bug Report

**Current Behavior**
No functionality of "hidden" check in news view / detailed news (BE). Nothing happened.
Functionality "hidden" in list view works fine. 
 

**Expected behavior/output**
Functionality in both views - list and news view (detailed view) (BE)

**Environment**
- TYPO3 version(s): [e.g. 8.7.19]
- news version: [e.g. 7.0.5]
- Is your TYPO3 installation set up with Composer (Composer Mode): [ no]
- OS: [ Windows 10]

**Possible Solution**

Probally the naming in the TCA is not correct. Button in list view is named with "disabled". For news view it is "hidden". If you change the TCA entry "disabled" to "hidden" - the function works in news view, but not in list view. 

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
So currently hidden records work in detail view?

**Comment by georgringer** [comment]
closed as lack of feedback
