### ISSUE TITLE
related news - bug in MM-table

### ISSUE THREAD

**Issue by HorstBaumann** [georgringer/news#741]
I think, there is a bug in the "related-article" function.

When I'm editing an article (e.g. "News 1 - uid1") and set another article to the list of related articles (e.g. "News 4 - uid4") - News 4 is not showen on the detail-Page of News 1. - but vice versa.

I discoverd, that this (false) behavior also take place in the mm-table (tx_news_domain_model_news_related_mm)

The ID of the "primary" news is written to the uid_foreign-column and the ID of the related news is written to the uid_local-column - in my opinion, this behavior is reversed....? or am I wrong ?

**Possible Solution**
I figured out, that disabling the line "'MM_opposite_field' => 'related_from'," in the TCA  tx_news_domain_model_news.php solves the problem, but it also disables the related_from function.

**Environment**
- TYPO3 version 8.7.18
- news version: 7.0.5
- no Composer Mode
- OS: debian linux

![news-mm](https://user-images.githubusercontent.com/11771888/45929321-3eff2e80-bf50-11e8-8801-2b63264b61be.jpg)

**Comment by georgringer** [comment]
I think you are correct but I won't change here stuff people depend on.
