### ISSUE TITLE
Add Media to translated news 

### ISSUE THREAD

**Issue by in-session** [georgringer/news#743]
We tried to insert an additional/separate image into an translated news, but the image is not visable in the frontend. Is this not possible yet?

- TYPO3 version(s): [8.7.19]
- news version: [7.0.5]

Greeting Chris

**Comment by in-session** [comment]
Here is the page config:

config {
  sys_language_mode = strict
  sys_language_overlay = 0 
  sys_language_uid = 0
}

**Comment by georgringer** [comment]
this is a core issue and IMO fixed in 9. you can use https://extensions.typo3.org/extension/repair_translation/ for 8x
