### ISSUE TITLE
SEO friendly URL

### ISSUE THREAD

**Issue by JavierYD** [georgringer/news#745]
Hi there.

Is it possible to have news articles SEO friendly URLs in Typo3 9.4? We are willing to sponsor the development.

**Comment by georgringer** [comment]
sponsoring is always welcome, however this will come with 9.5 and the so called enhancers, see https://docs.typo3.org/typo3cms/extensions/core/Changelog/master/Feature-86365-RoutingEnhancersAndAspects.html (url might change)

I have adopted already with https://github.com/georgringer/news/commit/717c1a324f2c1aa19aa2661af83dbd7860f5ada9 the new API and will update docs soon - as said, sponsoring more than welcome!

**Comment by runner78** [comment]
New link:
https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html

**Comment by christianarenz** [comment]
Hi,
is there anything else to configure to make the new slugs feature working?
Thanks

**Comment by zebastiane** [comment]
It's working for me with version `7.0.6` of the extension and the [configuration](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html#persistedaliasmapper) found in the link above.
