### ISSUE TITLE
TYPO3 9.5.0-dev (9.5 LTS): ext:news isn't listed in the manage translation packs module of the new maintainance section in the TYPO3 Install Tool

### ISSUE THREAD

**Issue by josefglatz** [georgringer/news#746]
## Bug Report

**Current Behavior**: ext:news isn't shown

![image](https://user-images.githubusercontent.com/2861556/46271092-2a6ff700-c54b-11e8-8275-69e85843aa77.png)

**Expected behavior/output**
ext:news must be listed in the Translation status section of the module like for ext:solr

**Environment**
- TYPO3 version(s): 9.5.0-dev
- news version: master and latest stable from TER
- Is your TYPO3 installation set up with Composer (Composer Mode): no (Core contribution DevEnv)
- OS: Linux, Apache, MySQL

**Comment by georgringer** [comment]
see `EXT:install/Resources/Public/JavaScript/Modules/LanguagePacks.js`

```
 if (allPackagesExist === true) {
          return;
        }
```

if all language packages are available, the ext is not rendered. this has of course multiple downsides:
- UI is not understandable
- language packs can'T be updated

however this is a core issue

**Comment by josefglatz** [comment]
Thx
