### ISSUE TITLE
Archive date is set to 1970 or 2018

### ISSUE THREAD

**Issue by EnzephaloN** [georgringer/news#749]
## Bug Report

**Current Behavior**
If saved, the archive date is set to (timestamp=) 1970 or 2018

**Expected behavior/output**
The given date or the predefined dates should be saved as timestamp.

**Environment**
- TYPO3 version(s): 8.7.x, 9.5.0
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian Linux

**Comment by georgringer** [comment]
how do you define the archive date?

**Comment by EnzephaloN** [comment]
In tsconfig I use:
tx_news.predefine.archive = august 15th +366 days
In backend it  shows right date before saving. After saving I get 1970-01-01 because in DB the value is 1970.
The behaivour still exist, if I remove these line.
