### ISSUE TITLE
MetaTagViewHelper should consider absRefPrefix for og:image

### ISSUE THREAD

**Issue by arnekolja** [georgringer/news#750]
## Bug Report

**Current Behavior**
When having TYPO3 installed in a sub directory and therefor setting `page.config.absRefPrefix = /subfolder/`, MetaTagViewHelper concatenates TYPO3_SITE_URL and the absolute path, which results in double `/subfolder/`.

**Expected behavior/output**
When having absRefPrefix set, TYPO3_SITE_URL and path should not be concatenated. It needs another solution then.

**Environment**
- TYPO3 version: 8.7.17
- news version: 6.1.1 (but checked with ViewHelper's code of current master, too)
- Composer Mode: no
- OS: macOS 10.14, Debian

**Comment by arnekolja** [comment]
Additional info: Seems to happen only when absRefPrefix is given as path without protocol+host.

**Comment by georgringer** [comment]
what about using forceAbsoluteUrl=1?

**Comment by arnekolja** [comment]
forceAbsoluteUrl=1 is the default setting I used.

In my tests,

TYPO3_SITE_URL is `https://domain.com/subfolder/`
absRefPrefix is `/subfolder/`
and the ViewHelper call
```
<n:metaTag
	property="og:image"
	content="{f:uri.image(src:'{newsItem.firstPreview.uid}', treatIdAsReference:1, maxWidth:'500')}"
	forceAbsoluteUrl="1" />
```
passes a string like `/subfolder/fileadmin/user_upload/bla.png`. So `https://domain.com/subfolder/` and `/subfolder/fileadmin/user_upload/bla.png` get concatenated.

**Comment by georgringer** [comment]
code changed a couple of times, closing issue therefore. feel free to reopen a new one if still relevant
