### ISSUE TITLE
Resource "web_NewsTxNewsM2" was not found

### ISSUE THREAD

**Issue by zelcode** [georgringer/news#751]
## Bug Report

**Current Behavior**

Create new record, click Save, Close and there is exception

#1425389240 TYPO3\CMS\Backend\Routing\Exception\ResourceNotFoundException
The requested resource "web_NewsTxNewsM2" was not found.

But record is created and saved.

Editing existing record is OK.

**Expected behavior/output**

Return to News list

**Environment**
- TYPO3 version 9.5.0
- news version: 7.0.6
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Mint 18.3, Nginx

**Comment by Treedent** [comment]
For me, fixed the problem by resaving news configuration in Settings > Configure extension.

**Comment by MediKathi** [comment]
An old record in sys_be_shortcuts caused this problem in my case.
