### ISSUE TITLE
Der Aufruf des BE-Moduls schläg fehl, wenn eine Nachricht in der Zwischenablage ist

### ISSUE THREAD

**Issue by CarstenHager** [georgringer/news#759]
## Bug Report

**Current Behavior**
Schritte zum Nachstellen:

1. Ich erstelle eine Nachricht
2. Ich rufe die Listenansicht meines News-SysOrdners auf
3. Ich kopiere die Nachricht in Zwischenablage
4. Ich öffne den News-SysOrdners erneut

**Environment**
- TYPO3 version(s): 9.5
- news version: 7.0.6
- Is your TYPO3 installation set up with Composer (Composer Mode): [ no]
- OS: [OSX 10.13.6] 
- PHP 7.2.4
- Hoster Mittwald

**Error-Message**
![bildschirmfoto am 2018-10-11 um 22 02 59-fullpage](https://user-images.githubusercontent.com/5907780/46830654-95b69600-cda1-11e8-92fc-a18e41f92e81.png)

**Comment by georgringer** [comment]
can you check if https://github.com/georgringer/news/pull/713 fixed this?

**Comment by CarstenHager** [comment]
yes, #713 works for me
