### ISSUE TITLE
Archive Date in 7.0.6 changes automaticly to 1.1.1970

### ISSUE THREAD

**Issue by paul-keller** [georgringer/news#766]
## Bug Report

**Current Behavior**
If I set an archive date with news version 7.0.6 and save news, the date is set back to 1.1.1970. As soon as I downgrade to version 7.0.5 it works correcty.

**Expected behavior/output**
Archive Date should stay as set by user

**Environment**
- TYPO3 version: 8.7.19
- news version: 7.0.6
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
Checkout master, should be fixed
