### ISSUE TITLE
News 7.0.6 archive date sets back to 01.01.1970 after saving

### ISSUE THREAD

**Issue by tcmueller** [georgringer/news#769]
Last week i updated News from 7.0.5 to 7.0.6.

Whenever a selected date is set the archive date sets back to 01.01.1970 after saving. This happens after the update to 7.0.6 was done. This occures on two completely seperate installations on different Servers.

Both installations are setup as follows
- TYPO3 version(s): 8.7.19
- news version: 7.0.6
- Is your TYPO3 installation set up with Composer (Composer Mode): no, classic installation
- OS: Ubuntu 18.04

Kind regards
Thorsten Müller

**Comment by georgringer** [comment]
fixed in master already
