### ISSUE TITLE
Page title and OG tags overridden when CE type shortcut to news record

### ISSUE THREAD

**Issue by jokumer** [georgringer/news#771]
## Bug Report

**Current Behavior**
Pages which has a default content element of type shortcut to at least one news record got page title and OG tags rendered with informations from selected news record.

**Expected behavior/output**
When news records are used as shortcut directly in content elements, they should not modify an page header data.

**Environment**
- TYPO3 version(s): 8.7.19, 9.5.0, also affects 7.6
- news version: 7.0.6
- Composer Mode: both

**Possible Solution**
Two ViewHelpers (TitleTag and MetaTag), which modifies page header data when news detail is rendered, should consider context of embedded news.

**Additional context**
It must be noted, that a content element of type shortcut wich use another content element of type list/plugin to view list or/and detail view of news may modify page header data nevertheless.

**Comment by georgringer** [comment]
Solved
