### ISSUE TITLE
Archive Date switching to 01-01-1970 after saving

### ISSUE THREAD

**Issue by kimchristiansen** [georgringer/news#773]
## Bug Report

**Current Behavior**
If an Archive Date is set and the news is saved, the archive date is switching to 01.01.1970. 

**Environment**
- TYPO3 version: [8.7.19]
- news version: [7.0.6]
- With and without Composer mode

**Comment by georgringer** [comment]
Pleas use 7.0.7

**Comment by Scunkaneli** [comment]
I can confirm it does work now with tx_news version 7.0.7 and TYPO3 8.7.18. 
Thanks!

**Comment by kimchristiansen** [comment]
Great, thanks alot!
