### ISSUE TITLE
The news of the main language works fine, but when you translate into others, then there is a problem

### ISSUE THREAD

**Issue by VladZadorozhnyy** [georgringer/news#775]
## Bug Report

**Current Behavior**
On the main page, when you select another language, everything works correctly, but when you click on the button it is sent to another language.

**Expected behavior/output**
А должно открывать именно тот язык который выбрал

**Environment**
- TYPO3 version(s): [9.5.0]
- news version: [e.g. 7.0.7]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Windows 10]

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
Sorry don't get it, which button are you talking about?

**Comment by VladZadorozhnyy** [comment]
Today I updated to topu3 v9.51 and installed yesterday's version news and everything now works well!
