### ISSUE TITLE
Path segment updater does not check if title is unique

### ISSUE THREAD

**Issue by zelcode** [georgringer/news#776]
## Bug Report

**Current Behavior**

Clean install of 9.5.0 works OK.

If site is updated (8.7 -> 9.5) then slug updater does not check if title is unique and you get same `path_segment` for different news records.

At first, it seems everything is fine, you can make new record with non existent title,
but if you try to make new record with existing title, you get:
**No pseudo-site found in root line of page xx**

Even for new records created in 9.5 with same title, `uniqueInSite` does not work, same error.

There was many updates over weekend so I tried commit TYPO3.CMS-d981bdc, but no luck.

**Expected behavior/output**
`path_segment` should be unique (with next number).

**Environment**
- TYPO3 version(s): 9.5.0
- news version: 7.0.7
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Mint 18.3, Nginx

**Comment by jokumer** [comment]
In TYPO3 v9.5.1 it does not work anymore. Even in clean installation (composer, none composer, with and without site configuration).

An error it thrown, each time you create or edit a news entry and want to save it.
`
Argument 1 passed to TYPO3\CMS\Core\DataHandling\Model\RecordStateFactory::TYPO3\CMS\Core\DataHandling\Model\{closure}() must be of the type string, null given
`
When TCA [path_segment][config][eval] is removed, the error is not thrown, but this change is contraproductive.

Furthermore did I notice, that TCA type slug for path_segment can not be updated by click update button in input field group.

**Environment**

- TYPO3 version: 9.5.1
- news version: 7.0.7
- Composer Mode: both (with and without)
- OS: MacOS 10.13

**Comment by zelcode** [comment]
Confirmed.

In 9.5.1 clean install you can't create news record at all.

`Argument 1 passed to TYPO3\CMS\Core\DataHandling\Model\RecordStateFactory::TYPO3\CMS\Core\DataHandling\Model\{closure}() must be of the type string, null given`

**Comment by typo3ua** [comment]
I am confirmed too...

I updated from TYPO3 version: 9.5.0 to TYPO3 version: 9.5.1

All extensions with last version

I can edit news record but I can not save him

**Comment by georgringer** [comment]
be aware that this requires a DB compare

**Comment by ohader** [comment]
https://review.typo3.org/#/c/58807/

**Comment by typo3ua** [comment]
I did it ... good working now
