### ISSUE TITLE
Old typoscript condition

### ISSUE THREAD

**Issue by Zillion01** [georgringer/news#782]
## Bug Report

**Current Behavior**
news/Configuration/TypoScript/setup.txt line 195
`[globalVar = LIT:0<{$styles.content.textmedia.maxW}]`
causes TYPO3 log to get flooded with:
> Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = LIT:0<600"}

**Expected behavior/output**
No log warnings

**Environment**
- TYPO3 version: 9.5.1
- news version: 7.0.7
- Is your TYPO3 installation set up with Composer (Composer Mode): yes, no
- OS: OSX 10.14

**Possible Solution**
Rewrite condition in Symfony Expression Language for TYPO3 9.5

**Comment by georgringer** [comment]
I don't plan to change there something as the same code base supports 8 AND 9.

I would suggest to not include the TS of news and use the new syntax. Sorry

**Comment by Zillion01** [comment]
lol

**Comment by georgringer** [comment]
?
