### ISSUE TITLE
Data object from page will be overoverriddeniden by the news data

### ISSUE THREAD

**Issue by jgrp** [georgringer/news#783]
## Bug Report

**Current Behavior**
When adding a News plugin element to a page, the whole data object from the page will be overridden by the News data.
I put a News plugin (Listview) on the root page. You can see the difference very well, when doing a debug output in the frontend, how uid and pid changes: 

News plugin activated
```
  data => array(86 items)
      uid => 182 (integer)
      pid => 1 (integer)

```

News plugin deactivated
```
   data => array(83 items)
      uid => 1 (integer)
      pid => 0 (integer)
```

Problem appeared after update Typo3 from v9.3 to v9.5 and updating from dev-master commit `[TASK] Allow 9.3 & 9.4` to version `7.0.7`

**Expected behavior/output**

Newsplugin acitvated
```
   data => array(83 items)
      uid => 1 (integer)
      pid => 0 (integer)
```

**Environment**
- TYPO3 version(s): 9.5.0
- news version: 7.0.7
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]
- OS: Ubuntu 14.04

**Comment by georgringer** [comment]
seems to be a core issue https://forge.typo3.org/issues/86733

**Comment by jgrp** [comment]
Thank you !
