### ISSUE TITLE
Category Menu, Search Form Templates not working

### ISSUE THREAD

**Issue by medarob** [georgringer/news#784]
## Bug Report

**Current Behavior**
I use customized Bootstrap templates vor my listview and detailview. Those work fine. Now I wanted to create a news plugin with a category menu and a search form and the default templates are not shown correctly.

**Expected behavior/output**
Even if I don't have any customized templates, the default templates should be used.

**Environment**
- TYPO3 version(s): 7.6.31
- news version: 6.3
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

**Possible Solution**

**Additional context**

in Typoscript:
```
plugin.tx_news {
        view {
                templateRootPaths {
                        10 = EXT:my_extension/Resources/Private/_News/Templates/Styles/Twb/Templates/
                }
                partialRootPaths {
                        10 = EXT:my_extension/Resources/Private/_News/Templates/Styles/Twb/Partials/
                }
                layoutRootPaths {
                        10 = EXT:my_extension/Resources/Private/_News/Templates/Styles/Twb/Layouts/
                }
        }
}
```

I override the Templates/Styles/Twb/Layouts/General.html like this

```
<f:if condition="{settings.cssFile}">
	<n:includeFile path="{settings.cssFile}" />
</f:if>

<f:if condition="{news}">
	<f:then>
		<f:switch expression="{settings.templateLayout}">

			<f:case value="10">
				<div class="grid-news">
					<f:render section="content" />
				</div>
			</f:case>

			<f:case value="11">
				<div class="grid-news news-slider">
					<f:render section="content" />
				</div>
			</f:case>

			<f:case value="12">
				<div class="news">
					<f:render section="content" />
				</div>
			</f:case>

			<f:case value="13">
				<div class="news">
					<f:render section="content" />
				</div>
			</f:case>

			<f:case value="14">
				<div class="news">
					<f:render section="content" />
				</div>
			</f:case>

			<f:case default="TRUE">
				<div class="news">
					<f:render section="content"/>
				</div>
			</f:case>

		</f:switch>
	</f:then>
</f:if>
```

In the option in the category menu plugin I have NOT choosen a template layout so I would expect, that the default template from inside the news extension [Styles/Twb/Layouts] folder would be used.
But the switch expression is not working (the default=TRUE" case). Only if I choose a template in the plugin options, the switch case would work... so the question is: Why can't I use the default news templates and do I have to use a template layout?

**Comment by georgringer** [comment]
closed as it has been a user's issue
