### ISSUE TITLE
Can't save any news on Fresh install latest versions

### ISSUE THREAD

**Issue by Treedent** [georgringer/news#786]
## Bug Report

**Current Behavior**
On a fresh install with latest versions, I can't just save one news.
The following error occurs : 

(1/1) TypeError

Argument 1 passed to TYPO3\CMS\Core\DataHandling\Model\RecordStateFactory::TYPO3\CMS\Core\DataHandling\Model\{closure}() must be of the type string, null given
in /var/www/clients/client36/web324/typo3_src/typo3_src-9.5.1/typo3/sysext/core/Classes/DataHandling/Model/RecordStateFactory.php line 103

**Environment**
- TYPO3 version(s): [9.5.1]
- news version: [e.g. 7.0.7]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [ Linux Debian 9 Stretch]

**Comment by georgringer** [comment]
either use master of core or news (which requires DB compare), fixed

**Comment by Treedent** [comment]
Sorry, I don't understand what you mean.
I use master of TYPO3  9.5.1 and news 7.0.7 from TER and my database is up to date.
I tested on a local Ubuntu server as well and the problem is the same.
I really don't understand what happen in RecordStateFactory.php when saving a news.

I temporary solved the problem by removing the string type cast in 
typo3/sysext/core/Classes/DataHandling/Model/RecordStateFactory.php at line 103.

function (string $aspectFieldName) use ($data) {
//changed to 
function ($aspectFieldName) use ($data) {

Am I the only one who have this error ?

**Comment by instruccionesaldorso** [comment]
@Treedent What he means is that you should use git master branch from this repository (https://github.com/georgringer/news/tree/master) and/or master branch from TYPO3 core repository (https://github.com/TYPO3/TYPO3.CMS/tree/master).
Try that and check if the error is gone.

**Comment by Treedent** [comment]
Yes it was about the l10n_source missing field.
So the tx_news version 7.0.7 in the TER marked as Stable for the 9LTS is not.

**Comment by georgringer** [comment]
This is a regression of the core and stable doesn't mean bug free
