### ISSUE TITLE
Error after saving new record or switching type

### ISSUE THREAD

**Issue by Artifex1** [georgringer/news#789]
## Bug Report

**Current Behavior**
I installed the extension, included the TS and wanted to create a new record, but as soon as I want to save it or switch the type I get the following error:
```
Oops, an error occurred!
Argument 1 passed to TYPO3\CMS\Core\DataHandling\Model\RecordStateFactory::TYPO3\CMS\Core\DataHandling\Model\{closure}() must be of the type string, null given
```

**Expected behavior/output**
Well I expect to have a new record.

**Environment**
- TYPO3 version: 9.5.1
- news version: 7.0.7
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10
- PHP Version 7.2.11

Help is highly appreciated :-)

**Comment by georgringer** [comment]
Use master of news, requires db compare, or core master
