### ISSUE TITLE
Creating new news entries fails (Argument 1 passed to [...] must be of the type string, null given)

### ISSUE THREAD

**Issue by timvonwerne** [georgringer/news#790]
## Bug Report

When trying to create new news entries an error message occurs:
`**Oops, an error occurred!**`
`Argument 1 passed to TYPO3\CMS\Core\DataHandling\Model\RecordStateFactory::TYPO3\CMS\Core\DataHandling\Model\{closure}() must be of the type string, null given`

**Environment**
- TYPO3 version(s): 9.5.1
- news version: 7.0.7
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Ubuntu

**Comment by JozhX** [comment]
Have same issue with same TYPO3 9.5.1 and news 7.0.7. versions

Argument 1 passed to TYPO3\CMS\Core\DataHandling\Model\RecordStateFactory::TYPO3\CMS\Core\DataHandling\Model\{closure}() must be of the type string, null given

Error at typo3/sysext/core/Classes/DataHandling/Model/RecordStateFactory.php line 103

    protected function resolveAspectFieldValues(array $data): array
    {
        return array_map(
            function (string $aspectFieldName) use ($data) {      /*  This is line 103 */
                return (int)($data[$aspectFieldName] ?? 0);
            },
            $this->resolveAspectFieldNames()
        );

**Comment by georgringer** [comment]
Use master of core or news, is duplicate

**Comment by timvonwerne** [comment]
Sorry, unfortunately I can't understand your solution, @georgringer.
What do you mean with "master of core or news"?

**Comment by georgringer** [comment]
use either the master branch of TYPO3 core or master branch of this extension

**Comment by timvonwerne** [comment]
I just tried using the master branch. It didn't work either.
