### ISSUE TITLE
Extend Flexform and get access to the new setting in template

### ISSUE THREAD

**Issue by Alexander-Hagemeier** [georgringer/news#797]
Hello everyone,

I made an extension for the flexform according to the documentation (for Typo3 8.x): https://docs.typo3.org/typo3cms/extensions/news/DeveloperManual/ExtendNews/ExtendFlexforms/Index.html

Now I can see my new input field in the plugin configuration (an additional tab exists besides "general", "additional" and "template") and set a value.

I fail to access this new setting and its value in the template. It seems that the new setting is not parsed to the template because it does not occur within the "settings" array (I used <f:debug>{settings}<f:debug> and the new setting key wasn't there).

May this be an error/misconfiguration from my side? The documentation says nothing to parsing the new configuration variable to the template.

Thanks a lot and
kind regards,

Alex

**Comment by georgringer** [comment]
So does your field have the prefix settings.?

**Comment by Alexander-Hagemeier** [comment]
What do you mean with prefix settings?

**Comment by georgringer** [comment]
I tested it now on master news, master core (but that will work in 8 as well)

<img width="441" alt="bildschirmfoto 2018-11-13 um 19 49 31" src="https://user-images.githubusercontent.com/1905663/48435635-489d5980-e77d-11e8-9a01-a00c54d6daaf.png">

and everything works fine.

**Comment by Alexander-Hagemeier** [comment]
I use the extension in version 6.3.0. For rendering the news I have a custom template. May this cause the problem?

**Comment by georgringer** [comment]
Please test with latest version. Otherwise I can also give you paid private support.

**Comment by Alexander-Hagemeier** [comment]
Ok I re-installed the extension in a fresh Typo3 installation and it works fine. Seems to be a configuration issue in my project. So the issue here can be closed.

**Comment by georgringer** [comment]
thanks for your feedback. have you thought about https://www.paypal.me/GeorgRinger/25? ;)
