### ISSUE TITLE
"tt_content.list.20.news_pi1" does not exist when including bootstrap

### ISSUE THREAD

**Issue by timvonwerne** [georgringer/news#798]
## Bug Report

**Current Behavior**
When including bootstrap_package's Content Elements into my page template the following error occurs:
`Oops, an error occurred!`
`TypoScript object path "tt_content.list.20.news_pi1" does not exist`

The [suggested solution](https://wiki.typo3.org/Exception/CMS/1253191023) did not help.

**Environment**
- TYPO3 version(s): 9.5.1
- news version: master
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by timvonwerne** [comment]
Bump

**Comment by georgringer** [comment]
this is no support channel and IMO a bug of `bootstrap_package`
