### ISSUE TITLE
add possibility to translate tags

### ISSUE THREAD

**Issue by ewokhias** [georgringer/news#799]
## Feature Request

One of our clients has many tags related to news. The use 2 languages and therefore I discovered, that the translation of tags is not possible (as opposed to categories). Are there certain reasons, why tags are non-translateable? Would it be easy to fix?

**Comment by georgringer** [comment]
Just didn't had the time yet. Can your client sponsor it?

**Comment by echavaillaz** [comment]
You can close here, it is reolved with https://github.com/georgringer/news/commit/bdfde0bfebad0fc21a9ae07b49112762d651c038

Thanks.
Eric
