### ISSUE TITLE
Restriction in Plug-In List ignores sys_category output in FE

### ISSUE THREAD

**Issue by angeloprevitali** [georgringer/news#802]
By adding News items on a sys_folder with assigned sys_categories and choosing in the Plug-In to show all items in the FE there will be no results.

- Add some sys_categories to a sys_folder
- Add in this sys_folder some news items and assign one or more sys_categories to this item
- Create a new normal FE page and add a News-Plug-In in List view
- Choose in the Plug-In to show ALL items of all sys_categories

**The result is NO items could be found!**

If you choose MANUALLY all single sys_categories in the Plug-In of the NEWS to show all the items it WORKS perfect. 

What we also already tried is:

- creating a additional folder in the sys_categories where the news items belongs and adding in this folder new sys_categories (no results)
- changing in the EM of the EXT:news the settings where the sys_categories (no results)
- even by adding the Page TS with TCEFORM.tx_news_domain_model_news.categories.PAGE_TSCONFIG_IDLIST = xx there is no difference and no results gets show.

Is that a problem that leads to the EXT:news OR is that a possible Bug of the TYPO3? Due to we work with news I suppose that the problem leads in the EXT:news.

TYPO3 CMS version 8.7.20
EXT:news version 7.0.8
PHP 7.1, LINUX

**THIS ONE WORKS PERFECT!!!**
![sys_categories-backend-1](https://user-images.githubusercontent.com/17588253/48832827-5dc84880-ed7a-11e8-83bc-b07673288291.png)

**THIS WILL NOT WORK AND GETS NO RESULTS AT ALL**
![sys_categories-backend-2](https://user-images.githubusercontent.com/17588253/48832826-5dc84880-ed7a-11e8-879d-cb335372890f.png)

**THERE IS NO DIFFERENCE BETWEEN CHOOSING ONE OF THE ITEMS** 
![sys_categories-backend-4](https://user-images.githubusercontent.com/17588253/48832824-5d2fb200-ed7a-11e8-8351-6c5e0be734ed.png)

**Comment by georgringer** [comment]
Using any extension which adds stuff to news? Using no category constraint should of course show all news. Can you reproduce on empty installation?

**Comment by angeloprevitali** [comment]
We do use the EXT:eventnews of you, too. But even if we disable this it will not work. So if you add a Plug-In of the NEWS to show ALL items of a certain category-folder and checking the checkbox to "include all subfolders" the results of the news-items remains empty. 

As soon as we will check the single sys_categories manually in the Plug-In to show all News-item that belongs to a certain sys_category the News-items will be shown. 

Sincerly I don't really know if that problem leads to your EXT:news OR it is some bug of the CORE of TYPO3.

**Comment by angeloprevitali** [comment]
And - YES - on a empty installation it will be the same.

Using TYPO3 CMS 8.7.20 with EXT:news 7.0.8.

**Comment by georgringer** [comment]
thanks for fast feedback but I can't reproduce that locally and I am pretty sure there would be a lot of issues reported if this happens to more users. contact me in private if I should look at your installation, would be interested as well
