### ISSUE TITLE
"Top news" wont work in translation mode

### ISSUE THREAD

**Issue by agendartobias** [georgringer/news#803]
## Bug Report

**Current Behavior**
Hey, I have a problem with "Top news" records and translations. If translate some news record from default language to "lang1" and i check option "Top news" **ONLY** in "lang1" record (translation) it does not work. If i check this option in default language then it starts working in "lang1" to. I think this is not correct behavior.

**Environment**
- TYPO3 version(s): 8.7.20
- news version: 7.0.7
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
this is a problem of extbase, not of news

**Comment by darthnorman** [comment]
Hi Georg, is there no workaround for this problem? Can you provide a link to the mentioned extbase bug, please?

**Comment by hannesbochmann** [comment]
A workaround might be to not use translations for such news but to create a standalone news in another language where it should be a top news.
