### ISSUE TITLE
Configurable addQueryStringMethod for paginate widget

### ISSUE THREAD

**Issue by ducrot** [georgringer/news#805]
For POST-based search forms, it would be helpful if the pagination widget also took POST parameters into account. Currently only GET parameters are supported.

For <f:widget:pagination> it can be controlled via configuration.addQueryStringMethod, but in <n:widget:pagination> it is fixed to addQueryStringMethod="GET".

If the feature is OK, I would like to submit a PR for it.

**Comment by georgringer** [comment]
Yes pls pr, thx

**Comment by jokumer** [comment]
related to #871

**Comment by georgringer** [comment]
closed in favor of #871
