### ISSUE TITLE
path_segment unique check on different language

### ISSUE THREAD

**Issue by cosmox** [georgringer/news#807]
## Bug Report

**Current Behavior**
consistent path_segments in different languages ​​not possible

**Expected behavior/output**

**Example**
First title: /somthing/with/it/
path_segment: ibm

Second title: /de/irgendwas/mit/it/
path_segment: ibm

Third title: fr/quelque/chose/avec/
path_segment: ibm

**Expected:**
/somthing/with/it/ibm
/de/irgendwas/mit/it/ibm
/fr/quelque/chose/avec/ibm

**Actual:**
when saving the path_segment is changed, so we get now:
/somthing/with/it/ibm
/de/irgendwas/mit/it/ibm0
fr/quelque/chose/avec/ibm1

See ticket 754

**Environment**
- TYPO3 version(s): [e.g. 8.7.20]
- news version: [e.g. 7.0.8]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Linux]

**Additional context**
See Ticket #754

**Comment by JarvisH** [comment]
Seeing how the new slug-based urls are used in Typo3 9+, this is only an issue for Typo3 v8.

The "uniqueness" of the path_segment value is simply handled via a TCA `config['eval]` setting of `nospace,alphanum_x,lower,unique`. The "unique" setting checks if the value is unique for the whole news table and so does not consider languages.

For this issue to be resolved, a custom eval method or processing hook would have to be added for Typo3 v8

**Comment by georgringer** [comment]
There is nothing I can really do there, furthermore an upgrade to 9 would solve the issue. therefore I am closing this one.
