### ISSUE TITLE
allowedColPos not working

### ISSUE THREAD

**Issue by Domi202** [georgringer/news#810]
## Bug Report

**Current Behavior**
When `allowedColPos` is set for templateLayouts in PageTSConfig, the layout is not removed if the colPos is not allowed.

**Expected behavior/output**
If `1.allowedColPos = 1`, the layout `1` should not be visible if the content element is in a column other than `colPos=1`

**Environment**
- TYPO3 version(s): 8.7.20
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux 4.9.125-linuxkit

**Possible Solution**
The method \GeorgRinger\News\Hooks\ItemsProcFunc::reduceTemplateLayouts uses a wrong key to remove restricted layouts from the $allLayouts array (https://github.com/georgringer/news/blob/b73b1db92fbe45a2c396ca4a86840ee0f2dfb377/Classes/Hooks/ItemsProcFunc.php#L82).

I will provide a pull request for that soon.

**Comment by georgringer** [comment]
PR merged
