### ISSUE TITLE
Create new Tag on the fly does not work in TYPO3 9

### ISSUE THREAD

**Issue by MoppieMop** [georgringer/news#813]
## Bug Report

**Current Behavior**
If I search for a non-existing Tag, I can click to dreate. But nothing happens. A JS-Error is thrown

**Expected behavior/output**
The Tag should be created.

**Environment**
- TYPO3 version(s): 9.5.1
- news version: 7.0.8

**Possible Solution**
In TYPO3 9 you have to use jQuery not with TYPO3.jQuery. You have to fix this in SuggestReciever. Maybe Condition for TYPO3-Version.

**Comment by zauni** [comment]
TYPO3 v8.7.24 also has the same problem. I attached a screenshot of the error message. It looks like the create method of the \Backend\TagEndPoint class has a problem.

![screenshot_2019-02-13 typo3 exception](https://user-images.githubusercontent.com/663845/52706853-a0b74800-2f86-11e9-94ac-2f1723b45e3e.png)

**Comment by mykhaylo-** [comment]
Have the same issue on Typo3 9.5.1. 
@georgringer , 
Please provide a fix as this feature would tremendously help with news tagging.
