### ISSUE TITLE
[7.0.8 on 9.5.2] News written in non-default language don't appear in list. Translated do.

### ISSUE THREAD

**Issue by janslu** [georgringer/news#815]
## Bug Report

**Current Behavior**
I am setting up a dual language site on typo3 9.5.2. I have some news items written in default language and translated and some written only in the "other", non-default language. Those translated (where translation parent is set) display fine, but I cannot get those without translation to display no matter the settings...

Initially I was using
`sys_language_mode = content_fallback
sys_language_overlay = 1`
in typoscript and similar setting in site configuration. 
Later I have also tried other combinations of settings (string, overlay 0, site config strict) but it didn't change behavior. 

**Expected behavior/output**
The same typoscript generate a proper list containing both translated and written in other language news items on typo3 8.7.21 with the same news 7.0.8. 
**Environment**
- TYPO3 version(s): problem exists in typo3 9.5.1 and 9.5.2. It works fine on 8.7.21
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: recent php 7.2 set up on ubuntu. 

**Additional context**
I'm not the only person with the same problem - here's a SO post describing the same issue: [https://stackoverflow.com/questions/53749759/typo3-how-to-allow-translated-news-appear-without-a-transl-orig](https://stackoverflow.com/questions/53749759/typo3-how-to-allow-translated-news-appear-without-a-transl-orig)

**Comment by janslu** [comment]
I've been trying to find a fix for this issue, but I'm lost. In my further tests it's apparent that enabling site config doesn't change the behavior, but using new 9.5 style urls does. 

Here's my setup:
1. page with list view - both languages in connected mode
2. page with details view - both languages in connected mode
3. storage folder with news - both languages in connected mode

Two languages - polish as default, english as L=1. fallback set to strict mode. Everything seems to be working ok on the site. Links, titles etc. 

News records: Some are written in polish and then translated, some are written in english (non-default language). 

Testing: One browser, two tabs. In first tab I enter the list page using url with index.php?id=11&L=1?no_cache=1 I can properly see all english news records - both translated and written in english. But if I open in second tab the same page but using /en/newslist?no_cache=1 url I can see the same list but news records *written in english* are not there. Only translated news records are visible. 

I'm banging my head on this one. Tried to debug variables, but I'm getting lost pretty soon... Any idea what may be going on?

**Comment by JarvisH** [comment]
I believe this has to do with how extbase handles translated records, which recently changed to reflect how language settings are handled in Typoscript for standard content. 
See https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Important-82363-MakeExtBaseTranslationHandlingConsistentWithTyposcript.html

Showing news records which only exist in a non-default language, in your case English, would require the following adjustment to the query settings:

`$query->getQuerySettings()->setLanguageOverlayMode(false);`

this could fx. be added to `function findDemanded()` in `Classes/Domain/Repository/abstractDemandedRepository.php`.

You could try this out to as a quick fix for your needs but obviously a more flexible solution would be needed for everyone, which should be configurable via plugin settings in typoscript.

**Comment by janslu** [comment]
@JarvisH Thank you so much. I am learning the inner workings of typo3 and you've helped me by explaining what's happening. Appreciated! Your fix works, and indeed it seems that a proper solution will be needed.

**Comment by georgringer** [comment]
So make a setting or change the implementation?

**Comment by janslu** [comment]
@georgringer I know too little to make a call here. For me a setting will be fine. A condition on typo3 version in the query will be fine too. It's hard to recommend one over the other without fully grasping consequences of either for other users :-)

**Comment by SvenJuergens** [comment]
hi, same problem here. the workaround from @JarvisH is working for me to. Therefore, I think a setting to adjust the behavior would be great

**Comment by tillschweneker** [comment]
A setting for that would be great! 👍

**Comment by luzat** [comment]
I have only now seen this issue, but already derived a similar fix. I used a hook. In `ext_localconf.php`:

    $GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['Domain/Repository/AbstractDemandedRepository.php']['findDemanded'][] = \Vendor\Extension\News\FindDemanded::class . '->find';

In `Classes\News\FindDemanded.php`:

```
<?php

namespace Vendor\Extension\News;

use TYPO3\CMS\Extbase\Persistence\Generic\Query;

class FindDemanded {
  public function find(array &$params, &$ref)
  {
    /** @var Query $query */
    $query = $params['query'];
    $query->getQuerySettings()->setLanguageOverlayMode(false);
  }
}
```

**Comment by georgringer** [comment]
is this still valid in 9.5.5? thx

**Comment by Geddo** [comment]
This is still valid for 9.5.5. @luzat solution works for me for news in a foreign language without a default-language. But if the foreign language has a default language original which is disabled, the translated news will be unavailible too in the detail view :-/

**Comment by janslu** [comment]
Same for me - I had to reapply @luzat fix on 9.5.5 and news 7.1.0.

**Comment by georgringer** [comment]
@janslu @Geddo @luzat https://review.typo3.org/c/Packages/TYPO3.CMS/+/60367 has just been merged, wanna do me a favor and test that out? the change will also be merged to 9.5 as well. thx  for your help

**Comment by LiNgOtT** [comment]
> https://review.typo3.org/c/Packages/TYPO3.CMS/+/60367 has just been merged, wanna do me a favor and test that out? the change will also be merged to 9.5 as well. thx for your help

Fix is not working for me. 
TYPO3: 9.5.7
News: 7.2

**Comment by LiNgOtT** [comment]
@georgringer Any chance to get this fixed soon?

**Comment by SvenJuergens** [comment]
@LiNgOtT you can use this small ext https://github.com/SvenJuergens/newsfixfor815 
it's the solution from @luzat so many thanks to @luzat :)

**Comment by LiNgOtT** [comment]
@SvenJuergens : Great. That works!
@georgringer : Is that something you can implement in your extension officially?

**Comment by chrisprog20** [comment]
TYPO3 9.5.8:
News: 7.2
I had a similar issue: Webpage has two languages: default (German) and English.
The news records exist only in default language.
On the English page none of them were shown.
After changing in the Site Module the Site Configuration under Languages > English > Fallback Type from "strict" to 
"Show default language if no translation exists" I got the news also on the English page.

By the way: config.sys_language_mode in TypoScript seems not to overwrite the site config.

For the authors issue: Maybe the news are shown if the fallback type in Site Configuration is set up to
"Free mode: Ignore translation and overlay concept, only show data from selected language".

More information about the fallback type in the site configuration module can be found here:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-86762-EnhancedFallbackModesForTranslatedContent.html

**Comment by fritzdacat** [comment]
This solution works in the listview. However, then the slugs no longer work, here only the UID is output.

**Comment by infabo** [comment]
Another side-effect of setting `setLanguageOverlayMode` to false via hook:

If you hide/disable a news record in the default language, the non-default english record still gets listed in list-view. but it won't work for detail-view -> it breaks.

**Comment by magicsunday** [comment]
This bug still exists in TYPO3 v9.5.14 and news v7.3.1

**Comment by ctnmjhall** [comment]
Bug still exists in typo3 9.5.20 news 8.4.0

**Comment by georgringer** [comment]
this can be fixed with https://github.com/georgringer/extbase_records_with_no_l10n_parent
