### ISSUE TITLE
Wrong advanced realurl example in documentation 

### ISSUE THREAD

**Issue by froemken** [georgringer/news#819]
## Bug Report

**Current Behavior**
```
[
  'GETvar' => 'tx_news_pi1[controller]',
    'valueMap' => [
    '' => 'detail',
  ],
  'noMatch' => 'bypass'
],
```

**Expected behavior/output**
```
[
  'GETvar' => 'tx_news_pi1[controller]',
    'valueMap' => [
    '' => 'detail',
  ],
  'noMatch' => 'bypass'
],
```

**Environment**
- TYPO3 version(s): *
- news version: master
- Is your TYPO3 installation set up with Composer (Composer Mode): *
- OS: *

**Possible Solution**
See coming PR

**Comment by georgringer** [comment]
thx, merged
