### ISSUE TITLE
No cache clearing for selectedListAction

### ISSUE THREAD

**Issue by JarvisH** [georgringer/news#825]
## Bug Report

**Current Behavior**
When using the "selectedList" controller action, the cache does not clear when editing any news which are part of the selected list.

**Expected behavior/output**
The list of selected news should update on change.

**Environment**
- TYPO3 version(s): 9.5.3
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Implement `Cache::addCacheTagsByNewsRecords([$news]);` at end of selectedList action.

**Comment by georgringer** [comment]
Wanna do a pr?

**Comment by JarvisH** [comment]
Yup, I'll do that
