### ISSUE TITLE
Plugin Flexform orderBy author "not allowed" when saved

### ISSUE THREAD

**Issue by zabinetta** [georgringer/news#831]
## Bug Report

**Current Behavior**
I have added the author field to the plugin flexform orderBy-options with tsconfig like in the documentation (plus the plugin.tx_news.settings.orderByAllowed in typoscript) When I create the plugin as a new Contentelement, the Field is there, perfect (Frontend is ok, too). But after I save and reopen my plugin-Contentelement in Backend the field looks empty with  ['WERT IST NICHT ERLAUBT("author")'].
Something must be missing... (there is also no fallback for the translation of the option in the backend-rendering, but that's not the exact problem)

**Expected behavior/output**
All options should again be visible in the flexform. If there is a configuration-option missing in the documentation, please add it.

**Environment**
- TYPO3 version(s): 8.7.24, 9.2.0
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: ubuntu

**Additional context**
I need a userdefined field for sorting, too, so just the author-field wouldn't fix it for me

**Comment by zabinetta** [comment]
Dear Georg,
I found out what it is: it's because of the ItemsProcFunc.
- in the plugin, I selected a Tag.
- this brings the user_orderby function in effect which propably removes my authorPlus-Field by removeNonValidOrderFields, because the property-name is not equal to the table-name (I'm not completely sure about that, because the author-field wasn't shown either)

So at the moment I added my field to the ext_tables.php of the extension that brings the new field:
$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['orderByCategory'] .= ',author,authorPlus';
$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['orderByNews'] .= ',author,authorPlus';
$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['orderByTag'] .= ',author,authorPlus';

Could you please have a look, if there is a chance to insert the new sorting-field from the tsconfig to the user_orderby as well, and could maybe somebody thing about the removeNonValidOrderFields-function because of the field-property-difference?

With the best regards,
Sabine

**Comment by georgringer** [comment]
code changed a couple of times, closing issue therefore. feel free to reopen a new one if still relevant
