### ISSUE TITLE
Using '-' for '/'-replacement in slug and publish to repository

### ISSUE THREAD

**Issue by stephangrass** [georgringer/news#832]
Hi,
I think it's better to user '-' for the slash-replacement in the TCA for slug.
Also, because if no replacement is used like in news < 7.0.8, a fatal error occurs, when using slash's in the news title. So it would be very nice, that this change will publish to the extension repository quickly.

Thanks
Stephan

**Comment by georgringer** [comment]
Wanna do a pr?

**Comment by stephangrass** [comment]
pr?

**Comment by stephangrass** [comment]
Oh. Sure ...
Yes, do a pr.

**Comment by nebrot** [comment]
I've created a PR. A new release would be cool, so that a slash don't lead to an error.

**Comment by nebrot** [comment]
@georgringer Should i also create a PR for replacements in Configuration/TCA/Overrides/sys_category.php and Configuration/TCA/Overrides/tx_news_domain_model_tag.php?

**Comment by georgringer** [comment]
Pls
