### ISSUE TITLE
Preview Mode

### ISSUE THREAD

**Issue by prdt3e** [georgringer/news#833]
Typo3: 9.5.3
News: 7.0.8

PageTS
```php 
	TCEMAIN.preview {
		tx_news_domain_model_news {
			previewPageId = 3
                        useCacheHash = 1
			useDefaultLanguageRecord = 0
			fieldToParameterMap {
				uid = tx_news_pi1[news_preview]
			}
			additionalGetParameters {
				tx_news_pi1.controller = News
				tx_news_pi1.action = detail
			}
		}
	}
```

In the Backend shows only /page/?no_cache=1
If i set previewPageId = 241251 (to a page that does not exist) the parm are correct.
Will this feature come back?

Thanks

**Comment by georgringer** [comment]
Sorry but can you describe what the output is and what do you expect?

**Comment by prdt3e** [comment]
Ok, I could find the mistake.
works not:
```php 
[PIDinRootline = 9]
     TCEMAIN.preview {.....
[END]
```
works fine:
```php 
[page["uid"] == 9]
     TCEMAIN.preview {.....
[END]
```
With PIDinRootline = <a href="/news?no_cache=1" class="btn btn-default btn-sm t3js-editform-view" title="Anzeigen">
Without it or page["uid"] = <a href="/news?tx_news_pi1%5Baction%5D=detail&amp;tx_news_pi1%5Bcontroller%5D=News&amp;tx_news_pi1%5Bnews_preview%5D=1&amp;cHash=8a3e6bb0dd79dc63c40679402373f575" class="btn btn-default btn-sm t3js-editform-view" title="Anzeigen"
