### ISSUE TITLE
cannot override method in repository class

### ISSUE THREAD

**Issue by ewokhias** [georgringer/news#836]
## Bug Report

**Current Behavior**
When I try to override the `getSearchConstraints()` method in the NewsRepository, I get the following exception in FE: 

`Fatal error: Cannot redeclare GeorgRinger\News\Domain\Repository\NewsRepository::getSearchConstraints() in C:\xampp\htdocs\test\typo3temp\var\Cache\Code\news\tx_news_domain_repository_newsrepository.php on line 524`

**Expected behavior/output**
To my knowledge, overriding public and protected functions should be possible, shouldn't it?

**Environment**
- TYPO3 version(s): 8.7.24
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux/Windows

To reproduce the error mentioned above, check out https://github.com/georgringer/news_filter and add the following in line 15 of `ext_localconf.php`:

`$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Domain/Repository/NewsRepository'][] = $_EXTKEY;` 

and create the following class in `Classes/Domain/Repository/NewsRepository`:

```
<?php

namespace GeorgRinger\NewsFilter\Domain\Repository;

use GeorgRinger\News\Domain\Model\DemandInterface;


class NewsRepository extends \GeorgRinger\News\Domain\Repository\NewsRepository
{


    /**
     * Get the search constraints
     *
     * @param QueryInterface $query
     * @param DemandInterface $demand
     * @return array
     * @throws \UnexpectedValueException
     */
    protected function getSearchConstraints(QueryInterface $query, DemandInterface $demand)
    {
        $constraints = [];
        return $constraints;
    }

}
```

**Comment by georgringer** [comment]
Checkout https://docs.typo3.org/typo3cms/extensions/news/DeveloperManual/ExtendNews/ProxyClassGenerator/Index.html and overriding is not allowed. This is not xclass. Use that if you need it

**Comment by ewokhias** [comment]
Sorry, I accidentally confused those two. Nevertheless, I stuck to the guide mentioned above, but it seems impossible to override the `getSearchConstraints()`-method. (see this commit https://github.com/ewokhias/news_filter/commit/dcde7b873ff67df1c827aa3e5ef0aab988ce9617)
Am I doing something wrong? Should it be possible?
