### ISSUE TITLE
Non ASCII language characters in news title of Asian languages are getting trimmed off on slug generation 

### ISSUE THREAD

**Issue by rickymathew** [georgringer/news#840]
## Bug Report

**Current Behavior**
Non ASCII language characters are trimmed off on slug generation.(Chineese,Japaneese ,Thai etc) 

**Expected behavior/output**
Non ASCII language characters must be preserved on slug generation from news title

**Environment**
- TYPO3 version(s): 9.5 LTS
- news version: [e.g. 7.0.8]
- Is your TYPO3 installation set up with Composer (Composer Mode): No
- OS: Windows 10,Ubuntu 18.04

**Possible Solution**
The culprit is postProcessText() function in GeorgRinger\News\Service\Transliterator\Transliterator class. I just tweaked some regex there to look like follows.

```
private static function postProcessText($text, $separator)
    {
        if (function_exists('mb_strtolower')) {
            $text = mb_strtolower($text);
        } else {
            $text = strtolower($text);
        }
        // Remove apostrophes which are not used as quotes around a string
        $text = preg_replace('/(\\w)\'(\\w)/', '${1}${2}', $text);
        // Replace all none word characters with a space
        $text = preg_replace('/[\W_]/u', ' ', $text);
        // More stripping. Replace spaces with dashes
        $text = strtolower(preg_replace('/[\W]+/u', $separator,
            preg_replace('/([a-z\d])([A-Z])/', '\1_\2',
                preg_replace('/([A-Z]+)([A-Z][a-z])/', '\1_\2',
                    preg_replace('/::/', '/', $text)))));
        return trim($text, $separator);
    }
```
With the above work around it works perfectly.
@georgringer if you find this sensible ,would you please push this tweak to master.

**Comment by georgringer** [comment]
9.5 shouldnt use Transliterator at all, so are you really using 9.5.?

**Comment by rickymathew** [comment]
Any updates?
