### ISSUE TITLE
Installtool Upgrade Wizard for path_segment Throws Exception

### ISSUE THREAD

**Issue by jokumer** [georgringer/news#844]
Installtool Upgrade wizard for "Updates slug field 'path_segment' of EXT:news records"
throws exception on execution.

**Current Behavior**

When perform upgrade  for update missing news slugs via installtool (both in backend and pure installtool gui), an error is thrown. Partially stacktrace
```
#1502721731 RuntimeException "No valid wizard identifier given"
...
at TYPO3\CMS\Install\Service\UpgradeWizardsService->assertIdentifierIsValid('GeorgRinger\\News\\Updates\\NewsSlugUpdater')
...
at TYPO3\CMS\Install\Service\UpgradeWizardsService->executeWizard('newsSlug')
...
```
But update of missing slugs has been done correctly and upgrade wizard has been marked as done as well.

Execution via shell (using helhum/typo3-console) returns no error or exception.

**Expected behavior/output**

Perform upgrade wizard without throwing error, when updates was done correctly.

**Environment**
- TYPO3 version(s): 9.5.4 (no composer mode), 9.5.5-dev (composer mode)
- news version: 7.0.8 (TER)
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes, no]
- OS: OSX 10.14
- Browser: Chrome

**Comment by jokumer** [comment]
Issue causes a TYPO3 core change set in UpgradeWizardService class https://review.typo3.org/#/c/59383/2/typo3/sysext/install/Classes/Service/UpgradeWizardsService.php

An additional condition for UpgradeWizard identifier validation was added, which requires implementation of class RowUpdaterInterface for class NewsSlugUpdater.

Should TYPO3 core beeing adopt or EXT:news got a workaround?
I'll add a comment to correspondending issue at https://forge.typo3.org/issues/87283

**Comment by georgringer** [comment]
fixed in master
