### ISSUE TITLE
path_segment doesn't work with "/"

### ISSUE THREAD

**Issue by Nostrabramus** [georgringer/news#845]
## Bug Report

**Current Behavior**
plugins list and searchResult return an exception in frontend if if a news_item contains a "/" in path_segment 

**Expected behavior/output**
the output of the plugin has to show the news list

**Environment**
- TYPO3 version(s):  9.5.3
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: linux debian distribuiton

**Possible Solution**
the widget path_segment could convert "/" in "-" as it does with " "

**Additional context**
this is the stack trace:
`Fri, 08 Feb 2019 09:30:08 +0000 [ALERT] request="65eb398cc08c4" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 201902080930052ed88047 - {"exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException: Parameter \"tx_news_pi1__news\" for route \"tx_news_pi1_0\" must match \"[^\/]++\" (\"radio-monte-carlo-e-radio-ufficiale-del-teatro-manzoni-di-milano-per-la-stagione-2018\/2019\" given) to generate a corresponding URL. in \/var\/www\/typo3_src-9.5.3\/vendor\/symfony\/routing\/Generator\/UrlGenerator.php:155\nStack trace:\n#0 \/var\/www\/typo3_src-9.5.3\/vendor\/symfony\/routing\/Generator\/UrlGenerator.php(128): Symfony\\Component\\Routing\\Generator\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'tx_news_pi1_0', 1, Array, Array)\n#1 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Routing\/PageRouter.php(257): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('tx_news_pi1_0', Array, 1)\n#2 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Typolink\/PageLinkBuilder.php(373): TYPO3\\CMS\\Core\\Routing\\PageRouter->generateUri(Object(TYPO3\\CMS\\Core\\Routing\\Route), Array, '', 'absolute')\n#3 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Typolink\/PageLinkBuilder.php(206): TYPO3\\CMS\\Frontend\\Typolink\\PageLinkBuilder->generateUrlForPageWithSiteConfiguration(Array, Object(TYPO3\\CMS\\Core\\Site\\Entity\\Site), Array, '', Array)\n#4 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(5405): TYPO3\\CMS\\Frontend\\Typolink\\PageLinkBuilder->build(Array, '|', '', Array)\n#5 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(5546): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->typoLink('|', Array)\n#6 \/var\/www\/mediakey_t3_htdocs\/typo3conf\/ext\/news\/Classes\/ViewHelpers\/LinkViewHelper.php(140): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->typoLink_URL(Array)\n#7 [internal function]: GeorgRinger\\News\\ViewHelpers\\LinkViewHelper->render()\n#8 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(262): call_user_func(Array)\n#9 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(250): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#10 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/ViewHelperInvoker.php(79): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#11 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(522): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke('GeorgRinger\\\\New...', Array, Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext), Object(Closure))\n#12 \/var\/www\/mediakey_t3_htdocs\/typo3temp\/var\/cache\/code\/fluid_template\/partial_List_Item_0e3df0a884070fb53fe25bcc66314ecdb3e7617f.php(583): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#13 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/View\/AbstractTemplateView.php(329): partial_List_Item_0e3df0a884070fb53fe25bcc66314ecdb3e7617f->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#14 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/ViewHelpers\/RenderViewHelper.php(141): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->renderPartial('List\/Item', NULL, Array, false)\n#15 \/var\/www\/mediakey_t3_htdocs\/typo3temp\/var\/cache\/code\/fluid_template\/News_action_searchResult_885e45f820377562e6c335b3bef175411b69905f.php(275): TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#16 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/ViewHelpers\/ForViewHelper.php(133): News_action_searchResult_885e45f820377562e6c335b3bef175411b69905f->{closure}()\n#17 \/var\/www\/mediakey_t3_htdocs\/typo3temp\/var\/cache\/code\/fluid_template\/News_action_searchResult_885e45f820377562e6c335b3bef175411b69905f.php(291): TYPO3Fluid\\Fluid\\ViewHelpers\\ForViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#18 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractConditionViewHelper.php(85): News_action_searchResult_885e45f820377562e6c335b3bef175411b69905f->{closure}()\n#19 \/var\/www\/mediakey_t3_htdocs\/typo3temp\/var\/cache\/code\/fluid_template\/News_action_searchResult_885e45f820377562e6c335b3bef175411b69905f.php(325): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#20 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractConditionViewHelper.php(85): News_action_searchResult_885e45f820377562e6c335b3bef175411b69905f->{closure}()\n#21 \/var\/www\/mediakey_t3_htdocs\/typo3temp\/var\/cache\/code\/fluid_template\/News_action_searchResult_885e45f820377562e6c335b3bef175411b69905f.php(350): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#22 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/View\/AbstractTemplateView.php(260): News_action_searchResult_885e45f820377562e6c335b3bef175411b69905f->section_040f06fd774092478d450774f5ba30c5da78acc8(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#23 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/ViewHelpers\/RenderViewHelper.php(143): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->renderSection('content', Array, false)\n#24 \/var\/www\/mediakey_t3_htdocs\/typo3temp\/var\/cache\/code\/fluid_template\/layout_General_html_db1a67a162e5e5fd9c1e4b47827ea97f5a7b6826.php(466): TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#25 \/var\/www\/mediakey_t3_htdocs\/typo3temp\/var\/cache\/code\/fluid_template\/layout_General_html_db1a67a162e5e5fd9c1e4b47827ea97f5a7b6826.php(473): layout_General_html_db1a67a162e5e5fd9c1e4b47827ea97f5a7b6826->{closure}()\n#26 \/var\/www\/mediakey_t3_htdocs\/typo3temp\/var\/cache\/code\/fluid_template\/layout_General_html_db1a67a162e5e5fd9c1e4b47827ea97f5a7b6826.php(475): layout_General_html_db1a67a162e5e5fd9c1e4b47827ea97f5a7b6826->{closure}(Array)\n#27 \/var\/www\/typo3_src-9.5.3\/vendor\/typo3fluid\/fluid\/src\/View\/AbstractTemplateView.php(201): layout_General_html_db1a67a162e5e5fd9c1e4b47827ea97f5a7b6826->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#28 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(324): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()\n#29 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(167): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod()\n#30 \/var\/www\/mediakey_t3_htdocs\/typo3conf\/ext\/news\/Classes\/Controller\/NewsBaseController.php(50): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#31 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(73): GeorgRinger\\News\\Controller\\NewsBaseController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#32 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/extbase\/Classes\/Mvc\/Web\/FrontendRequestHandler.php(92): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#33 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(172): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#34 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(159): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#35 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#36 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(5947): call_user_func_array(Array, Array)\n#37 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/ContentObject\/UserContentObject.php(41): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#38 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(814): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#39 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(730): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#40 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3853): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#41 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3814): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript_process(Array)\n#42 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3781): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()\n#43 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(187): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript()\n#44 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/OutputCompression.php(46): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#45 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Frontend\\Http\\RequestHandler))\n#46 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/ContentLengthResponseHeader.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#47 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\ContentLengthResponseHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#48 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/ShortcutAndMountPointRedirect.php(65): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#49 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\ShortcutAndMountPointRedirect->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#50 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/PrepareTypoScriptFrontendRendering.php(118): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#51 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PrepareTypoScriptFrontendRendering->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#52 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/PageArgumentValidator.php(87): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#53 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PageArgumentValidator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#54 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/MaintenanceMode.php(53): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#55 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\MaintenanceMode->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#56 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/PageResolver.php(162): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#57 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PageResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#58 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/StaticRouteResolver.php(66): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#59 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\StaticRouteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#60 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/SiteBaseRedirectResolver.php(80): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#61 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\SiteBaseRedirectResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#62 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/SiteResolver.php(68): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#63 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#64 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/BackendUserAuthenticator.php(95): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#65 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#66 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/FrontendUserAuthenticator.php(79): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#67 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\FrontendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#68 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/TypoScriptFrontendInitialization.php(91): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#69 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\TypoScriptFrontendInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#70 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/EidHandler.php(50): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#71 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\EidHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#72 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/PreprocessRequestHook.php(57): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#73 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PreprocessRequestHook->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#74 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Middleware\/NormalizedParamsAttribute.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#75 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#76 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Middleware\/TimeTrackerInitialization.php(49): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#77 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\TimeTrackerInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#78 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(67): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#79 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/AbstractApplication.php(98): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#80 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(69): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#81 \/var\/www\/typo3_src-9.5.3\/typo3\/sysext\/core\/Classes\/Http\/AbstractApplication.php(110): TYPO3\\CMS\\Frontend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#82 \/var\/www\/typo3_src-9.5.3\/index.php(24): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#83 \/var\/www\/typo3_src-9.5.3\/index.php(25): {closure}()\n#84 {main}"}`

**Comment by stephangrass** [comment]
Take a look here: /Configuration/TCA/Overrides/tx_news_domain_model_news.php

`            'replacements' => [
                '/' => '-'
            ],`

You should add this manually in your tx_news_domain_model_news.php until this will be part of te next release.

**Comment by Nostrabramus** [comment]
> Take a look here: /Configuration/TCA/Overrides/tx_news_domain_model_news.php
> 
> ` 'replacements' => [ '/' => '-' ],`
> 
> You should add this manually in your tx_news_domain_model_news.php until this will be part of te next release.

thank you @stephangrass,
it works!
It's not a perfect solution because it solves the problem only for the news inserted or if the segment_path is regenerated.
The old segment_paths obviously are not modified and therefore the news already inserted in the database continue to generate the exception.
However, for the site I'm working on, it's already enough.
Thanks again

**Comment by georgringer** [comment]
closing issue because solved and changed TCA is released

**Comment by hannesbochmann** [comment]
@georgringer Is it possible that this has to be taken into account in the NewsSlugUpdater, too? At least I got slashes in the path_segment when a news has slashes in in it's title and the updater is executed. When the path_segment is recalculated in the backend editing form the slash is removed as expected. Can you shed some light on this?

**Comment by darthnorman** [comment]
Maybe you should open a new issue on this, since this one is already closed.
