### ISSUE TITLE
respecting categories within detail action?

### ISSUE THREAD

**Issue by TrueType** [georgringer/news#85]
Hi Georg,
nice code here, but as in older versions of tt_news the detail action does not respect any categories configuration. If you withdraw a category from a news item that already made its way into a search index it will still be called under the outdated URI. You probably know about that aspect I guess. There was a hook - sViewSelectConfHook - where one could readd a category selection. But that wouldn't be too nice. Please let me know, if I miss something. Thanks.
Henri

**Comment by georgringer** [comment]
News is not the successor of tt_news but yes that feature could be added. Can you sponsor it?

**Comment by TrueType** [comment]
Ok. Sponsoring is not out of the world. Could you give an estimate about the effort it'll take?

**Comment by georgringer** [comment]
I guess it takes me at least 4 hours

**Comment by georgringer** [comment]
@TrueType wanna help?

**Comment by TrueType** [comment]
I'd love to but cannot do more as my customer asks for. That's little and personally I have another subject going on.

**Comment by georgringer** [comment]
closed as I won't handle it.
