### ISSUE TITLE
Plugin Action List retrieves all news records

### ISSUE THREAD

**Issue by robertvonhackwitz** [georgringer/news#852]
## Bug Report

**Current Behavior**
News Plugin "Action List" with pagination retrieves all news records from database. 
Having thousand of news records causes system to hangs.

**Expected behavior/output**
When using news plugin to list news records with pagination, it would be better if the query on DB will select only "n" records for the selected page.

**Environment**
- TYPO3 version(s): 9.5.4
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS:Centos 7, Php 7.2, Mysql 5.7

**Comment by georgringer** [comment]
This is new to me, are you using default templates or iterating still offer all news?

**Comment by robertvonhackwitz** [comment]
Hi, i'm using default templates.
There are about 10.000 news records to show, paginated by 50 items per page.
News Plugin shows correctly 50 items with pagination but it takes about 5 minutes to load the page.
After a little investigation I noticed the query in findDemanded doesn't have limit nor offset set.
Sorry for my bad english

**Comment by robertvonhackwitz** [comment]
There was something wrong in my installation. Sorry

**Comment by georgringer** [comment]
The limit is set in the pagination widget, it must be something else

**Comment by robertvonhackwitz** [comment]
On a new fresh TYPO3 9.5.4 installation with News extension installed, using default news templates:
- web page created
- typoscript template created and configured only with: 
page = PAGE
page.10 < styles.content.get
- inserted plugin News on web page, Action: "List view without overloading ...), Items per Page = 10
- sysfolder created, fullfilled with about 3.000 news records
- set Startingpoint in News Plugin to above sysfolder
- inserted "debug($newsRecords)" in class GeorgRinger\News\Controller\NewsController at line 206 (inside listAction method)
- in FE News Plugin shows correctly 10 items and pagination at bottom, but it takes several seconds to shows and debug function above shows all 3.000 items

**Comment by georgringer** [comment]
Yes but there is a lazy loading, the query result is really loaded in the view when accessed, debug all news inside the pagination vh
