### ISSUE TITLE
Problems with showing latest 3 translated records if one of them is hidden

### ISSUE THREAD

**Issue by agendartobias** [georgringer/news#856]
## Bug Report

**Current Behavior**
We have our TYPO3 site in two languages and we are showing latest 3 news on our landing page. After we translate news record to second language, it shows in FE as expected. But if we hide translated record, FE shows only 2 news records, instead of 3. But then if we hide "original/parent" record FE shows latest available (not hidden/deleted) 3 records as expected.

Is this a bug? Or is this expected behaviour?

**Expected behavior/output**
I think if we hide latest translated news record, then plugin must stil showl 3 latestvavailable (not hidden/deleted) records.

**Environment**
- TYPO3 version(s): 8.7.24
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
this is how TYPO3 works as the real overlay is done while rendering the record and not within the query. there is not really something I can do... I would propose doing a limit in the plugin by e.g. 10 and then just render 3 in the view
