### ISSUE TITLE
News detail view is not restricted to startingpoint

### ISSUE THREAD

**Issue by sebkln** [georgringer/news#863]
## Bug Report

**Current Behavior**
The news detail plugin renders all news records which can be found in a TYPO3 installation, regardless of the set `startingpoint` (in news detail plugin).

**Expected behavior/output**
If a `startingpoint` is set in a news detail plugin (or TypoScript), this plugin should not render news records from other pages/sysfolders.

**Environment**
- TYPO3 version: 8.7.24
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux 4.15.0, macOS 10.14.3

**Additional context**
Steps to reproduce:

New installation of TYPO3, only EXT:news is installed.

Minimal TypoScript setup:

````
plugin.tx_news.settings.startingpoint = 2

page = PAGE
page.10 =< styles.content.get
````

Page tree:

````
[1] List view (root)
- [2] News detail A
- [3] News detail B
````

Each news detail page contains:

- a news 'detail view' plugin. The `startingpoint` is always set to the page of the current plugin.
- an individual news record

----

The __list view__ can then be configured to list the news records from both detail pages (startingpoint). Adding either one of the two PageIds for single news display, it will link every news record to this detail view. And the detail view will render every record, regardless of the `startingpoint`.

This issue seems not limited to the plugin's flexform value, it also ignores the TypoScript setting `plugin.tx_news.settings.startingpoint`.

**Comment by georgringer** [comment]
checkout https://github.com/georgringer/news/blob/master/Classes/Controller/NewsController.php#L343-L347 how this can be fixed.

does that works for you

**Comment by sebkln** [comment]
It does! I was not aware of this setting.

`plugin.tx_news.settings.detail.checkPidOfNewsRecord = 1` restricts the rendering of news records to the `startingpoint` and will output _'The news record is not available anymore.'_, if needed.

So it was a case of RTFM. Thank you for your help!
