### ISSUE TITLE
configuration of archiveRestriction

### ISSUE THREAD

**Issue by blueamerican** [georgringer/news#864]
is archiveRestriction not missing here as default?:
overrideFlexformSettingsIfEmpty

https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Configuration/TypoScript/Index.html#overrideflexformsettingsifempty 

**Environment**
- TYPO3 version(s):  8.7.24
- news version: 6.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

**Comment by georgringer** [comment]
wanna do a PR for code and doc?
