### ISSUE TITLE
Error: Unknown Namespace: <n:format.nothing>

### ISSUE THREAD

**Issue by dirk2014** [georgringer/news#865]
Dear Georg,
Thanks for your wonderful extension news.

I did an update of TYPO3 6.2 to 8.7 and news to 7.0.8.

Now I get the error prompt in the frontend:

Fluid parse error in template News_action_detail_aa63ae64b26a5f8c6f215fc25de31dc49273d615, line 1 at character 1. Error: Unknown Namespace: <n:format.nothing> (error code 0). Template source chunk: ...

I inspect your templates. There are a lot, which are using the namespace "n:". But i didn't fin any file, which set the namespace like {namespace n=...}

What I must do, that the namespace is registered proper?

Kind regards
Dirk

**Comment by georgringer** [comment]
maybe using still old namespace inclusion with `Tx_News_ViewHelpers`?

I propose removing your templates and start new with current templates

**Comment by dirk2014** [comment]
Bingo :)

Customer templates were deprecated.

It's solved.
