### ISSUE TITLE
On any extension activation, a SchemaException is thrown

### ISSUE THREAD

**Issue by benjaminpick** [georgringer/news#866]
## Bug Report

**Current Behavior**

When the extension "news" is active, whenever I activate any extension the following Exception is thrown. The column exists in the Database, however, and I'm not sure why he is trying to add an index to this. (The same error occurs during activation of the news extension itself, or when I call the database analyser in the install tool.) After executing the install tool "Dump autoload", the site functions as it shoulds.

Here is the stacktrace:
```

(1/1) #30 Doctrine\DBAL\Schema\SchemaException

There is no column with name 't3ver_oid' on table 'tx_news_domain_model_news'.
in /home/b/htdocs/wiedenest.de/typo3_src-9.5.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php line 89

     * @return \Doctrine\DBAL\Schema\SchemaException
     */
    public static function columnDoesNotExist($columnName, $table)
    {
        return new self("There is no column with name '$columnName' on table '$table'.", self::COLUMN_DOESNT_EXIST);
    }

    /**
     * @param string $namespaceName

at Doctrine\DBAL\Schema\SchemaException::columnDoesNotExist('t3ver_oid', 'tx_news_domain_model_news')
in /home/b/htdocs/wiedenest.de/typo3_src-9.5.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php line 314

                $columnName = $indexColOptions;
            }

            if ( ! $this->hasColumn($columnName)) {
                throw SchemaException::columnDoesNotExist($columnName, $this->_name);
            }
        }

        return new Index($indexName, $columnNames, $isUnique, $isPrimary, $flags, $options);

at Doctrine\DBAL\Schema\Table->_createIndex(array('t3ver_oid', 't3ver_wsid'), 't3ver_oid', false, false, array(), array())
in /home/b/htdocs/wiedenest.de/typo3_src-9.5.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php line 175

                array_merge([$this->getName()], $columnNames), "idx", $this->_getMaxIdentifierLength()
            );
        }

        return $this->_addIndex($this->_createIndex($columnNames, $indexName, false, false, $flags, $options));
    }

    /**
     * Drops the primary key from this table.

at Doctrine\DBAL\Schema\Table->addIndex(array('t3ver_oid', 't3ver_wsid'), 't3ver_oid')
in /home/b/htdocs/wiedenest.de/typo3_src-9.5.5/typo3/sysext/core/Classes/Database/Schema/DefaultTcaSchema.php line 520

            if (!empty($tableDefinition['ctrl']['versioningWS'])
                && (bool)$tableDefinition['ctrl']['versioningWS'] === true
                && !$this->isIndexDefinedForTable($tables, $tableName, 't3ver_oid')
            ) {
                $tables[$tablePosition]->addIndex(['t3ver_oid', 't3ver_wsid'], 't3ver_oid');
            }
        }

        return $tables;
```

**Expected behavior/output**
This exception should not be thrown :-)

**Environment**
- TYPO3 version(s): 9.5.5
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Comment by georgringer** [comment]
Add news as dependency in extemconf and reinstall the ext

**Comment by georgringer** [comment]
does that work for you?

**Comment by benjaminpick** [comment]
Indeed, when I add it as a dependency, the error disappears. However I would need to add it in every extension (even when unrelated to `news`) so this is not a solution.

**Comment by georgringer** [comment]
no it is only required to those exts which extend news

**Comment by benjaminpick** [comment]
Oh I'm sorry, I now found one of our extensions that extend news in their SQL/TCA but did not declare it in emconf ... now it's working again.  ... (The weird thing was that this broke the activation of all other extensions as well.)

**Comment by naturefund-falk** [comment]
This behaviour is also true for typo3 10.4. It looks like this is not really a problem of news extension. The above solution work: Look up for an extension which extends the database tables of news (has a file of a news table in Configuration/TCA/Overrides/) and define news as a dependency in ext_emconf.php.
