### ISSUE TITLE
Button for fullscreen mode missing is using htmlArea RTE

### ISSUE THREAD

**Issue by responseinformationsdesign** [georgringer/news#868]
## Bug Report

**Current Behavior**
The button for switching to fullscreen mode is missing if htmlArea RTE is used

![grafik](https://user-images.githubusercontent.com/15003759/54368931-51dbfb80-4675-11e9-9ddb-b6a5f9fd7840.png)

**Environment**
- TYPO3 version(s): 8.7.24
- news version: 7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 2008 R2

**Comment by georgringer** [comment]
the htmlarea is deprecated, if you need that, please extend TCA yourself
