### ISSUE TITLE
SearchForm Pagination

### ISSUE THREAD

**Issue by infabo** [georgringer/news#871]
## Bug Report

**Current Behavior**
Place Search Form Plugin. Place List Plugin below. Visit FE. Enter search word. See results. Need more than one result-pages. Navigate to page 2. Search-word lost - empty list.

**Expected behavior/output**
I want to see items of page 2.

**Environment**
- TYPO3 version(s): 8.7.24
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): no
 OS: Debian

**Possible Solution**
https://github.com/georgringer/news/blob/master/Resources/Private/Templates/News/SearchForm.html defaults to a POST form.
The f:widget.link viewhelpers here https://github.com/georgringer/news/blob/master/Resources/Private/Templates/ViewHelpers/Widget/Paginate/Index.html have 'addQueryStringMethod="GET"'. It is clear how to fix, but this should not be broken out of the box.

**Additional context**
Add any other context about the problem here

**Comment by jokumer** [comment]
I have written a solution to handle this feature in my own project/sitepackage extension.
If you are interested, i could share. But the best would be, to get it included in news itself.

**Comment by p380** [comment]
hy,
the above code does not work on the latest version of the news module.

**Comment by C0d3Br3aker** [comment]
hi,
is there now another solution for this problem?

**Comment by jokumer** [comment]
https://github.com/georgringer/news/blob/master/Documentation/Misc/Changelog/9-0-0.rst#removed-viewhelpers

**Comment by C0d3Br3aker** [comment]
@jokumer I need a solution for Version 8.6.0. I can't use 9.0.0 yet
