### ISSUE TITLE
newsItem.[firstCategory|category].parentcategory properties unavailable 

### ISSUE THREAD

**Issue by janslu** [georgringer/news#873]
## Bug Report

**Current Behavior**

I have a small category tree (few main categories, some have children, so 2nd level is the deepest) and need to render a category breadcrumb in the frontend. In f:debug I can see the parentcategory property existing, condition <f:if condition="{category.parentcategory}"> is working, but I cannot get the properties of a parentcategory to display if editors tick subcategories without ticking off parent category (which is what we want). 

I was trying to use a simple code: 

```
<f:if condition="{newsItem.firstCategory}">
	<f:for each="{newsItem.categories}" as="category">
		<f:if condition="{category.parentcategory}">
		<f:then>
			{category.parentcategory.title}: {category.title}
		</f:then>
		<f:else>
			{category.title}
		</f:else>
		</f:if>
	</f:for>
</f:if>
```

This gives me an output of  ` : subcategory` even though if I display properties of a category using `<f:debug>{category}</f:debug>` inside the for loop parentcategory property is properly filled with data. 

I have also copied a snippet from [Simple snippets in extension manual](https://docs.typo3.org/typo3cms/extensions/news/stable/singlehtml/Index.html#render-category-rootline)  hoping that it works differently (it is camelcase - 'parentCategory'), but it also doesn't work. 

What's interesting is that my snippet starts to show parentcategory data when news item is marked as having both subcategory and parentcategory. But then categories are being shown double:
```
Parentcategory
Parentcategory: subcategory
```
which is not what we need. 
 
**Expected behavior/output**
I want to be able to mark newsItem as having a subcategory and to be able to display a parentcategory title and uid in the frontend. 

**Environment**
- TYPO3 version(s): 9.5.5
- news version: 7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Possible Solution**

**Additional context**

I have a test environment available if needed.

**Comment by georgringer** [comment]
Sorry for getting back to you so late. can I have ftp/ssh access to the test einvironment as well? I guess I have a fix available. please contact me via slack
