### ISSUE TITLE
Missing dummy image resource

### ISSUE THREAD

**Issue by jokumer** [georgringer/news#874]
## Current master is broken in frontend cause of missing Resources/Public/Images/dummy-preview-image.png

Due to one of latest change in master this resource got deleted (by accident)
https://github.com/georgringer/news/commit/f8ed372fde4e68b0aa728e0c0234bfedf26cba68#diff-079a37f08adbb88e14643aad072a6e49

**Given**
Download master and install. Embed default typoscript from extension. Create some news entries without images. Create content element with list/detail view. Show in frontend.

**Current Behavior**
An exception is shown or logged:
_FolderDoesNotExistException: Folder "/typo3conf/ext/news/Resources/Public/Images/dummy-preview-image.png_ 

**Expected behavior/output**
You should see list view with links to detail view. Default typoscript and FLUID configuration will embed dummy images for each news entry.

**Environment**
- TYPO3 version: 9.5.6-dev
- news version: 7.1.0
- No Composer Mode
- OS: OSX 10.14

**Possible Solution**
Restore _Resources/Public/Images/dummy-preview-image.png_ again
PR will follow

**Comment by georgringer** [comment]
fixed, can be closed
