### ISSUE TITLE
Ajax Pagination not working

### ISSUE THREAD

**Issue by droomdre** [georgringer/news#876]
Hello Georg,

i used the tutorial on this page https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Templates/AjaxBasedPagination/Index.html
The generated links look like this:
`<a data-container="45" data-link="/newsroom/aktuelles?tx_news_pi1%5Bcontroller%5D=ViewHelpers%5CWidget%5CPaginate&amp;tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_45%22%2C%22path%22%3A%22tt_content.list.20.news_pi1%22%7D&amp;cHash=8dab4ebfdf6a3f3322334c6e" href="/newsroom/aktuelles?tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=2&amp;cHash=ed023c1a313f9e3d1d0f6e6e6a68fa44">2</a>`
It doesnt matter which link i click (2,3 or 10) i can see that the news-container-45 is being actualised but always with the same result as of page 1.

**Expected behavior/output**
Pagination to work and take the current page in account.

**Environment**
- TYPO3 version(s): 9.5.5
- news version: 7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux (Mittwald)

**Comment by droomdre** [comment]
The problem is in the extension typoscript_rendering. 
Adding the following line at line 76 in the render() Function of AjaxActionViewHelper.php solves the problem:
`$additionalParams = $this->arguments['additionalParams'];`

**Comment by georgringer** [comment]
I don't see a `AjaxActionViewHelper` in typoscript_rendering. If you think the issue is in https://github.com/helhum/typoscript_rendering, please open an issue there. thx
