### ISSUE TITLE
Adding documentation about news and routing (TYPO3 v9)

### ISSUE THREAD

**Issue by sebkln** [georgringer/news#877]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A proper documentation of Routing features and examples will make it easier for administrators to set up speaking URLs for the news extension in TYPO3 v9 and above.

**Describe the solution you'd like**
I currently plan to cover the following subjects:

- A **brief** introduction to Routing in general:
  - what does it to
  - why routing (and no longer RealURL)
  - how to use
  - where to use (site config)
- Links to the according core changelog entries
- A basic configuration for list and detail view
- Additions for categories and tags (using the new slug fields)
- Extended configurations (localized pagination, localized archive view, ...), kindly provided by @jokumer.

Every configuration will be described by its objectives/effects. I would also explain some settings of each configuration. I'd limit myself to the most important settings though, as I consider an extension documentation the wrong place to describe the whole routing features in general.

The documentation would also contain some further thoughts and descriptions, like using `limitToPages` on websites where editors are allowed to add new views.

Your thoughts on this?

Should the basic configuration already handle more views (which?), so integrators can simply copy/paste it for most installations?

**Comment by jokumer** [comment]
Thanks for starting this awaiting feature. 
To your question: I would like to embed configuration examples for some simple usecases, depend on how plugin settings are done (list+detail in one plugin or list and detail on different pages).
