### ISSUE TITLE
category menu showing always all categories

### ISSUE THREAD

**Issue by Uhradone** [georgringer/news#878]
## Bug Report

**Current Behavior**
In the plugin "Category Menu" - if you unmark some categories they are shown in FE anyway.

**Expected behavior/output**
Only show the marked categories in the menu in FE

**Environment**
- TYPO3 version: 9.5.5
- news version: 7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Possible Solution**

**Additional context**
disabling the category completely will help

![Bildschirmfoto 2019-03-23 um 22 54 05](https://user-images.githubusercontent.com/7649619/54872166-39c85280-4dc0-11e9-941e-a779aa612382.png)

**Comment by georgringer** [comment]
the current behaviour will return not only the given categories but also the child categories. you should be able to create a check in the template to filter the desired ones.

I keep the issue open as feature

**Comment by Uhradone** [comment]
Hello Georg thank you for the reply.

But in this case it is not a decision the BE-user can make. You have to alter the template with every change. In my case the customer wants to decide what to offer and what not, depending on seasonal changes. But as long as the "complete disable" workaround functions it's fine.

**Comment by georgringer** [comment]
Maybe the customer wants to sponsor a flag so that the child categories are not processed? disabling the categories is IMO not the way to go as those could be used somewhere else as well

**Comment by Uhradone** [comment]
In this case the project is unfortunately already sealed. But we had developers invovled and payed them out of our own budget. We try to give back where we can.
Site with the for the time beeing reduced menu: https://www.gesitrel.ch/download

**Comment by georgringer** [comment]
closing the feature request because it can be achieved by either change the templates or use one of the signals, events
