### ISSUE TITLE
simplePrevNext ignores categories

### ISSUE THREAD

**Issue by boosim** [georgringer/news#882]
Hello Georg,

on one of our TYPO3 projects we moved from tt_news to tx_news. Everything works fine but we have an issue we could not solve yet.

Our Customer placed most of his News in one folder and used Categories to display them on different pages in different settings. That works fine for the list views in tx_news but we can't use the PrevNext Viewhelper in this setting, because the Detail View has no settings for categories and the PrevNext Viewhelper therefore also ignores categories.

If we activate the PrevNext Viewhelper, the PrevNext Links will always browse through all available News.

In tt_news that feature worked as expected, so our customer asked us to search for a solution, but we could not get it to work as of yet. 

Do you have any suggestions for us or could you make us an offer for a paid implementation of this feature?

Kind regards 
Florian

TYPO3 Version 7.6 (Upgrade to TYPO3 8 in a few weeks)
News Version 6.3

**Comment by georgringer** [comment]
Dear Florian,

sorry to get back to you so late. I can support you by delivering a custom VH but I won't add more logic into the *Simple*PregNextViewHelper. 
Contact me in private (slack or email) if still needed.
