### ISSUE TITLE
Localize a news record with more than 1 related link triggers exception

### ISSUE THREAD

**Issue by r3h6** [georgringer/news#885]
## Bug Report

**Current Behavior**

1. Create a news in default language
2. Set title and create two related links
3. Save record
4. Localize record through dropdown or list view

Following exception will be thrown:
<code>
(1/1) #1486233164 RuntimeException
Child record was not processed
in /var/www/web/typo3/sysext/core/Classes/DataHandling/Localization/DataMapProcessor.php line 626
</code>

Funny enough, with content elements it works, which has more less the same inline tca definition. Also with only 1 related links localization works.
..But not sure if its a news or core bug.

**Expected behavior/output**
Form of translated record is displayed.

**Environment**
- TYPO3 version(s): 9.5.5
- news version: 7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Comment by instruccionesaldorso** [comment]
Same issue here.
The funny thing is that it works with just 1 news link attached to the news record, but not with 2.
