### ISSUE TITLE
Limit Number of news items does not work properly

### ISSUE THREAD

**Issue by tsurfer84** [georgringer/news#886]
Bug Report

new version, old problem still exists:

I use the news plugin module 3x on one site:

    the first module should show a maximum number of news of 1, starting at news item 0 (for the last news item).
    the first module should show a maximum number of news of 1, starting at news item 1 (for the second last news item).
    finally, the third module should show a maximum number of news of 1, starting at news item 2 (for the third last news item).

Current behaviour is: first and second plugin module both showing news as they should. but the third plugin does not show up at all. For testing, I copied each elements in order to avoid any other configuration mistakes. I also tried other starting numbers as 4,5 and 6. But also this did not fix it.

The expected behaviour works fine with tx_news version 6.3 und lower.
The bug results since the update of version 7.0 and following up.

Environment

    TYPO3 version: [8.7.16]
    news version: [e.g. 7.0.5]
    Is your TYPO3 installation set up with Composer (Composer Mode): [no]
    OS: [Windows 10]

**Comment by georgringer** [comment]
multilingual records?

**Comment by tsurfer84** [comment]
No, none of them.
Is it possible to build my setting as I described an reproduce this issue?
The problem exists by publication of tx_news version 7. version 6.3. is fine.

**Comment by georgringer** [comment]
of cause is https://github.com/georgringer/news/pull/546. I need to check that out
