### ISSUE TITLE
selected list news results in "Uncaught TYPO3 Exception"

### ISSUE THREAD

**Issue by rr-it** [georgringer/news#887]
### Current Behavior

`NewsController::selectedListAction` calling `Cache::addCacheTagsByNewsRecords` results in "Uncaught TYPO3 Exception"

```
Uncaught TYPO3 Exception
Argument 1 passed to GeorgRinger\News\Utility\Cache::addCacheTagsByNewsRecords() must be of the type array, object given, called in /home/internwwwamsel/staging_typo3_8_html/public/typo3conf/ext/news/Classes/Controller/NewsController.php on line 315

TypeError thrown in file
/home/internwwwamsel/staging_typo3_8_html/public/typo3conf/ext/news/Classes/Utility/Cache.php in line 57.

68 GeorgRinger\News\Utility\Cache::addCacheTagsByNewsRecords(TYPO3\CMS\Extbase\Persistence\Generic\QueryResult)
```

### Environment
- TYPO3 version(s): 8.7.24
- news version: 7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

### Additional context
Introduced with issue #825 / commit https://github.com/georgringer/news/commit/d921e823ee55a0c81b4a4b8c12b1928548aa6d9e

**Cache::addCacheTagsByNewsRecords**
Param `$newsRecords` is set to `array`, but might also be `\TYPO3\CMS\Extbase\Persistence\Generic\QueryResult`.

https://github.com/georgringer/news/blob/9752108d4d3aec430ca3358719af1519962fb60e/Classes/Utility/Cache.php#L55-L57

**Error provoked in NewsController::selectedListAction**

https://github.com/georgringer/news/blob/9752108d4d3aec430ca3358719af1519962fb60e/Classes/Controller/NewsController.php#L300-L303

`$newsRecords` is `\TYPO3\CMS\Extbase\Persistence\Generic\QueryResult` now.

https://github.com/georgringer/news/blob/9752108d4d3aec430ca3358719af1519962fb60e/Classes/Controller/NewsController.php#L314-L316

### Possible Solution

A: https://github.com/rr-it/news/commit/12c89d35e6ef97d07ba8bef9a10e736267bcc412
or
B: https://github.com/rr-it/news/commit/b1888a491e5dd7fe8cc3c540a6b5c9d3e22886ee

**Comment by georgringer** [comment]
Wanna do a pr for A?

**Comment by georgringer** [comment]
resolved, can be closed
