### ISSUE TITLE
countByDate generates invalid mysql query when used with orderBy in custom controller

### ISSUE THREAD

**Issue by w010** [georgringer/news#892]
## Bug Report

**Current Behavior**
In custom controller when I try to use of $this->newsRepository->countByDate($demand); it causes mysql exception. Generated mysl query shows, that theres such part: "ORDER BY `tx_news_domain_model_news`.`datetime` ASC" inside of WHERE part, instead of being on it's place (order is not even used in count, I found it weird during debugging)
```
SELECT FROM_UNIXTIME(datetime, "%m") AS "_Month",   (...)
WHERE ((`tx_news_domain_model_news`.`type` = 0)  (...)
ORDER BY `tx_news_domain_model_news`.`datetime` ASC AND  (...)
GROUP BY _Month, _Year ORDER BY _Year asc, _Month asc': You have an error in your SQL syntax
```

**Expected behavior/output**
Method countByDate() should generate valid mysql query when order set

**Environment**
- TYPO3 version(s): 8.7.24
- news version: at least 7.0.8 - 7.1.1, probably older too
- Is your TYPO3 installation set up with Composer (Composer Mode): no / n/a
- OS: any

**Possible Solution**
I found that it adds another ORDER BY, because one is already there - the one added by findDemandedRaw(), which then builds own query, trying to use WHERE, but instead uses WHERE + ORDER which is also there. This is not stripped later.
So the solution might be like this:
Right before $sql = $this->findDemandedRaw($demand); call in coundByDate method there might be $demand->setOrder(''); to not generate it here - is unneeded anyway.

**Comment by georgringer** [comment]
this has been solved with #883, therefore closing the issue
