### ISSUE TITLE
proper translation handling

### ISSUE THREAD

**Issue by DavidBruchmann** [georgringer/news#893]
## Bug Report

**Current Behavior**
Having a fallback from sys_language_uid 2 to sys_language_uid 1 doesn't work.  
I don't know if it's exclusively related to the core and seo-extension or if news is or could or should be involved here somehow.

**Expected behavior/output**
Having defined mentioned fallback, lang 1 should be shown on sys_language uid 2.

**Environment**
- TYPO3 version: 9.5.5]
- news version:  7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Additional context**
Common CEs are translated correctly, at  least with patch 3 below.

Benni is working on this related issue
 - https://review.typo3.org/c/Packages/TYPO3.CMS/+/60367
 - https://forge.typo3.org/issues/86762

**Comment by georgringer** [comment]
This is a core issue

**Comment by DavidBruchmann** [comment]
Ok, thanks for the quick feedback ;-)
