### ISSUE TITLE
Is Release 7.1.1 missing?

### ISSUE THREAD

**Issue by DavidBruchmann** [georgringer/news#896]
## Bug Report

**Current Behavior**
Release 7.1.1 is shown in commit-messages (Commits on Apr 6, 2019) but not in releases / tagged versions

**Expected behavior/output**
Show tag 7.1.1 in releases tab, packagist and TER

**Environment**
- TYPO3 version: 9.5.5
- news version: 7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Comment by georgringer** [comment]
Yes changed my mind all will release next week

**Comment by DavidBruchmann** [comment]
Ok, thanks!
