### ISSUE TITLE
Exception error with BE modul

### ISSUE THREAD

**Issue by zzzooorrrx** [georgringer/news#897]
## Bug Report

**The following error is thrown, when choosing the BE Modul News:**
#1407060572: Fluid parse error in template Administration_action_index_d19dfbd87b1dabde758460d9be865196c83b4da9, line 154 at character 1. Error: The ViewHelper "<n:be.multiEditLink>" could not be resolved. Based on your spelling, the system would load the class "GeorgRinger\News\ViewHelpers\Be\MultiEditLinkViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <n:be.buttons.icon uri="#" onclick="{n:be.multiEditLink(items:paginatedNews, columns:'title')}" icon="actions-document-open" /> (More information)

**Expected behavior/output**
Should show the news items

**Environment**
Typo3: 8.7.24
news: 7.2.0
eventnews: 3.0.0
news_importicsxml: 3.0.0
php: 7.1.26

classic install

**Comment by georgringer** [comment]
I guess you have some old backend templates somewhere among your templates

**Comment by zzzooorrrx** [comment]
ya, that was it. I already did a search for that before.
Now it works...
Thx
