### ISSUE TITLE
Remove path segment of details page

### ISSUE THREAD

**Issue by Balindil** [georgringer/news#898]
Hello, is there a possibility to remove path segment of the details page from url?
E. g. www.domain.com/news-of-the-day instead of www.domain.com/details/news-of-the-day

**Comment by dhuf** [comment]
As far as I know under < v9 you need to use this realurl config https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/BestPractice/Realurl/Index.html#advanced-example defining the page uid as fixedPostVars for the configuration.

Usually I also limit the length and I add the uid to avoid collisions and to make it easier to find the news again:
```
'table' => 'tx_news_domain_model_news',
'id_field' => 'uid',
'alias_field' => 'CONCAT(left(IF(path_segment!=\'\',path_segment,title), 85), \'-\', uid)',
```

**Comment by Balindil** [comment]
Sorry, I forgot to mention that I use TYPO3 v9. With Realurl I've managed that so far. With TYPO3 9.x I can't do that anymore?

**Comment by robsonrobi** [comment]
Is there no hook or anything else to modify the route enhancer and remove the detail segement ? :-(

**Comment by DavidBruchmann** [comment]
you should post your configuration, in general that's possible

**Comment by robsonrobi** [comment]
Hi @DavidBruchmann. My config:

77 and 78 are the pages named detail, where the detail plugin is placed.
Thanks for you help! I need /news/mynews-pathsegment.

`
routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    limitToPages:
      - 77
      - 78
    routes:
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    defaultController: 'News::detail'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
`

**Comment by DavidBruchmann** [comment]
I don't know how to break out of the page-path but I see the following options:  

 -  you could place the detail-plugins on the startpage and display details if present, else the common page content. than in your configuration you enter `routePath: '/news/{news-title}'`  
 - you leave the configuration like it is but make the detail view on a page with the name "news". This is cleaner than the hacky first solution.

You describe the problem different in your last post in comparison to your question, but with my hint you could be able to realize both solutions.

**Comment by robsonrobi** [comment]
@DavidBruchmann : I solved it deleting the detail page and setting the limitToPages to the ListView-PageIds. Is that the proper way? Works like a charm.

**Comment by DavidBruchmann** [comment]
Yeah that's one option to configure news. Glad that you're satisfied with that solution ;-)
