### ISSUE TITLE
dd_googlesitemap not working with multiple pids

### ISSUE THREAD

**Issue by dead-bread** [georgringer/news#899]
The sitemap generator no longer works with multiple pids. 

?eID=dd_googlesitemap&sitemap=txnews&pidList=190,191,192&useCategorySinglePid=1
for example leeds to no result, because the rewritten method generateSitemapContent() 
merges the pids to 190191192 in the where statement:

'pidInList' => implode('', $this->pidList),

this should be 
'pidInList' => implode(',', $this->pidList),

Problem first occurs with news version 7.2.0

**Comment by rr-it** [comment]
I can confirm this.

The proposed fix is also working for me:
https://github.com/rr-it/news/commit/8182564046d91a189bae231bbbdbe2f84b837e43
