### ISSUE TITLE
Wrong HTML Tag in Partial /Category/Items.html

### ISSUE THREAD

**Issue by t3premium** [georgringer/news#901]
## Bug Report

**Current Behavior**
The html tag of the partial Category/Items.html is rendered to the main source code which causes an w3c error of html validation.
`<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"><!-- categories -->`

**Expected behavior/output**
No output of the html header tag with namespace info.

**Environment**
- TYPO3 version: 9.5.5
- news version: 7.2.0

**Possible Solution**
`<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">` fixes the output of the html tag with namespace.

**Comment by georgringer** [comment]
wanna do a PR? thx

**Comment by t3premium** [comment]
Got it: https://github.com/georgringer/news/pull/902
