### ISSUE TITLE
It's not possible to use option orderByAllowed

### ISSUE THREAD

**Issue by DanielSiepmann** [georgringer/news#907]
## Feature Request

We would like to create new custom plugins for news within our installation, e.g. `news_recent`. This is a use case provided by TYPO3. Poorly the NewsController has hardcoded values for `news_pi`, preventing configuration of Option `orderByAllowed`. This is prevented to be overwritten by Flexforms. As the original value for reset is always fetched from `pi1`, it's not possible to define a different one for another plugin signature.

We therefore would propose to follow Extbase convention, and use `$this->extensionName` and `$this->pluginName` instead of hardcoded values.

**Comment by codegm** [comment]
Please revert!

In typo3 v9 "pluginName" is always null, that result in tssettings is missing overrides from typoscript.

In v10 "extensionName" was removed, so would be breaking anyway in the next months. 
https://github.com/TYPO3/TYPO3.CMS/commit/a8b673daf995b024580d393f5ebada6ea82bc6b1

**Comment by DanielSiepmann** [comment]
So instead of reverting, I would suggest to replace it with a call to the request to fetch the information.
