### ISSUE TITLE
"Show in all views" is shown in list of media elements headline (backend)

### ISSUE THREAD

**Issue by christianbltr** [georgringer/news#912]
## Bug Report

**Current Behavior**
In the list of attached media elements a little "checkbox icon" is shown which is labeled "show in all Views". It's right beside the "move" icon. This icon does not have any function.

**Expected behavior/output**
There should no be such an icon since it does not provide any function and editors asks questions about it.

**Environment**
- TYPO3 version: 9.5.5
- news version: 7.1.0
- Composer Mode: yes

**Additional context**
Example:

![Bildschirmfoto 2019-05-16 um 14 49 47](https://user-images.githubusercontent.com/11410553/57855301-9eb18f00-77ea-11e9-95f6-660377ea466b.png)

**Comment by georgringer** [comment]
even though this is no icon and not the best idea I won't change it unless I come up with a better solution
