### ISSUE TITLE
Last translated link gets re-assigned to newly translated news entry

### ISSUE THREAD

**Issue by derBretti** [georgringer/news#914]
## Bug Report

**Current Behavior**
When a news entry with a link is translated, the last non-deleted link in that language (highest uid) gets re-assigned to the newly created translated entry.

**Expected behavior/output**
No links getting re-assigned

**Environment**
- TYPO3 version(s): 8.7.26
- news version: 7.0.8 - 7.8.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: debian

**Comment by MatzeLandwehr** [comment]
We have seen the same problem and I have taken a look into the code and found a workaround or the reason for the problem. If you change _$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['related_links']['config']['behaviour']['allowLanguageSynchronization']_ from _true_ to _false_ the bug won't happen anymore.

To be honest I don't know if this is a bug of the news extension or of the TYPO3 core.

Environment

-     TYPO3 version(s): 8.7.31
-     news version: 7.3.1
-     Is your TYPO3 installation set up with Composer (Composer Mode): no
-     OS: debian

**Comment by georgringer** [comment]
as the issue is very old and I can't reproduce it anymore
