### ISSUE TITLE
add itemprop="image" to f:image viewhelper

### ISSUE THREAD

**Issue by Uhradone** [georgringer/news#918]
## Feature Request

**Is your feature request related to a problem? Please describe.**
google testtool gives an error since itemprop="image" is missing

**Describe the solution you'd like**
add to f:image viewhelper at Partials/Detail/MediaImage.html:  additionalAttributes="{itemprop=\\"image\\"}"   (quotes must be escaped)

**Describe alternatives you've considered**
none

**Teachability, Documentation, Adoption, Migration Strategy**
will automatically do the job

**Comment by georgringer** [comment]
Wanna do a pr?

**Comment by Uhradone** [comment]
What is a "pr"?

It's not a huge thing and anyway the Partial is in my sitepackage but of course it is nice if the code comes correct in the sense of Rich Text Snippets.

Here the corrected code in **Patials/Detail/MediaImage.html**:



`<f:if condition="{settings.detail.media.image.lightbox.enabled}">
				<f:then>
					<a href="{f:uri.image(image:mediaElement, width:'{settings.detail.media.image.lightbox.width}', height:'{settings.detail.media.image.lightbox.height}')}" title="{mediaElement.title}" class="{settings.detail.media.image.lightbox.class}" rel="{settings.detail.media.image.lightbox.rel}">
						<f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop=\"image\"}"  />
					</a>
				</f:then>
				<f:else>
					<f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop=\"image\"}" />
				</f:else>
			</f:if>`
