### ISSUE TITLE
renderType missing in TCA time columns 

### ISSUE THREAD

**Issue by t3easy** [georgringer/news#922]
## Bug Report

**Current Behavior**
deprecation_xxx.log
The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_news_domain_model_link['columns']['crdate']['config']
The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_news_domain_model_link['columns']['tstamp']['config']
The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_news_domain_model_news['columns']['crdate']['config']
The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_news_domain_model_news['columns']['tstamp']['config']
The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_news_domain_model_tag['columns']['crdate']['config']
The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_news_domain_model_tag['columns']['tstamp']['config']

**Expected behavior/output**
No entries

**Environment**
- TYPO3 version(s): 8.7.26
- news version: 7.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: docker stack

**Possible Solution**
add renderType to TCA

**Comment by georgringer** [comment]
Wanna add a pr?

**Comment by t3easy** [comment]
Sure. I'll have a the next days.
