### ISSUE TITLE
Extend sys_categories with news

### ISSUE THREAD

**Issue by sevensix** [georgringer/news#926]
Hi, 
i extended the sys_categories with a colorpicker by using an own extension (to color the background of a newscategory). I added the needed field an made this a colorpicker field. I can save and change the value via the colorpicker when i add a newscategorie. But i can't make this field showing up in the frontend. the f:debug on the newsitem categorie doesnt show this field. What am i missing? any hints?

thx for help

**Comment by georgringer** [comment]
this is no support channel, pls use stackoverflow. however pls follow the guide in the docs which works really well
