### ISSUE TITLE
Module List -> New Record empty

### ISSUE THREAD

**Issue by kathihasselbach** [georgringer/news#928]
## Bug Report

**Current Behavior**
After I have installed and activated the news extension, I get only the News Record (News, News tag) and for System Records only Internal Notes in the List Module and creating a new record (see screen-01).
When I deactivate the news extension, I get the New Record like Create New Page, Create new content element and System Records includes for example Website Usergroup, Website User etc. (see screen-02)

**Expected behavior/output**
I would expect to see the same records under List module and creating new records as there are showing when the extension is deactivated.

**Environment**
- TYPO3 version: 8.7.12
- PHP version: 7.3.0
- news version: 7.2.0
- TYPO3 installed with composer
- OS: OSX 10.13.4
- XAMPP 7.3.0-0

<img width="1511" alt="screen-01" src="https://user-images.githubusercontent.com/51864450/59580475-21499a80-9086-11e9-9880-037967eb8223.png">
<img width="1513" alt="screen-02" src="https://user-images.githubusercontent.com/51864450/59580476-21499a80-9086-11e9-9db8-f0f35307415c.png">

**Comment by JohnNDK** [comment]
Not a bug.

Edit root page, go to resources and remove "EXT:news :: Restrict pages to news records" from includes.
