### ISSUE TITLE
The hidden translated news will show the news in default language on the detail view

### ISSUE THREAD

**Issue by sunweiye** [georgringer/news#930]
## Bug Report
A translated news, which is disabled ("hidden" is checked), can be still accessed with default language as fallback, if the url to the detail view is cached in the RealUrl cache.

**Current Behavior**
1. Translate a news in the backend
2. Enable the translated news by unchecking the `hidden` field.
3. Open the news list page or call a sitemap generator, so that the url to the detail page will be created and cached in the RealUrl cache table.
4. Make the translated news disabled by checking the `hidden` field.
5. Direct access the translated news with the generated detail view url in sitemap or the list view (The list view should not be refreshed, otherwise the news will not appear in the list.)

**Expected behavior/output**
The news should not be accessible. 

**Environment**
- TYPO3 version(s): 8.7.22
- news version: 6.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): Yes
- OS: All OS

**Comment by georgringer** [comment]
the issue is too old and can't be reproduced anymore. feel free to reopen a new issue if still valid
