### ISSUE TITLE
news type default tca is always the tca from article

### ISSUE THREAD

**Issue by blueamerican** [georgringer/news#932]
I only want two have the news types internal and external link. No article.
Therefore i remove the article type:
`TCEFORM.tx_news_domain_model_news.type.removeItems = 0`

If i create a new news record, i get per default the tabs form the article. eg. Inhaltselemente.
Only if i save my news as internal or external link, this tab disappears.

How can i get rid of the tab per default? How can i get the tca which is the first entry in the type selectbox?   

![news](https://user-images.githubusercontent.com/5647051/60364749-4d9ada80-99e7-11e9-97f5-8b20187abf41.jpg)

- TYPO3 version(s): 8.7.9
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

**Comment by georgringer** [comment]
confirmed but this is a core issue, see also https://forge.typo3.org/issues/94408, therefore closing it here
