### ISSUE TITLE
Starting Point of an archive item

### ISSUE THREAD

**Issue by chequille** [georgringer/news#937]
Hi,
have the following problem:

Scenario:
I have a news one day event item f.e. at 22.06.2019
THe archive date is set to 23.06.2019

Unfortunately, the item is shown till 24.06.2019, because archiv date cannot be set with a time and therfore it waits till midnight before it is not shown anymore.

unfortunately, I cannot set the archive date to the same day as the event, because in this case, the event is not shown.

Therefore my question: Is there a possiblity to define archive date with time as well?
My event should not be displayed beginning midgnight.

Looking forward ot hearing from you.
Best regards,
Chequille

**Comment by georgringer** [comment]
you can change the date format by overriding the TCA. however I leave that as confirmed and accepted

**Comment by chequille** [comment]
Thanks for the tip.

If somebody wants to know how to do it, here it is. Just change one line in /configuration/tca/tx_news_domain_model_news.php

old Line 245:
`          	'eval' => $configuration->getArchiveDate() . ',int',
`new line 245:
 `           	'eval' => 'datetime,int',
`
Thats it. Archive does have now as well a time, and the record is archived exactly at that time. The only thing you have to care about is your server time, because very often it is not the real time. F.e. no summertime etc.

I tried this now in the source code of the extension itsel.f, but of course the better way is to do it somewhere else to override it.

Regards,
Chequille

**Comment by georgringer** [comment]
I am sorry that I forgot that there is already a configuration for that, in extension settings 

> Archive Date: Define if the archive date is a &quot;Date&quot; or &quot;Date &amp; Time&quot;

therefore closing the issue

**Comment by chequille** [comment]
Could have had a look to the configurations as wel to see it !
Thanks for the information.
Regards
Chequille
