### ISSUE TITLE
AdministrationController::extendMenu() treats signal result incorrectly (+fix)

### ISSUE THREAD

**Issue by dmitryd** [georgringer/news#938]
## Bug Report

**Current Behavior**

The code in the function:
```php
    protected function extendMenu(Menu $menu)
    {
        $signalParameters = [
            'menu' => $menu,
        ];
        try {
            $menu = $this->signalSlotDispatcher->dispatch(__CLASS__, 'createMenu', $signalParameters);
        } catch (\Exception $exception) {
            // Nothing to do
            $menu = $signalParameters['menu'];
        }

        return $menu;
    }
```

The function assumes that signal dispatcher returns the menu. However, signal dispatcher [returns the same array](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/extbase/Classes/SignalSlot/Dispatcher.php#L172) as was passed to it (`$signalParameters`). So only one signal slot may work with the current implementation: the slot needs to return something, which is not an array. In this case the signal dispatch will throw an exception, news administration controller will catch it and thus one single slot will work. Every other signal slot will not be executed.

**Expected behavior/output**

1. Every slot is processed.
2. The function works in accordance with TYPO3 expectations to the signal dispatcher. 

**Environment**
- TYPO3 version(s): 8.7.26
- news version: 7.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian Linux in docker

**Possible Solution**
The fix should be simple:

```php
    protected function extendMenu(Menu $menu)
    {
        $signalParameters = [
            'menu' => $menu,
        ];
        try {
            $signalParameters = $this->signalSlotDispatcher->dispatch(__CLASS__, 'createMenu', $signalParameters);
        } catch (\Exception $exception) {
            // Nothing to do
        }
        $menu = $signalParameters['menu'];

        return $menu;
    }
```

**Comment by dmitryd** [comment]
And I have to admit that this was my wrong code.

**Comment by georgringer** [comment]
merged, thx for your contribution!
