### ISSUE TITLE
TSConfig is not working with 'Hide page tree for Administration module'

### ISSUE THREAD

**Issue by MediKathi** [georgringer/news#942]
## Bug Report

**Current Behavior**
If the PageTree is disabled:
If 'Hide page tree for Administration module' is enabled the Page TS-Config is no loading correctly. Additional Files in the TS-Config are not Loaded nor the TSconfig field of the page.

If the PageTree is enabled, everthing works normal.

If I include the file with: 

```
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig('
    	<INCLUDE_TYPOSCRIPT: source="FILE:EXT:myExt/Configuration/TSconfig/basic.tsconfig">
    ');
```

everthing works as well

**Expected behavior/output**
Additional TSConfig-Files should be loaded

**Environment**
- TYPO3 version: 9.5.8
- news version: 7.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Ubuntu 18.04.2 LTS

**Comment by georgringer** [comment]
there is nothing I can do within the extension. if there is no page tree, then no page tsconfig can be loaded.
