### ISSUE TITLE
Upgrade wizard for slug makes another one than the button in the news record

### ISSUE THREAD

**Issue by chrisprog20** [georgringer/news#943]
## Inconsistent Behaviour Report

Hi,
just wanted to inform you about the following I noticed. 

**Current Behavior**
The slug of a news record generated by the Upgrade Wizard 
'Updates slug field "path_segment" of EXT:news records' is different from the one generated by the button 'Recalculate URL segment from page title' in the news record itself with respect to how a date is transformed.

Example:
News Title is "Newsletter 16.08.2018"
The Upgrade wizard generates the slug "newsletter-16-08-2018" while the button in the news record itself generates the slug "newsletter-16082018".

**Expected behavior/output**
The slug generated by the Upgrade Wizard should be the one generated by the button in the news record. 

**Environment**
- TYPO3 version: 9.5.8
- news version: 7.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 7

Cheers
Christian

**Comment by georgringer** [comment]
Will be solved with #913

**Comment by chrisprog20** [comment]
Thank you ! :)
