### ISSUE TITLE
Disable external/internal News in link handler

### ISSUE THREAD

**Issue by echavaillaz** [georgringer/news#945]
**Current Behavior**
Actually when I try to add a link to a news (in a CE), I can choose all news type (include external and internal). It make no sense.

**Expected behavior/output**
List only the "default" news in the link modal.

**Environment**
- TYPO3 version(s): 9.5.8
- news version: 7.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 16.04

Thanks

**Comment by georgringer** [comment]
If someone is interested, I guess the hook `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['typo3/class.db_list_extra.inc']['getTable']` is the proper entry point for that

**Comment by echavaillaz** [comment]
Yes, I test it and it works fine with this hook.

Thanks

**Comment by georgringer** [comment]
@echavaillaz thanks for feedback but mayb you wanna share the hook as well?!?!

**Comment by echavaillaz** [comment]
Oh sure:

ext_localconf.php, add: $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['typo3/class.db_list_extra.inc']['getTable'][] = \GeorgRinger\News\Hooks\RecordListGetTableHook::class;

And the file is like this:

```
<?php
declare(strict_types = 1);
namespace GeorgRinger\News\Hooks;

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

use TYPO3\CMS\Backend\RecordList\RecordListGetTableHookInterface;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * Hook for the record list.
 */
class RecordListGetTableHook implements RecordListGetTableHookInterface
{
    public function getDBlistQuery($table, $pageId, &$additionalWhereClause, &$selectedFieldsList, &$parentObject): void
    {
        if ($table === 'tx_news_domain_model_news' && GeneralUtility::_GET('route') === '/wizard/link/browse') {
            $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable($table);

            $additionalWhereClause = (string)$queryBuilder->expr()->andX(
                $additionalWhereClause,
                $queryBuilder->expr()->eq($GLOBALS['TCA'][$table]['ctrl']['type'], 0)
            );
        }
    }
}

```

Thanks

**Comment by georgringer** [comment]
I am closing this issue. 1st this could be solved with such hook and more important there can be uses cases where this is useful.
