### ISSUE TITLE
Update wizard for tx_realurl_uniqalias misses check for table exist

### ISSUE THREAD

**Issue by jokumer** [georgringer/news#949]
## Bug Report

**Current Behavior**
Upgrade wizard `[Optional] Migrate realurl alias to slug field "path_segment" of EXT:news records` fails, when no table `tx_realurl_uniqalias`exists, but is executed anyway.

**Expected behavior/output**
This upgrade wizard should not be available, if no table exists at all.

**Environment**
- TYPO3 version: 9
- News version: since 7.1
- Composer or classic mode

**Possible Solution**
A check for table exists should be implemented in _checkForUpdate()_ method

**Additional context**
This upgrade wizard was introduced with **[FEATURE] Add realurl alias migration for news slugs** See #849

**Comment by georgringer** [comment]
Hey,

I checked the wizard and it is using `$this->slugService->countOfRealurlAliasMigrations(`  which uses

```
if ($schemaManager->tablesExist(['tx_realurl_uniqalias']) === true) {
```

so is this really valid?

**Comment by jokumer** [comment]
Yes, it is valid.
https://www.doctrine-project.org/api/dbal/2.5/Doctrine/DBAL/Schema/AbstractSchemaManager.html#method_tablesExist

**Comment by georgringer** [comment]
imo all merged, so closing this issue
