### ISSUE TITLE
Breaking: 7.2.1 github tag actually points to 7.0.8 breaking composer-based setups!

### ISSUE THREAD

**Issue by foobar13372** [georgringer/news#951]
The latest 7.2.1 does not have the AddNewsToMenuProcessor (the whole directory is missing).

Just broke one of our setups.

Downgraded to 7.2.0 to hotfix it for the time being.

Not sure if actually a packagist bug. (I cleaned compsoer caches, file still missing in 7.2.1, but in the git repo it is clearly there)

**Comment by foobar13372** [comment]
Nope, no packagist bug, the github zip https://github.com/georgringer/news/archive/7.2.1.zip is missing the DataProcessing folder as well.

**Comment by foobar13372** [comment]
The TER release zip has the file correctly.

**Comment by Crontis** [comment]
Yeah, seems like the github tag points to an older commit which contains 7.0.8 (https://github.com/georgringer/news/tree/06d72d4b6749a8afe651aef89ca55f9554c4b979).
https://github.com/georgringer/news/releases/tag/7.2.1 -> 49 commits to master since this tag

**Comment by georg-tiefenbrunn** [comment]
Hooks\Backend\PageViewQueryHook::class is also missing in https://github.com/georgringer/news/archive/7.2.1.zip and 
https://github.com/georgringer/news/archive/7.2.1.tar.gz which will throw an exception in the page module when upgrading from version 7.2.0 to 7.2.1. without clearing caches.

**Comment by georgringer** [comment]
sorry for the problems, released 7.2.2
