### ISSUE TITLE
The configuration cannot be read in injectConfigurationManager

### ISSUE THREAD

**Issue by nemstaa** [georgringer/news#952]
With 7.2.1 the configuration cannot be read correctly.
In NewsController.php -> injectConfigurationManager() -> $this->configurationManager->getConfiguration on line 592:
$this->pluginName is not "news_pi1". It's "News".

This configuration gives empty teaser text and my custom function (ajax request) doesn't work anymore.

Specs:
Typo3 8.7.27 / 9.5.8
PHP 7.2
Apache

**Comment by Crontis** [comment]
Maybe related to following commit: https://github.com/georgringer/news/commit/095bd174cc5134296142fb3e969c88d5a3f741af
Getting the same error as @koch-louis mentions.

**Comment by nemstaa** [comment]
It seems so. But in 7.2.0 it's:
`$tsSettings = $this->configurationManager->getConfiguration(
            \TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface::CONFIGURATION_TYPE_FRAMEWORK,
            'news',
            'news_pi1'
        );`

**Comment by foobar13372** [comment]
Can confirm. This practically breaks the Frontent plugins in one way or another because no configuration can be found anymore.

Yes, the named commit is the cause. And actually in the commit people said this - it was ignored.

**Comment by fnagel** [comment]
Above mentioned commit also leads to this error (as documented in the commit but not here in this ticket): `#1400741142: The itemsPerPage is 0 which is not allowed. Please also add "list.paginate.itemsPerPage" to the TS setting settings.overrideFlexformSettingsIfEmpty! (More information)`

Downgrading to version 7.1.0 fixes this issue.

**Comment by georgringer** [comment]
sorry for the hassle, released 7.2.3
