### ISSUE TITLE
The itemsPerPage is 0 which is not allowed

### ISSUE THREAD

**Issue by brotkrueml** [georgringer/news#954]
## Bug Report

**Current Behavior**
After updating from 7.2.0 to 7.2.2 I got this error on the list view:

The itemsPerPage is 0 which is not allowed. Please also add "list.paginate.itemsPerPage" to the TS setting settings.overrideFlexformSettingsIfEmpty!

So I set ```settings.overrideFlexformSettingsIfEmpty := addToList(list.paginate.itemsPerPage)``` in my TypoScript configuration, but the same error occured. Looking at TypoScript Object Brower the setting change was set.

**Expected behavior/output**
Showing the list view correctly like in 7.2.0

**Environment**
- TYPO3 version(s): 9.5.8
- news version: 7.2.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux 4.0.15

**Additional context**
Reverting to version 7.2.0 and the problem disappeared.

**Comment by Crontis** [comment]
Related to #952 and should be fixed with the 7.2.3 release

**Comment by georgringer** [comment]
fixed

**Comment by Teisi** [comment]
Seems that this error is back again
TYPO3 10 and news 8.3.0

**Comment by Pinoerkel** [comment]
This also happens to me on Typo3 10.4.6 and News System 8.5.0. Until now, I did not find any way to get it working.

**Comment by ararename** [comment]
Same error on a brand new install of tx_news 8.5.2 with Typo3 10.4.15. 
Is there a workaround or a fix somewhere to be found or someplace else where i can find is a solution?

**Comment by ararename** [comment]
Ah, is this to do with PHP type hints?
Some default missing somewhere in TCA maybe?

**Comment by SigiK** [comment]
Have the same issue (error message) with Typo3 v10.4.20 and news 8.6.0. Tried to set list.paginate.itemsPerPage in TS without success. Maybe I am missing something? 

Which version would be without this issue? Thx for your help!!
