### ISSUE TITLE
Page Not Found And Error handling in Frontend (deprecation)

### ISSUE THREAD

**Issue by instruccionesaldorso** [georgringer/news#955]
When setting up TypoScript setting 
`plugin.tx_news.settings.detail.errorHandling = pageNotFoundHandler`, deprecated method `TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->pageNotFoundAndExit()`: is still being used.

See: https://github.com/georgringer/news/blob/7.2.2/Classes/Controller/NewsBaseController.php#L115
and here:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.2/Deprecation-83883-PageNotFoundAndErrorHandlingInFrontend.html

Would it be possible to use instead the 404 error management from Sites configuration? (at least for TYPO3 9.5)

**Comment by instruccionesaldorso** [comment]
@georgringer I just tested your patch against `master` branch and TYPO3 9.5.8, and it is not working for me.

**Comment by georgringer** [comment]
Yes thought so, not that easy

**Comment by mschwemer** [comment]
Can be closed. It is solved in commit  #8ea355e.

Thanks.
