### ISSUE TITLE
TypoScript setup can't be overwritten since news version 7.2.3

### ISSUE THREAD

**Issue by angeloprevitali** [georgringer/news#957]
Adding some typoscript in the setup it won't overwrite the main ts from the EXT:news. There is no configuration possible like this.

Seems to be new since EXT:news version 7.2.3

OS: Linux
Composer: No
TYPO3: 8.7.27
PHP 7.2
EXT:news 7.2.3

**Comment by georgringer** [comment]
I had some issues with the 2 versions before but everything is fine in current master (and IMO also in 7.2.3),
tested with following TS
```
plugin.tx_news.settings.overrideFlexformSettingsIfEmpty = limit,cropMaxCharacters,dateField,timeRestriction,archiveRestriction,orderBy,orderDirection,backPid,listPid,startingpoint,recursive,list.paginate.itemsPerPage,list.paginate.templatePath
plugin.tx_news.settings.limit = 2
```
