### ISSUE TITLE
Allow to override registered icons

### ISSUE THREAD

**Issue by echavaillaz** [georgringer/news#958]
## Bug Report

**Current Behavior**
If I try to register an icon with the same identifier of news before news is loaded, I can not.

**Expected behavior/output**
Have the possibility to override the registered icons.

**Environment**
- TYPO3 version(s): 9.5.x
- news version: latest
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu

**Possible Solution**
Just add a check in `ext_localconf.php` like this : 

```
foreach ($icons as $identifier => $path) {
    if ($iconRegistry->isRegistered($identifier) === false) {
        $iconRegistry->registerIcon(
            $identifier,
            \TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class,
            ['source' => 'EXT:news/Resources/Public/Icons/' . $path]
        );
    }
}
```

Thanks

**Comment by georgringer** [comment]
Why not loading your extension afterwards and override?

**Comment by echavaillaz** [comment]
Because it is not possible for my case.

And the icon `apps-pagetree-folder-contains-news` is already registered in the core (https://typo3.github.io/TYPO3.Icons/images/apps/apps-pagetree-folder-contains-news.svg), the icon is better for the UI than one provided by news.

So no need to override it if already registered.

And this patch will not modify the behaviour for the icon `apps-pagetree-page-contains-news`.
But if I want to have another one (e.g https://typo3.github.io/TYPO3.Icons/images/content/content-news.svg) I can register it before or after your ext with the patch.
