### ISSUE TITLE
Show in preview select box: wrong german translation

### ISSUE THREAD

**Issue by klodeckl** [georgringer/news#962]
The translation of the select items in german is wrong:
0 = In Vorschau-Ansichten anzeigen
1 = In Ansichten anzeigen
2 = Nur in Listenansichten anzeigen

But it should be:
0 = Nur in Detailansichten anzeigen
1 = In allen Ansichten anzeigen
2 = Nur in Listenansichten anzeigen

And the select field itself is named „In Vorschau-Ansichten anzeigen“, it would be better „Ansichts-Einstellungen“.

In de.locallang_db.xlf it is right though the word „allen“ is missing in 1. In de.locallang_db.xml it is wrong.

By the way I did not find how to override translation via tsconfig. How to do that? I tried the following, but did not work:
TCEFORM.sys_file_reference.showinpreview.altLabels.0.label = rgwrg
plugin.tx_news_domain_model_media {
  _LOCAL_LANG.de {
    tx_news_domain_model_media.showinviews.0 = gvwerfwe
  }
}

Even changing de.locallang_db.xml and clearing the cache did not work. So I edited the cache generated file directly.

**Environment**
- TYPO3 version: 8.7.24
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian 10

**Possible Solution**
Change the translation labels to the proposed translations above.

**Comment by georgringer** [comment]
update language packs, it is now changed
