### ISSUE TITLE
Allow to use record for the news author

### ISSUE THREAD

**Issue by echavaillaz** [georgringer/news#964]
## Feature Request

I think it could be a cool feature to be able to set a database record as news author. For example a list of `be_user` instead of plain input text for the name and email.

Thanks

**Comment by georgringer** [comment]
I am asking for some feedback at https://twitter.com/georg_ringer/status/1161218330914623488

3rd party extension you can use is https://github.com/cdaecke/md_news_author

**Comment by georgringer** [comment]
Closing the issue, custom extension is fine
